### ISSUE TITLE
Select icon when creating a composition

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#10108]
When using the new create doctype dialog in v8.12, the the icons in the dialog should be selected in the new type being created.

Right now we have to select the same icon every time we create a composition. 

Also, it would be nice to have some colours pre-selected too. Maybe based on how @prjseal does in his awesome tutorials.

**Comment by nul800sebastiaan** [comment]
I am a little lost here @soreng - would you be able to illustrate with a couple of screenshots/gif please?

**Comment by soreng** [comment]
When you click the type of type (?) you want to create, there is no icon set.
![image](https://user-images.githubusercontent.com/359492/114313617-6eb6b780-9af7-11eb-8b13-1ddeee2ef090.png)

It would be nice if, instead of nothing, the icon from the type, ie the "defrag" icon for compositions, was set on the new type you are creating.

**Comment by skttl** [comment]
I think it makes perfect sense for the default icon to match the ones in the dialog 👍

**Comment by nielslyngsoe** [comment]
I think it's a good idea. :-)

The only one of these icons I'm concerned about is the "Document Type" (without template). 

I´m not sure what the icon symbolizes, plus I would think many use this choice as a default initial step, which ends up begin used as any of the other choices. Then the icon ends up giving a messy look. 
I myself always pick "Document Type" and then I later use it for a composition or with a template. I probably already have a template that I wanted to use for it.

As the icon of the DocumentType is used in the Editor Experience we are not going to ensure that icons represent the features/configuration of the DocumentType, in other words, we cannot make sure that we have an icon that provides the right representation. This argues against having such a feature, but I think for the choices "Element Type" and "Composition" we are fairly certain of the purpose and it will most likely not be changed, therefore I think we can set the default icon for those.

In order to provide a meaningful solution to the problem, I think the icon ofthe choice "Document Type"(No template) should be the document icon as the one for "Document Type with Template"

I can add that I think this dialog would be improved as well by using the same icon as Document Type with Template, as they are almost the same, this would visually provide a relation, making it easier to distinguish these two from the others.

That's my 50 cents :-)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/11008 - I've moved the labels there!
