### ISSUE TITLE
Nested BlockLists do not work on Umbraco 9

### ISSUE THREAD

**Issue by crjc** [umbraco/Umbraco-CMS#10200]
Attempting to load the editor for a block list that has a nested block list does not work with Umbraco 9. It just loads forever and silently spits out an error in the console.

This works fine on Umbraco 8.

Console error: `angular.js:15635 Could not find umbVariantContent in the $scope chain`

![loadforever](https://user-images.githubusercontent.com/57661759/116533486-573e4380-a8d9-11eb-906a-00e5cc50aee1.png)

Reproduction
------------

### Steps to reproduce

Create element type A which contains a text property
Create element type B which contains a block list editor with type A as a block.

Create a document type C with a new block list editor that has type B as a block.

Create a page of document type C,
Insert a new block of type B
Click on this new block
Edit UI will show, but it will load forever!

### Expected result

Back office should load the edit UI and allow me to insert nested blocks (of type A)

### Actual result

Loads forever. See screenshot and console error above.

**Comment by kjac** [comment]
Strange... I'll give it a look 🙂 thanks for reporting and for being so thorough in your steps to replicate 👍

**Comment by kjac** [comment]
@crjc I can't seem to replicate this. 

![10200](https://user-images.githubusercontent.com/7405322/116771517-6691ce00-aa4c-11eb-85fb-4fd410b692ee.gif)

I am testing on the latest `netcore/dev` branch, but I can't imagine it's any different than the beta in this regard. Do you have anything custom running in your solution, that could be triggering this upon editing - maybe a custom label template?

**Comment by crjc** [comment]
Nothing custom, it's a brand new installation. 

I've just tried again on another new installation of the beta and I can reproduce the bug on a different machine as well. 

maybe it's already fixed on `netcore/dev`?

**Comment by kjac** [comment]
@crjc turns out this only happens in production build. The JS minification borks up things.

@nielslyngsoe I need your input here. The JS minification changes the constructor name, so [this line](https://github.com/umbraco/Umbraco-CMS/blob/netcore/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js#L72) no longer finds the `umbVariantContentController` controller. Short of changing the minification to run less optimized, do you have any ideas how to change this? The only thing I can think of is to introduce a string variable on the controller `vm` instance for identification purposes, but that's rather an ugly fix.

Note that there is at least one more place in the codebase where this might be a problem... will have to investigate once a proper solution has been found.

**Comment by kjac** [comment]
OK I did some digging into this, and we can fix it in the minifier. I will submit a PR shortly.

**Comment by nielslyngsoe** [comment]
Hi @kjac thanks for looking into this, I haven't spent any time at v9 jet, so I have no knowledge about whether we tread the JS code differently, but it's intended for us to do exactly the same, so let's aim for that. Thanks

**Comment by kjac** [comment]
PR in #10223
