### ISSUE TITLE
CMS changes not showing on front end on a load balanced site

### ISSUE THREAD

**Issue by MylesB93** [umbraco/Umbraco-CMS#10240]
Occassionally, when making changes in the CMS on a load balanced site, the changes don't appear on the front end. Restarting the app service in Azure causes the changes to appear. I can confirm that the steps in here were followed: https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.4

Reproduction
------------

### Steps to reproduce

- Making a content change within the CMS (e.g. editing text inside a Rich Text Editor)
- Hitting "Save and Publish"
- Viewing that page

### Expected result

The page should be updated with the latest change.

### Actual result
The page isn't updated and still shows content from before the new content was published.

**Comment by nul800sebastiaan** [comment]
Sorry to hear @MylesB93. I would highly recommend you upgrade to he latest version 8.13 at least, we have done a quite a few caching updates since 8.6.4. Then if this is still happening, check to see if there's an error in the backoffice saying the content can't be routed (on the info tab of the content item where the URLs are), if that has an error you might be running into this issue: https://github.com/umbraco/Umbraco-CMS/issues/9514

If not, then it's some mysterious other issue and I unfortunately don't have much to offer there. If the above fails then I would head on over to our friendly forums at https://our.umbraco.com to get some help with you load balancing setup, it's pretty likely that something is a bit off there.
