### ISSUE TITLE
When inserting a link in RTE without selecting any text, insert a link using the title of the selected node

### ISSUE THREAD

**Issue by T9Creative** [umbraco/Umbraco-CMS#10258]
I don't know if there's a reason for this sort of behavior or if it's a bug.  If I go to insert a link **without** selecting any text, I can select a content item and click on "submit" and I expect the "link title" property to be displayed with the link, etc.  However as you'll see in my screenshot video, it results in nothing.  If I enter text first and select it, then go to add the link, it then works.

Is my expectation just incorrect for some reason?

https://user-images.githubusercontent.com/59846795/117706960-8f743a80-b193-11eb-9de9-2438b7c85eaf.mp4

## Umbraco version

I am seeing this issue on Umbraco version: 8.13.0 and also earlier versions, and also on newly installed versions

**Comment by emma-hq** [comment]
Hi @T9Creative 

I suppose it is expected behaviour but it could be nicer. For instance, if the user tries to add a link without any text, they should be unable to proceed. Or else, there is a default behaviour that the selection of a link without text adds the node name/link details as the text. Certainly, it's something that happens all the way back to early v8 releases. 

What's the behaviour you'd expect in this instance? 

Emma

**Comment by emma-hq** [comment]
Hey @T9Creative 

Ah ha, I see. And if they type an external link rather than selecting a node, we display the url? 

Emma

**Comment by T9Creative** [comment]
Yeah, if an external URL is used and no other text added, then the link could be displayed. I just don't see why it should ever result in nothing when the action is taken to insert a link and an item has been selected and submitted.
