### ISSUE TITLE
Feature request: Export Document Types for v8

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#10304]
### Umbraco version

v8

### Description

I could swear there was an option to export a document type in early v8 installations...
![image](https://user-images.githubusercontent.com/56038614/119096898-729df980-ba14-11eb-84d5-26c68ab953b9.png)

I checked v 8.13 (and a few latest versions of v8) and it is gone.
However I noticed the export/import function is there in beta v9.

It would be ｕｍｂａｚｉｎｇ if we could use that feature to export doctypes on v8, and import them into v9. Not sure why that feature was removed from v8 in the first place 🤔

**Comment by nul800sebastiaan** [comment]
It's still there even in the latest version: 

![image](https://user-images.githubusercontent.com/304656/119099870-a6c6e980-ba17-11eb-9d45-71a4d36a0987.png)


However, I bet you're using a Cloud site and it's not available on Cloud since importing doctypes will mess up Deploy. 😊

In any case, the preferred way to export doctypes is to create a package  👍

**Comment by Jay-umbr** [comment]
Ah, righto! My mistake was that I tried this on the Cloud. Thanks 👍
