### ISSUE TITLE
Cannot add colors and see color palette using Color Picker

### ISSUE THREAD

**Issue by carolina351** [umbraco/Umbraco-CMS#10322]
### Which Umbraco version are you using?

8.12.2

### Bug summary

Cannot add colors using Color Picker for Data Type.
However when I add the first default color (#0), there's no color panel to select, I cannot input the HEX value for the color neither. And afterwards I can't add any other color.

### Specifics

* Bug found on version 8.12.2 
* Browser: Chrome, Firefox, Microsoft Edge, Internet Explorer

### Steps to reproduce

1. Create a custom data type with a color picker
2. Choose colors

### Expected result / actual result

**Expected Result**

1. Should expand the color palette for users to choose like previous versions
2. User should be able to input the HEX value in case the palette isn't provided

**Actual result**

1. No color palette appears
2. User cannot input the HEX value for the color

![image](https://user-images.githubusercontent.com/44266207/119464880-16e8ae80-bd3b-11eb-85d5-a8f2a1974a1c.png)

**Comment by bjarnef** [comment]
@carolina351 I haven't noticed this on various projects based on Umbraco v8.12 and v8.13

It would help if you could add more details to ask these questions:

- Do you get any console errors?
- Do you use any packages?
- Do you use custom property editors, dashboard etc. injecting custom CSS and/or JavaScript?
- Do you include a custom Spectrum Color Picker, either the original version here https://bgrins.github.io/spectrum/ or the v2 here https://seballot.github.io/spectrum/ ?

**Comment by carolina351** [comment]
@bjarnef  I have just updated Umbraco to the newest version (v8.13) and the problem persists.

- Do you get any console errors?
No.

- Do you use any packages? Any based on Spectrum? 
Yes. (https://our.umbraco.com/packages/backoffice-extensions/spectrum-colour-picker/ and https://our.umbraco.com/packages/backoffice-extensions/color-picker-u8/ )

- Do you use custom property editors, dashboard etc. injecting custom CSS and/or JavaScript?
No.

- Do you include a custom Spectrum Color Picker, either the original version here https://bgrins.github.io/spectrum/ or the v2 here https://seballot.github.io/spectrum/ ?
No.

**Comment by carolina351** [comment]
@bjarnef I have deleted the spectrum.css file inside App_Plugins folder and it worked. 
Thanks anyways :)

**Comment by bjarnef** [comment]
@carolina351 you probably don't need to use that package since Umbraco 8.13 which includes an Eye Dropper Color Picker: https://umbraco.com/blog/umbraco-813-release/ 

You could try creating a datatype instance using Eye Dropper Color Picker property editor and see if you can change the property to use this instead although I am not sure if these packages maybe store the color in a different format.

Since Umbraco 8.10.0 an `<umb-color-picker>` component has been included, so it is quite easy to implement this in a custom property editor, prevalue editor, dashboard, content app:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorpicker.directive.js
