### ISSUE TITLE
(v9-beta003) Adding media content from the media library to a grid type doc editor locks the backoffice interface

### ISSUE THREAD

**Issue by leehowarth** [umbraco/Umbraco-CMS#10355]
### Which Umbraco version are you using?

v9-beta003

### Bug summary

I'm currently setting up a site in Umbraco v9 to test a few of the features however I have discovered that if I add any images to a grid layout (either as an image or an image within a RTE) then as soon as the image has been selected the back office interface completely locks up so the page is unable to be saved. 

As an example up until this point works fine 
![image](https://user-images.githubusercontent.com/917718/120008484-e58a1000-bfd2-11eb-9de8-3c9c2f767d7a.png)

However when I select an image (just a ucommerce logo here - ucommerce is not installed) the the image displays but the interface is locked meaning the page cannot be saved. 
![image](https://user-images.githubusercontent.com/917718/120008853-47e31080-bfd3-11eb-86aa-dd5b1d22381c.png)

### Specifics

Standard image within the grid layout editor causes backoffice to freeze. No special changes has been made at this point and the version is a standard v9-beta003 install. The only package installed is usync v9 beta. 

### Steps to reproduce

1. Create a document type with a field that is a grid editor.
2. Create a page from the new document type 
3. Attempt to add an image within the page grid editor 
4. As soon as an image is selected the back office freezes

### Expected result / actual result

I would expect the page to not freeze to allow save.

**Comment by nul800sebastiaan** [comment]
Thanks, this was fixed in v8 (https://github.com/umbraco/Umbraco-CMS/issues/10297) after the v9 beta3 was created,  so for the next beta release of v9 it will work. In the mean time you can try nightly builds if you'd like a sooner fix: https://our.umbraco.com/documentation/UmbracoNetCoreUpdates#umbraco-9-nightly-builds

I am not sure when we're going to merge changes up to v9 but hopefully this week. Sorry for the inconvenience! I will close this issue as it will be automatically fixed after the next merge, keep an eye on the changes to `v9/dev` to see when this is done!
