### ISSUE TITLE
Email regex is wrong - JS bundling error?

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco-CMS#10404]
### Which Umbraco version are you using?

8.13

### Bug summary

The default email regex in the Backoffice is wrong.
More importantly, it's not the regex that's defined in source!

I'm assuming that this is an issue with whatever's bundling the JS but I haven't investigated yet.

Left is [source](https://github.com/umbraco/Umbraco-CMS/blob/v8/8.13/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/propertysettings/propertysettings.controller.js). Right is from umbraco.controllers.js from a freshly cloned cloud project,
![Screenshot 2021-06-07 091208](https://user-images.githubusercontent.com/7151793/120983181-5d91cc00-c771-11eb-9c65-9e51e8927493.png)

Also the "correct" regex could probably do with thinking about. I appreciate that it's probably too complex  [a specification](https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1) to meet fully in a simple regex but I wonder if it should at least 
 allow for TLD addresses i.e. `user@example`.

### Steps to reproduce

Choose email validation on a textbox.

![image](https://user-images.githubusercontent.com/7151793/120983915-0fc99380-c772-11eb-839d-c3a8f2c66a50.png)

Will allow all kinds of weird addresses.

**Comment by nul800sebastiaan** [comment]
I'm afraid it is entirely "correct", and your wish is already granted? `user@example` is a valid email address. 

This exact email validation Regex has been in place for a long time, even dating back to v7 if I recall correctly. I know that some people really don't agree with it but changing it now would also create an inconsistent experience, new properties would behave differently because of the updated Regex and that's only going to be confusing (I'd say that it would be a breaking change). 

The input Regex is escaped for JSON purposes so what is generated from the source you linked to is intended behavior.

So, for fear of breaking things and changing the behavior, we've decided not to touch this Regex, it does mostly what it needs to do, though it might be a bit too permissive. Of course we're also happy if you put in your own, more restrictive Regex (and yes, we realize it's annoying for you to have to remember to do that 😅 ).

**Comment by JasonElkin** [comment]
@nul800sebastiaan I understand not wanting to change the regex. 

However, the existing behaviour isn't intentional is it?

Before gulp:
`"pattern": "[a-zA-Z0-9_\.\+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-\.]+",`
After gulp:
`'pattern': '[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+',`

In fact the same goes for:
"pattern": "https?\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}",
`'pattern': 'https?://[a-zA-Z0-9-.]+.[a-zA-Z]{2,}',`

**Comment by nul800sebastiaan** [comment]
Must be intentional. Maybe it isn't. I'm really rusty in regex. 

In any case.. we're not going to change it at this time. Been like this since I believe v7.

There's a related issue where we're talking about decoupling validations from the document type and making the datatype responsible, this should open us up for adding different regexes at some point: https://github.com/umbraco/Umbraco-CMS/issues/9015

**Comment by JasonElkin** [comment]
Are "wontfix" bugs kept track of anywhere for Umbraco?

In terms of a bug this is pretty low hanging fruit, and I can't be the first person to flag it.

**Comment by nul800sebastiaan** [comment]
I did a search, couldn't find it either. 😄 

So seems like nobody is all that upset about this regex or they've learned to use their own?

**Comment by c9mbundy** [comment]
@JasonElkin "Also the "correct" regex could probably do with thinking about."
Email regex is notoriously difficult to get right and actually meet the multiple specs that cover it. 
The local-part has been loosened up to allow almost anything when you take quoting into account, and combined with INA domains, it's a bit of a nightmare.
I'm yet to see anyone produce a regex that actually meets the specs.

**Comment by JasonElkin** [comment]
@c9mbundy sure but thanks to the wildcard this is _very_ wrong i.e. jason@jason@jason or even jason@jason🤣jason are valid.

**Comment by nul800sebastiaan** [comment]
This is valid 😅 

> There can be any number (within the size limits of an email address) except that the last one must be the separator between the domain name and the "local part".

https://stackoverflow.com/a/12355882/5018

**Comment by c9mbundy** [comment]
When too many Jasons is never enough...  yep, absolutely - although technically @ can be used in the local-part if quoted, only the one unquoted can be used, as the delineator of the local-part and domain. If there is one rule you should be able to rely one, that's probably it.

**Comment by JasonElkin** [comment]
@nul800sebastiaan that says we can only have multple @ if it the email is enclosed in quotes i.e. "jason@jason"@jason anayway
@ was clearly a confusing example, lets instead go with literally any other char that the regex currently allows in a domain part at the moment
jason@jason*jason
jason@jason:jason
jason@jason\jason
jason@jason🙃jason

**Comment by nul800sebastiaan** [comment]
Yes. 

Maybe @c9mbundy has a preferred Regex for you, despite not finding the perfect one yet? 

There's also the `Email` datatype which is an `<input type="email" ...` so the browser is responsible for the correct validation, might be a better option for you. I am not sure how the server side implementation validates though, it's coming from .NET Framework (https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.emailaddressattribute?view=netframework-4.8)

**Comment by JasonElkin** [comment]
Not really concerned from that point of view @nul800sebastiaan - I know we can validate an email correctly other ways and I can (and did) just manually update the regex. Just bugs me that the default is wrong (and happens to be exercise 1 on the extending the backoffice course).

**Comment by c9mbundy** [comment]
@nul800sebastiaan  To be honest, I'm not sure I do have a preferred regex for this. It's easy enough to create a basic test that will work for 'common' cases, but I don't believe it's possible to create one that works for all cases. I guess this is why there are API services out there such as Kickbox for validating email addresses in 'real time' by actually partially testing it - but come at the cost of 3-400ms REST response (as well as money).
