### ISSUE TITLE
Media item not updating from File (SVG) to Image (PNG)

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#10481]
### Which Umbraco version are you using?

8.13.0

### Bug summary

When a SVG is uploaded to the media section it is uploaded as a File.
If a user then replaces the media item content to be a PNG, the media item doesn't get changed from "File" to "Image"

This can cause a null exception if using crops.

### Steps to reproduce

Upload a SVG to the media 

Edit the media item, and replace with a PNG

### Expected result / actual result

Expected: Media Item should be changed to a Image 

Actual: Remains stored as file

**Comment by nul800sebastiaan** [comment]
Yeah, this is not how that works, you've given it a datatype and it's not going to change to a different one. You wouldn't expect a document of type "Blog post" to change to "Contact page" when you add a contact form either. 😄 

With the default types, I understand it would be "easy" to change it but consider the fact that there will be custom properties on media types (like on content types) and you get into trouble pretty quickly. In 8.14 you can limit what types of files can be uploaded to each media type, which will indicate that the editor needs to create a new item instead of replacing the file.

I do believe on 8.13 you can get SVG to be treated as an image  by default though, if you add it to the `umbracoSettings.config` - https://our.umbraco.com/Documentation/Reference/Config/umbracoSettings/#imaging
