### ISSUE TITLE
umbracoRedirectId not redirecting as expected

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco-CMS#10506]
### Which Umbraco version are you using?

Umbraco 8 (Latest)

### Bug summary

In Umbraco 8 when you set up a field with umbracoInternalRedirectId and content picker the redirect does not behave as expected.

The page you are redirecting will have something like: /knowledge-base/the-item-page
And the page you select using the content picker has a URL of - /my-special-page

The redirect that is performed creates a URL redirect with the URL...

/knowledge-base/my-special-page

Which is not what you want. It appears the re-write is wrong?

When you use umbracoInternalRedirect with the same content picker it will redirect as expected going to the /my-special-page

### Specifics

umbracoInternalRedirectId - (Docs says it performs a rewrite) creates a relative alternative to the new page (Not its original URL)
umbracoInternalRedirect - Redirects as expected

### Steps to reproduce

- Have a item that is a child of another so it has a URL similar to /something/my-page
- Have a custom umbracoInternalRedirectId field and content picker
- Have a root url page /my-special-page
- Select the special page in the content picker of the first item
- Load url of the first item (something/my-page)
- You should see the rewite becomes /something/my-special page

### Expected result / actual result

It is not clear that the umbracoInternalRedirectId version is going to rewrite as a local based URL so matches any sub folders vs the umbracoInternalRedirect which does a 302.

On that can there not be something that is a full 301 in this case as well?

**Comment by bjarnef** [comment]
Do you mean `umbracoRedirect` redirects as expected? I have used this on a few Umbraco v8 projects. `umbracoInternalRedirect` doesn't seem to exist, but `umbracoInternalRedirectId` does.
https://github.com/umbraco/Umbraco-CMS/blob/f69cee87f94f46ec014ca36d213552cd4813e6fc/src/Umbraco.Core/Constants-Conventions.cs#L42

and should handle the redirect here: https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/Routing/PublishedRouter.cs#L538-L557

If you need 301 redirects you have a few options:

- IIS redirects in web.config
- Implement a Content Finder: https://our.umbraco.com/Documentation/Reference/Routing/Request-Pipeline/IContentFinder
- Use a package like [Skybrud Redirects](https://our.umbraco.com/packages/website-utilities/skybrud-redirects/) or [SimpleRedirects](https://our.umbraco.com/packages/backoffice-extensions/simpleredirects/) to manually handle redirects.

**Comment by nul800sebastiaan** [comment]
@thenexus00 Yes, @bjarnef is correct here, we don't do 301s and the `umbracoInternalRedirectId` property works as described. We have 301 redirects only when you rename a page (from `the-item-page` to `my-special-page` for example, so ` /knowledge-base/the-item-page` will then redirect to  `/knowledge-base/my-special-page`). 

Otherwise there's the options that Bjarne mentioned.

**Comment by nul800sebastiaan** [comment]
Sidenote: I updated your issue description to assume you're using 8.14.0, which is currently the latest, please always specify the full version so we can figure out 3 months in the future where a possible problem happened.

**Comment by thenexus00** [comment]
I think you guys missed everything :(

Firstly I did state "umbracoInternalRedirect - Redirects as expected"

Secondly umbracoInternalRedirectId states nothing about relative path change and looking at the code seems to again indicate the behaviour is different to what actually happens when in sub folders.

I still believe my comments on the bug/unexpected behavior stands.

**Comment by nul800sebastiaan** [comment]
@thenexus00 maybe we did miss everything 🙂 

A bit of back story: unfortunately, these redirect property aliases were thought up in version 3 or 4 of Umbraco and were not properly thought through. We have carried them along all this time because people started relying on them and any attempts to change or fix them have been met with huge friction since it would break people's redirects.

So we have come to accept the flaws that exist in them. 

So:
- `umbracoInternalRedirectId` will display the contents of the picked content item on the existing URL - giving a node in Umbraco and additional URL
- `umbracoRedirect` will do a 302 redirect to the picked content item

I think the documentation for `umbracoInternalRedirectId` should probably be updated as it technically is a URL rewrite, but that might be a bit confusing if you were expecting the URL to actually change.
