### ISSUE TITLE
Media Item Contrast

### ISSUE THREAD

**Issue by steinmeier** [umbraco/Umbraco-CMS#10558]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.13.1

### Bug summary

The contrast on the media picker is very low, and it makes it hard to differ between various file types

### Steps to reproduce

As you can see here, I've highlighted a .zip file to show that there are several file types, but it's very har du differentiate them
![Screenshot 2021-06-30 at 09 40 23](https://user-images.githubusercontent.com/1426125/123925161-eecc1b00-d98a-11eb-8c98-92351b6f9ac7.png)

**Comment by nul800sebastiaan** [comment]
Hmm, not sure what's going on @steinmeier - I just tested in 8.13 with a regular media picker and a multinode treepicker but it's supposed to have black text for the file extensions:

![image](https://user-images.githubusercontent.com/304656/123928504-41f39d00-d98e-11eb-84b3-27a973a58865.png)

So maybe an upgrade didn't complete? Usually changing the version in clientdependency.config should help clear browser cache to get the latest available stylesheets.

**Comment by greystate** [comment]
Just did a quick look here - the styles for the labels in the site @steinmeier's screenshot is from, have a specific `color: #fff` set (where a quick check in a v8.14 site has `color: #1b264f`).

Both from the `.umb-file-icon .file-icon > span { ... }` rule in the CSS.

If it's indeed a ClientDependency issue, it's going to affect a lot of sites, since this was a site created on Umbraco Cloud, and thus might have been upgraded automatically there. We should expect any upgrades to bump the CD-version, no?

**Comment by nul800sebastiaan** [comment]
Ah of course, Cloud sites should get their CDF version bumped automatically.

I see this [was indeed white until v8.14](https://github.com/umbraco/Umbraco-CMS/blame/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/umb-file-icon.less#L23) in the 2 years before the text was indeed white. So in that case I would encourage you to upgrade to 8.14 🙂
