### ISSUE TITLE
Add svg as an Image mediatype by default

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#10604]
### Discussed in https://github.com/umbraco/Umbraco-CMS/discussions/10602

<div type='discussions-op-text'>

<sup>Originally posted by **sigrundis** July  6, 2021</sup>
### Umbraco Version
8.14

### Description
When uploading an SVG it is uploaded as media type `File` instead of `Image` or the like.

**Comment by nul800sebastiaan** [comment]
From the discussion: 

>this is due to SVG by default not being set as an image file type. In order to preserve backwards compatibility, we currently can't change that (people expecting SVG to be created as a File will suddenly get different behavior.
>
>This seems like a good one to fix for v9, adding svg here and mark it as breaking change: v8/dev/src/Umbraco.Core/Configuration/UmbracoSettings/ContentImagingElement.cs#L17
>
> I'll put this as up for grabs to fix in v9, accepting svg as an image by default.

**Comment by sigrundis** [comment]
Hmm... sounds like I was not clear enough 😅  

The feature I'm requesting is that when uploading media through the content section - I want to be able to select a media type for it - like you can do when you upload it through the media section:
![image](https://user-images.githubusercontent.com/35728588/124611356-a7a1c680-de71-11eb-83e9-cc6af2b18ad9.png)

In the example described above, I don't want it to get the media type: image or file, I want it to be uploaded as my custom media type: SVG - since the field has a validation that the media used must have the type: SVG.

AND/OR 
Be able to choose the default media type for media uploaded through the content section for a specific field. 

The reason:
Improve editor experience for the content editors. When they add content for a media field, they usually do so in the content section while updating the content. It could be annoying for them needing to close what they are doing to add the media type through the media section since they get a validation error if they upload it through the content section - because they can't make sure the file is uploaded as the correct media type for the field. 

To put things to perspective, I'm using your suggestion here:
https://github.com/umbraco/Umbraco-CMS/issues/4921#issuecomment-850350891

But yeah, I want to be able to add media through the content section without getting a validation error because I can't make sure the file has the correct type if I do it from there. 

Hope I managed to explain it properly this time 😅 Or am I misunderstanding something, is it maybe possible? 😊

**Comment by JamieTownsend84** [comment]
@nul800sebastiaan hey - I am looking at 'up for grabs' issues, this one appears to be resolved in v9 so not sure if you want to mark this issue as closed now?

**Comment by nul800sebastiaan** [comment]
Thanks @JamieTownsend84 - with the new media picker this is now handled appropriately in both v8 and v9 👍 Time to close!
