### ISSUE TITLE
v9-rc001: Can't upgrade using SQL CE

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#10626]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-RC001

### Bug summary

When upgrading to RC1 the migrations can't be run as there is an error

![image](https://user-images.githubusercontent.com/527305/124945220-dc468700-e005-11eb-8929-7377863bc138.png)

Ultimately it looks like you can't run the migration that calls

    ALTER TABLE [cmsContentNu] ALTER COLUMN [data] NTEXT NULL

### Steps to reproduce

1. Install v9 beta with SQL CE
2. Try to upgrade to v9 RC

### Expected result / actual result

Expected it to upgrade nicely

**Comment by bergmania** [comment]
Thanks.. Seems to be required the nucache table has content, otherwise it works..

Looks like a v8.15 issue? 

@nul800sebastiaan, are we sure SQL CE upgrates to 8.15 are working?

**Comment by mattbrailsford** [comment]
Could be 8.15 actually as I copied an older database

**Comment by bergmania** [comment]
The migration that fails is from 8.15, and the underlying SQL should be identical. Could be nice to have fixed for 8.15 before release of that :)

**Comment by nul800sebastiaan** [comment]
Yes, all the upgrade testing I do is on SQL CE since.. that's what I would expect to break the most. Not had any problems on v8.

Are you sure that mapper gets applied correctly during upgrades as well? https://github.com/umbraco/Umbraco-CMS/pull/10592/ 

Ah.. but it's suddenly taking a column and making it nullable, which.. is fine if there's no data in it yet, but I guess fails if there is. I'll have a look.

**Comment by nul800sebastiaan** [comment]
No.. there's plenty of data in it. However it didn't actually update the column definition: 

![image](https://user-images.githubusercontent.com/304656/125039373-b3220700-e096-11eb-9cea-0a7af8824610.png)

Which might be because the SQL CE syntax provider knows that this is not possible so won't attempt it? So then we're back to.. does the mapper work when in upgrade mode? 🙈

**Comment by nul800sebastiaan** [comment]
And just to double check, on a fresh, non-upgrade v8 install, it is set as nullable: 

![image](https://user-images.githubusercontent.com/304656/125040093-85898d80-e097-11eb-933a-b715039ac392.png)

**Comment by patrickdemooij9** [comment]
Is there a good way to get around this? I always use SQL CE for my packages as it's easy to setup and I am also stuck with this error.
I know that you were able to regenerate your database in V8, but I haven't figured out how to do that here yet. I tried removing the connection string, but then it just complains about not being able to find a database

**Comment by deMD** [comment]
> 
> 
> Is there a good way to get around this? I always use SQL CE for my packages as it's easy to setup and I am also stuck with this error.
> I know that you were able to regenerate your database in V8, but I haven't figured out how to do that here yet. I tried removing the connection string, but then it just complains about not being able to find a database

For me it started working when I deleted all content from cmsContentNu AND deleted the nucache files on disk

**Comment by deMD** [comment]
Any updates on this as I am also running into issues :/

**Comment by deMD** [comment]
@patrickdemooij9 There is an umbraco/install folder. deleting the file in there as well as removing the query string seems to work for me (I also deleted all cach files, logs and other temp files but I don't think that is necesary)

**Comment by nul800sebastiaan** [comment]
I've just upgraded a v8 SQL CE database to v9 RC003 so this seems to be fixed now, I'll close this one.
