### ISSUE TITLE
Umbraco 9 package template issue with dots "." in name

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#10641]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco 9RC

### Bug summary

Just tried to play with the dotnet new-templates for creating a package which is really nice!

Found an issue when naming my package something that contains a dot "."  ie:

```
dotnet new umbracopackage -n Markus.Package
dotnet new umbraco -n Markus.Package.Testsite -p Markus.Package
```

This will generate names and variables in the .target file in the package that contains the "." char which is an "invalid character".

I guess there would be a way to "clean" the input as the package name is a valid name and works as a solution.

### Steps to reproduce

```
dotnet new umbracopackage -n Markus.Package
dotnet new umbraco -n Markus.Package.Testsite -p Markus.Package
```

Try to build the Testsite with `dotnet build`

**Comment by DanDiplo** [comment]
Yeah, this threw me, too, especially as the default namespaces will be based on the package name, so you'd often want to use a period in the name.

**Comment by nikolajlauridsen** [comment]
Hey thanks for reporting, I've come across this once or twice too, but I don't know if there's a good way to solve it.

This essentially boils down to how our templates currently work with the `.targets` file. We have a default "template" targets file where the properties and paths all default to something with `UmbracoPackage` in the name, for instance `UmbracoPackageContentFilesPath`. The template will then replace all these instances with the name you specify so everything matches up. This is why the error occurs because it'll try to use a dot in the property name which is not allowed. 

There is a workaround though if you want a dot in your default namespace like @DanDiplo mentioned, in your csproj file you can specify the default namespace like so:

```xml
<PropertyGroup>
  <TargetFramework>net5.0</TargetFramework>
  <RootNamespace>Your.Desired.Namespace</RootNamespace>
</PropertyGroup>
```

You might also want a dot in your package name, this can also be achieved through the ccsproj file like so:

```xml
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PackageId>Your.Desired.Package.Name</PackageId>
</PropertyGroup>
```

**Comment by enkelmedia** [comment]
Hi!

Hmm I guess that it would be possible to just strip the dots "." from the variable names? Create a method

```
public string MakeSafeVariableName(string incommingPackageName)
{
   return incommingPackageName.Replace(".","");
}
```

And then use this method in all places where variables for the target file is created or used, and then use the other "none stripped" value for things like namespace etc.

**Comment by bergmania** [comment]
If just is was that simple ;)

I created a PR: https://github.com/umbraco/Umbraco-CMS/pull/11041
