### ISSUE TITLE
V9: Cannot access IMvcBuilder

### ISSUE THREAD

**Issue by lauraneto** [umbraco/Umbraco-CMS#10709]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

Due to the way the code is built, there is no way to configure the IMvcBuilder.
In my case, I wanted to try to enable xml in my controllers by using the `.AddXmlSerializerFormatters()` extension method of the IMvcBuilder but at the moment this is not exposed.

### Specifics

The `.AddMvcAndRazor()` method can receive an `Action<IMvcBuilder>` as a parameter but at the moment `.AddBackOffice()` (from which it is called) does not expose it.

### Steps to reproduce

Install Umbraco 9 and try to enable xml on the controllers by using `.AddXmlSerializerFormatters()`

### Expected result / actual result

I expected the IMvcBuilder to either be accessible, or a way to configure it to be exposed.

**Comment by Shazwazza** [comment]
There's a couple options. You can call `var mvcBuilder = Services.AddControllersWithViews()` again to gain access to the builder. Calling this multiple times shouldn't harm anything since all these calls are doing is adding services to the container if they haven't already been added.

Else, the umbraco method: `services.AddMvcAndRazor` takes a callback with the MVC builder, it would be possible to replace this call `AddBackOffice` https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/src/Umbraco.Web.UI.NetCore/Startup.cs#L44 with all of the manual calls: https://github.com/umbraco/Umbraco-CMS/blob/25e2016e826989d4b0f8145c482e988f8210faa1/src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilderExtensions.cs#L34 and then pass your callback to the `AddMvcAndRazor` method. 

and/or, you could create a PR that allows a callback to be passed to AddBackOffice to pass to AddMvcAndRazor

**Comment by lauraneto** [comment]
Thanks for the reply!
I'm using the workaround for now, but it would indeed be a much cleaner solution to be able to pass in the callback.
I hope #10713 gets merged soon 😊

**Comment by nikolajlauridsen** [comment]
I've merged #10713 🎉 So I'll go ahead and close this issue 😄
