### ISSUE TITLE
media.GetCropUrl returns ImageProcessor Querystring params and not ImageSharp Querystring params

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#10725]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-rc001

### Bug summary

imagecropper setting "Square" : 560 x 560

`image.GetCropUrl(cropAlias: "Square", width: 1200);`

returns 
`/media/o24liyyr/dummy-639-200x300.jpg?center=0.8933333333333333,0.56&mode=crop&heightratio=1&width=1200&rnd=132714307686070000`

that's the old imageprocessor querystrings...

imagesharp equivalent is

/media/o24liyyr/dummy-639-200x300.jpg?**rxy**=0.8933333333333333,0.56&**rmode**=crop&**height**=1200&width=1200&rnd=132714307686070000`

### Specifics

[ImageSharp.Web/Processors/ResizeWebProcessor.cs](https://github.com/SixLabors/ImageSharp.Web/blob/master/src/ImageSharp.Web/Processors/ResizeWebProcessor.cs)
shows the new querystring params.

Note that ratio (heightratio/widthratio) is no longer present (ratios are maintained with rmode=max/min)

Not sure if `.SetRequestParser<QueryCollectionRequestParser>()` could be used to remap existing imageProcessor querystring variables.. though with no ratio support it's maybe not a simple mapping?

### Steps to reproduce

Create Media with crops, Add a defined Crop,  and use `image.GetCropUrl(...)`

### Expected result / actual result

crop urls would behave the same as in umbraco8.

**Comment by nul800sebastiaan** [comment]
Thanks @mistyn8 - this is being worked on in https://github.com/umbraco/Umbraco-CMS/pull/10715 👍

**Comment by mistyn8** [comment]
Ah apologies.. there were no open issues... didn't think to search pull requests.

**Comment by nul800sebastiaan** [comment]
Not to worry! Better 1 issue too many than 1 too little. :-)

**Comment by ronaldbarendse** [comment]
@mistyn8 Unfortunately it's a bit more work then renaming some query string parameters, as `ImageSharp.Web` doesn't support the crop coordinates Umbraco uses when moving the crop box and/or zooming. Even the focal point coordinates are swapped (`center` used top/left and `rxy` uses left/top) and like you mentioned, the width/height ratios are automatically maintained based on the resize mode (or can otherwise be calculated on the server beforehand if one dimension is provided).

PR #10623 fixes these issues by updating the generated image URLs and implementing a custom `CropWebProcessor`.

Maintaining compatibility with v8 will be quite difficult, as not all query string parameters, processors (like [overlay](https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/overlay/) and [watermark](https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/watermark/)) and formats (like [WebP](https://imageprocessor.org/imageprocessor/plugins/webp/)) are supported (yet). But if you really want this, implementing a custom [`IRequestParser`](https://docs.sixlabors.com/api/ImageSharp.Web/SixLabors.ImageSharp.Web.Commands.IRequestParser.html) and rewriting the parameters would indeed be a possibility (although that's not exactly what this interface is intended for). This will expose the same image on different URLs though, so maybe it would be better to implement this as redirects?
