### ISSUE TITLE
Unexpected value: 'on'. Expected one of these: 'Yes'

### ISSUE THREAD

**Issue by jebastin-jeyaraj** [umbraco/Umbraco-CMS#10728]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

7.13.0

### Bug summary

Getting the error, **Unexpected value: 'on'. Expected one of these: 'Yes'** after upgrading the Umbraco Forms from version 7.0.5 to 7.5.4. This issue is happening with a checkbox data type.

### Specifics

**I've checked in the following browsers:**
Google Chrome Version 91.0.4472.164 (Official Build) (64-bit)
Firefox 90.0 (64-bit)

**Screenshots of error:**
![image](https://user-images.githubusercontent.com/44998835/126755216-56b5dcf0-69e9-4f56-92ff-6df06b4479d2.png)

### Steps to reproduce

Step 1:
Create a form with a checkbox property.
![image](https://user-images.githubusercontent.com/44998835/126755337-02792336-7467-424e-92e8-611b988e3e6c.png)

Step 2:
Set up these configurations in the form.
![image](https://user-images.githubusercontent.com/44998835/126755386-f926e086-8529-4c64-9298-daf7e7f02480.png)

Step 3:
Submit the form & the error message is being displayed near the checkbox:
Unexpected value: 'on'. Expected one of these: 'Yes'

### Expected result / actual result

**Expected result:**
The form should be submitted successfully & the data is logged in the form entries.

**Actual result:**
Form is not getting submitted & an error message is shown near the chekbox:
Unexpected value: 'on'. Expected one of these: 'Yes'

**Comment by nul800sebastiaan** [comment]
Hey there @jebastin-jeyaraj - Umbraco version 7 is no longer maintained, except for security issuees.

You can read more about that here: https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/

Maybe this issue was fixed in a later version and you could try Umbraco 7.15.7. 

I would recommend heading to the forums where our friendly community can help you find the best solution or workaround for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
