### ISSUE TITLE
Mandatory field doesn't revalidate after inputing some value

### ISSUE THREAD

**Issue by aelghoneimy** [umbraco/Umbraco-CMS#10831]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.11.2

### Bug summary

1. Open a document with mandatory field
2. Type in the name
3. Save or Save and Publish
4. Mandatory field shows error
5. Fill the mandatory fields with some value
6. Save again

![image](https://user-images.githubusercontent.com/4632474/129014346-0266d394-852e-4799-a800-6652e1ead3a7.png)

### Specifics

The bug seems to be related to RichTextEdit

### Steps to reproduce

1. Open a document with mandatory field
2. Type in the name
3. Save or Save and Publish
4. Mandatory field shows error
5. Fill the mandatory fields with some value
6. Save again

![image](https://user-images.githubusercontent.com/4632474/129014346-0266d394-852e-4799-a800-6652e1ead3a7.png)

### Expected result / actual result

After filling in the mandatory fields or after saving the error tooltip should disappear and the document should be saved

**Comment by emma-hq** [comment]
Hiya @aelghoneimy 

Thanks for reporting! This one has been fixed in a later release so I will close. I've attached a gif of the behaviour working as expected in the latest release.

![validation](https://user-images.githubusercontent.com/78740801/129018488-43b7f615-d1d7-4408-a038-02164894f790.gif)

Emma
