### ISSUE TITLE
Umbraco v8 is almost usable on small mobile devices, but has many styling and usability bugs

### ISSUE THREAD

**Issue by Superhands89** [umbraco/Umbraco-CMS#10921]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.2

### Bug summary

I don't know if it's in scope to have basic content editing available on mobile devices, but I just think it's a shame as the interface is 95% responsive already.

### Specifics

I'm using a Samsung Galaxy A52 5G personally but the same issues appear on other real devices.
1) Save and Publish button overflows the screen width.
2) The screen is scroll-able horizontally in most cases.
3) When clicking on a content node the cursor auto-focuses on the first field which causes the keyboard to popup.
4) Scrolling through a content node can lead to accidentally re-ordering nested content items.
5) Slide-out panels can be wider than the screen so content cannot be seen.

+ others...

### Steps to reproduce

Pull out your phone, log into Umbraco, try to edit the homepage content.

### Expected result / actual result

The backend is fully responsive.

**Comment by bjarnef** [comment]
I agree there could be more focus on making the backoffice useful and acessible from mobile devices. Although many content editors probably update websites/web apps from desktop or tablet, I believe there are scenarios where content editors may want to update a page/article, e.g. while using public transportation.

It might worth to consider for backoffice rebuild or part of the accessibility enhancements.

//cc @nul800sebastiaan @nielslyngsoe @madsrasmussen @BatJan

**Comment by nul800sebastiaan** [comment]
Thanks @Superhands89 and @bjarnef - Most of all we believe that managing content effectively is better on larger screens and that will be our main focus. 
Improving usage on smaller screens is on our radar. While working on the new backoffice project we'll take those considerations into account. 

I'll close this issue for now, since we have no immediate plans to work on this, but I'll add the idea label so it will pop up in review at a later time. 👍 

Thanks again!
