### ISSUE TITLE
Removed user groups coming back OnExternalLogin, OnAutoLinking

### ISSUE THREAD

**Issue by robgha01** [umbraco/Umbraco-CMS#11026]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0

### Bug summary

I'm implementing a BackOfficeExternalLoginProviderOptions OnExternalLogin and OnAutoLinking the problem im facing is
the removed user group is not persisting or somehow added back after it is removed see videos. I tried to pin point what could be the problem but as of now im lost as it looks ok when i debug and right after i save and get the user again it looks correct its after exiting the "OnExternalLogin" that the group "editor" comes back. I need to remove this group from the user as thay have other isolated groups to work with.

https://gist.github.com/robgha01/edbe0f4f81980cce9591badb7123cd9e
https://user-images.githubusercontent.com/362726/132068535-f3889b20-0259-4479-8706-826c3b303387.mp4
https://user-images.githubusercontent.com/362726/132067317-3a194f0f-9d23-40fc-ab28-4b33a18ef93c.mp4

if it can help here is the saml login provider setup: https://gist.github.com/robgha01/77ac58faf3167697bf5fc05cce2fdc97

### Steps to reproduce

Implement any custom login provider OAuth for example and try to remove the editor group of the user in the OnExternalLogin or OnAutoLinking by first getting a IUser using the IUserService.

### Expected result / actual result

Expecting the user group editor to get removed and not come back.

**Comment by emma-hq** [comment]
Hiya @robgha01 

Thanks for this report - I'll take a look at the video and see if I can recreate. I'll shout if I have questions and update on progress right here.

Speak soon,

Emma

**Comment by emma-hq** [comment]
Hey @robgha01 

I've taken a look at the issue - thanks especially for the videos. I can see that when you're stepping through the code during debug, the group reappears. It's because you're removing the group that you've added as the default user group - set in the BackOfficeExternalLoginProviderOptions. This means it is getting added again. Have a look here 

[https://github.com/umbraco/Umbraco-CMS/blob/d9f92ec91dc49032d0bbeb7130a6b485667abf1d/src/Umbraco.Web/Editors/BackOfficeController.cs#L507-L517](https://github.com/umbraco/Umbraco-CMS/blob/d9f92ec91dc49032d0bbeb7130a6b485667abf1d/src/Umbraco.Web/Editors/BackOfficeController.cs#L507-L517)


I'm going to close, as this means it isn't a bug we're looking at here. 

Emma
