### ISSUE TITLE
Rebuild causes build errors in Visual Studio 2020 Preview 4 and  Visual Studio 2019

### ISSUE THREAD

**Issue by JohnBergman** [umbraco/Umbraco-CMS#11215]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

Brand new project created using the visual studio 2020 File-New method.

close, reopen visual studio, then do a rebuild all with multiple projects of multiple types (in my case I have a database project, a couple of class libraries that are .net 5, and the umbraco project.

Right-clicking on the solution and choosing rebuild leaves a bunch of build errors, as seen in the imag
<img width="1207" alt="Rebuild Errors" src="https://user-images.githubusercontent.com/5505858/135164187-4e9c9175-152f-4bef-b2f6-33ca574eeb53.png">
es

If I right click on the project itself and select build or rebuild it is fine.  

### Steps to reproduce

See the bug summary for a way to see the repo steps.

### Expected result / actual result

Regardless of how I choose the build/rebuild, the results should be consistent.

**Comment by OzoneNZ** [comment]
Can confirm this happens in Visual Studio 2019 as well as 2022 Preview 4

Issue seems to be the `BeforeTargets` value specified on the `CopyUmbracoAssets` target here, which is leading to the target being skipped when running a **Rebuild** rather than just a **Build**

https://github.com/umbraco/Umbraco-CMS/blob/release-9.0.0/build/NuSpecs/build/Umbraco.Cms.StaticAssets.targets

`BeforeTargets="Rebuild;Build"` rather than just `BeforeTargets="Build"` may fix this

Replicated on a fresh `9.0.0` project

**Comment by p-m-j** [comment]
Closed by #11216
