### ISSUE TITLE
Adding tabs to a member type breaks member creation

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#11255]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

If you create tabs in a Member Type it will break member creation, because afterwards the "Login", "Email", "Password" and "Member Group" properties will be missing. Trying to then restore back to the original setup, tabs cannot be removed, resulting in a permanently broken Member Type.

### Steps to reproduce

1. Take the default Member Type
2. Add two tabs: "Something" and "Umbraco".
3. Move the default "Membership" group to the Umbraco tab.
4. Add a groupless property to something, for example a Content Picker.
5. Save, then go to the Members section and try to create a member.
6. All the properties needed to create a member are missing, after trying to save you will even get validation errors, but you can't see where.

### Expected result / actual result

We have tabs with groups, and still the "Properties" group with all the required fields to make a member.

---
_This item has been added to our backlog [AB#14273](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/14273)_

**Comment by bjarnef** [comment]
The "Membership" group is still hardcoded group added by default, but I noticed it currently isn't possible to move this to a tab instead in 8.17-RC https://github.com/umbraco/Umbraco-CMS/issues/11132

I haven't checked in v9 if it is different, but I guess is should be possible to move the properties to a different group or tab as long the properties still exists.

**Comment by nul800sebastiaan** [comment]
This is sure doing some weird things! I couldn't see it at first but when looking at the "Umbraco" tab in the end of this video I can see there should be a lot more properties.

This was introduced in 8.17 with the new tabs feature and is not just a v9 issue.

https://user-images.githubusercontent.com/304656/135852549-8ebe3be6-d44f-46ee-a9e0-392a3c1ec9b1.mp4

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan Umbraco always adds the Membership group, even though the required/default properties are already present in another group/tab. It will then remove empty groups on save again, so that's why you only saw it in the member type designer (at 0:18 in the video).

The username, email, password and member group picker are added dynamically as generic properties when rendering the member, so that's why the Generic tab shows up.

Adding to this weirdness, some of the default properties are moved to the Info Content App, so that's why you were missing some of them 😉 This is probably also where some filtering logic didn't work correctly with tabs and caused validations errors on properties that weren't rendered...

I have a fix ready for all this weirdness (which I'll link to this issue), so would be great if you could test that out when I've submitted it!

**Comment by Zeegaan** [comment]
This issue should be fixed in https://github.com/umbraco/Umbraco-CMS/pull/11587
