### ISSUE TITLE
Performance issue loading javascript files in back office takes 12-15 seconds

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#11393]
### Bug summary

The back-office is very slow to load, mostly due to 2 javascript files taking a long time, between 12-15 seconds
They also load in series rather than in parallel.
![image](https://user-images.githubusercontent.com/354777/137669262-38fae060-fa01-4fb4-8e4f-2053209fa923.png)

### Steps to reproduce

load the back office with dev tools open.

### Expected result / actual result

I expect this should load in under 3 seconds and would prefer it to load in under 1 second.
Umbraco version 8.17.0 loads in 0.7 seconds.

---
_This item has been added to our backlog [AB#15135](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15135)_

**Comment by KevinJump** [comment]
Hi,  

I think these settings don't fix the issue they merely mask it. 😞 

if you set your minification settings to `AppDomain` then the js files are only built once per run (and cached based on the appdomain) 

The first request when you start the site up still has poor performance for the minification of the` umbraco-backoffice-js` file (and depending on how many plugins you have `umbraco-backoffice-extensions.js` is also slow). 

With appdomain set, all subsequent requests are fast, because they are using the cache, but there is an issue with the generation of these files

**Comment by bielu** [comment]
@KevinJump it does not only load slowly but also causing really high cpu usage on that process, I think that ticket should be reopen... @nul800sebastiaan can we reopen that issue?
