### ISSUE TITLE
V9: Error when you try to invite user via backoffice 

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco-CMS#11453]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

This is on Umbraco 9.0.1 Umbraco Cloud 

### Bug summary

When you try to invite a user from the backoffice you will get an error I have included the error in the specifics

### Specifics

![Skærmbillede 2021-10-22 kl  09 57 14](https://user-images.githubusercontent.com/2038482/138416290-8fe75b40-947c-4269-affa-75b689cb2f5c.png)
 
 Unfortunately there is no error in the logviewer for this one 

### Steps to reproduce

1. Go tot the backoffice 
2. Go to the user section 
3. Click invite user 
4. Follow the flow for this and click invite user

### Expected result / actual result

I would expect that I can invite users to the backoffice without any issues

---
_This item has been added to our backlog [AB#15057](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15057)_

**Comment by bjarnef** [comment]
Oh I just noticed this as well also v9.0.1 🙈
It would be great to get this fixed as we soon need to invite content editors, but currently we need to create users manually or enabled the invited user afterwards.

**Comment by ronaldbarendse** [comment]
Looks like the error occurs because 9.0.1 doesn't set the sender address to the back-office user that's sending the invite anymore (which was a bug, as that might not be a valid sender address for the configured SMTP settings): https://github.com/umbraco/Umbraco-CMS/pull/11266.

Even though Umbraco Cloud adds a fallback for sending invitations without having SMTP configured, this doesn't expect the `null` value, hence the `Value cannot be null` error.

You can work-around this issue by at least providing the `Umbraco:CMS:Global:Smtp:From` setting as shown in the example on https://our.umbraco.com/documentation/umbraco-cloud/Set-up/SMTP-settings/. If you want to send out emails, you will need to configure the SMTP server anyway...

**Comment by bjarnef** [comment]
> If you want to send out emails, you will need to configure the SMTP server anyway...

Yeah, except when the client don't use form or similar to send emails, but only need the feature to invite other users. Previous this required SMTP to be configured, but in a V8 version this changed, so the invite user button always was shown on Umbraco Cloud environments and thus didn't required further SMTP configuration to use the invite user flow.

Not sure if it is related to this: https://github.com/umbraco/Umbraco-CMS/issues/11575

**Comment by bjarnef** [comment]
@ronaldbarendse it doesn't seem to be enough just providing the Umbraco:CMS:Global:Smtp:From setting.

It still throw this exception:

![image](https://user-images.githubusercontent.com/2919859/141685128-57513885-53a0-4643-b59b-7ce73ce5a780.png)
