### ISSUE TITLE
Adding hostname with granular permissions not working

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#11650]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

When a user only has permissions to set culture and hostname via granular permissions, a permission error is thrown when clicking the save button.

The user has access to the Culture and Hostnames menu item (because the user has the permission), but still when clicking save a permission error is thrown.

### Steps to reproduce

1. Set the following permissions on a group
![image](https://user-images.githubusercontent.com/2575817/142208689-1407db82-514a-45ff-9ebb-9c55df0a812b.png)
2. Add a user to the group and login with the user
3. Right a subnode to the node where use set the granular permission to allow Culture and Hostname
4. Add a domain
5. click save
6. An error is displayed

![hostname](https://user-images.githubusercontent.com/2575817/142209229-9a489574-3e87-4476-b700-eed87d7055f3.gif)
 

### Expected result / actual result

When setting Culture and Hostname permission in granular permission on a node, the permission should be inherited.

---
_This item has been added to our backlog [AB#15196](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15196)_

**Comment by elit0451** [comment]
Hi @jesperweber 

You are right, the issues are related! The problem is that the child notes are not inheriting the permissions of the parents, which explains why you get such error in the "Culture and Hostnames" case and why you can't sort on the #11066

**Comment by jesperweber** [comment]
I guess this issue is related as well: #10502

**Comment by nul800sebastiaan** [comment]
I've now investigated this and I'm afraid to have to disappoint you: this is currently expected behavior and we're not going to be able to change it. The description for Granular permissions is quite specific about this: 

![image](https://user-images.githubusercontent.com/304656/147935519-c396afcb-6f64-4649-bc2c-57d69920beea.png)


So on each user group you have "Default permissions" - they apply to all the nodes for that user.

![image](https://user-images.githubusercontent.com/304656/147935660-d18ec764-5705-46c7-94a7-d8c17712b879.png)


Then you have granular permissions, which describe what they do: "Set permissions for specific nodes" - so only to the single node you select there, they don't cascade down.

You can argue that is not what you expect, but this is how it works. Changing that now, would be a huge breaking change for everyone already using granular permissions. 😅 

I'm afraid we don't have any updates to permissions on the roadmap any time soon, it would be a huge task. The workaround I can suggest is to build your own custom hostname property editor maybe, then you have full control over which users would be able to use it and where. Sorry that I don't have better news for you!

**Comment by jesperweber** [comment]
Hi @nul800sebastiaan,

Okay, I see that the granular permissions says "Set permissions for specific nodes" and understand that this would be a breaking changes if it's not a bug, but a feature.

I guess what confused me and the administrators working with the groups and granular permissions, is that some of the granular permissions actually do cascade down. E.g. the Browse Node, Create, Delete and others, this made me believe that all granular permissions would cascade down and this makes it hard to know when to expect cascading and when not to.

It would be nice with some uniform rules or some kind of help text so users know what to expect, but this might be a new feature rather than a bug.

**Comment by nul800sebastiaan** [comment]
I think you might be able to combine multiple user groups to achieve what you want. 

Yeah you're totally right.. that is totally inconsistent and that's a shame.. I hope we can make permissions better in the future, but at the moment we're super stuck with what we have now, sorry. 🙁

**Comment by jesperweber** [comment]
Some of the sites we have are dynamic multi-site solutions with lots of users and user groups.

We can't use Default permissions as the user groups has different permissions depending on where in the content tree they are working.

Also it's not possible to use Granular permissions if they do not cascade down (hostname and sorting), because we will have to modify the user groups/granular permissions every time we add new content nodes, making it impossible to maintain the user groups.

Maybe the permissions will get an overhaul in the future, we have some feature requests for permissions for some of our customers in the public sector, but I understand this is not a small task :-)
