### ISSUE TITLE
Umbraco v8 high CPU usage.

### ISSUE THREAD

**Issue by AndreyKarandashovUKAD** [umbraco/Umbraco-CMS#11699]
### Which *exact* Umbraco version are you using? 

8.16.0

### Bug summary

We realized that we have high CPU usage in production and after profiling we found this in Azure Application Insights.
![8jLAf0c](https://user-images.githubusercontent.com/304656/146408819-7aa7c8b9-fa50-4416-b488-d1bc622e3a70.png)

Is it something that can be fixed without development?
If we receive a lot of requests in production our response time get slower and slower.

### Steps to reproduce

Refresh your start page frequently and check your CPU usage.

**Comment by AndreyKarandashovUKAD** [comment]
I'm not working with that project anymore, but we have seen that issue after. not sure if it's still the same trace.

**Comment by nikolajlauridsen** [comment]
Hey @AndreyKarandashovUKAD again sorry that this got to wait so long, it's understandable that you've moved on since then 😄 

However, with little to go on in terms of pointing down a specific issue that we can take action on I'll go ahead and close this one down for now. Please don't hesitate to comment here if you have more information, and then we can always open this one up again 😄
