### ISSUE TITLE
Nested content using custom validation on property fails to validate when item failed the first time

### ISSUE THREAD

**Issue by d-gibbs** [umbraco/Umbraco-CMS#11735]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

Custom validation when used on a property of a nested content item fails to validate if validation failed the first time.

### Specifics

Example property definition:

![image](https://user-images.githubusercontent.com/59481722/144996286-ad12f918-61b1-4142-b5ff-c0285806c94a.png)

### Steps to reproduce

- Add > 1 nested content items to field
- Trigger custom validation error (in our case enter > 120 chars into textarea field)
- Resolve issue, e.g. update content to be < 120 chars
- Submit form
- Observe that 'Parent validation error' is not cleared and form cannot be saved

Example vid:

https://www.awesomescreenshot.com/video/6305908?key=370e4dc68ca2ec18f7adce695a3dbee8

Note that this issue does not occur if there is only 1 nested content item saved against the field, the issue arises when there are > 1 items, for example:

https://www.awesomescreenshot.com/video/6322746?key=07f49132fb1b03d9c5d061cb762b3f38

### Expected result / actual result

We expect the validation to clear once the rule has been satisfied.

**Comment by d-gibbs** [comment]
This issue is also reproducable with a standard required field:

![image](https://user-images.githubusercontent.com/59481722/144997882-96daa920-80cb-432a-9717-ff2e67e23409.png)

Example vid:

https://www.awesomescreenshot.com/video/6322672

Note that this issue does not occur if there is only 1 nested content item saved against the field, the issue arises when there are > 1 items, for example:

https://www.awesomescreenshot.com/video/6322746?key=07f49132fb1b03d9c5d061cb762b3f38

This bug may relate to: https://github.com/umbraco/Umbraco-CMS/issues/10788#issuecomment-986661655

**Comment by d-gibbs** [comment]
Note that this issue does not occur if there is only 1 nested content item saved against the field, the issue arises when there are > 1 items, for example:

https://www.awesomescreenshot.com/video/6322746?key=07f49132fb1b03d9c5d061cb762b3f38

**Comment by emma-hq** [comment]
Hi @d-gibbs 

I have seen this bug before 🙈 I'm going to check to see if it's a regression. I'll update here

Emma

**Comment by nul800sebastiaan** [comment]
Did know you can configure a textarea to have a maximum amount or characters? 

![image](https://user-images.githubusercontent.com/304656/148088248-e2dc7a2f-f710-4137-aea3-fbbb253e2e9d.png)

If I read the regex correctly, you would get the same result just using that.

That said, I am afraid something went wrong on your site, probably during an upgrade from before this issue was fixed, as you can see it works as expected for me. 


https://user-images.githubusercontent.com/304656/148089554-3d80f2cd-d310-4a30-aa91-712a460edf1d.mp4



Often this is a problem with clientdependency, make sure to go into ClientDependency.config and change the version number in there (make it 1 higher). Sometimes it's also a problem that updated files don't get copied into the `~/umbraco` folder, so make a backup of that and delete the folder, then do a build in visual studio - NuGet should copy the folder with all it's content back in, if not then you could copy it from the zip download of Umbraco 8.17.1. Afterwards, bump the ClientDependency version again.

I'll close this for now, thanks for reporting!

**Comment by d-gibbs** [comment]
Thanks for testing this @nul800sebastiaan.

On reflection I think this may actually be a bug with Our.Umbraco.DocTypeGridEditor:
https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/

I've just created a fresh 8.17.1 install and couldn't reproduce the issue with a nested content field against a regular _page/document_, however _I can reproduce_ if using DocTypeGridEditor and adding as content to an editable zone. 

![image](https://user-images.githubusercontent.com/59481722/150518523-daddf9c8-72fe-4a1f-9fca-72c0f5a947c2.png)

We ended up working around this issue in the end but appreciate the investigation. I may raise this as a bug with DocTypeGridEditor if i can find the time.

Thanks again
