### ISSUE TITLE
Authorised update info page from 9.0.1 -> 9.1.2 didn't show current version only (5e02f241)

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#11754]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

When Updating to 9.1.2 the authorised update confirm step didn't show the current version
![image](https://user-images.githubusercontent.com/12418214/145566454-247b441e-42b3-45ee-974e-fde74685bc82.png)

### Steps to reproduce

udpate from 9.0.1 -> 9.1.2

### Expected result / actual result

Show the current version

**Comment by mistyn8** [comment]
The view report button also incorrectly compares 9.0.0 to 9.1.2?
https://our.umbraco.com/contribute/releases/compare?from=9.0.0&to=9.1.2&notes=1

**Comment by emma-hq** [comment]
Hiya @mistyn8 

We've had a chat about this one. The way that Umbraco 8 worked was to use the xml to generate the report but with the way that upgrades work in Umbraco 9, there's only the migration data to work with so essentially the report doesn't know if where we are coming from.

We'd like some help with this issue - the approach we'd like to take is to update the UI to reflect what that report will actually show, i.e. release notes for each version rather than specific notes from the version the user is upgrading from. With this in mind, I'm labelling as up for grabs :)

Emma

**Comment by kjac** [comment]
Hi everyone. This one seems to have gone rather stale, and it affects a rather old version upgrade (from 9.0.1 to 9.x). 

I'm going to close this in the assumption that very few are going to be affected by this moving forward - it's doubtful that a whole lot of brand new 9.0.1 projects will be created, and anyone migrating from 8.x should be targeting the latest 9.x,
