### ISSUE TITLE
Mandatory content picker field throwing a Value cannot be null error

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco-CMS#11829]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

When saving a page using a mandatory content picker in a block list, I get a Value cannot be null error.

### Steps to reproduce

- Create a page which uses a block list and add a block
- Edit the element type for the block and add a content picker field that is mandatory
- Edit the page and select a value in the content picker
- Save and publish the page

### Expected result / actual result

The page won't save and publish and the content picker field has an error next to it.  The error message is Value cannot be null.

The page should have just saved and published without error.

**Comment by emma-hq** [comment]
Hey @richarth 

I've had a play with this and am getting an issue too - although for me I get stuck on loading. The issue here is around data persistence. We have a blocklist property editor with one kind of data (in my test case it was just text) and we're then trying to ask it to accept another. It's something that we've looked at ways to handle but at present, what we do is warn the developer that there are issues around changing data types when they do that. 

So while we'd like to be able to publish without issues, it is likely that we'd go in another direction and tell the developer to remove the existing data before changing the datatype for the time being as the data persistence issue is quite broad and we're still looking at possibilities around how to handle that.  With this in mind I will close the issue but if you'd like to follow discussion on progress in this area, take a look [here](https://github.com/umbraco/Umbraco-CMS/discussions) to see what's already being said or to start a discussion.

Emma
