### ISSUE TITLE
RTE auto height adjustment sometimes fails

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#11839]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.0

### Bug summary

Sometimes the auto-height adjustment for the RTE  property does not work correctly. leaving the RTEs looking like this:
![image](https://user-images.githubusercontent.com/354777/148838396-9fcbd01c-7e7d-4200-9b97-86b93052e4e5.png)
This seems to occur in conjunction with opening an RTE within Nested Content.

### Specifics

I did not see any console errors in conjunction with the failure to resize the RTE

### Steps to reproduce

Given:
- An element doctype containing an RTE.
- A Nested Content datatype that includes said element.
- A content type with properties of type RTE and the Nested Content datatype.
- A piece of content using the content type where the RTE has content, and the Nested Content RTE does not.
When:
- I REFRESH the browser while editing the piece of content, 
- And expand the nested content to show the inner RTE (happens to be on another tab)
Then:
- I observe the main RTE is collapsed, as shown in the screenshot above.

This failure to resize is somewhat intermittent, I suspect a timing issue (perhaps font loading) or something is involved.
The resizing fails to occur in other circumstances also, but the above seems the most consistent.
Other scenarios could include just the RTE in a nested content data type. and switching tabs a few times, sometimes it fails to expand

In all cases clicking in the RTE edit area causes the resize to occur correctly.

### Expected result / actual result

I expect the RTE to be the correct size when opening the tab/nested content

**Comment by markadrake** [comment]
This behavior may be related. 

TBH I had a hard time trying to reproduce your issue @Myster. Could you tell me if you think what I've captured below may have the same root cause as your issue? I'm guessing they are related.

Steps in the case below:

1. Create a document type
2. Create a property with a block list data type
3. Configure that block list to include an RTE
4. Configure that block list for inline editing
5. Save the document type, create your content
6. Add 2+ RTE editors, add text if you like
7. Save
8. Open both blocks so you can see the content
9. Sort them
10. Watch the RTE height close completely, hiding your content
11. Resolve it by toggling the block list closed/open again

https://user-images.githubusercontent.com/713355/150909155-859fc07a-2f76-46e8-a47a-1be9bba38174.mp4

**Comment by Myster** [comment]
It does seem similar, the code to resize the RTE seems to not get triggered sometimes, perhaps your case has a different trigger (or not), or perhaps the trigger isn't 'general' enough. I can work around it easily enough by clicking in the RTE to trigger the resize. (although my RTE has more room to click that yours)

**Comment by Myster** [comment]
I also just noticed this on a 9.2.0 website, the RTE was on a tab (not in a nested content or block editor) 
It was a "simple RTE" with only Bold, Italic, Link

**Comment by kjac** [comment]
Hi everyone,

I can replicate this on V10, but it's quite hard and happens *very* rarely. Thus I suspect it's going to be equally hard to fix, but anyone feeling up for it should definitively have a go at it 👍

**Comment by nielslyngsoe** [comment]
Hi everyone, this issue has not been picked up by anyone. judging from the interesting and KJACs conclusion I will close it until further interest shows. I also have a feeling that this was fixed in some of the later versions.
