### ISSUE TITLE
Empty recycle bin view not found

### ISSUE THREAD

**Issue by ecca** [umbraco/Umbraco-CMS#11868]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0 (Linux)

### Bug summary

URLs for empty recyclebin fails because the views path have upper case letters in them even though the files are all lower cased. This breaks especially on Linux.

### Specifics

**Content**: views/content/emptyRecycleBin.html
**Media**: views/media/emptyRecycleBin.html

### Steps to reproduce

**Content**: Go to content -> Recycle bin -> expand menu -> Empty recycle bin

**Media**: Go to content -> Recycle bin -> expand menu -> Empty recycle bin

### Expected result / actual result

View for empty recycle bin should come up and allow us to empty everything at once

**Comment by garpunkal** [comment]
I'm seeing this as well on linux docker. Umbraco 9.2.0
![image](https://user-images.githubusercontent.com/13114807/151354905-66419c59-1bb1-4578-a36a-66172c7c7f83.png)

case sensitive issue?

**Comment by garpunkal** [comment]
yep, it should be lower case.

**Comment by dknippers** [comment]
Hi guys,

I could also reproduce the issue and believe I have found the source of this bug so submitted #12010 to fix this.
With the PR I now get the correct dialog both in content and media:
![image](https://user-images.githubusercontent.com/2269742/154143665-b6ad71de-969d-4fcb-9c28-714b32f6a0b3.png)

Hopefully someone from HQ can have a look at this and merge it soon as it is actually quite annoying you cannot empty the recycle bin on Linux at the moment. 

@nul800sebastiaan I hope you don't mind I tag you here, you seem to be the most active HQ member on the Issue tracker and I'm not sure if you guys get notified otherwise of new PRs for issues.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12010

@dknippers Yeah we have an overview!
