### ISSUE TITLE
CopyUmbracoFilesToWebRoot in UmbracoCms.targets has a condition which prevents files being copied after an upgrade

### ISSUE THREAD

**Issue by tompipe** [umbraco/Umbraco-CMS#11873]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17 (previous versions also affected)

### Bug summary

Consider the following:

- Developer 1 has an umbraco project checked out which is running 8.12.2 (or any prior version). 
- Developer 2 checks out the project, and performs an upgrade to 8.17 (or any version), commits and pushes the changes. A .gitignore file excludes the umbraco folder from being committed
- Developer 1 returns to the project, fetches the latest version from the repo, including developer 2's changes for the upgrade. 

### Scenario 1
On developer 2's checked out version, nuget **installed** the updated package, so the ```install.ps1``` script runs, and as the robocopy command within ```install.ps1``` has flags set to always copy existing files, the correct Umbraco files from the 8.17 nuget package are copied over to the web site root, overwriting any from 8.12.2.

### Scenario 2
Developer 1 has pulled the upgraded project, which now includes 8.17 in the packages.config. Nuget will **restore** any missing packages (and not install) so the ```install.ps1``` script does not get executed.

### Specifics

In both scenarios the ```CopyUmbracoFilesToWebRoot``` MSBuild target defined in ```UmbracoCms.targets``` will execute ```AfterBuild```. However, this has a condition defined on the Copy task to exclude files that already exist. 

In scenario 2, this exclude condition prevents the UmbracoFiles from being updated, effectively this version of the project on developer 1's computer now contains binaries from 8.17 but front end files and scripts from 8.12.2. 

Deleting the umbraco folder and rebuilding resolves the issue.

### Steps to reproduce

See above

### Expected result / actual result

The copy task in the ```CopyUmbracoFilesToWebRoot``` target should correctly copy over updated files from the nuget package folder in both scenarios.

This could be handled with the ```SkipUnchangedFiles="true"``` parameter instead of the ```!Exists``` condition - but this _could_ impact build time, as MSBuild would check file size and last modified time for each file, every time the solution is built. 

Additionally, a custom build task to undo any files copied over by any custom build targets should be considered, e.g so a clean of the solution would delete the umbraco folder etc. 

Its also possible that if a project has been upgraded through multiple versions, the umbraco folder might still contain files from an earlier version, which were removed in a subsequent version.

**Comment by nul800sebastiaan** [comment]
Hi @tompipe and thanks for the report. 

Unfortunately, over the years we've tried various permutations of all of the workflows and settings you've mentioned here. The current way is really the only way that has the least problems for most people, though sometimes it requires manual fixing. Most of all I would recommend that you put the ~/umbraco directory in git so that all of the problems you mention here will be avoided.

In v8 we're "abusing" nuget a bit for things it's not supposed to do, including that powershell file.

In v9 and onwards we're using nuget the proper way and this is no longer a problem.

We don't expect to make any more changes in the nuget setup for v8 from now on. As such, I'll close this issue and encourage you to consider putting the umbraco folder in source control.

**Comment by LottePitcher** [comment]
FYI there is further discussion on this topic in case it helps anyone here: 
https://github.com/umbraco/Umbraco-CMS/issues/10133
