### ISSUE TITLE
Multinode Treepicker searching doesn't work the same anymore.

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco-CMS#11917]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9
8.7.6 
8.17.1

### Bug summary
Multinode Treepicker searching doesn't work as it worked on 8.7.6 anymore.
There seems to be regression.
On 8.7.6 if you search for the entire node name you get the node in the search
On 8.17.1 if you search for the entire node name you don't get it anymore

Also, it is a buggy around special characters especially "_"

### Specifics
The gif will explain it a little bit better.
Left is 8.6.7 - Right is 8.17.1
![MultinodePicker](https://user-images.githubusercontent.com/83580347/151410006-52103627-b32b-4f57-a524-1724ea6cc8c8.gif)

### Steps to reproduce
1. Create a Multinode Treepicker and configure it
2. Create some content using the Multinode Treepicker
3. Try to add a node by searching for it with the entire name.
4. Searching the entire name of the node will give you the node on 8.7.6 but not on 8.17.1

### Expected result / actual result
Expected to get the node back if you write the same name.
Expected to work properly

**Comment by kjac** [comment]
Hi @sergiutesu,

Thank you for this - and apologies for the late response 😞 

This was changed in 8.8 to counter YSODs caused by certain characters that conflict with Lucene queries. See https://github.com/umbraco/Umbraco-CMS/pull/7330 for details.

You can still find the content if you search without underscores:

![image](https://user-images.githubusercontent.com/7405322/211734255-965e6f37-cfae-4cfa-bd40-94c44b0a128c.png)
