### ISSUE TITLE
Cannot acquire MainDom

### ISSUE THREAD

**Issue by Ibrahimogod** [umbraco/Umbraco-CMS#12038]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

```
{
    "@t": "2022-02-23T08:56:16.0195316Z",
    "@mt": "{FailMessage} ({Duration}ms) [Timing {TimingId}]",
    "@l": "Error",
    "@x": "Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.TimeoutException: Cannot acquire MainDom\r\n   at Umbraco.Core.Runtime.MainDom.Acquire() in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\MainDom.cs:line 172\r\n   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)\r\n   at Umbraco.Core.Runtime.MainDom.get_IsMainDom() in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\MainDom.cs:line 211\r\n   at Umbraco.Core.Runtime.CoreRuntime.AcquireMainDom(IMainDom mainDom) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 471\r\n   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\CoreRuntime.cs:line 183\r\n   --- End of inner exception stack trace ---",
    "FailMessage": "Boot failed.",
    "Duration": 53319,
    "TimingId": "5f5a93d",
    "SourceContext": "Umbraco.Core.Runtime.CoreRuntime",
    "ProcessId": 10540,
    "ProcessName": "w3wp",
    "ThreadId": 23,
    "AppDomainId": 7,
    "AppDomainAppId": "LMW3SVC4ROOT",
    "MachineName": "IBRAHIMOGOD-5D-",
    "Log4NetLevel": "ERROR",
    "HttpRequestNumber": 1,
    "HttpRequestId": "05a5a968-d1fa-4e94-80ef-5187372ff814"
}

```
### Specifics

Appreciate your urgently support to solve this issue, I'm working with SQLCE I just migrated my website and It failed to boot after installation process I'm hosting locally now but I'm planning to use TMD hosting, I've tried several solutions but It doesn't work , I'm not sure what causes this

### Steps to reproduce

All Solutions I found was related to azure and It's not for SQLCE

### Expected result / actual result

Boot Failed
Umbraco failed to boot, if you are the owner of the website please see the log file for more details.

**Comment by nul800sebastiaan** [comment]
Hi @Ibrahimogod - unfortunately I also have no answers for you. When this error happens we'll need to know how to reproduce it, usually though it happens intermittently and can't be reproduced, so it's very difficult to figure out what to fix if we don't know what the cause is. 

However, we would strongly recommend you do not use SQLCE for any hosted websites, SQLCE is "end of life" and no longer supported. It's fine for casual local development on a developer machine but not suitable for hosting on a public website. 

I suspect that your SQLCE database is probably in use by something and once you restart your site it would work again.,
If you have more details about this error, make sure to describe them in detail on the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

Once you have exact steps to reproduce the error we would be able to look into it again, but as said this error is too intermittent at the moment for us to have enough clues to know where to start.

**Comment by Ibrahimogod** [comment]
thanks a lot @nul800sebastiaan  any Recommended to Migrate the database from SQLCE to SQL Server?

**Comment by nul800sebastiaan** [comment]
There's a few different ways, these search results looks good 

- http://erikej.blogspot.com/2012/02/migrating-databases-between-sql-server.html
- https://blog.nicolaayan.com/2018/02/how-to-migrate-sdf-database-to-sql-server/
