### ISSUE TITLE
Error occurred during a cryptographic operation.

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#12082]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

Hi All,

we are registering a bunch of repeating exception logs with the following information and have no clue what this is about:

```
Path: /umbraco/RenderMvc
Type: System.Security.Cryptography.CryptographicException
Exception Message: Error occurred during a cryptographic operation.
Stacktrace: 

`at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input) at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.Unprotect(Byte[] protectedData) at System.Web.Security.FormsAuthentication.Decrypt(String encryptedTicket) at Umbraco.Core.StringExtensions.DecryptWithMachineKey(String value) in D:\a\1\s\src\Umbraco.Core\StringExtensions.cs:line 322 at Umbraco.Web.UmbracoHelper.DecryptAndValidateEncryptedRouteString(String ufprt, IDictionary`2& parts) in D:\a\1\s\src\Umbraco.Web\UmbracoHelper.cs:line 828 at Umbraco.Web.Mvc.RenderRouteHandler.GetFormInfo(RequestContext requestContext) in D:\a\1\s\src\Umbraco.Web\Mvc\RenderRouteHandler.cs:line 137 at Umbraco.Web.Mvc.RenderRouteHandler.GetHandlerForRoute(RequestContext requestContext, PublishedRequest request) in D:\a\1\s\src\Umbraco.Web\Mvc\RenderRouteHandler.cs:line 330 at Umbraco.Web.Mvc.RenderRouteHandler.GetHttpHandler(RequestContext requestContext) in D:\a\1\s\src\Umbraco.Web\Mvc\RenderRouteHandler.cs:line 74 at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context) at Umbraco.Web.UmbracoInjectedModule.RewriteToUmbracoHandler(HttpContextBase context, PublishedRequest pcr) in D:\a\1\s\src\Umbraco.Web\UmbracoInjectedModule.cs:line 299 at Umbraco.Web.UmbracoInjectedModule.ProcessRequest(HttpContextBase httpContext) in D:\a\1\s\src\Umbraco.Web\UmbracoInjectedModule.cs:line 144 at Umbraco.Web.UmbracoInjectedModule.b__18_4(Object sender, EventArgs e) in D:\a\1\s\src\Umbraco.Web\UmbracoInjectedModule.cs:line 412 at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`
```

**The solution is not hosted in a load-balancing environment and only has a single Web Site and App Pool on the server.**

Anyone with an idea? 

It seems like we are not the only ones with this:

https://our.umbraco.com/forum/using-umbraco-and-getting-started/106964-exception-message-error-occurred-during-a-cryptographic-operation

### Steps to reproduce

not clear

**Comment by nul800sebastiaan** [comment]
Hi there @deekoulos - unfortunately without any reproduction steps there's not much we can say about this either. I would recommend checking if you have a machinekey in your web.config, maybe adding one would help since it will stay the same even if the site might move to a new machine (azure app service).

Other than that the only other thing I could think of is to start comparing the web.config umbraco ships with, with the one you have and seeing if any of your customizations might be causing problems by reverting those.

In reality though, the error very much points to a load balanced setup.

If all else fails, you're probably going to have to dive into the source code to make any progress here.

If there's any steps to reproduce on a clean Umbraco install we can have another look.

**Comment by deekoulos** [comment]
Hey @nul800sebastiaan ,

thank you for your suggestions. it seems like adding a machine key to the web.config resolved the issue.
