### ISSUE TITLE
Umbraco 8.17.0 - Name of IContent is/was never "Dirty" in ContentService events

### ISSUE THREAD

**Issue by jerpenol** [umbraco/Umbraco-CMS#12131]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.0

### Bug summary

After changing the name of a Content Node and saving and publishing, the property `Name` is/was never dirty on `ContentService` events `Saving`, `Saved`, `Publishing` and `Published`. `TreeEntityBase` suggests that the name should be listed as dirty (added to `ContentBase._currentChanges` `IsDirty` or `ContentBase._savedChanges` = `WasDirty`).

Furthermore on the `ContentService.Published` event (could be on the other events as well) the name of the version with id that equals `IContent.VersionId` is exactly the same as the version with id equals `IContent.PublishedVersionId`, while these two Id's differ (`PublishedVersionId` is the older one). They both hold the newly edited name of the content node.

This combined looks like in some way content gets saved twice before publishing. The weird thing would be that "normal" properties (not base properties like Name) are dirty in all these cases.

I have a multilingual setup, but I am not sure if that has any influence. Furthermore, this might occur as well in Umbraco 9, since I have been experiencing similar issues in Umbraco 9.

### Steps to reproduce

- Change the name of an existing node
- Hook into `ContentService.Saving`, `ContentService.Saved`, `ContentService.Publishing` and `ContentService.Published`
- Loop through `PublishEventArgs<IContent>.PublishedEntities` or `ContentSavedEventArgs.SavedEntities` 
- Check if the name was listed in `IContent.GetDirtyProperties()` and through `IContent.WasPropertyDirty("Name")` and through `IContent.IsPropertyDirty("Name")`

### Expected result / actual result

Expected: The `Name` property **is** listed in the list of dirty properties, and therefore dirty when checked
Actual: The `Name` property **is never** listed in the list of dirty properties, and therefore never dirty when checked

**Comment by nul800sebastiaan** [comment]
I don't know if the node name was ever intended to be included in the list of dirty properties as that was supposed to be for custom properties as far as I can remember. You can get the current node name from the content service and compare it to see the difference, the variant names are also available, for example

![image](https://user-images.githubusercontent.com/304656/158194915-9b70b8fb-3a1a-43f9-8ad2-29c4f5bd1541.png)

Note that I did test this on 9.4 and we recently fixed something for that for the upcoming 8.18.1 and 9.4.0 releases so you might not have enough info at the moment but will when those releases are out. https://github.com/umbraco/Umbraco-CMS/pull/12069

I'm going to send this off to the team as it feel like it would be nice if we had a `IsNodeNameDirty` / `WasNodeNameDirty` or something like that.

I haven't checked the `Saved` or `Published` notifciations, (as opposed to the `Saving` and `Publishing` ones), but I am sure you can't see the difference at that point since `ContentService` will have the same content as the `Entities`. I'd be curious what exactly you'd like to be able to do with the information that the node name was changed? It seems to me that it's most useful to know what the previous vs. current node name is but maybe I'm missing an interesting use case.

**Comment by jerpenol** [comment]
@nul800sebastiaan The problem is that we update the Index OnPublished, because we fetch the data from the ContentCache. As I said in my initial bug, the version behind VersionId and PublishedVersionId contain the same properties and names, so I cannot compare those two. 

Additionally, I think it's a bit overkill that I have to manually compare per culture while this information is being collected by the Dirty-interfaces, why not specify a change by culture?
