### ISSUE TITLE
Folders created in wwwroot when using UmbracoMediaPhysicalRootPath 

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#12176]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

I'm using the fixes from this PR: https://github.com/umbraco/Umbraco-CMS/issues/12027 to store media on a network-drive.

Storing and removing images on the network path works great. But during startup the "media folder" is still created in the wwwroot.

### Specifics

I have configured a network drive to store the media:

```
  "Global": {
        "UmbracoMediaPhysicalRootPath": "\\\\data.obviuse.se\\Site1\\Media"
      }
```

Files get stored, read and deleted as expected but during startup Umbraco will create the "media folder" in the wwwroot.

So during startup the following folder is created in wwwroot:

`\wwwroot\data.obviuse.se\site1\media`

### Steps to reproduce

Se above

### Expected result / actual result

If `UmbracoMediaPhysicalRootPath` is configured the folder should not be created inside wwwroot.

**Comment by kjac** [comment]
Hi @enkelmedia,

Thank you for reaching out, and apologies for the late response.

You are correct, the local media folder is created regardless of the physical media file system root path. This is by design, not a bug. 

The local media folder shouldn't cause any issues though. If it does, we would very much like to hear about them. In that case, please reopen this issue with details 😄
