### ISSUE TITLE
Error404Collection not used when node is redirected

### ISSUE THREAD

**Issue by GertyEngrie** [umbraco/Umbraco-CMS#12182]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

Specific situation not using the configured the error404collection but showing the default notfound.cshtml from Umbraco.

### Specifics

We've configured an error404Collection but it doesn't kick in when a redirect has been added. So f.e. we have a page test-1, we rename it to test-2. A redirect is added from test-1 -> test-2. If we delete test-2 and surf to test-1, the default page not found (UmbracoWebsite/NotFound.cshtml) is shown instead of the 404 we've configured in the error404collection in the appsettings. 

### Steps to reproduce

- Configure Error404Collection in appsettings
- Create a page test-1
- Rename page to test-2
- Delete test-2
- Surf to test-1, notice the error404collection is not being used

### Expected result / actual result

Show the configured 404 page (even that means showing the default, not culture-related).

**Comment by nikolajlauridsen** [comment]
Hey @GertyEngrie, sorry for the late reply. 

Just got around to testing this in the latest V10, where the issue seems to have been resolved, probably by #12002, so I'll go ahead an close this as resolved for now, please don't hesitate to let us know if you're still having issues and we can have another go at reproducing.

Thanks for reporting 😄
