### ISSUE TITLE
Composition is now created as element type

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#12226]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

When creating a composition if now seems to create the document type as element type.

![image](https://user-images.githubusercontent.com/2919859/161739124-83f1fca5-7778-4471-8286-e451ceb52f93.png)

Previous it has just been a document type without template.

### Steps to reproduce

Create a composition document type and notice it is created as element type.

![image](https://user-images.githubusercontent.com/2919859/161739334-d0558fe8-b6f5-41d8-bc51-69452b6d3f94.png)

**Comment by bjarnef** [comment]
In Umbraco v8.14.4 it did this:

![image](https://user-images.githubusercontent.com/2919859/161745488-7f7ec7a9-d4f5-499c-b7a0-7f5f8efd4163.png)

**Comment by kjac** [comment]
@bjarnef I might be wrong here, but isn't it better to have compositions as elements? Or... does it introduce any issues for you to have compositions as elements?

**Comment by bjarnef** [comment]
@kjac yes, I guess you are right. I don't recall if document types previously in v8 could use element types as composition or if it was first supported later. When I tried this a few days ago I couldn't select the "Hero" composition on Home Page document type because it was an element type, but worked when I disabled "Hero" as an element type.

However when I try this now it does seem to work with a composition as an element type. Maybe it was because I removed the properties from the Home Page document type, but didn't saved it before selecting the "Hero" composition which the same properties.

**Comment by kjac** [comment]
@bjarnef fair point :) on the other hand, element types cannot be composed by non-element types, because it would break ModelsBuilder due to inheritance order (`IPublishedElement` models cannot implement `IPublishedContent` based interfaces).

I'm sure there are loads of pros and cons for both scenarios. 

It's a little bit disturbing that the change wasn't made consciously, but as part of a PR related to icons. However, since this has been the new normal since september 21, maybe the best thing to do is to leave it be as-is to avoid additional confusion? That is of course unless something decisively breaking pops up...

@nul800sebastiaan maybe you/HQ can weigh in here?

**Comment by bjarnef** [comment]
Yeah, I noticed most or the compositions we have in the project on v9.4.1 are element types, but not the SEO composition as it use `Cultures` property. Currently The element type does have the "Allow vary by culture", so I guess it can vary by culture.

**Comment by nikolajlauridsen** [comment]
Heya, sorry for the late reply. 

Looks like you got to the conclusion that it should be left as is, I tend to agree, so I'll go ahead and close this one for now. Don't hesitate to comment or create a new issue if you think this shouldn't be closed 😄
