### ISSUE TITLE
Anchor picker does not appear

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#12253]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.3

### Bug summary

When I add a link to a document that contains an anchor, the dropdown menu does not appear.

### Specifics

The RTE is located inside a grid editor, not sure whether it matters or not.
Tested with Chrome and Edge.

### Steps to reproduce

Insert an anchor in a document:

![image](https://user-images.githubusercontent.com/10199821/163152335-fdc0facf-058b-418b-a58d-dee0fc17408a.png)

Then I create a link to the page:

![image](https://user-images.githubusercontent.com/10199821/163152543-db3a4e06-171f-4bf6-b566-b4eb0dc8e973.png)

### Expected result / actual result

Expected result: the anchor selector should show the anchor available in the target page
Actual result: the list does not appear

**Comment by ssougnez** [comment]
I investigated a bit and here is a bit more information:

**The issue comes when the rich text box is in a grid.**

In this case, the condition `if (contentProperty.PropertyType.PropertyEditorAlias.InvariantEquals(Constants.PropertyEditors.Aliases.TinyMce))` in `ContentServiceExtensions` is not matched and the anchors are not retrieved.

Maybe this method should browse the controls of the grid and analyze the one with the "rte" view?

**Comment by marcoteodoro** [comment]
@sebastian-claesson I'm planning to take a look at this as I'm working on a v10 product that is implemented using the blocklist. 

But what other types should I take into consideration? Grid is not 11 - will it be added on v10 ish?

so should I concentrate on blocklist and nested content?

**Comment by rpjengaard** [comment]
@sebastian-claesson it seems like you have closed down the contribution on the V10 branch. Are @marcoteodoro supposed to add a PR for V11 instead? And in that case, what types are we supposed to support?

**Comment by marcoteodoro** [comment]
@nul800sebastiaan I've created a PR for this, but it would be great if someone else could look at this specific [part](https://github.com/umbraco/Umbraco-CMS/blob/c9410391bf5cc7a05c138208fbbbb404e85847bf/src/Umbraco.Core/Services/ContentServiceExtensions.cs#L73). 

This was a hack to test if the anchor link fix works, and it looks like it does. But need someone to review the culture issue. Why does it return null (unless I force the culture variable to be an empty string) if I don't have any culture assigned to it? 
![image](https://user-images.githubusercontent.com/3866444/204337383-d2a59c3b-1f87-432d-8388-5b778eb87a53.png)

A null value is actually because the property does support variation. https://github.com/umbraco/Umbraco-CMS/blob/c9410391bf5cc7a05c138208fbbbb404e85847bf/src/Umbraco.Core/Models/Property.cs#L157-L157

So, what do you recommend? Forcing null when culture is * or returns the default value? The one without culture? 

cc @rpjengaard
