### ISSUE TITLE
Unexpected error, cannot acquire MainDom after upgrading to v10 RC

### ISSUE THREAD

**Issue by alanwthom** [umbraco/Umbraco-CMS#12432]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.0.0-rc1

### Bug summary

- Perform a NuGet upgrade from v9.4.3 to v10.0.0-rc1
- Went through the upgrade steps detailed in the [documentation](https://our.umbraco.com/Documentation/Fundamentals/Setup/upgrading/version-specific#version-9-to-version-10)
- Ran upgrade locally (against Azure SQL database), site builds, starts and performs as expected
- Commit code to Git and deploy to Azure Web App (using same Azure SQL database)
- Site fails to start with the following error 
```Unexpected error, cannot acquire MainDom
System.ArgumentException: The specified invariant name 'System.Data.SqlClient' wasn't found in the list of registered .NET Data Providers.
```

I've also tried installing `System.Data.SqlClient` as a dependency, but this hasn't had any effect.

### Steps to reproduce

- Clean install of v9.4.3 on Azure SQL database
- Deploy to Azure Web App
- Upgrade to v10.0.0-rc1
- Deploy to Azure Web App

### Expected result / actual result

Expected result: Site to run on Azure Web App after upgrade to v10 RC
Actual result: Site does not run on Azure Web App after upgrade to v10 RC

**Comment by p-m-j** [comment]
Are you setting the connection string on azure with `SQLAZURECONNSTR_umbracoDbDSN`?

This will work rc2+ but not for rc1 as it will result in provider being set to `System.Data.SqlClient` instead of `Microsoft.Data.SqlClient`.

As a workaround for rc1 you can set the connection string without using the azure sql prefix and everything should be fine.

This issue was resolved by https://github.com/umbraco/Umbraco-CMS/pull/12408
