### ISSUE TITLE
RTE strips image tags of src attributes on save

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco-CMS#12523]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

On "save" and "save and publish", src attributes are stripped from within rich text editors creating broken images.

### Specifics

adding media before save:
![image](https://user-images.githubusercontent.com/1363512/171577229-69c19e49-d7af-43e1-ac6c-bd856cfa5be2.png)

`<p><img src="/media/1nglku5e/billede.png?rmode=max&amp;width=500" alt="" width="500" height="281.2816188870152" data-udi="umb://media/53b54cdd9ce448ef9c0ee2760193a618" /></p>`

after save:
![image](https://user-images.githubusercontent.com/1363512/171577401-e74e124b-3adf-4a8a-ad6a-149c7d7ef6b9.png)
`<p><img src="/?rmode=max&amp;width=500" alt="" width="500" height="281.2816188870152" data-udi="umb://media/53b54cdd9ce448ef9c0ee2760193a618" /></p>`

### Steps to reproduce

- Create a content type with an RTE property, and make sure the media picker is allowed in the configuration.
- Create a content-node
- Add an image via the RTE media picker
- "Save" or "Save and publish"

**Comment by nul800sebastiaan** [comment]
Hi there @krebil, that's certainly not the experience you should have. Unfortunately, it seems like there's something wrong in your setup since a clean install of Umbraco doesn't have this problem. 


https://user-images.githubusercontent.com/304656/171586266-98a32682-eb83-4dc6-aa75-b6c564fe8598.mp4

If you have additional steps to reproduce the problem we can have another look.

**Comment by krebil** [comment]
Yes it seems like it only happens if you have some configuration of the figure tag in CustomConfig -> style_formats

For example
` {
        "title": "figure",
        "block": "figure",
        "wrapper": true
      }`
