### ISSUE TITLE
CS8669 Nullable reference types warning in Sitemap.cshtml

### ISSUE THREAD

**Issue by alandraper** [umbraco/Umbraco-CMS#12549]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5

### Bug summary

Sitemap.cshtml line 24 
void Traverse(IPublishedContent? node)

should be 
void Traverse(IPublishedContent node)

\Website\umbraco\PartialViewMacros\Templates\SiteMap.cshtml(24,36): warning CS8669: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.

### Steps to reproduce

Create new Umbraco project. Build it. See the warning.

**Comment by Ambertvu** [comment]
@alandraper did you perhaps selected net 6 during the installation? I believe nullable reference types are fully supported from net6/umbracov10

**Comment by alandraper** [comment]
This is an .Net 5 / Umbraco 9.5 site.

**Comment by kjac** [comment]
In V10 these files have been moved to a Razor Class Library, so you shouldn't see these kinds of warnings in your build.

As a side note: For V10 (.NET6) the nullable notation (`IPublishedContent?`) is correct in the context of this particular view 😄 

I'll go ahead and close this issue now. Please feel free to reopen if this is still causing issues on V10.

**Comment by alandraper** [comment]
But shouldn't it _not_ use nullable reference types in Umbraco 9?

**Comment by kjac** [comment]
Well... nullable reference types are available in .NET5. 

By default they are disabled at a project level, but they can be enabled by adding `<Nullable>enable</Nullable>` if you fancy.

One could argue that the built-in template snippets shouldn't be using nullable reference types for V9 since they aren't enabled by default at project level. That's a fair argument. But we won't be taking steps towards changing them, since V9 has been surpassed by V10 (which has long term support).
