### ISSUE TITLE
v10: ImageSharp HMAC not working

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco-CMS#12582]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10 rc5

### Bug summary

With ImageSharp v2 you can secure URLs with HMAC through ImageSharpMiddlewareOptions. Unfortunately this doesn't seem to be used by Umbraco as GetCropUrl is not generating HMACs and therefore all images will fail with a 400 error code.

(Transferred from #12581)

### Steps to reproduce

Add this to ```ConfigureServices```.
```csharp
        services.Configure<ImageSharpMiddlewareOptions>(options =>
        {
            options.HMACSecretKey = new byte[] { 1, 2, 3, 4 };
        });
```
Now images generated with GetCropUrl will return HTTP 400 error.

### Expected result / actual result

Umbraco should use HMACSecretKey to generate correct URLs.

---
_This item has been added to our backlog [AB#20792](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20792)_

**Comment by jannikanker** [comment]
Looks like there's something underway to fix this in https://github.com/umbraco/Umbraco-CMS/pull/12376 ?

**Comment by ronaldbarendse** [comment]
Hi @Nuklon, we couldn't get support for HMAC image processing protection into Umbraco 10.0, but as @jannikanker mentioned, we did start working on it in PR #12376 and will ship this in an upcoming minor.

You can already create a custom `IImageUrlGenerator` that does add the HMAC token to all generated URLs, but currently not all image requests in the backoffice use this, so you might see broken images (400 errors) in the overview of the media section, etc. This is also something that's fixed in the linked PR, so you probably want to wait for that to be released 😄

**Comment by nielslyngsoe** [comment]
Hi @Nuklon I'm closing this issue as this feature has been implemented for v.12 as part of this PR:
https://github.com/umbraco/Umbraco-CMS/pull/14181
I hope that works for you and thanks for making us aware about this missing feature.
