### ISSUE TITLE
V10 - Changing UmbracoPath in appsettings does not work

### ISSUE THREAD

**Issue by albinj** [umbraco/Umbraco-CMS#12593]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

In v9 you are able to change the Umbraco backend url using the UmbracoPath appsetting. In v10 you will get a blank page when you change the backend url. 
I think it has something to do with the new `Umbraco.Cms.StaticAssets` Razor library

### Specifics

Chrome dev tools shows that the assets files are missing:

<img width="1036" alt="Screenshot 2022-06-20 at 14 23 06" src="https://user-images.githubusercontent.com/525843/174611572-f8b3d7ed-27f6-4b46-aa8c-0345acd71ab7.png">

### Steps to reproduce

Create a new umbraco site and install it as normal
modify appsettings.json
```
{
  "Umbraco": {
    "CMS": {
      "Global": {
        "ReservedPaths": "~/app_plugins/,~/install/,~/mini-profiler-resources/,~/my-secret-backend/,",
        "UmbracoPath": "~/my-secret-backend",
        "IconsPath": "~/my-secret-backend/assets/icons"
      },
    }
  }
}
```

run website again
goto https://localhost:44356/my-secret-backend

### Expected result / actual result

Expect to see the Umbraco backend login page (like in v9)
Actual result was a blank page

---
_This item has been added to our backlog [AB#20467](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20467)_

**Comment by bergmania** [comment]
Sorry for the late reply. It is correct this feature is currently broken. We are looking into ways to resolve this, but we are a bit limited in what we can do. 
The reason is because static assets are loaded from the Razor Class Library, and here we can't rename the folder.

The workaround - Even that it sucks - should be to rename the `staticwebassets/umbraco` folder in the nuget cache for the specific version of `umbraco.cms.staticassets` you use.

![image](https://user-images.githubusercontent.com/1561480/184813957-21c08014-91a7-4d8c-b442-6a7bb27e08e6.png)

**Comment by Navorski** [comment]
@bergmania  Thanks for your reply, but even with renaming the folder this issue is still present. it is indeed not the nicest solution, but if it would work i would gladly use it. now i am obliged to stay on the v9 because a lot of devices in the field depend on an API that is on the custom location.

If you mean the nuget cache in this location
**%userprofile%\.nuget\packages\umbraco.cms.staticassets\10.1.0\staticwebassets**

renaming the **umbraco** folder to **custom** for example.

In addition with these changes
**appsettings.json**

"Umbraco": {

    "CMS": {
      "Global": {
        "UmbracoPath": "~/custom",
        "ReservedPaths": "~/custom,~/apidocs,~/mqtt",
        "IconsPath": "~/custom/assets/icons",
      },
    }
  },


and in the csproj file 


<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <RootNamespace>Control_Delta.SITE</RootNamespace>
        <DefaultItemExcludes>$(DefaultItemExcludes);App_Plugins/**;</DefaultItemExcludes>
        <DefaultItemExcludes>$(DefaultItemExcludes);umbraco/**;</DefaultItemExcludes>
        <DefaultItemExcludes>$(DefaultItemExcludes);wwwroot/media/**;</DefaultItemExcludes>
        <UmbracoWwwrootName>custom</UmbracoWwwrootName>
    </PropertyGroup>

In visual studio i cleaned the solution, and after running, it is still the same behavior. a white page.

**Comment by bergmania** [comment]
@Navorski, that should do the work.. 

Did you test on Umbraco 10.1.0 linke the version in the path says?

**Comment by Navorski** [comment]
![image](https://user-images.githubusercontent.com/7352877/184825587-adde849e-e932-41f1-a680-adecefac7e39.png)
Yes i did

**Comment by bergmania** [comment]
@Navorski, you are right.. This does not work. I'm sorry.

The RCL creates a json file in the bin folder with all the parts, these has the umbraco/ prefix.

**Comment by bergmania** [comment]
@Navorski, I gave it one more try and have a workaround. Instead of renaming the folder in the cache, you can copy it into the wwwroot folder of you project. 
![image](https://user-images.githubusercontent.com/1561480/184873248-1404411f-f24c-4c36-b396-e2edaa2312f2.png)


![image](https://user-images.githubusercontent.com/1561480/184872867-aae453a3-7fbd-4bc3-8379-eb503977cb6f.png)

**Comment by kjac** [comment]
@Navorski thank you for reaching out and thank you for being so helpful with testing various solutions.

This issue has been discussed both internally and with some external stakeholders, and the consensus is that the feature should be removed entirely from Umbraco.

The recommendation is to apply IP restrictions or similar public access limitations to */umbraco*. See [this article](https://our.umbraco.com/documentation/Reference/Security/Security-hardening/) for inspiration. The article is slightly outdated and is being rewritten for V10 (and not least for the removal of `UmbracoPath` as a configurable setting), but it is still relevant as-is.

I'm closing this issue now. Feel free to reach out if you have any questions 😄

**Comment by SimJWalter** [comment]
such a lackey attitude, invent a best parctise and throw it on the "too difficult" pile.  Well done, completely resolved.

**Comment by Navorski** [comment]
Remove it entirely? thats even worse. We are having applications in the field that rely on a path like this (without Umbraco) we are facing a major problem if this would be completeley removed and forced to be /umbraco. 
for now we are on u10, with copying the static files manually. This is working fine for us.

**Comment by SimJWalter** [comment]
I can't see that I'll be using u10 any time soon

**Comment by kjac** [comment]
@SimJWalter please do try to keep a friendly tone here. 

@Navorski can I ask you what your use case is for changing the path?

**Comment by SimJWalter** [comment]
What it comes down to for me is that clients don't want to see the word 'umbraco' stuck on their admin URL, it's unprofessional and detracts from the value of the deliverable because 'umbraco' is not a facet of my clients' businesses whereas maybe /siteadmin or /cmsportal is, we don't know this in advance and you certainly can't, I imagine even in Denmark your clients would wonder why they're logging into an allen-key, it looks like the url to a product page.  I wouldn't want a site from me to look like www.furnitureoutlet.com/**bicycleclip** or something, it's irrelevant.
Secondly, it's not just a feature, it's a part of your system that was introduced for a reason, possibly security based but thats not MY primary intention for using it
If anything you should be looking for ways to make it easier to implement custom url extensions for the BO not eliminate it

**Comment by Navorski** [comment]
It was a design choice in the past to change the backend URL to something not commonly known as a default CMS, but we are using the backend API's for other purposes as well, 
But the bigger issue with this is that we also developed a system driven by umbraco, a .Net application, and IoT devices that are communicating to a custom umbraco API, and that API is mapped by the umbraco system to 127.0.0.1/**umbraco**/abcAPI, and all these devices/clients are deployed in the field, so we cannot just change the URL to something else, this would need an update an all devices, we just cannot do this.

**Comment by Navorski** [comment]
i know you can do that (at least i know it now, but the choice was made in the past not to do this) and it is already deployed and used with the /umbraco/ part in the url ;-)

**Comment by SimJWalter** [comment]
I didn't say the word "umbraco" is unprofessional, what I'm telling you is that as a word it is irrelevant in the context. In my view changing the admin url should be a mandatory part of the installation process.  I personally don't care what your platform is called and clients dont either, nice as it is.

**Comment by richarth** [comment]
In our use case we had a client's security team request that we change the URL, to make it less obvious that it's an Umbraco site.

If there is an Umbraco security issue it theoretically increases the time until they get attacked and gives us a bit more time to mitigate/patch.

**Comment by BartDM** [comment]
I have to pile on this discussion. As @richarth already mentioned, our security  department is unwilling to accept an backend URL with Umbraco in. This way it's too easy to find out the architecture from the site.
Just as they don't allow /admin/ in the URL path as an URL to the backend.

As I was making the proposal to move to Umbraco with 25 websites, this was still documented as a feature in V9!

Just blocking bij IP is not always possible. Our users connect by a shared VPN solution from a datacenter in Amsterdam. We can't allow all the IP's from the datacenter (the VPN product range) as these IP's are shared between different customers.

Regards,

Bart

**Comment by kjac** [comment]
Hi @BartDM,

I understand the sentiment. But simply renaming the login path does not make the system architecture more secure. It only adds a layer of obscurity which can be circumvented if the renamed path leaks (unless of course you change the path super frequently, which I assume you don't since it would be a nightmare for the editors).

To add the kind of security you (and your security department) is looking for, fortunately you have better options at hand:

1. Add 2FA/MFA challenge to the backoffice users.
2. Use an external authentication provider - ideally one tied to the organisation AD (Azure AD or similiar).
3. A dedicated admin instance with IP restrictions (which I understand you can't use, but included here for the sake of completion).

**Comment by TRexStark** [comment]
@kjac I must agree with the guys above.

It's not always about security, it's more about branding, context and some corporate bs (from clients) if I must say ... You have few cases here that explain why this should be a default feature (or available somehow) and I'm not going to repeat what has been said already, but I can add that most of the CMS Platforms out there allow you to change the admin or backoffice URL.

If there is a workaround in v10 (Great!), but in this case, I guess a lot of people will stop at that and never upgrade if this feature is never allowed, which will result on Umbraco implementers dropping in the future and migrating somewhere else with more freedom.

if this is a business decision from Umbraco to enforce its brand name upon the world, it needs to be revisited and look at how the digital world is changing to a more free internet instead of getting locked into a corporate bubble that won't last.

The question we can ask you is if it's time for us to look somewhere else if this feature is important to us?

**Comment by dlidstrom** [comment]
Has anyone tried to berried the admin url using rewrite rules?

According to the [documentation](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting):

> Because the client isn't redirected, the URL in the browser's address bar doesn't change. Clients can't detect that a URL rewrite operation occurred on the server.

**Comment by dlidstrom** [comment]
@tedse1982 Try this out. It seems to work, apart from just after logging in which goes to "umbraco". But for logged in users who go to "site/contoso" it seems to stay on that url. Of course this is a hack and it would be better if Umbraco HQ would support this fully. Maybe it is so simple to support that it only requires another small fix to the post-login code redirect.

```csharp
            var options = new RewriteOptions()
                .AddRewrite("contoso", "umbraco", true);
            app.UseRewriter(options);

            app.UseUmbraco()
                .WithMiddleware(u =>
                {
                    u.UseBackOffice();
                    u.UseWebsite();
                })
                .WithEndpoints(u =>
                {
                    u.UseInstallerEndpoints();
                    u.UseBackOfficeEndpoints();
                    u.UseWebsiteEndpoints();
                });
```

**Comment by SimJWalter** [comment]
edit the umbraco.directives.js and add a build task to your project to overwrite it in the output path

**Comment by nul800sebastiaan** [comment]
Since this question comes up some times, I've summarized the reason why this was done. I know the people commenting here don't accept that you can't customize the path any more, so no need to comment that you don't like it, trust me, we know! 😅 

Over the years, we have had many issues reported with plugins not working because the URL of the backoffice was renamed. This could be overcome by extra care and attention from plugin developers, but it's been a struggle as those developers don't know to expect the name change.

The breaking point for us (as Umbraco HQ) came when we wanted to move towards using Razor Class Libraries (RCLs) for the backoffice assets. RCLs provide a much more robust way of installing and deploying NuGet packages that contain static assets, making the developer experience better. The trade-off here: we can't rename the directory from Umbraco to something else. 

Additionally, the same plugin developers that already knew to look for sites changing the `/umbraco` URL were for the same reason unable to use RCLs for their packages, for the exact same reason, the umbraco path has to be consistent for this to work.

Unfortunately, we didn't see a way out of this and we weighed reliable installs and deploys against the obscuring of the Umbraco path. Realizing that there are very robust ways to protect the backoffice, even if it is on a predictable path, was the biggest factor in deciding to lean towards a better install/deploy experience vs the relatively small amount of people wanting to customize the backoffice URL. 

Hope that gives a bit more insight.

## How can we allow it again?

As said, we hear you, some of you really don't like this decision. 

So as a call to action: if you know of any way that we can avoid having to keep the path to `umbraco` then by all means, we'd love to hear about solutions to the RCL problem. As far as we can tell, we need to define a directory to put our static assets in, NuGet / the dotnet framework in turn doesn't allow us any flexibility with that. 
If we can find a way to make this flexible, with the same reliability of installing/deploying and making sure that package developers don't have to know anything about the umbraco path then we can consider having a look at that.

Personally, I don't know how the upcoming new backoffice will be deployed, but I imagine it will be in much the same way as we have to do it today, bundled in the NuGet package. So in that case, a solution would benefit many future versions as well.

**Comment by JasonElkin** [comment]
Has anyone tried doing this with a reverse proxy? It should be possible to put the Backoffice behind one (and even rewrite `/umbraco` to `/custom` in the responses from the server.

YARP can do this in app (i.e. no external service) but other reverse proxies are available (IIS _can_ do it).

The benefit of this approach is that you don't have to "mess" with Umbraco itself - which would solve the upgrade problem @SimJWalter.

**Comment by TRexStark** [comment]
@JasonElkin it's not a total proof with IIS. when you do that, login and logout, the path will revert back to umbraco. Plus for those who do a full rebrand, there are many other things that require a more in-depth work. The Invites to the backoffice as example, get messed up too, because they remain pointing to the umbraco path, then the title (meta tag) etc etc.

**Comment by JasonElkin** [comment]
Yes @TRexStark, Umbraco's not designed to be white-label, so there's a bit more work to do if you want to remove more of the public facing references to Umbraco but it's not insurmountable (YARP + response transforms, custom email service etc. for what you mention). 

A proxy is easy, will maybe get maybe 80% of the way there and will be enough for many use cases.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/do-we-really-need-to-define-a-custom-route-for-signalr-hub/3021/2

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/new-install-with-remote-db-backend-url-issues/7024/2
