### ISSUE TITLE
v9 - v10 upgrade process should be smoother.

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco-CMS#12659]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10

### Bug summary

Manually deleting folders in the /umbraco directory is an unusual step and is catching people out.

As it's a manual process with multiple steps it also makes the upgrade look more complicated than it actually is.

### Specifics

I've noticed that a number of people have been caught out by the need to delete specific folders as part of the [upgrade process from v9 to V10](https://our.umbraco.com/Documentation/Fundamentals/Setup/upgrading/version-specific#version-9-to-version-10) (step 9).

In previous Umbraco versions we're used to everything in the /Umbraco folder just being taken care of as part of the NuGet install. I'd expect when installing that if Umbraco has placed files in the project, then subsequent Umbraco versions that need those files gone would be responsible for removing them.

Is it possible to make it so that these files are taken care of automatically?

### Steps to reproduce

Upgrade a v9 project to V10.

### Expected result / actual result

I didn't expect to have to manually remove files/folders.

**Comment by nul800sebastiaan** [comment]
I think it's a wonderful suggestion but unfortunately not workable for us to take care of manually, the problem is that the NuGet upgrade already fails the build before we can even get to the Umbraco upgrade installer. In the older NuGet we could hack in some powershell scripts to help with this, but that is no longer possible on the dotnet core versions of NuGet (thankfully!). 
Equally, we can't just upgrade people's csproj file from using .NET 6 if they were using .NET 5 before on Umbraco v9.

So for now, we'll have to take the hit temporarily and point people to the documentation. It's a short-lived problem, as v9 only lived for a short time and we expect most new installs to be starting on v10.

Thanks for the suggestion though, I have always been pushing these kinds of hacks for upgrades because I agree they can be difficult and confusing if you just naively do what you think is "normal" by doing a nuget upgrade. It was not fun or easy to maintain these hacks though and it's actually a relief that we can no longer run "funny" powershell scrips during NuGet installs, that also means we don't need to debug the plethora of edge-cases when the scripts would fail. 😅
