### ISSUE TITLE
SQLite Alter throws null

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#12676]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

In one of my packages, I have a migration that updates a column from non nullable to nullable. However, due to the limitations in SQLite, it'll throw an error.
![image](https://user-images.githubusercontent.com/11466511/178041950-216f8d51-6842-4605-ab02-48233986c7bf.png)

I did read a bit on this as I am quite new to SQLite and I know this isn't really possible with SQLite, but wouldn't it be better for Umbraco to either handle that case or to throw an error itself. Would love to know what the consensus about this is!

### Steps to reproduce

Try to alter a non-nullable column to a nullable column in a migration while running SQLite.

`Alter.Table("SeoToolkitSitemapPageType").AlterColumn("ChangeFrequency").AsString().Nullable().Do();`

### Expected result / actual result

Ideally, it would also work on SQLite, but that might be a bit difficult with the SQLite restrictions. Otherwise would be nice to provide a good way to work around it.

---
_This item has been added to our backlog [AB#20784](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20784)_

**Comment by nul800sebastiaan** [comment]
Thanks @patrickdemooij9 - had a chat with the team about it. 
At the moment we haven't really tested many (if any) migrations for SQLite. Your suggestion to then add a `NotImplementedException` is what we'd prefer to do for now, instead of letting this migration fail because it can not work at the moment.

If you still would like to make it work then the suggestion would be to use raw SQL queries to add a new column, copy all the data over, and then delete the old column and rename the new column to the old column's name.

**Comment by bergmania** [comment]
IMO `NotSupportedException` is the right type. With a description of how to work around it. Before when our migrations had to support both SqlServer and SqlCE we also often had to special case SqlCE.

**Comment by nikolajlauridsen** [comment]
I'll go ahead an close this since this is not supported in SQLite, but a nice error has been implemented in #12848
