### ISSUE TITLE
Datepicker property returns datetime in wrong timezone when set via DateTime.Now

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco-CMS#12722]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.4

### Bug summary

In the Publishing event, i set the value of a datepicker to the current date and time using:

`contentItem.SetValue("start", DateTime.Now);`

After saving the date is shown correctly in the backoffice, correctly in the umbracoPropertyData table.
But at the frontend the time has 2 hours less. My computer timezone is UTC+1 (Europe/Amsterdam)

### Specifics

When I update the field with

`contentItem..SetValue("start", contentItem.PublishDate);`

the date is showed correctly in the backoffce, database and frontend.

### Steps to reproduce

Set the computer's timezone to Europe/Amsterdam

Create an Publishing event and set the date via Datetime.Now

```
        public override void Publishing(IContentService contentService, PublishEventArgs<IContent> args)
        {
            foreach (var contentItem in args.PublishedEntities)
            {
                    contentItem.SetValue("start", DateTime.Now); //Fieldname is "start"
            }

        }
```

After publishing, the date show correct in the backoffce and in the database.
At the view the date is 2 hours back in time. (or 1 hour without daylight saving).

### Expected result / actual result

I woud expect that the date in the view matches the date in the backoffice/database.

**Comment by nul800sebastiaan** [comment]
> In the Publishing event, i set the value of a datepicker to the current date and time using:

If you're setting times programmatically, you need to be aware of the server timezone vs your browser's time. We handle this for you automatically when you do the same action in the content editor.
The time displayed to you in the Umbraco backoffice is offset from the stored time on the server to show the time in "your timezone". 

I guess you have 2 options:

1. If you're expecting times to be displayed "correctly" for you, you can do the offset manually in your code.
2. Disable `Offset time` on the date picker datatype, when you do this it will always show you the time that is saved in the database.

![image](https://user-images.githubusercontent.com/304656/180216775-905f4d22-67f2-4974-98da-ab31a78416e3.png)

In either case, this is entirely expected behavior and hopefully you understand better what is happening now. 

Ps. On our wish list for the future is that we always save DateTime in UTC ([though it has pitfalls](https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/), so we'll have to remember that).

**Comment by mcl-sz** [comment]
Thanks for your reply @nul800sebastiaan! I fixed it by setting the properyvalue via a string instead of DateTime:

`contentItem.SetValue("start", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));`
