### ISSUE TITLE
Trying to change member password results in 'Password cannot be changed without the old password' error

### ISSUE THREAD

**Issue by AsmusAB** [umbraco/Umbraco-CMS#12811]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.4

### Bug summary

When trying to change the password of a member an error appears.
"Password cannot be changed without the old password"

![bug](https://user-images.githubusercontent.com/17725024/183649301-feec0930-f1b3-43e8-a2c2-ee65fe017fa6.PNG)

Our MemberShipProvider is setup as follows:
`<add name="UmbracoMembershipProvider" type="Umbraco.Web.Security.Providers.MembersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="10" useLegacyEncoding="false" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Hashed" allowManuallyChangingPassword="true" />`

### Steps to reproduce

Choose a member and change their password

**Comment by dinc5150** [comment]
I have the exact same issue in 8.18.4 after upgrading from 7.15.7

I have tried different combinations of enablePasswordReset and allowManuallyChangingPassword in the membership providers in the web.config without any luck.

It seems to only be affected if you specify the password (e.g. reset password checkbox unchecked).
When ticking  Reset Password tickbox instead of entering a password, it does successfully reset the password 

The following video shows how the password reset works when checked, but does not work when manually entered
[Password reset does not work](https://vimeo.com/738832085/01d2d0e067)

**Comment by nul800sebastiaan** [comment]
While it's confusing UI, this is indeed how it's intended to work, the checkbox is there to reset the password without having to know the previous password. With that new password you could do a password reset on the frontend and set it to whatever you want it to be.

We're not planning to update this in v8 any more, but now you know how to get it to reset a password successfully and with that move on.

**Comment by dinc5150** [comment]
So just to clarify, this will stay with the option to supply a new password, but will always though an error is used?

**Comment by dinc5150** [comment]
For others out there with the same issue, it has been fixed in #12306 and released in V8.15.5
