### ISSUE TITLE
Umbraco 10 2FA throws console exception for 402 response to a Post endpoint before the 2FA code can be entered

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#12817]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1

### Bug summary

Umbraco 10 2FA throws console exception for 402 response to a Post endpoint before the 2FA code can be entered. I'm not sure if the exception happens prior to the 2FA page being rendered or after. But it does happen prior to submitting the code. The 2FA login process does work, however.

![Screen Shot 2022-08-09 at 7 11 21 PM](https://user-images.githubusercontent.com/1504331/183777336-1c7f033c-71fd-4c9b-bd12-ce3ad3f80fd7.jpg)

### Specifics

I used the sample code on the website to build my 2FA process, though I wrote my own TOTP/QR code handling. The sample code I used was from the initial launch. I took a look at the sample code today and it appears to be the same.

### Steps to reproduce

Log in with a 2FA process using the sample code. When the 2FA page is shown, the JS console will show the exception.

### Expected result / actual result

No console exception.

**Comment by bergmania** [comment]
Hi @argentini..

402 response sounds like the right status code, when requesting 2FA. But sounds like a bug if this is leaking to the console.

**Comment by argentini** [comment]
@bergmania Understood.

It seems that a standard 200 code would be more appropriate since 402 is currently assigned to "Payment Required" and the authentication was successful. In that case the user is presented with a new form to submit which also should return a 200. I have also read about a proposed 250 code for this specific scenario. But I'm sure the team has already discussed these options prior to building the feature :)

**Comment by nul800sebastiaan** [comment]
I just remember when we first added 2FA in.. I want to say early v8, not sure when it was exactly, that it was not possible to use 200 because we couldn't detect that a 2FA prompt was needed, probably something with AngularJS - so we chose a status code that would otherwise never be used in the login screen. 

All 402 responses will show this in the console:

https://httpstat.us/402

![image](https://user-images.githubusercontent.com/304656/185369762-b284a87d-56b7-4c07-bb7c-d05459185970.png)

For example, the same shows in v8.1.1 with 2FA enabled: 

![image](https://user-images.githubusercontent.com/304656/185372024-15433f1b-7de2-4e67-81df-f689ac67c8cb.png)

It's not harmful, it doesn't break anything, I suggest we leave it alone.

**Comment by kjac** [comment]
It would seem @nul800sebastiaan is right on the money here... it is indeed a 402 so AngularJS can handle it explicitly - see https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js#L255

Chrome logging it to the console is "just how Chrome works" with 40X codes. It is annoying but there is nothing harmful in it.

If a status code is accepted as the standard for MFA we should certainly consider updating the source to match. For now though I will go ahead and close this issue.
