### ISSUE TITLE
Login macro rendered incorrectly in rich text grid editor.

### ISSUE THREAD

**Issue by jbreuer** [umbraco/Umbraco-CMS#12837]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

The login macro has a form. This is rendered incorrectly when it's added rich text grid editor. If the macro is added directly to the template it does work.

### Specifics

The node in Umbraco:

![image](https://user-images.githubusercontent.com/5444597/184608113-a7ff55a7-3858-4b94-84d6-f712a6a9dba8.png)

The template in Umbraco:

![image](https://user-images.githubusercontent.com/5444597/184608172-8d72297d-29ec-4a35-89fc-775c14c59b51.png)

The rendered page on the frontend:

![image](https://user-images.githubusercontent.com/5444597/184608239-b0f6ef12-498b-493c-a735-993b5fd54684.png)

### Steps to reproduce

Start a clean Umbraco website and add the starter kit: https://our.umbraco.com/packages/starter-kits/the-starter-kit/

Than add the login macro from the docs: https://our.umbraco.com/Documentation/Tutorials/Members-Registration-And-Logins/index-v9

Allow macros to the grid:

![image](https://user-images.githubusercontent.com/5444597/184608708-64e0c29f-fa9b-47f8-9ee7-d4e7b3564f5c.png)

Then insert the login macro to the rich text grid editor. See the screenshot from the specifics.

### Expected result / actual result

The login form should be rendered the same way in the rich text grid editor as when it's added to a template directly.

**Comment by nul800sebastiaan** [comment]
Note that the grid is being deprecated in (tentatively) v13 (https://github.com/umbraco/rfcs/blob/main/cms/0024-implement-the-new-backoffice.md#grid-layout) and I wouldn't recommend starting new builds with it. 

I'm surprised you even got the macro in the grid RTE as for me the macro disappears whenever I insert it, like in issue https://github.com/umbraco/Umbraco-CMS/issues/11755 

This seems to be a problem other people are having as well, I you might want to try this snippet I found: https://gist.github.com/EpicOfficer/0587a68c38454ca1e02e7138e23a04fc

Unfortunately I don't think we'll be spending time trying to get either of these issues fixed, maybe if a PR comes in that is small and doesn't rely on a hacky regex we would have a look.

So if you're happy to look into it for a PR, then please go for it, but I'll close this issue for now as a "won't fix" since we don't plan to make time for it at HQ at the moment.

**Comment by jbreuer** [comment]
I'm building a demo site where I want to demo some login features. So adding it to the template directly is fine for me. Just thought other people might also run into this issue so that's why I created a bug report for it.

It's also mentioned in the docs here so other people might also try it: https://our.umbraco.com/Documentation/Tutorials/Members-Registration-And-Logins/index-v9#include-the-macros-and-partials-in-content-and-templates
