### ISSUE TITLE
Umbraco 10 - After publishing, True/false editor does not work

### ISSUE THREAD

**Issue by chrno1209** [umbraco/Umbraco-CMS#12977]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.1

### Bug summary

After publishing an Umbraco application, the True/False editor does not work, it works normally on local development but not on server after publishing

### Steps to reproduce

Install Umbraco 10.1.1
Publishing the app to server
Open any documen type/data type which has a True/False editor inside
Try to click on it

### Expected result / actual result

Expected: the True/False editor will change
Actual: it does not change, just stay as False

**Comment by justin-nevitech** [comment]
Hi @chrno1209,

You're not using any HTML minification are you?  I had this exact problem which was being caused by back office files being minified.  It worked locally on dev as the files weren't minified but they were on production.  I fixed it by excluding the back office from being minified by WebMarkupMin.  I think a blank attribute was being removed.  Maybe worth a check...

Justin

**Comment by chrno1209** [comment]
> Hi @chrno1209,
> 
> You're not using any HTML minification are you? I had this exact problem which was being caused by back office files being minified. It worked locally on dev as the files weren't minified but they were on production. I fixed it by excluding the back office from being minified by WebMarkupMin. I think a blank attribute was being removed. Maybe worth a check...
> 
> Justin

You save my days @justin-nevitech , thanks so much.
I think I will switch to use WebmarkupMin directly instead of using MissingCode.Umbraco.HtmlMinifier.
