### ISSUE TITLE
Settings content model default value for true/false toggle not applied when saving block list

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/Umbraco-CMS#13134]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.0

### Bug summary

The default value for a toggle in a settings model is not set when saving the element.
The values are only set when the settings are opened and submittet.

### Steps to reproduce

Configure a settings model content type for block list editor that does have a Toggle true/false with default value set to true.
When you add a block with this settings model to a block list datatype and don't press the settings button and then save the page. The default True value for the toggle was not applied. Only when pressing the settings button and submit the settings the default will be applied to the block list value.

### Expected result / actual result

Default values will be applied to block list when adding new blocks without opening settings modal.

---
_This item has been added to our backlog [AB#29453](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29453)_

**Comment by Nikkelmann** [comment]
This is exactly the same as #11161

**Comment by Nikkelmann** [comment]
Might be related to #10160

**Comment by Wiggee11** [comment]
I can replicate this bug on Umbraco 10.1.1.

Initial state value should be respected regardless of whether the settings window is opened or not. Cannot tell/expect clients to open a window every time to change nothing!

**Comment by nikolajlauridsen** [comment]
Heya, I've had a go at reproducing this, and can reproduce in both 10.3.2 and 11.0.0. 

An interesting thing here is that in 10.3.2, this problem only occurs if using the inline editing mode, however, in 11.0.0 this always occurs, even if not using inline mode. 

I guess it sort of makes sense why this is happening since the initial state toggle states "The initial state for the toggle, when it is displayed for the first time" and since it's never displayed the value doesn't get set.

However, I agree that this user experience is quite troublesome, so I'll try and bring it up at HQ to see how we can proceed 😃

**Comment by Nikkelmann** [comment]
@nikolajlauridsen 
Ran in to this issue again, but this time with the Slider property.
The initial value is not being set, unless the user opens the settings for the block item.

![image](https://user-images.githubusercontent.com/3674690/216020805-26a26d31-520f-44e2-8e0d-b66badcada42.png)

When accessing the IBlockReference<TSettings>.Settings property on the model the default values of the properties from the Settings Model Element Type are not as defined in the backoffice, but simply the C# default value, e.g. int = 0, bool = false, etc.

**Comment by nikolajlauridsen** [comment]
Heya, yes that makes sense, I think this issue is not with one specific data type, I think the issue is that the default or initial values currently are only set on the frontend, however, this doesn't happen until open up the settings pane are set, however I do appreciate you letting us know, so we know we need to take a look at this. 

Also sorry about not getting back to you sooner, but we've had a chat about this at HQ, and we want to fix this, however right now, we're not sure the best way to go about this. 

I have a task to take a look at this, so we haven't forgotten you 😄

**Comment by iOvergaard** [comment]
Hi everyone, we are fixing the bug for the block list and block grid in normal mode with #14493. I have created a new issue specifically to treat the bug that @nikolajlauridsen has uncovered for **the block list in inline mode**. This new issue is found at #14494.

**Comment by iOvergaard** [comment]
This was released along with 12.0.0 earlier this year and has now been picked for v10. We expect to include it in the upcoming 10.7.1 patch.
