### ISSUE TITLE
Imagecropper Does not crop / resize on Linux

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#13157]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10+

### Bug summary

When using the image cropper on linux, it will always return the original image and not the cropped / resized version.

### Specifics

Feel free to use the url for testing:

https://testdeploy.umbhost.dev/media/5xbo33mw/umbraco-bg.jpg?width=1080&height=786&rnd=133063549238530000

This should return an image cropped to 1080 x 786 but instead it returns the original uncropped image

### Steps to reproduce

Install a clean Umbraco V10+ Installation on Linux (I used Ubuntu 22:04)
Upload an image
Attempt to crop / resize the image using the image cropper

### Expected result / actual result

Actual:
Original uncropped image returned

Expected:
Resized / Crop image to be returned.

**Comment by cornehoskam** [comment]
Hi @AaronSadlerUK,

After some experimenting, I found out it appears to be an issue caused by media path existing on disk (or being reserved), and therefor not having the ImageSharp do the processing! Trying out the same url with a different capital letter, like https://testdeploy.umbhost.dev/media/5xbo33mw/umbraco-bg.jpg?width=1080&height=786&rnd=133063549238530000, does resize correctly! 
This is not a fix of course, but an addon/direction to look for the one fixing this bug! 😄

**Comment by ronaldbarendse** [comment]
@AaronSadlerUK Did you manually create the `Media` folder using a capital letter? As @cornehoskam highlighted, the ImageSharp middleware does process the image if the URL casing matches exactly, which seems to be different to how the default ASP.NET Static File middleware matches URLs.

I recommend making sure you always configure/create directories and files using the same casings to avoid this problem in the first place and start a discussion on the ImageSharp.Web respository if you think they should relax the URL/path matching to align with the ASP.NET Core Static File middleware.

**Comment by AaronSadlerUK** [comment]
@ronaldbarendse No the media folder on disk is lower case.

I have had this issue on clean Umbraco installations too, the issue seems to be as @cornehoskam suggested, that it's passing it off to the actual media folder rather than running it through the processor.

If this is indeed the case, they it should work OOB and would be an Umbraco bug (as that's what controls the media path)

**Comment by ronaldbarendse** [comment]
Hmm... Just to be sure: is `Umbraco:CMS:Global:UmbracoMediaPath` set to the lowercase `~/media` value as well? And have you configured `Umbraco:CMS:Global:UmbracoMediaPhysicalRootPath` or are you using Azure Blob Storage?

> The reason it works with a capital, is that this does path not exist on disk and so the processor takes over.

All requests are handled by middleware and the ImageSharp one runs before the ASP.NET Static File one, so it can use the query string to process the image and return that instead of letting other middleware serve the original file. Both middlewares will skip any requests where they can't find the file, so the weird thing is that ImageSharp only finds the file when the URL contains a different casing than what's used on the filesystem 🙃

I do see you're using Cloudflare, so also make sure that caches unique URLs including query strings (and maybe purge all caches/disable caching while debugging). And while comparing response headers, I noticed the `/Media/` URL (with the cropped image) has the extra `Cache-Control: public, max-age=604800, immutable` and `X-Powered-By: Phusion Passenger(R) 6.0.13` headers present.

**Comment by AaronSadlerUK** [comment]
The `Umbraco:CMS:Global:UmbracoMediaPath` is the default and has not been overriden (so is `~/media`)

The `Umbraco:CMS:Global:UmbracoMediaPhysicalRootPath` has not been set, so as per the documentation should fallack to `Umbraco:CMS:Global:UmbracoMediaPath`

There is no blob storage involved, it's using the local media storage as per a standard installation

Is regards to Cloudlare, the same thing happens with or without development mode enabled which rules the cdn out.

The only difference between the 2 paths is that `media` exists on disk and 'Media' does not (do remember folders are case sensitive on Linux)

**Comment by AaronSadlerUK** [comment]
On the case sensitive note, maybe that's the problem?

Is the imagesharp middleware using an invariant path check?

**Comment by nul800sebastiaan** [comment]
Hmm, gave it a go on my Linux box as well (Ubuntu 22.04) as well. I published (`dotnet publish -r ubuntu.22.04-x64 --configuration Release -o ../test`) and ran the published site. 

It "just" works for me, so I'm guessing it's something with how the hosting environment is set up?

![image (61)](https://user-images.githubusercontent.com/304656/195273667-d5e4873d-e69d-4b37-92b2-b3d4617ae427.png)

**Comment by AaronSadlerUK** [comment]
Ok strange, however that is using dotnet directly, so there is nothing sat in front.

To be useful in a shared hosting environment you need to sit Nginx in front of it to act a proxy for the domain, I'll do some digging into the Nginx proxy configuration and see if maybe that is not passing it through to dot net 🤔

Feels like we're getting closer though!

**Comment by AaronSadlerUK** [comment]
Ok so one step closer, if the media folder exists on disk Apache / Nginx will serve that as "static" and not pass the request to the backend.

I have moved the media outside of `wwwroot` and set the `Umbraco:CMS:Global:UmbracoMediaPhysicalRootPath` and now it works.

I guess this is a Nginx configuration 🤔

**Comment by AaronSadlerUK** [comment]
o I've got to the bottom of the Image Cropper issue... You were right it's the server...

I'm no Nginx expert, so my Google Fu seems to have an explanation... Nginx processes static assets before passing to any backend / proxy for speed and efficiency, so because the image was physically on disk it never passed it to dot net to be cropped.

The fix (unless any one on here knows Nginx) is to move the media folder outside of the wwwroot and then update the UmbracoMediaPhysicalRootPath setting to the absolute path to the media folder.

This forces Nginx to pass it to dot net as it doesn't exist on disk.
