### ISSUE TITLE
Emails send with attachments are not encoded correctly when received by some SMTP servers

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#13343]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

The problem is described in [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/905) on the Umbraco Forms issue tracker.   However on investigation it seems the problem isn't anything Forms specific, as it can be replicated with default CMS email sending functionality.

In summary, if attachments are added to a message, non-ASCII characters aren't displayed properly, at least via some SMTP servers (gmail and outlook are noted).  If no attachments are added, the characters come through as expected.

Working locally with smtpdev doesn't exhibit the problem.

### Specifics

It is the case that we have a slightly different route for building the email message object when attachments are involved, as can be seen [here](https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Infrastructure/Extensions/EmailMessageExtensions.cs#L28).

### Steps to reproduce

There are a couple of tests cases in the discussion on the linked issue.

**Comment by elit0451** [comment]
Thanks for porting the issue to this tracker Andy 💪 

Hi @vonlinaa, I hope we can transfer the discussion about the issue that you observed when receiving emails (with attachments) containing the special Danish letters `æøå ÆØÅ` to here. 🙂 

I tried to reproduce using the two code samples provided in the original issue by setting up[ Gmail's Outgoing Mail (SMTP) Server](https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Cstep-change-smtp-other-settings-in-your-email-client) since you said you can't see the problem locally. But still **no luck**. Below you can find the modifications I had to make in order to make my Gmail account send emails to myself:

```c#
    public IActionResult Native()
    {
        // CHANGE: add GMAIL credentials
        NetworkCredential NetworkCred = new NetworkCredential("@gmail.com", "password"); // my Gmail email and password

        // CHANGE: create new client
        SmtpClient client = new SmtpClient
        {
            Host = "smtp.gmail.com",
            Port = 587,
            EnableSsl = true,
            UseDefaultCredentials = false,
            DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network,
            Credentials = NetworkCred
        };

        // CHANGE: my Gmail email here
        MailAddress from = new MailAddress("@gmail.com", "Jane " + (char)0xD8 + " Clayton", System.Text.Encoding.UTF8);
        MailAddress to = new MailAddress("@gmail.com"); // CHANGE: my Gmail email here


        // Specify the message content.
        MailMessage message = new MailMessage(from, to);
        message.Body = "This is a test email message sent by an application. ÆØÅ æøå ";
        // Include some non-ASCII characters in body and subject.
        string someArrows = new string(new char[] { '\u2190', '\u2191', '\u2192', '\u2193' });
        message.Body += Environment.NewLine + someArrows;
        message.BodyEncoding = System.Text.Encoding.UTF8;
        message.Subject = "test message 1" + someArrows;
        message.SubjectEncoding = System.Text.Encoding.UTF8;

        var filePath = "App_Plugins\\test.txt"; // CHANGE: different path
        Attachment attachment = new Attachment(filePath, MediaTypeNames.Application.Octet);

        message.Attachments.Add(attachment);

        client.Send(message);

        // Clean up.
        message.Dispose();

        return Ok("Done");

    }
```

OR to use the other example, I added the following setting:
```json
        "Smtp": {
          "From": "@gmail.com", // my Gmail email here
          "Host": "smtp.gmail.com",
          "Port": "587",
          "Username": "@gmail.com",  // my Gmail email here
          "Password": "password",  // my Gmail password
          "DeliveryMethod": "Network"
        }
```

As you can see in the image below, the non-ASCII characters are displayed properly (I even added Cyrillic characters 😅 ). I also tried doing the same on Umbraco Cloud, and still no issue for me. 🙁 Could you try your example with my changes and let me know the output, please?

<p float="left">
<img src="https://user-images.githubusercontent.com/21998037/200800475-41c48753-3e47-4565-98ae-ca45d5b00b62.jpg" width=51% /> <img src="https://user-images.githubusercontent.com/21998037/200800490-69709eef-043c-429d-a88c-5fc2c1e37dcd.jpg" width=45% />
</p>

**Comment by elit0451** [comment]
Hi again @vonlinaa 🙂 
Since we haven't heard back from you and unfortunately, I was unable to replicate the problem you described I will have to close this as non-reproducible.
