### ISSUE TITLE
Umbraco Default Preview not working properly on Umbraco 10

### ISSUE THREAD

**Issue by MaksymShuldiner** [umbraco/Umbraco-CMS#13366]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

We've recently updated our Umbraco to v10 from v8 and noticed that default preview that Umbraco v8 was using when there is no template specified for document type is not presented right now. 

### Specifics

So, when there is no template for component, at Umbraco v8 we had the: 

![image](https://user-images.githubusercontent.com/61598586/200521463-de0b3040-4410-4e25-acf2-63500824261f.png)

And at Umbraco v10 we have this :

![image](https://user-images.githubusercontent.com/61598586/200521630-db709316-e535-4454-9e05-14b21b10f1d7.png)

This collapsed something cannot be selected. Can you please help me - was something on this logic changed from v8 to v10 or that's configuration issue on my side?

### Steps to reproduce

1. Create a document type (element type)
2. Create a page
3. Add document type to grid editors, 
4. Add editor document type to the page, 
5. Do not create a template for the document type
6. Create content as a page
7. Add document type to the page
8. Ensure that there is no default template as in Umbraco 8
9. Ensure that the document type is shown as collapsed box which cannot be clicked

### Expected result / actual result

Expected - Default template is specified
Actual - Document type is shown as collapsed box which cannot be clicked

**Comment by elit0451** [comment]
Hey @MaksymShuldiner 👋 

I need some help trying to understand your test scenario. Let me know if my interpretation is wrong 🙂 
You can also specify what were you used to do in Umbraco 8 so we can try to figure out what is the new approach in Umbraco 10 and therefore clarify what the bug is!

Going step by step, you are trying to:
1. Create an Element type (_ex: `E`_) under your Document Types?
2. Create a new document type (_ex: `D`_) with a property editor (Block list or Nested content) so that we are able to select the element type `E`, that we just created?
3. Add the element type `E` to the property editor of document type `D` - ex: Block list?
  3.1. What do you mean by `"grid editors"`?
4. Add a rich text editor to the document type `D`?
5. Remove the template from the document type `D` or on step 2. we had to select to create a document type without a template?
6. Create a content node from the document type `D`?
7. _Not sure what you mean on this step?_
8. Visit the Info tab of the content node and verify that no Template is selected?
9. Preview the content node?

**Comment by kjac** [comment]
Hi @MaksymShuldiner. We haven't heard from you in a while, so we're going to close this issue now.

We hope you managed to resolve the issue on your end. If the issue is still relevant, please feel free to reopen with additional information to help us track down what's causing the issue.
