### ISSUE TITLE
Content Type Picker should not allow selection of Containers

### ISSUE THREAD

**Issue by markadrake** [umbraco/Umbraco-CMS#13463]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

- The [EditorService](https://apidocs.umbraco.com/v10/ui/#/api/umbraco.services.editorService) has a [ContentTypePicker](https://apidocs.umbraco.com/v10/ui/#/api/umbraco.services.editorService#methods_contenttypepicker) that opens an infinite editor window and allows us to select one or many content types.
- This window also allows us to select containers. (Bug 1)
- If you select a container, an error is shown both in the console and the Backoffice. (Bug 2)
- When you close the ContentTypePicker, the data is filtered and any containers selected are correctly removed.

### Steps to reproduce

- Make a button and on click, use the `EditorService` to open a `ContentTypePicker`.
- The rest of this video is OOTB behavior.

https://user-images.githubusercontent.com/713355/203385899-1c5730f8-f429-49d2-9076-0e5fc45b985e.mp4

### Expected result / actual result

- Users should not be able to select container types.
- If users should be able to, it should be exposed to a boolean configuration value (angular).
- The OOTB angular component should not request the API if the selected item is a container.

---
_This item has been added to our backlog [AB#24466](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24466)_

**Comment by iOvergaard** [comment]
Thanks for this very detailed bug description, @markadrake !

I have been looking into this issue. It's a little complex, but there is a bug for sure seeing, that we shouldn't call the server on unknown types (containers). 

On the server, the document type containers (and for that matter data type containers) have a different key and cannot be found in the lookup to the entity controller here, because we are in the context of "document types" and not "document type containers". Meanwhile, this is fixable by testing for the `nodeType` property and just constructing a simple object if it equals "container" and returning that allowing the user to select containers anyway.

The other bug in your report says, that a user should not be able to select containers. While I factually agree with you here, we probably cannot build generic logic into this picker to prevent the selection of containers, because this is a tree picker and not a content-type picker per se. 

To rectify this, there is already built-in logic to provide a "filter" function that will say go/no-go to each item in the tree. We use this filter in several places in the Backoffice, for example with document types in the "permissions" picker, where we are only allowing non-container data types and removing element types as well:

https://github.com/umbraco/Umbraco-CMS/blob/69c725b3ec71bd6cd67f93be4de7a666be547d24/src/Umbraco.Web.UI.Client/src/views/documentTypes/views/permissions/permissions.controller.js#L71:L72

I will contemplate and ask around at HQ, whether it would make sense to always disable certain types of entities to be picked. 

Meanwhile, your video clearly shows an example of where a filter should be used - would you provide a little more information as to where you are experiencing this, please?

**Comment by iOvergaard** [comment]
I have made a draft PR that at least fixes "Bug 2" as described above to see if that is the right approach: #13507

**Comment by nielslyngsoe** [comment]
Fixed in #13507
