### ISSUE TITLE
Model's builder doesn't nicely catch a type error making it hard to debug an data type issue.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#13515]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Model's builder throws an exception and fails to build the models.

The way we discovered this was by creating a Data List type using Contentment, there may be other ways to replicate the same error. When trying to generate Models using Models Builder, we receive the following error:

```
Object reference not set to an instance of an object.
at Umbraco.Cms.Core.Models.PublishedContent.ModelType.MapToName(Type type, Dictionary`2 map, Boolean dictionaryIsInvariant)
```

Which as you can see, this isn't particularly useful to help debug where the issue might be, it would be great if this error could be caught and a more helpful error message thrown so the developer knows which datatype is causing the issue.

### Specifics

The current error is thrown on this line:

https://github.com/umbraco/Umbraco-CMS/blob/e7fae144c2bdedfd78ccd53c27ec97b3fa41604b/src/Umbraco.Core/Models/PublishedContent/ModelType.cs#L229

### Steps to reproduce

To replicate this error, create a Contentment Data List data type and use a .NET Enumeration, don't select a library or class to enumerate, then save it. Add this to a document type and then try to build the models.

### Expected result / actual result

We would expect when building models that any error in data types were handled gracefully and hopefully bubbled up to the UI, or worst case scenario they should be thrown with useful debugging information so a developer can easily fix the issue without having to spend an hour trying to debug :)

It would be great for this error to indicate the name of the data type that caused the issue.

**Comment by Zeegaan** [comment]
@readingdancer Would you happen to have a good way to replicate this error? 🙈 
Preferably with a few steps I can follow 👍

**Comment by Zeegaan** [comment]
But as pointed out, this happens when type is null, so we could add a guard statement in the `MapToName` function, with a helpful exception, maybe like so: 
```
if (type is null)
{
    throw new ArgumentNullException("Can't map a type when its null");
}
```

**Comment by readingdancer** [comment]
@Zeegaan - Instead of just throwing a generic error, we thought it would be more useful to throw an error that specified which datatype was failing as I believe that information is available. It will help developers debug this much more quickly as they can go and check the data type within Umbraco to see if there is something wrong with the way it has been configured before needing to dig into the code.

**Comment by Zeegaan** [comment]
@readingdancer I sadly do not think we have that info available, as when we try to map it, the object is null, so we cannot infer types from it 😞 
I'm just spitballing here, but it be interesting to see if it's possible to make the null check earlier, where we might know more about the datatype 😅

**Comment by JasonElkin** [comment]
This is a really interesting issue.

I just tried to replicate it in order to test the linked PR. If I understand this issue correctly - In order replicate it, I need to create a Property Value Converter where `GetPropertyValueType` returns `null`.

The compiler will not let me do it. This is because, as is now default, I have Nullable Reference Types turned on and `GetPropertyValueType` is not nullable.

![Screenshot 2023-03-06 220730 (Phone)](https://user-images.githubusercontent.com/7151793/223249915-7729d129-90e4-46d1-a53c-178fc7ddeeb7.png)

This is a quirk of taking code that uses Nullable Reference Types, which is a compile time feature, and using it in a project where Nullable Reference Types are disabled. 

I'd say this is an issue to be dealt with at the `IPropertyValueConver` level, rather than ModelsBuilder. If `GetPropertyValueType` is not supposed to be null then I think the Type check and throwing the resulting error needs to happen earlier in the process - perhaps at the point the converter is registered.
