### ISSUE TITLE
Missing step 4 in introduction guide.

### ISSUE THREAD

**Issue by Hacker-Wolf** [umbraco/Umbraco-CMS#13518]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

I was using a startup guide by appearing in pop-up window or getting there by clicking on help -> getting started -> introduction. Then following next procedures, the 4 step out of 13 was missing. After clicking next on step 3, it already jumped to 5.

### Specifics

https://contenthub-dev.simployer.tech/umbraco#/content?mculture=nb-NO

On pop-up window on main site after loging in

### Steps to reproduce

1. Check sum of steps if it was 13 or 12
2. If it was missing, add 4 to queue
3. If counting was wrong, then lower numbering for pop-up windows 5-13 by 1 and reduce all steps to 12

### Expected result / actual result

missing page completed or fixing counting steps

**Comment by nikolajlauridsen** [comment]
Hey @Hacker-Wolf, thanks for your bug report, but this is actually intentional, but I get why you'd think otherwise. 

Step 4 is not missing per. say, but it'll only be shown if you're not in the Content Section since step 4 is "Navigate to the content section", which is a bit redundant if you're already there 😄 So I'll go ahead and close this issue.
