### ISSUE TITLE
Cant configure EnableSsl in Global Settings SMTP in Umbraco 11

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#13584]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

I need to configure EnableSsl=true in smpt inside Global Settings but it is not available, there is not such property.
Previously, i could configure the smtp generic settings in web.confg and that options was available.
As i cant configure it, notifications and umbraco forms are not working

### Steps to reproduce

set "EnableSsl" : true in SMTP config inside Global

**Comment by kjac** [comment]
Hi @teeto,

I believe you can use "SecureSocketOptions":

![image](https://user-images.githubusercontent.com/7405322/207869631-07ce5360-2222-44d8-8e29-2a329e08d333.png)

Ref: https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings#secure-socket-options

I hope this helps 😄 otherwise I would urge you to get in touch with the good people at the forum to help you onwards: https://our.umbraco.com/forum

**Comment by teeto** [comment]
thanks, i did not know that one. It was the sender email was blank...
BTW @kjac , could you tell me where i can configure the sender email for all the forms? i refer to the default send template email workflow. I dont want to set it in the workflow each time. It shows: "Enter the sender email (if blank it will use the settings from configuration)." where are those settings?

**Comment by teeto** [comment]
OK, after searching the docs:

I have set this configuration and now it works:

```
"Forms": {
      "FormDesign": {        
        "SettingsCustomization": {
          "WorkflowTypes": {
            "sendEmailWithRazorTemplate": {
              "SenderEmail": {
                "IsHidden": true,
                "DefaultValue": "sender@email.com"
              }
            }
          }
        }
      }
    }
```

**Comment by kjac** [comment]
@teeto great news 👍
