### ISSUE TITLE
Sorting items in listview via Actions menu does not update the list

### ISSUE THREAD

**Issue by pniniG** [umbraco/Umbraco-CMS#13607]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

When viewing children in a listview, if you use the actions menu to drag-sort the items and save, the listview does not update the sort numbers or order of items in the lsit until you click the sort header to toggle the sort direction, or leave and come back to the listview.

### Steps to reproduce

When viewing a listview use the Actions menu to drag-sort the items and save.

### Expected result / actual result

Expected : After sorting items the listview should refresh to reflect the changes to the sort order.

Actual : Original list order.

**Comment by pniniG** [comment]
it is related to a release that you are actively supporting

**Comment by elit0451** [comment]
Hey @pniniG 👋 

You are completely right, we are actively supporting Umbraco 10 😊 

Regarding your bug report, it seems like there is a bit of a misunderstanding about how sorting works in your particular case. Hope the following helps:
- We are persisting the sort index of the items (children) in the database - this is also the order you see the items in when you use the Sort Action;
- The order you see the items in the listview doesn't have a direct tie with the sort index above ⬆️
- The dialogue which appears after selecting the Sort Action will update the sort indexes on Save;
- While the listview can visually sort items based on any columns that the listview contains.

So the active listview will not necessarily respect the result from the Sort Action. It all depends on what column is your listview sorting after.
</br>

_Here is a quick example_:
- I've added the sort column in the listview, so that we can visually see the sort order that the items appear in when you attempt the Sort Action.
![image](https://user-images.githubusercontent.com/21998037/208924897-f8b8fcc6-3e1b-43e8-867e-c407f873963e.png)

</br>

That way we will be able to see that the items in the listview are sorted based on the "Last edited" values and **not** based on the Sort order:


![image](https://user-images.githubusercontent.com/21998037/208925199-21c9ae28-1ce5-4da3-9e9c-84e177988b86.png)

</br>

 You can compare the values in the Sort listview column with the order of the items that appear in the Sort dialogue:
<img src="https://user-images.githubusercontent.com/21998037/208925550-54f3e62b-54b8-47a3-871f-f64626754074.png" width=65% >

> **Note**:
> When you sort you might have the last edited date updated - if you for example drag the first item to the last, and thus affect each of their sort indexes.

</br>

After clarifying that this isn't an actual bug, I will close this. 🙂

**Comment by pniniG** [comment]
thanks @elit0451
