### ISSUE TITLE
Bug when using multiple styles for the same selector in RTE 

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco-CMS#13606]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

It's not possible to use multiple styles for the same selector when using custom styling in an RTE.

### Steps to reproduce

Set up two styles for the same selector:

![image](https://user-images.githubusercontent.com/88326257/208887129-c6d26baf-509f-4ee4-bcca-7d167a05ef2a.png)
 
![image](https://user-images.githubusercontent.com/88326257/208887218-925a3c50-831b-4327-b812-7d3801012958.png)

Added the stylesheets to the RTE:

![image](https://user-images.githubusercontent.com/88326257/208887260-12b7f604-1e6c-4cd7-b7ea-d51433153a7b.png)

The 2nd style overwrites the 1st one:
![image](https://user-images.githubusercontent.com/88326257/208887325-670619d5-66f1-44c4-a612-54e883b58dc0.png)

### Expected result / actual result

Expected it to be possible to make one selection red and another selection blue.

**Comment by elit0451** [comment]
Hey @RasmusUmbraco 😁 

There is just one small thing you overlooked in order to make the two styles work. If you are using the same selector in two different styles, you have to be more specific with the selector value otherwise you will end up with the following code and the last style for `h1` (_in this case_) will override any previous `h1` styles:
```css
/**umb_name:Example*/
h1{
	color:red;
}

/**umb_name:Example2*/
h1{
	color:blue;
}
```
</br>

The solution to this is to give 2 different selector values, like:
<img src="https://user-images.githubusercontent.com/21998037/208918820-88ecf3fe-23f9-4df0-90e6-ef5982bb17de.png" width=49%> <img src="https://user-images.githubusercontent.com/21998037/208918952-6c529e57-5104-488f-aaae-6ca3db82e15a.png" width=49%>

</br>

And then the styles will appear 😉 So I will close this one now, as it isn't a bug but rather a topic for [our forum](https://our.umbraco.com/forum/).
