### ISSUE TITLE
Mini-list view search by id is not working!

### ISSUE THREAD

**Issue by dKumarmj** [umbraco/Umbraco-CMS#13701]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Search by id/key is not working in the Mini-list view of MNTP. This issue will only occur when we try to add a node that is enabled as a list view.

### Steps to reproduce

- Create 6 doctypes as below structure.

- Repo1 (allow as root,list view enabled, disable infinite editor )
   - doctype 1 (list view enabled,enable infinite editor )
        - doctype 2
- Repo 2 (allow as root,list view enabled, disable infinite editor )
   - doctype 3 (list view enabled,enable infinite editor )
       - doctype 4
   
- Create a _MNTP_  (_Allow items of type_ as **doctype 1**  , Node Tye as **Repo 1**
- Create a property with the created _MNTP_ in any **doctype 4**
- Create nodes as per the above structure.

**Id of a **doctype 1** content**

![image](https://user-images.githubusercontent.com/58820887/213498959-e9f57559-155a-46d6-bf2b-83f3b044e10f.png)

**When we search from doctype 4 -> MNTP -> minilistview search**

![image](https://user-images.githubusercontent.com/58820887/213499265-e1ac46ac-9566-49bf-b1ee-fe6adb07b0fc.png)

**MNTP Settings**

![image](https://user-images.githubusercontent.com/58820887/213499810-b0a74cd4-5193-4fa2-a2a9-77311acb8d87.png)

### Expected result / actual result

**Expected Result:**  The content must show as the search result based on the Id.
**Actual Result:**  Showing no results.

**Comment by elit0451** [comment]
Hi @dKumarmj 👋 

I've tried to reproduce this in the latest Umbraco 10 version (_v10.4.0_) and for me, the search by id works. Check the video below and l let me know if I missed something 🙂 


https://user-images.githubusercontent.com/21998037/213421584-f71f062c-aa32-44b7-ab8e-9a51aa2907b9.mp4

**Comment by dKumarmj** [comment]
Hi @elit0451  ,  thanks for checking this!

Yes, this will work for normal tree content, but it won't work with contents enabled as listview, please see the video below.
I changed the **Steps to reproduce** above, now it will give more clarity.


https://user-images.githubusercontent.com/58820887/213503858-099abbd9-7cdc-4522-b8cf-0045691095b3.mp4



_My findings are_

- if it's tree content then the API call is `/umbraco/backoffice/umbracoapi/entity/Search?query=......` , but when it's mini-listview and the _Node type_ is selected for MNTP then the API call will change to `/umbraco/backoffice/umbracoapi/entity/GetPagedChildren?` , is this expected ?

- Only the name is considered as the filter! , please see here https://github.com/umbraco/Umbraco-CMS/blob/v10/main/src/Umbraco.Web.BackOffice/Controllers/EntityController.cs#L752

**Comment by elit0451** [comment]
Seems like a bug. I've managed to reproduce it in a few simple steps:
- Create the following doc types:
  - Doc 1 - root node;
  - Doc 2 - doc type that is allowed as a child node of Doc 1;
  - Root - root node with MNTP.
- Create content from the doc types
  - Home (from "Root" doc type);
  - Document 1 (from "Doc 1" doc type);
    - Document 2 (from "Doc 2" doc type).
- Go back to the Root doc type and change the configuration of the MNTP, like:
  - **Node type**: Document 1;
  - **Allow items of type**: Doc 2.
- Get the id of the "Document 2" content node;
- Go to the Home node and try searching for the node id from ⬆️ - the search will **succeed** and you will see the node item.
- Enable the List view of Doc 1;
- Try the same search in the Home node - search for the "Document 2"'s id - here the search would yield "_**Sorry, we can not find what you are looking for.**_"
- _Bonus:_ If you remove the **Node type** from the MNTP configuration of Root, keeping the list view **enabled** for Doc 1, you will get a result again from searching for a node by id.

> **Note**:
> Perhaps another nested node of Document 2 will make more sense for the search but for a simple test, the above scenario works fine.

</br>
 
So the problem is really when listview is enabled for the node, together with setting up the node type in the MNTP..
When the list view is not enabled, we use the Examine search from `EntityController.Search()`, while when enabled, we get the data directly from the repository (from `EntityController.GetPagedChildren()`).

Also good findings @dKumarmj, you are right that if the filter parameter of `EntityController.GetPagedChildren()` contains the node name, then we get a result. If we search for the id, though, perhaps the SQL query, built in `EntityRepository.GetPagedResultsByQuery()` doesn't consider ids when searching for nodes. 🤔 

I will mark this as up for grabs and see if anyone is up for spotting the problem 💪
