### ISSUE TITLE
Users Section blank

### ISSUE THREAD

**Issue by ANT-GBR** [umbraco/Umbraco-CMS#13789]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.0

### Bug summary

I was having an issue with an Umbraco 7.15.4 site where the Users section was blank, no users were loading, with the JS error:

TypeError: usersResource.getPagedResults is not a function at getUsers (DependencyHandler.axd

I upgraded the site to 10.1.0 which I assumed would fix the issue but the exact same issue is occurring:

TypeError: usersResource.getPagedResults is not a function at getUsers (umbraco.controllers.min.js)

### Specifics

I have deleted all users in the database apart from the initial user and I'm still getting the issue.

![blank-users](https://user-images.githubusercontent.com/1932798/216941816-45631ac6-2666-4621-ac45-851de527152d.PNG)

### Steps to reproduce

I presume something got corrupted so cannot be reproduced on a new site.

**Comment by kjac** [comment]
Hi @ANT-GBR - thanks for reaching out 😄 

It looks like a resource cache issue, either in the client or (more likely) on the server.

I would like you to try a few things before we move any further on this:

1. Update the runtime minification `version` in appsettings.json:
![image](https://user-images.githubusercontent.com/7405322/216961875-2f23beda-b629-4ca5-97de-214fa12c74c6.png)
2. Delete the folder defined as the runtime minification `dataFolder`.
3. Make the site runs in debug mode:
![image](https://user-images.githubusercontent.com/7405322/216962131-b7fc33cc-cd62-4a21-9392-5ffd04e49f1d.png)
4. Log in using incognito mode.

Remember to restart the site when trying either of the steps. Please try them all and get back to me 👍

**Comment by ANT-GBR** [comment]
Hi Kenn,

I have tried those steps and am getting the same error.

Thanks
Tony

**Comment by kjac** [comment]
Hi @ANT-GBR,

Strange. The error you're seeing is because the browser somehow cannot find `getPagedResults` on `usersResource`. The method is supposed to be bundled up in the scripts:

![image](https://user-images.githubusercontent.com/7405322/217179208-9380012e-0bda-47a9-9e34-35ddc4b8f39d.png)

The next thing to try is to create a new, clean install of Umbraco 10.1 (or whatever V10 you're testing on now). See if the error persists there as well. Hopefully it does not! 

Assuming this goes well, stop the new site and update its connection string to point at the database of your current site. Restart the new site and see if the users section is working.

**Comment by ANT-GBR** [comment]
Hi Kenn,

I have swapped the database of my current site over to the new site and I can see the users section with all the users.

From this I have managed to track down the error. It was down to a custom section I had built that was using a javascript file called users.resource.js, so there was a conflict.

Thanks for your help in narrowing it down.

Cheers,
Tony
