### ISSUE TITLE
Pasted images get stuck and do not upload when using the Block Grid

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco-CMS#13857]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

Pasted images get stuck and do not upload when using the Block Grid

### Steps to reproduce

Using the Block Grid:

Choose an image block
![image](https://user-images.githubusercontent.com/88326257/220052844-28792de7-a0a7-4e67-a17c-32251876a351.png)

Paste an image/screenshot.
Expected behavior: The image/screenshot is uploaded to the block.
Actual behavior: The image/screenshot is stuck loading and does not upload. 
![image](https://user-images.githubusercontent.com/88326257/220052096-113d308e-7de4-4d6f-a77d-d7c2789c294b.png)

I don't know if pasting from the clipboard is a supported feature, but IIRC it worked on previous versions.

**Comment by Zeegaan** [comment]
Great news, I can reproduce this in 11.1, but it seems to have been fixed in 11.2 🎉 
https://github.com/umbraco/Umbraco-CMS/pull/13780/

As this is fixed, I will close this issue for now, feel free to re-open if this still doesn't work for you have upgrading to the 11.2-RC, or the official 11.2 release (which will be released on Thursday the 23rd) 👍
