### ISSUE TITLE
Following update to 11.2 the <umb-overlay> directive no longer functions correctly.

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco-CMS#13899]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2

### Bug summary

This issue was introduced in 10.2 and was resolved in 10.2.1.

The same issue has returned in 11.2

See previous issue here:

https://github.com/umbraco/Umbraco-CMS/issues/12989

### Steps to reproduce

See previous issue in 10.2

**Comment by elit0451** [comment]
Hi @marcloveUSN 👋 

Apologies for getting back to you just now! I tried to reproduce your issue based on the reproduction steps listed in the issue you referenced (https://github.com/umbraco/Umbraco-CMS/issues/12989) and as you can see below, in am unable to spot the same problem in 11.2. 

Could you point me in the right direction by providing more details about how to reproduce your issue? 🙂 Here, I have created just a simple form and used a Form Picker on my Content node ⬇️ 

</br>

![Screenshot](https://user-images.githubusercontent.com/21998037/225006277-7a69051a-13bd-4048-a6d6-8707592f1599.png)

**Comment by dalyUSN** [comment]
Hi @elit0451 

The previous issue #12989, was fixed by amending the CSS from:

`.umb-property-editor {
contain: layout;
position: relative;
}`

to:

`.umb-property-editor {
contain: style;
position: relative;
}`

You can see the fix in #13033. This was released in version 10.2.1

The fix was removed in version 11.2. In your screenshot, you can see that the CSS has returned to `contain: layout;`.

Thanks
Paul

**Comment by Zeegaan** [comment]
Yea it was reverted in this PR: https://github.com/umbraco/Umbraco-CMS/pull/13583
We will discuss what to do here internally and then get back to you (this might take a while) 😅

**Comment by dalyUSN** [comment]
Do you have any update on this @Zeegaan? Thanks!

**Comment by Zeegaan** [comment]
Sorry not yet, most of the team is on easter vacation 😁 
We will discuss this Tuesday next week 👍

**Comment by iOvergaard** [comment]
Hi @dalyUSN 

We have discussed this internally at HQ.

While we initially tried to keep `umb-overlay` alive all the way up to and including v10, it turned out that it gives a lot of trouble for the other issue that #13583 tries to solve, namely, that we have to contain the styles of property editors for the benefit of the rest of the UI. We decided that we would rather fix the UI as a whole knowing that components such as `umb-overlay` can break. Unfortunately, this means that umb-overlay works poorly when used inside a property editor.

The `umb-overlay` was marked as deprecated back in 2019 in Umbraco version 8 following the release of Infinite Editors. Creating an infinite editor should provide the same capabilities (and much more!) as `umb-overlay` did. You should expect the component to be removed entirely in any of the upcoming major versions of Umbraco CMS.

You can read more about building a custom infinite editor on [the API Docs for the editorService](https://apidocs.umbraco.com/v11/ui/#/api/umbraco.services.editorService).

Alternatively, if you want to continue using `umb-overlay` for a while, you could probably overwrite the stylesheet of the backoffice [as you highlighted before](https://github.com/umbraco/Umbraco-CMS/issues/13899#issuecomment-1479556575) by creating a CSS file and including it through a `package.manifest` file.

I am really sorry I cannot give you better news, but I hope you will be able to use one of the alternatives mentioned above!
