### ISSUE TITLE
Block list not loading images till clicked

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#13916]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

When a block list contains a MediaPicker3 it only starts to load it's images once the block list item is opened. It can take many seconds to load if left alone. However, if the list item is clicked into, the image will load immediately.  Below are two videos, one where the images are left to load themselves and one where the block list items are clicked into asap.

https://user-images.githubusercontent.com/1143883/223108348-cb24abd2-442b-466d-a850-30d3dc0a9e24.mp4

https://user-images.githubusercontent.com/1143883/223108382-038a3819-810f-4e7f-8ec4-98cbc998ac89.mp4

### Steps to reproduce

Create a block list with an item that contains a MediaPicker3. Add images. Then navigate the block list.

### Expected result / actual result

Expected that the images appear immediately, just as they did in the old nested content structure.

Actual result is either a long delay before the image appears or it only appears once the block list item is clicked on

**Comment by kjac** [comment]
Hi there @craigs100,

Thank you for reporting this 🚀 I can reproduce in V10 too. How absolutely strange. The image is actually loading, but the "loading" state of the media picker only disappears when one clicks inside the block item.

This only happens when using inline editing mode, so the best workaround is to use the default infinite editing mode instead.

![image](https://user-images.githubusercontent.com/7405322/223651894-5de7eacd-a85c-418a-8c89-f09d19aa56d2.png)

We'd love some help getting this fixed. I'm putting this up for grabs so you or anyone else can start working on it.

**Comment by digbyswift-joe** [comment]
Quick note to say we were also experiencing this issue, and had been working to replicate.

Originally we flagged the issue on this (now closed) ticket:
https://github.com/umbraco/Umbraco-CMS/issues/13822

We now have a reproducible example that also points to **inline editing mode** being the issue, and this is in Umbraco 11.2.2.

**Comment by kasparboelkjeldsen** [comment]
Have possible solution for this, pull request inc.

**Comment by nielslyngsoe** [comment]
This issue has already been fixed, but this specific issue entry was not connected therefor I'm closing this.
Ref: https://github.com/umbraco/Umbraco-CMS/issues/14250
