### ISSUE TITLE
Unable to access a url, as it throws cloudfront error on ClientDependencyHandler file with a status of 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by nehanupur0507** [umbraco/Umbraco-CMS#13917]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 8

### Bug summary

When trying to access a url: .../DependencyHandler.axd?s=L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL2ltYWdlLWFzc29jaWF0ZWQtdHJpcHMvY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2Rhc2hib2FyZHMvbGlzdC12aWV3L,,,, 

I am getting an error on ClientDependencyHandler, which says 413, 'Request Entity Too Large'.
I tried checking the character size of this url and it was 8228, which is higher than the character limit for url constructed by the cloudfront from the request, that is, 8192.
I am unable to increase this limit through AWS and also not sure if I can edit this through Umbraco.

### Steps to reproduce

We don't have steps to recreate this. Its just if the url size is more that 8192, we get this error..

### Expected result / actual result

I should be able to make javascript changes for my Umbraco 8 application and not face this cloudfront error for ClientDependencyHandler file about the url size being too large

**Comment by kjac** [comment]
Hi @nehanupur0507,

That sounds really weird! 

I just spun up a vanilla Umbraco 8.18.5 and set it in production (non-debug) mode. The `DependencyHandler.axd` path there is 232 characters.

I'm afraid this is not what we'd consider a bug in Umbraco, nor in the upstream dependency [`ClientDependency`](https://github.com/Shazwazza/ClientDependency). If it was indeed a bug in either, this would have been disrupting every V7 and V8 site out there - which is luckily not the case.

In other words, this is a setup, deployment or a configuration issue. I recommend you get in touch with the good people on [the forum](https://our.umbraco.com/forum) to see if anyone can help you pinpoint the root cause of your issue. A few have reported issues like this earlier on the forum - in some cases it was down to a malfunctioning URL rewrite rule, in other cases they had published temporary folders or manually bundled up a whole lot of dependencies in the core dependency bundle.

**Comment by nehanupur0507** [comment]
Just want to mention here that I found a solution to this issue here:  
https://github.com/umbraco/Umbraco-CMS/issues/10769
