### ISSUE TITLE
The UPDATE statement conflicted with the REFERENCE constraint "FK_umbracoRedirectUrl_umbracoNode_uniqueID"

### ISSUE THREAD

**Issue by piotrbach** [umbraco/Umbraco-CMS#13928]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

Sometimes it's impossible to change the IContent node's Key due to SQL error.

This option is critical for us @wtct because we need to be able to store special Guids generated in other systems.

The consistency in related table (umbracoRedirectUrl) is not supported due to "No Action" option in the foreign key.
Please see the image below:

![image](https://user-images.githubusercontent.com/62244560/223695339-e720c38a-9dcc-46f9-a0f8-cf0b290785fc.png)

### Specifics

```
public class TestSavingNotificationHandlers : INotificationHandler<ContentSavingNotification>
{
    public void Handle(ContentSavingNotification notification)
    {
        foreach (var entity in notification.SavedEntities.Where(e => e.HasIdentity))
        {
            entity.Key = Guid.NewGuid();
        }
    }
}

public class TestComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<ContentSavingNotification, TestSavingNotificationHandlers>();
    }
}
```

### Steps to reproduce

1. Publish the Node.
2. Change the name of the node and publish again.
3. Create ContentSavingNotification Handler.
4. Ensure ContentSavingNotification Handler is registered & fired.
5. Try to change the Key of the Node (IContent) to the Guid.NewGuid() via Content Service in ContentSavingNotification Handler.

### Expected result / actual result

**Expected result:**
The New Id is saved correctly and visible in the back office.

**Actual result:**
SQL error occurs.
Server error: Contact administrator, see log for full details.
The UPDATE statement conflicted with the REFERENCE constraint "FK_umbracoRedirectUrl_umbracoNode_uniqueID". The conflict occurred in database "Database-Dev", table "dbo.umbracoRedirectUrl", column 'contentKey'. The statement has been terminated.

**Comment by kjac** [comment]
Hi @piotrbach,

I would highly advice against changing the keys of the core Umbraco entities. That is not something we actively support, and as you've learned it likely won't work at all.

Off the top of mind I can think of two alternatives:

1. Add a label field to the relevant Umbraco content types and store the external entity keys there.
2. Create your own mapping table between the Umbraco entity keys and your external entity keys.

The first option is likely the easiest to get going with, as it utilizes the Umbraco storage mechanism. However, depending on your query requirements it might not be the best functional option. For the latter option you can likely leverage `IUmbracoDatabase`, which at the time of writing is based on NPoco.

**Comment by wtct** [comment]
Hi @kjac,

Thank you for suggestions!

We have already considered several options (also 1. and 2.), but they have nasty consequences as well.

We decided to use the built-in Key property of IContent and IPublishedContent which was created for some reason.

This functionality is really powerful with conjunction of EntityService.ReserveId() method.

I hope that this functionality will not be removed from ContentService and will be bugfixed.

It is obviously a really easy bugfix.

Please re-consider opening this issue :) 

cc: @piotrbach

**Comment by kjac** [comment]
Hi @wtct and @piotrbach,

The `Key` property is to be considered equal to the `Id` property; it is not ever supposed to change for the entire lifetime of any Umbraco entity. For a long time we have been on a path to migrate away from the `Id` properties, or at least away from using them explicitly, because they do not transfer well between environments (being auto-incremented table primary key values).

Any number of things could depend on the entity `Key` - both now and in the future. So while the fix for redirect URLs might be somewhat straightforward, it doesn't really future proof anything in this respect.

In principle you could define the `Key` yourself at first save using a `ContentSavingNotification` handler. That would likely work for the time being, but there are no guarantees it will work in the future. Since we've applied a unit-of-work pattern to all operations, some services might have already queued referenced entities for saving using the auto generated `Key` as content reference before you change it in the `ContentSavingNotification` handler.

**Comment by wtct** [comment]
Hi @kjac,

Thank you for mentioning about the path of migrating Ids.

If we have only Guids in the future, it still would be nice to have the possibility to set it through ContentService. During creating a new node by EntityService.ReserveId() method or when saving already persisted node through IContent).

This way, identifiers could be generated outside of the Umbraco. The key will be stil available in IContent and IPublishedContent without additional mapping, data redundancy etc.

This functionality opens up a lot of advanced possibilities for us.

I hope you will take into account our case :) 

Best!

cc: @piotrbach
