### ISSUE TITLE
Changing start node in different document types for Image Media Picker changes all document types

### ISSUE THREAD

**Issue by tonylorentzen** [umbraco/Umbraco-CMS#14009]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

On two different document types I've created an Image Media Picker, but changing the "start node" property on each of them overwrites the setting on the other.

### Steps to reproduce

Just create two different document types with an Image Media Picker (Umbraco.MediaPicker3) property on each and try changing the "start node" and then check the other document type.

### Expected result / actual result

This bug makes it impossible to make different start nodes across different document types.

**Comment by nikolajlauridsen** [comment]
Heya @tonylorentzen, I'm sorry you've run into issues, but this is intended behaviour. 

The thing is that data types live separately to document types, but they can be shared between document types, additionally, the `Image Media Picker` is a premade, existing, data type. This means that when you use it on two different document types, it's actually the same data type used, so changing it on one document type will change it on both.

I'd recommend copying the data type twice in the side menu, one for each site, and then use each of those in your document types to reach your desired behaviour, hope it helps 😄 

![image](https://user-images.githubusercontent.com/16456704/227856044-641b973b-286e-4803-b1ab-295ea55e3d19.png)

But since this is the intended behaviour I'll go ahead and close your issue.
