### ISSUE TITLE
Umbraco.TextBox property validation problem (Maximum allowed characters)

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco-CMS#14063]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.1

### Bug summary

When I was trying to specify characters limit for Umbraco.TextBox default data type I got a validation error. Property description says, that if I not fill it, then limit is 512, but when I manually set limit to 512 it trigger validation error. Max currently allowed value is 500 characters

## I dont know is it importnant, I use MS SQL Server
![image](https://user-images.githubusercontent.com/45105665/230377242-483e1f38-e69f-41b8-b39b-1cea004b809f.png)
![image](https://user-images.githubusercontent.com/45105665/230377446-75eda5c4-2b37-4a32-a91c-9cea91a44a53.png)

### Steps to reproduce

1. Open backoffice
2. Got to "Settings" -> "Data type"
3. Create folder "Data Type/Base Types"
4. Move all default types to "Data Type/Base Types" folder
5. Create folder "Data Type/User-Defined Types/Shared"
6. Create new data type "UDT - Text box" under "Data Type/User-Defined Types/Shared" folder with defaukt props and save it
7. Try to set 512 to "Maximum allowed characters" property

### Expected result / actual result

There is possibility to set that value which displayed in "Maximum allowed characters" property description (512)

**Comment by PeterKvayt** [comment]
## It is also reproduced with 10.1.0

**Comment by kjac** [comment]
Hi @PeterKvayt,

Thanks for reporting 😄 I can reproduce this. 

The reason behind is likely someone being cautious, since the values from `Umbraco.TextBox` properties are stored in the `varcharValue` column of the `umbracoPropertyData` table... and that column is `nvarchar(512)`:

![image](https://user-images.githubusercontent.com/7405322/231462968-25b9b904-7da8-495a-bd6d-e6892a6f1f0d.png)

But - of course it should be possible to configure this max length to be less than or equal to 512. I'm going to mark this as up for grabs, in case you or someone else would like to have a go at fixing it.

On a side note, I would recommend you use the `Umbraco.TextArea` property editor for texts that are expected to be long. Entering 500+ characters in a single line text field is not the friendliest of editorial experiences.
