### ISSUE TITLE
Installing Umbraco Forms

### ISSUE THREAD

**Issue by ontranet** [umbraco/Umbraco-CMS#14111]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

Just installed Umbraco Forms 11.1.1 on a Umbraco 11.3.0 solution.
Every time i install Umbraco Forms, i loose the connection to the database.

### Specifics

localhost

### Steps to reproduce

Just installed Umbraco Forms 11.1.1 on a Umbraco 11.3.0 solution.

Tried several times.
Every time i install Umbraco Forms, i loose the connection to the database.
Uninstalling forms, re-establish the connection.

### Expected result / actual result

Get this errorr:

```
An unhandled exception occurred while processing the request.
        BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.
    
    -> Umbraco.Cms.Core.Exceptions.BootFailedException: A connection string is configured but Umbraco could not connect to the database.
    at Umbraco.Cms.Infrastructure.Runtime.RuntimeState.DetermineRuntimeLevel()
    at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.DetermineRuntimeLevel()
    Umbraco.Cms.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException)
```

**Comment by marciscaupjonoks** [comment]
Hi, I have experienced this multiple times after installing Umbraco forms and fixed it by adding "TrustServerCertificate=True" to the connection string

**Comment by kjac** [comment]
Hi @ontranet,

We haven't heard from you in a while, so we're going to close this issue. Hope you managed to resolve it in the meantime.

If adding `TrustServerCertificate=True` to the connection string, it sounds like this issue is related to what's reported [here](https://github.com/umbraco/Umbraco-CMS/issues/14272) for V12. In that case we're looking into a fix for core, which will then also benefit Forms in this case 😄
