### ISSUE TITLE
List view is empty inside a page even after save

### ISSUE THREAD

**Issue by maximyzer** [umbraco/Umbraco-CMS#14266]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

I have a page definition with a Tab which contains a list view. (the tab is not required for this bug)
![image](https://github.com/umbraco/Umbraco-CMS/assets/13802168/0a75db21-216a-478f-9698-e7db8f527f28)

When creating a Page, the child list view is empty, it doesn't even show the create child item button
![image](https://github.com/umbraco/Umbraco-CMS/assets/13802168/d88f843e-c390-41d5-98ee-92ebcba4fae5)

Even after saving, the create child item button doesn't appear, it's only after refreshing the page (or leaving and coming back) that the button and list actually appear.
(View after refreshing the page)
![image](https://github.com/umbraco/Umbraco-CMS/assets/13802168/99b19982-1a52-4cac-ac51-34becce60f12)

### Steps to reproduce

Steps:
Setting:
- Create a page template
- Add a list view in the page

Content:
- Create a new page
- Fill in the information (don't save)
- Check the List view -> It's empty
- Save
- Check the List view -> Still empty
- Refresh
- The list view is now available

### Expected result / actual result

The list view should be available (sonot be empty) during creation and after saving the page.
At the very least, the list view should be disabled during creation and available after a first save.

**Comment by kjac** [comment]
Hi @maximyzer,

The list view is not supposed to be used as a regular property. It is a special thing that only works (properly) under very specific circumstances. 

It is a bit unfortunate that one is able to apply it to content types as any other property, and the history behind that is long and quite opinionated. For the sake of keeping this short, you will have to settle for "that's just how it is".

List view usage and setup is documented in detail [here](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/listview).

In short: You need to enable list view on the content type itself, instead of adding a list view property to a tab:

<img width="863" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/7bab360f-6ae4-473a-b5a4-2119eebae422">

Now the content item will list its children in the "Child items" content app:

<img width="850" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/a229bea2-fbae-4476-ac86-58c9fa4f5a51">

There are a bunch of things you can tweak on the list view configuration, which you can reach either directly from the content type or by editing the list view datatype. For example you can change the name of the "Child items" content app and the sort order of the apps:

<img width="473" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/41279a12-80a9-4e89-b89b-7ffd7760397c">

...which will yield something like this:

<img width="863" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/18f7ffa1-4c50-44c0-b524-a3e9d3dd9813">
