### ISSUE TITLE
Rendering GLB (3D Animations) files within Umbraco

### ISSUE THREAD

**Issue by NCLAMB** [umbraco/Umbraco-CMS#14284]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco Cloud 11.1

### Bug summary

When using a Media picker to load a GLB file, which is a 3D rendered interactive model like this https://modelviewer.dev/ the picker selects the file but receive a 404 error on the glb file. 

### Specifics

I render the GLB file using a model viewer 

`<model-viewer alt="Neil Armstrong's Spacesuit from the Smithsonian Digitization Programs Office and National Air and Space Museum" src="shared-assets/models/NeilArmstrong.glb" ar environment-image="shared-assets/environments/moon_1k.hdr" poster="shared-assets/models/NeilArmstrong.webp" shadow-intensity="1" camera-controls touch-action="pan-y"></model-viewer>`

and use Google JS library here <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.1.1/model-viewer.min.js"></script>

### Steps to reproduce

Upload a GLB file to the Media folder

Implement the code here https://modelviewer.dev/ within a page template

Create Media Picker Doctype for a page to render.

Try selecting the GLB file from the media library and publish

### Expected result / actual result

Video of issue  [https://streamable.com/kewcfn](url)

**Comment by kjac** [comment]
Hi @NCLAMB,

Thank you for reaching out 👍 

When I upload a (fake) GLB file it uploads just fine, but I am unable to request it, which certainly is down to MIME types on the server since the file is on disk, ready to serve.

This sounds like this is a question for the [forum](https://our.umbraco.com/forum) more than a bug in Umbraco. If you're able to upload the file, the error isn't in Umbraco but rather in your implementation.

Here are a few things you can check before reaching out at the forum:

1. The `shared-assets/models` path looks suspicious and not very Umbraco-y, are they resolving in the frontend?
2. Can you request the uploaded GLB file from the frontend?
3. Is the MIME type handling correct for the GLB file - should it be handled/served differently by the server?

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/86788803-805c-4019-82db-c0f6bd9edbfc)

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/2b45d6a7-74d4-44bf-aea3-54ae5936a60e)

I'm going to close this issue as I don't see it being an Umbraco bug but rather something that must be handled in your implementation 😄
