### ISSUE TITLE
User null from IP address "::1" has logged out

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco-CMS#14281]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

When checking the logs to check the history of logout users, the user that logged out is going to be shown as null.

![image](https://github.com/umbraco/Umbraco-CMS/assets/83580347/947216d3-cc58-4e5d-ae34-4932915bd525)

### Specifics

In your application.json you must enable the logging of login / logout users.
"Microsoft.AspNetCore.Identity.SignInManager": "Information",

### Steps to reproduce

- Create a new project
- Change the logging level (add "Microsoft.AspNetCore.Identity.SignInManager": "Information", in your appsettings.json)
- Spin up the project
- Logout 
- Login 
- Check the logs

### Expected result / actual result

Get the right username instead of null.

**Comment by bergmania** [comment]
Seems to happen because we sign-out before we log. Can be fixed by saving the username in a variable before we sign out, and use it in the log message.

I have marked as up for grabs

**Comment by russellshome** [comment]
I've added  a pull request https://github.com/umbraco/Umbraco-CMS/pull/14322

The code in PostLogout was incorrectly referring to User but that is not populated because as per the comment
"this is not an authorized endpoint"
So we have to use the result of
AuthenticateResult result = await this.AuthenticateBackOfficeAsync();
at the beginning of that function to get the user that just logged out.
