### ISSUE TITLE
Rendering GLB (3D Animations) files within Umbraco with Media picker

### ISSUE THREAD

**Issue by NCLAMB** [umbraco/Umbraco-CMS#14304]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco Cloud 11.1

### Bug summary

When using a Media picker to load a GLB file, which is a 3D rendered interactive model like this https://modelviewer.dev/, when publihed the GLB file doesn't render on the page instead a 404 error shows. Seems like Umbraco doesn't recognise the .glb extension

### Specifics

https://dev-saietta.euwest01.umbraco.io/products/emotor/

### Steps to reproduce

Upload GLB file to media folder
Create a Media picker datatype
Add the doctype to a page template doctype
Choose GLB file with Media Picker
Publish File
On the frontend the GLB file doesn't show and has a 404 error on the media file link

https://streamable.com/kewcfn

![Screenshot 2023-05-26 at 00 17 07](https://github.com/umbraco/Umbraco-CMS/assets/153417/bc339b77-f227-4474-acc6-c10fde7f3437)

### Expected result / actual result

https://streamable.com/xi1mcl

**Comment by kjac** [comment]
Hi @NCLAMB,

This sounds a lot like the previous issue you reported for GLB rendering. Did you go through the steps in https://github.com/umbraco/Umbraco-CMS/issues/14284#issuecomment-1558645157 - specifically adding MIME types?

I tried a quick test of adding MIME types, serving GLB files as PDF (because my test-GLB-file is really a PDF file), and that works just fine:

```cs
            var provider = new Microsoft.AspNetCore.StaticFiles.FileExtensionContentTypeProvider();

            provider.Mappings.Add(new KeyValuePair<string, string>(".glb", "application/pdf"));

            app.UseStaticFiles(new StaticFileOptions()
            {
                ContentTypeProvider = provider
            });

            app.UseStaticFiles();
```

Again, I do not believe this is a bug in Umbraco, but rather ASP.NET Core doing its thing, not serving files that aren't whitelisted.

**Comment by harikrishna43** [comment]
provider.Mappings.Add(".glb", "model/gltf-binary");
provider.Mappings.Add(".gltf", "model/gltf+json");
this two would work
