### ISSUE TITLE
v12 RC2 Swagger UI not working on Umbraco Cloud

### ISSUE THREAD

**Issue by jbreuer** [umbraco/Umbraco-CMS#14309]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc2

### Bug summary

I cloned an Umbraco Cloud project (11.3.1) locally and upgraded it to `12.0.0-rc2` with the following command: `dotnet add package Umbraco.Cms --version 12.0.0-rc2`.

After that I enabled the Content Delivery API following these steps: https://docs.umbraco.com/umbraco-cms/v/12.latest/reference/content-delivery-api

Then I tried the Swagger UI on my local environment and it worked. I pushed my changes to Umbraco Cloud and tried to do the same there. However there the Swagger UI is not working:

Local:
![image](https://github.com/umbraco/Umbraco-CMS/assets/5444597/ba07a921-af8d-401a-a0f4-397542cd7d6f)

Umbraco Cloud:
![image](https://github.com/umbraco/Umbraco-CMS/assets/5444597/10b34ea4-7911-4b47-add7-03bd7eff5cb0)

Swagger UI doesn't work, but the Content Delivery API does work.

Local:
![image](https://github.com/umbraco/Umbraco-CMS/assets/5444597/c1382175-d863-47be-944a-71097e200814)

Umbraco Cloud:
![image](https://github.com/umbraco/Umbraco-CMS/assets/5444597/1728d252-f0ff-493a-9970-a48511f2cbb8)

If you visit this Umbraco Cloud URL you can see the results (it's a trial which is almost over): https://umbraco-trial.euwest01.umbraco.io/umbraco/delivery/api/v1/content

### Steps to reproduce

See bug summary.

### Expected result / actual result

The Swagger UI should work local and on Umbraco Cloud.

**Comment by warrenbuckley** [comment]
Hi @jbreuer 
I think this is by design, that swagger is disabled when your environment is not in debug mode AFAIK. 

@KennethJakobsen is this correct?

**Comment by nathanwoulfe** [comment]
This is the Kenn you're looking for - @kjac 😺

**Comment by kjac** [comment]
Hi @jbreuer,

Thanks for reaching out 😄 

This is indeed by design. 

For security reasons, the Swagger endpoints and the Swagger UI are never enabled in Production mode (`IWebHostEnvironment.IsProduction()`). On their own, neither Swagger nor the Delivery API poses a security issue. However, they implicitly leak the version of your Umbraco install, thus making it easier for potential attackers to narrow down their attack vectors.

You should be able to change this if you really really want, by creating your own pipeline filter based off the one in `UmbracoBuilderApiExtensions`. I would not recommend it for actual production use, though.
