### ISSUE TITLE
IPublishedContent extension method AncestorOrSelf(string contentTypeAlias) is inconsistent with the other method overloads

### ISSUE THREAD

**Issue by iliyan-kulishev** [umbraco/Umbraco-CMS#14345]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

![image](https://github.com/umbraco/Umbraco-CMS/assets/22516081/d040afdb-1765-4ec4-b909-cc562ec9c293)

The method returns the published model itself when no ancestors type alias match the input, **even if its alias doesn't match the input**.

### Steps to reproduce

1. Create a variable of type **IPublishedContent**
2. Run **AncestorOrSelf(string contentTypeAlias)** on it, where **contentTypeAlias** is an alias of a type, that doesn't match the type aliases of the variable or any of the ancestors.
3. Store the result in a variable
4. Inspect the value of the result variable.

### Expected result / actual result
**Expected**: the result should be null.
**Actual result**: the result is the value of the content itself.

**Comment by shearer3000** [comment]
I think I've just struck this same issue in Umbraco 13.x (13.2.2 and 13.3.0 to be exact)

expected: AncestorOrSelf("myContentAlias") returns an Ipc of that content type, otherwise null
actual: returns my homepage Ipc (which is not "myContentAlias")

from "Umbraco.Extensions.PublishedContentExtensions"
`/// <returns>The content or its nearest (in down-top order) ancestor, of the specified content type.</returns>
    /// <remarks>May or may not return the content itself depending on its content type. May return <c>null</c>.</remarks>
    public static IPublishedContent AncestorOrSelf(this IPublishedContent content, string contentTypeAlias)`

https://docs.umbraco.com/umbraco-cms/reference/templating/mvc/querying

**Comment by TwoMoreThings** [comment]
I agree with the previous comments that this is inconsistent and a breaking change from earlier versions

I would expect AncestorOrSelf("myContentAlias") should return null if there are no nodes of the specified type

**Comment by nikolajlauridsen** [comment]
Hey y'all good points about the earlier versions, I looked into this a bit again and found that the change was introduced in this PR: #12703, where similar issues were stated. 

Now this put us in a bit of a predicament since this issue has been there since V11, this means that it's very likely that a good amount of people have already migrated to the new behaviour or made new solutions relying on the current behaviour, and it would be breaking for them to unbreak this now. 

Given this I think a discussion with the team is warranted as to the best way to proceed, so I'll bring this up with the team, and get back to you 😄

**Comment by shearer3000** [comment]
thanks for update and workaround sample @nikolajlauridsen 😊
