### ISSUE TITLE
Installing Umbraco.Cms 10.5.1 startup.cs contains .AddDeliveryApi() and that's not in v10!

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#14453]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

I Installed a Vanilla 10.5.1 to trigger an upgrade from a V8 site...
I used Visual Studio to search for the Umbraco Project template
and specified the version as 10.5.1 and added db connection string

Project created successfully

went to run the project and got error:

_IUmbracoBuilder does not contain a definition for 'AddDeliveryApi' and no accessible extension method 'AddDeliveryApi' accepting a first argument of type 'IUmbracoBuilder' could be found (are  you missing a using directive or an assembly reference?)_

`  services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddDeliveryApi()
                .AddComposers()
                .Build();`

looking at startup.cs it has the AddDeliveryApi() called... commenting out made everything ok, but just wondered if something got merged back into V10 or something by mistake...

![v1051error](https://github.com/umbraco/Umbraco-CMS/assets/260802/090f8fd7-f319-42a4-b31f-d87be082e541)

anyway thought I'd raise it in case it were a thing...

### Specifics

The contrib branch of V10 doesn't appear to have the issue.

### Steps to reproduce

Yeah install 10.5.1 and try to dot net run it, should get the error above

### Expected result / actual result

You'd expect the latest version of v10 series to just work after installing it.

**Comment by abjerner** [comment]
Personally I find the whole setup with templates a bit messy - especially since you can only have one version of a template installed at a time. And to install an older version of Umbraco you have to install the template for that specific version first. I don't see a way to do this latter part from Visual Studio.

I think your issue happens because you have a template installed for Umbraco 12, but in the dialog, you've manually specified 10.5.1. Which means you're using the Umbraco 12 template, but with the Umbraco 10.5.1 dependencies (AFAIK).

It works fine when using Paul Seal's [**Package Script Writer**](https://psw.codeshare.co.uk/?InstallUmbracoTemplate=true&UmbracoTemplateVersion=10.5.1&Packages=&UserEmail=admin%40example.com&ProjectName=MyProject&CreateSolutionFile=true&SolutionName=MySolution&UseUnattendedInstall=false&DatabaseType=SQLite&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=false&StarterKitPackage=clean&OnelinerOutput=false) (as it installs the template of the expected Umbraco version):

```powershell
# Ensure we have the latest Umbraco templates
dotnet new install Umbraco.Templates::10.5.1

# Create solution/project
dotnet new sln --name "MySolution"
dotnet new umbraco --force -n "MyProject"
dotnet sln add "MyProject"

dotnet run --project "MyProject"
#Running
```

**Comment by kjac** [comment]
Hi @marcemarc,

Thanks for reaching out 😄 

Anders is spot on here. The templates only allow for one version of the templated files (including Startup). Thus... when installing V12 of the templates, you're expected to create V12 projects. 

With the way templates work, we can't really do a lot about this. We're currently considering restricting the templates from creating lower version projects than what they're designed for, thus forcing people to downgrade the templates in order to create new projects of a previews version. Emphasis on considering 😄 it would prevent these kinds of issues, but on the flipside it might be a bit of a hassle in the odd case that one needs to create a new project of an older version.

I'm going to close this as a non-issue ... but once again, thank you for taking the time to report it 🚀

**Comment by kjac** [comment]
@marcemarc it's no interruption 😄 it's a valid point. It would be nice to be backwards compatible in the templates... but it's a right mess to implement (to say the least).
