### ISSUE TITLE
Block List (inline): Settings model is not always persisted

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco-CMS#14494]
## Affected versions
8.0.0–v13.9.9 (all AngularJS versions with Block List)

## Description
The Settings model for blocks needs to have been seen by the user in order for the values to be persisted. If the user only creates a new block in the inline mode without clicking the "Cog" icon, then the settings are not persisted.

**Not yet persisted**
![image](https://user-images.githubusercontent.com/752371/250576334-5a78ecb3-f00c-4c06-8772-fc5e854aa207.png)

**Persisted after clicking Submit**
![image](https://user-images.githubusercontent.com/752371/250576379-8b5400b1-d7e5-4743-92ac-65ef7c87d3b2.png)

_Originally posted by @nikolajlauridsen in https://github.com/umbraco/Umbraco-CMS/issues/13134#issuecomment-1340752221_
            

---
_This item has been added to our backlog AB#41800_

**Comment by nielslyngsoe** [comment]
Hi @bergmania 

I've chosen to assigning you on this issue, because we are missing a general strategy for handling 'default' values.

The problem above is that we currently only set the defaults of the Slider, and many other property Editors, if they get rendered in Backoffice(v.8-13). I would say this should be handled on the server, as we do not want to make sure that Property Editors are rendered in all cases.
This case is even more discoverable in v.14 where we do not render content of non-opened Tabs of Documents.

For starters we are missing a general approach.

The main question is:
Do we want to treat defaults as a Preset, or as a Fallback when not set. This will determine if we expect a value to be set in the DB or corrected/defaulted only when read. Noticeable a preset-value is set when the document is created(before so its visible in the editing UI) VS. The fallback would never be saved in the DB, but used by Property Value Converters (and alike) when the DB value is null.

I do feel this is a project for v14+, and this should not be handled in existing versions as it would be breaking for projects already accepting this fact.

And I do think we need an Discussion or RFC for this topic.

**Comment by bergmania** [comment]
@nielslyngsoe 

IMO it should be a preset. With the current UI, there is no indications that this should be a fallback value, that, thereby can be changed by changing the defaults.

**Comment by nielslyngsoe** [comment]
This would be a breaking change and can therefor not be solved in v.11-13. We will be looking into making such feature possible in future versions. :-)
