### ISSUE TITLE
Content with '-' as name cannot be retrieved using delivery api

### ISSUE THREAD

**Issue by RoyvandenHeuvel** [umbraco/Umbraco-CMS#14506]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0

### Bug summary

You cannot retrieve content which is named '-' using the content delivery api. Given that it is possible to name content '-' (without jumping through any hoops) one would expect that the content delivery api can correctly retrieve this content.

### Specifics

Given this content: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/9801523/7349fcca-088a-422d-b3b7-ba5aa0fba20a)

You would expect this query to retrieve 2 descendants:
![image](https://github.com/umbraco/Umbraco-CMS/assets/9801523/4ad886a2-c43c-4ab5-b4a9-a98979c052ee)

However, as you can see, it only returns the descendant named 'Test':
![image](https://github.com/umbraco/Umbraco-CMS/assets/9801523/717f3ad0-a5b4-4d23-ac03-4cf12b375851)

### Steps to reproduce

1. Create a document type which can be placed in the root.
2. Create a document type which can be placed inside the previous document type.
3. Create the root document type.
4. Create a document type inside the previously created content named '-'.
5. Attempt to retrieve the inner document type using the content delivery api.

The api will not return the content you named '-'.

### Expected result / actual result

The api should return the content.

**Comment by elit0451** [comment]
Hey @RoyvandenHeuvel 

This is a tricky one as the issue comes within the core of Umbraco - if you check the published link of your content item named `"-"` (_in the Info tab_), you will see that there is no path for this item. So it seems like Umbraco doesn't allow for trailing/leading dashes in the name of the content items (they will be ignored when constructing the item's path). 

And by having your item named `"-"` it is not in the cache, so you cannot retrieve it through the Delivery API.
Changing the name to "_Item - 1_" or something else apart from the dash, will make your content item available through the Delivery API.


I will go ahead and close this as such content item name is not supported and therefore this isn't an actual issue.
