### ISSUE TITLE
Color Picker - selected color not displaying in Google Chrome (v12) #14375

### ISSUE THREAD

**Issue by mwillebrands** [umbraco/Umbraco-CMS#14553]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

It's identical as the problem described in #14375 and does not seem to be fixed yet. The fix seems to be manually cherry picked for 10, but does not seem to be in 11 or 12.

### Steps to reproduce

See #14375

**Comment by andr317c** [comment]
Hey!

Thanks a lot for taking the time to post this issue 😄. The fix was cherry-picked for 10 and later merged up to 11.4.3 and 12.1.0, but those versions are not released yet. 
Right now v11.4.3 does not have a target date, v12.1.0 has a target date, of August 10, 2023.
Since the issue has been fixed in an upcoming release, I will go ahead and close this issue.
