### ISSUE TITLE
UserDefaultLockoutTimeInMinutes is being ignored.

### ISSUE THREAD

**Issue by Ryan-Kirkwood** [umbraco/Umbraco-CMS#14561]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 11.3.0

### Bug summary

Setting the UserDefaultLockoutTimeInMinutes property in appsettings.json Umbraco -> CMS -> Security to any value is being ignored.

![image](https://github.com/umbraco/Umbraco-CMS/assets/49120112/c38eff49-4856-46e3-b69b-da8f0fd29770)

### Specifics

I have followed the documentation for [Security Settings](https://docs.umbraco.com/umbraco-cms/reference/configuration/securitysettings) to configure my User password options I have set the required length to 12 and the max failed access attempts before lockout to 3, both of these properties do take affect so when changing a password you need to have a minimum length of 12 and if you enter the wrong password 3 times you get locked out of the back office.

However I have set the user default lockout time in minutes property to 5 and no matter how long I wait on the locked account I can't log in with the correct password.

![image](https://github.com/umbraco/Umbraco-CMS/assets/49120112/84f50954-9b35-4621-9d08-e1a166f8b5b2)

As you can see from the image above I have created a new test user, failed to log in three times, which caused a lockout but the lockout time is 10:36 and the account is still locked.

### Steps to reproduce

1. Add the following into your appsettings.json:

`"Umbraco": {
    "CMS": {
      "Security": {
        "UserPassword": {
          "RequiredLength": 12,
          "MaxFailedAccessAttemptsBeforeLockout": 3
        },
        "UserDefaultLockoutTimeInMinutes": 5
      }
    }
  }`

2. Create a new user.
3. Enter the wrong password for the user to trigger a lockout.
4. Wait 5 minutes and try to log in again. 

### Expected result / actual result

I would expect that after the 5 minutes are up that the lock is taken off the user and that they can try again to log into the back office.

What is actually happening is that the user is locked out for an indefinite amount of time.

**Comment by marcemarc** [comment]
Wonder if the fix for this is to change the line here:

https://github.com/umbraco/Umbraco-CMS/blob/2b629693950818865a9f8ee316ec7bc1538d287f/src/Umbraco.Infrastructure/Security/IdentityMapDefinition.cs#L110

`   target.LockoutEnd = source.IsLockedOut ? DateTime.MaxValue.ToUniversalTime() : (DateTime?)null;
`
That forces the lockout date to be the maximum value possible for a DateTime - if 'noconsole' is true  - this seems to conflict with the notion of having a default lockout timeout period as per AspNet Identity??

Would the fix be this instead?

`       target.LockoutEnd = source.IsLockedOut ? (source.LastLockoutDate.HasValue ? source.LastLockoutDate?.ToUniversalTime() : DateTime.MaxValue.ToUniversalTime()) : (DateTime?)null;`

Essentially check if the user IsLockedOut (eg noconsole is true) and if it is

 check if a LastLockoutDate has been set, 

and if it has, use that value - so the user can become unlocked after the specified time period

but if the LastLockoutDate doesn't have a value  (eg an upgraded Umbaco site with a user locked out before the notion of LastLockoutDate was introduced), and the value isn't set, then use the MaxValue....to prevent them from ever becoming unlocked?? (or only unlockable via the backoffice?)

regards

Marc

**Comment by Ryan-Kirkwood** [comment]
Hey Marc,

Thanks to your reply on the Umbraco forum and after looking at the source code examples you sent I came to the same conclusion that it seems to be this line that is tripping up the lockout logic. I think you're right that should fix it, I am going to pull the source and update apply the change and see if that uses the property set in the app settings.

I haven't contributed to open source before so going to take my time to make sure everything is above board, thanks again for the information.

**Comment by marcemarc** [comment]
@Ryan-Kirkwood cool yes go for it! There is a guide here: https://github.com/umbraco/Umbraco-CMS/blob/contrib/.github/CONTRIBUTING.md that should help.

(I was going to say on the forum, we could raise an issue, but you already had!)

The only thing I'm not sure about though, is whether LastLockoutDate stores the date of Lockout + the timeout in minutes, or whether it is literally the datetime that someone was locked out!

and therefore with this change - people won't be locked out at all! - eg there maybe is a different way to get the Lockout End DateTime? or maybe the configured timeout period needs to be added to the LastLockoutDate for the comparison!

But be great if you get it up and running and can work that out!

Excitingly if your PR is accepted @nul800sebastiaan will grant you a shiny 'Contrib' badge for your forum profile, I mean that's gotta be worth it!

**Comment by Zeegaan** [comment]
Hey @Ryan-Kirkwood thanks for reporting this 🙌 
I can definitely also reproduce this 👍 
I've marked this one as up-for grabs, it seems you are already in the process of fixing this, love it! 
Good luck 🤞

**Comment by Ambertvu** [comment]
As I don't think Ryan is working on it at the moment, I've picked this up right now :-)

**Comment by SeanFarrow-RSK** [comment]
Is this still up for grabs?
If yes, it is something I'd like to work on.

**Comment by Ryan-Kirkwood** [comment]
Hey @Ambertvu thanks for picking this up!

@SeanFarrow-RSK, you might have seen @Ambertvu has made a pull request for this issue so you may want to take a look at that or have a go at a solution yourself.

Sorry I've not been able to pick this up just been a busy few months for me.

**Comment by Ambertvu** [comment]
No problems @Ryan-Kirkwood We're all doing this together 👍
