### ISSUE TITLE
JsonException thrown due to json object depth exceeding 32 in delivery api

### ISSUE THREAD

**Issue by NikiSkaarup** [umbraco/Umbraco-CMS#14610]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

System.Text.Json.JsonException being thrown due max depth exceeding 32 when the resulting json is deeply nested, such as making a navigation menu with possible submenues that can nested a couple times, this will quickly result in exceeding the max depth of 32, this results in a closed connection

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth?view=net-7.0

Shows it can be set 64 instead of the default of 32

Exposing it as a configuration option we can set ourselves would also work for those of us hitting this issue, since most probably won't need more than 32

### Specifics

Delivery Api endpoints

### Steps to reproduce

Create property that can self nest (like a block grid that accepts the same block grid as a child) and then nest it couple times until the resulting json tree would be more than 32 deep

### Expected result / actual result

Successfully getting a response from the delivery api

**Comment by kjac** [comment]
Hi @NikiSkaarup,

That's some nesting you've got going there! Thank you for raising awareness on this issue 👍 

Fortunately you can configure this yourself. In the `ConfigureServices()` method of `Startup`, add:

```cs
services.AddControllers().AddJsonOptions(
    Constants.JsonOptionsNames.DeliveryApi,
    options =>
    {
        options.JsonSerializerOptions.MaxDepth = [your desired max depth];
    });
```

You may also need to add `using Umbraco.Cms.Api.Common.DependencyInjection;` to resolve the `AddJsonOptions()` extension method.

I tested the API with a max depth of 2 and got this fine error:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/f6fe50c8-ae6a-4d08-9317-ce0d61042cd5)

As expected, the error went away when I increased the max depth.

Since this is configurable in the framework, we're not going to implement additional configuration options for the Delivery API. But this is an obvious candidate for a docs update, so I'll get that going.

As you say, most won't need to bump this configuration. That being said, we'll be monitoring for similar issues to find out if this is going to be a wider spread issue that expected. In that case we might have to do something about the default configuration 😄

**Comment by Wiggee11** [comment]
@kjac We have a deeply nested Block grid structure that if we add a 7th level it exceeds the maxDepth 32 limit (each block adds ~5 levels. 7 x 5 = 35 💥 ).

<img width="1381" height="244" alt="Image" src="https://github.com/user-attachments/assets/a8213e75-aa90-4864-b988-52581a297926" />

This is blocking us from saving nodes in the backoffice.

I've tried increasing the maxDepth as per the documentation but that only relates to the Delivery API output. We would need a way to configure the default JsonSeralizer options.

**Comment by AndyButland** [comment]
@Wiggee11 - I recall this came up in internal testing a while ago.  You should find that the management API is already configured with the maximum supported value: https://github.com/umbraco/Umbraco-CMS/pull/19001

**Comment by Wiggee11** [comment]
> [@Wiggee11](https://github.com/Wiggee11) - I recall this came up in internal testing a while ago. You should find that the management API is already configured with the maximum supported value: [#19001](https://github.com/umbraco/Umbraco-CMS/pull/19001)

We are running Umbraco 15.4.1, released 5th May, after the PR was merged into `v15/dev` on April 14th.
<img width="366" height="103" alt="Image" src="https://github.com/user-attachments/assets/d26edcdc-1e30-41ef-8983-049ee635c2dc" />

The ManagementApi may be updated to set maxDepth of 64 but we think there are other JsonSerializer classes used elesewhere that have not been updated. Still waiting for v15 codebase to load so I can dig deeper.

I've tested on a v16 instance and I am able to nest 14 blocks before exceeding the maxDepth 64.

I will try upgrading to 15.4.4 to see whether that improves the issue.

I also don't think `64` is the [maximum value allowed](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth?view=net-9.0).

> Gets or sets the maximum depth allowed when serializing or deserializing JSON, with the **default value of 0 indicating a maximum depth of 64**.

You should be able to set 128, 256, 512...

**Comment by AndyButland** [comment]
> You should be able to set 128, 256, 512...

Looks like you may be right - could be I misread that line in the docs and took it as the max depth you could have.

Please feel free to make a new issue for this is you see a problem after you've investigated, so we keep it separate from this closed on specifically about the delivery API.
