### ISSUE TITLE
Changing property editor of datatype true/false to dropdown another throw error on content (possible related to issue #14746)

### ISSUE THREAD

**Issue by tomotrepo** [umbraco/Umbraco-CMS#14753]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1.

### Bug summary

Changing property editor of datatype true/false to dropdown throw error on content (possible related to issue #14746)

### Steps to reproduce

1. Create Document Type With Template e.g. Common Page
2. Create Data Type Umbraco.DropDown.Flexible e.g. 'Background Style' and add 3 options: Red, Blue, Yellow
---
3. Go to Settings/Document Types and select Common Page
2. On the Common Page, create a property with the name e.g. 'Styled Background' of type Umbraco.TrueFalse and save it
4. Go to Content and create a Common Document page
5. Set the 'Styled Background' box to True and save it
---
6. Go to Settings/Document Types and select Common Page
7. Change the 'Styled Background' field from Umbraco.TrueFalse to 'Background Style' of type Umbraco.DropDown.Flexible and save it
8. Go to Content and open the aforementioned Common Page
9. An error occurs 'Error converting value 1 to type 'System.String[]' appears. Path '', line 1, position 1.'

![Capture1](https://github.com/umbraco/Umbraco-CMS/assets/7202849/1e435e50-0287-42ac-9ad8-ca8712810a4a)

### Expected result / actual result

Correct mapping from bool to string.

**Comment by kjac** [comment]
Hi @tomotrepo,

Thanks for raising this 😄 

This is the expected behavior. It is generally not possible to change data types on properties, if content already exist with values for said properties. The editors are (with a few exceptions) unable to convert values between each other. In this case, the dropdown editor is trying to convert the existing boolean value (from before the editor was changed) in to a string array, which it expects as value. That is not possible, thus an error occurs.

The best way to go about this kind of change is to introduce a new property (with a different alias) and delete the old one. Obviously this results in data loss on the existing content, but since existing data cannot be ported between property editors anyway, it won't introduce additional data loss.
