### ISSUE TITLE
Multinode Tree Picker does not show path to the selected item (multilingual website)

### ISSUE THREAD

**Issue by AdamczykMaciej** [umbraco/Umbraco-CMS#14793]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

Multinode Tree Picker does not show the path to the selected path (multilingual website).

Instead it shows '#'.
On the default language version it works fine. But on the other language version of my website it shows '#'. All content published.

Page View (Block List item)
Default language
![image](https://github.com/umbraco/Umbraco-CMS/assets/34938878/a14d7e21-5e93-4cc5-a2ed-a064d2452bce)

Secondary language
![image](https://github.com/umbraco/Umbraco-CMS/assets/34938878/78b134fd-b823-429a-a7cb-384fd8febe3d)

### Steps to reproduce

Create 2 language versions of a page.
Create a field of type Multinode Tree Picker. I used xPath to restrict the results. Select a value.
DO the same for both language versions of the page. You will notice that on one it shows the correct path, on the other one it shows '"'. I did it in a BlockList in a module but you can do it on a page as well I think.

**Comment by andr317c** [comment]
Hey!

Thanks for reporting this issue. I just took a look into the issue, and I think the reason you are getting returned '#' for the multiNodeTreePicker for your second language, is that you do not have a configured domain for the content you are inserting into the TreePicker for the second language.

So if you try to add a domain for the content you are inserting into your TreePicker for the second language, you should be able to get the correct path. 

See GIF:
![MultiNodeDomain](https://github.com/umbraco/Umbraco-CMS/assets/73799582/3291049b-c10b-463e-b3dc-ec2735c6853c)

Since this isn't really an issue, I go ahead and close this. Please reopen the issue if you do not get a path for the multiNodeTreePicker for your second language when adding a domain! 😄
