### ISSUE TITLE
Data type is not updated during package migration 

### ISSUE THREAD

**Issue by yiscaGi** [umbraco/Umbraco-CMS#14871]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

When updating a datatype in a package, during package migration the datatype is not updated in the target Umbraco site.

### Specifics

Updating most of the time means adding - like adding optional block to blocks list data type or adding option to radio button data type.

### Steps to reproduce

1. Create Data type of blocks List type
2.  Add optional blocks
3. Create the package
4. Install the package in the target site
5. Create a new block (in original project)
6. Add it to existing block list data type
7. Update package
8. Run package migration
9. The block list data type in target site does not contain the new optional block

### Expected result / actual result

Data type should be updated in target site when upgrading package.
I think that there should be some built in option for that .. every package needs the option to change data types .
the same  as the option to update document types or every component in the package .

**Comment by kjac** [comment]
Hi @yiscaGi,

Thank you for reaching out 😄 

This is by design for package migrations as described [here](https://docs.umbraco.com/umbraco-cms/extending/packages/creating-a-package#package-migration), and at this point there are currently no plans to change the design. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/261172e1-e567-4c69-884b-b5c52ee1a2e6)

See also the previously report [here](https://github.com/umbraco/Umbraco-CMS/issues/13616#issuecomment-1400196393) (but I believe you already found that 👍).

You *should* be able to achieve your goals by creating a custom migration plan, instead of relying on generated packages. Of course this is somewhat more cumbersome to build, and we do recommend you use tools like uSync or Umbraco Deploy to automate these things.
