### ISSUE TITLE
During Umbraco install connection string is set in the base appsettings.json instead of in the appsettings.{environment}.json

### ISSUE THREAD

**Issue by miguelcrpinto** [umbraco/Umbraco-CMS#14957]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0 and 10.7.0

### Bug summary

During Umbraco install the connection string is set in the base appsettings.json instead of in the appsettings.{environment}.json.

### Specifics

During Umbraco install the connection string is set in the base appsettings.json instead of in the appsettings.{environment}.json. In case there's an empty connection string set in appsettings.{environment}.json, the connection string of the environment file is used (instead of the new connection string set in the base appsettings.json) and this causes the error below:

![Umbraco database installation error](https://github.com/umbraco/Umbraco-CMS/assets/8625173/425c07ce-0aed-4c8a-9c32-6533891a1736)

Log file:
[UmbracoTraceLog.MIGUEL-LAPTOP.20231010.json](https://github.com/umbraco/Umbraco-CMS/files/12861180/UmbracoTraceLog.MIGUEL-LAPTOP.20231010.json)

### Steps to reproduce

1. Create a new project based on the Umbraco Project template from Umbraco.Templates
2. Make sure there's no connection string set in the appsettings.json
3. Add/Replace the connection string in the appsettings.Development.json with the the following values: `"ConnectionStrings": {
  "umbracoDbDSN": "",
  "umbracoDbDSN_ProviderName": ""
}`
4. run the project
5. configure the admin user and click install

### Expected result / actual result

The connection string should be set in the appsettings.{environment}.json file instead of in the base appsettings.json

**Comment by Migaroez** [comment]
Hey @miguelcrpinto

I think this should be considered a misconfiguration instead of a bug. Below is my reasoning.

Since we are using the (.net options pattern) [https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0] we have no idea of knowing where a setting actually comes from. Nor should we as the source of a setting doesn't even have to a configuration file, you could in theory add a configuration source that just supplies static values from code.

Because of this, we update the default appsettings.json file with any configuration values we let you configure in the configuration part of the installer.

When the actual installer runs, the Options pattern takes over again and combines all configuration sources. Because you supply a key with a whitespace value in a superseding configuration (which again, could be anywhere) the configuration is made invalid and we can't actually install.

**Comment by elit0451** [comment]
Based on @Migaroez ⬆️ I will close this

**Comment by miguelcrpinto** [comment]
@Migaroez This could be improved by looping through the configuration providers from last to first (assuming they show up in the list in the order they were registered) in the GetJsonConfigurationProvider method of the JsonConfigManipulator class. In theory the last registered provider is the one overriding all the previous and adding the connection string to that provider would increase the chances of writing to the correct file/provider. But this would always be a best guess...

It's fair enough to consider this a misconfiguration and close the ticket.
