### ISSUE TITLE
Block Grid drag and drop not working on Firefox Version 118.0.2 - Umbraco 10.7.0

### ISSUE THREAD

**Issue by jawood1** [umbraco/Umbraco-CMS#15027]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7.0

### Bug summary

The ability to drag and drop blocks within a Block Grid isn't working on the latest version of Firefox (118.0.2).

### Specifics

I've tested this on the latest version of Firefox and Chrome, this is working correclty on Chrome.

This effects both the standard drag and drop and the sort mode. The sort mode only works when dragging directly on the text.

https://github.com/umbraco/Umbraco-CMS/assets/47325234/b1ca15be-0ea5-40c7-9f0e-857ac99c802e

### Steps to reproduce

- Create a Block Grid dataType
- Add some blocks
- Attempt to drag the blocks
- The blocks aren't able to be dragged.
- Go into sort mode
- Blocks can't be dragged in sort mode unless dragging directly from the text.

### Expected result / actual result

Blocks are able to be dragged and dropped.

**Comment by netcamo** [comment]
Hi @jawood1,

I hope everything is going well for you!

Thank you for bringing up this issue to our attention!


While I have not been able to reproduce it this issue on the specified version of Mozilla Firefox, I have also noticed that there is  a new Firefox version released (v119). I would be very happy if you could check if new version of Mozilla Firefox has fixed the issue for you. Otherwise could you please also specify OS that you are using?

Thank you again for bringing this issue and I wish you a wonderful weekend ahead! 😄

**Comment by jawood1** [comment]
Hi @netcamo 

I'm good thank you I hope you are as well?

I've updated to v119 of Firefox and re-tested to find the issue still persists. I can move the blocks around around if I drag from the block name on the right hand side or from the block name if it's doesn't have a preview but dragging from the inside the block itself doesn't work. This is also the case for when I'm in sort mode.

The OS I'm using is Windows 11 Pro version 10.0.22621 Build 22621.

Many thanks and have a good weekend as well!

**Comment by netcamo** [comment]
Hi @jawood1,

I hope everything is going well for you!


Thank you. very much for additional details that you have provided!
I have been able to reproduce it in the Windows OS with Firefox v119. I will assign appropriate labels now.

Thank you again and I wish you a wonderful rest of the week!

**Comment by andr317c** [comment]
This issue is something we would like help with! So I will set this issue up for grabs 😄

**Comment by nielslyngsoe** [comment]
As this issue is very specific and not completely prohibiting working with data neither moving Blocks — as the user of this specific setup can drag from the name, I will mark it as stale and close it.
Also notice this is not the case in never versions of the CMS, so please upgrade to latest.
If you find interest in providing a fix for this version, note we do not release bug fixes for v.10 any longer so it would have to target v.11, feel free and re-open the issue in that case. Thanks in advance.
