### ISSUE TITLE
v13: Validation of form should only happen after form is invalid

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#15074]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0

### Bug summary

I noticed the new login form in `v13/dev`, but it seems the validation trigger after blur.
Best practise is that it first happen after form has been submitted (invalid).

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/efd01fb1-6439-4a38-a325-1f0e954d8201)

### Steps to reproduce

Set focus in username/email field and click elsewhere to blur.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/b419e326-0c57-4525-a970-24629a476fd1)

Next each time a character is typed the validation message updates.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/28da1dff-8d65-496e-90a5-42669ff401fc)

**Comment by iOvergaard** [comment]
Hi @bjarnef, thanks for reporting this. I generally concur that it doesn't work well on the login screen. Unfortunately, this is the only option available to us through the UI library at the moment. We will consider building in more options to control when the validation happens, so I'll go ahead and create a discussion on the UI library.

There are a few reasons why we chose to go down this route with "blur", and I am not convinced that neither blur nor submit is considered a best practice per se. [This article from Smashing Magazine](https://www.smashingmagazine.com/2022/09/inline-validation-web-forms-ux/) says otherwise, for instance.

However, since we don't have good server validation from the backend that can be matched to individual fields, we might consider it being more user-friendly behavior to validate on submit in this particular case. I will leave it up to the UI library discussion to implement more functionality. We will need it for sure when we start implementing validation in Bellissima.

**Comment by iOvergaard** [comment]
I have created a discussion on the Umbraco UI Library to follow through with a holistic perspective on validation: https://github.com/umbraco/Umbraco.UI/discussions/640
