### ISSUE TITLE
V13 RC: Deleting a webhook opens up webhook side bar

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#15094]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v13 rc1

### Bug summary

Clicking on delete on a webhook, opens up both the confirm delete webhook, and the edit webhook sidebar. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/830aa39c-b166-47f0-896d-19be629c73ec)

### Specifics

On the webhook dashboard, if you attempt to delete a webhook via the 'delete' button, you get both the confirm overlay and the edit sidebar.

once you have deleted via the overlay, if you then click save on the open sidebar, you also get an error (because you just deleted the thing it is trying to edit.

### Steps to reproduce

1. Create a webhook,
2. Delete the webhook from the dashboard.

### Expected result / actual result

Only the Confirm delete webhook should be shown.

**Comment by bjarnef** [comment]
I have fixed that 😉😁😎

**Comment by KevinJump** [comment]
just noticed it also happens if you attempt to enable/disable the webhook on the dashboard (via the checkbox) ? not sure if that's the same code that needs fixing for that too?

**Comment by bjarnef** [comment]
No the checkbox in the list is not really a checkbox, but a checkmark 🙂
And the clicking the table row opens the edit view, but clicking the delete button shouldn't bubble to parent event.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15077, so I will go ahead and close this 😁 

I do however wonder if we could do anything about the enabling thing.. But I think it's a bigger issue in itself in general with the <umb-checkmark>.
Maybe because when you hover the checkmark, it actually changes color, and therefore gives an impression that it does something when you click it? 🤔
