### ISSUE TITLE
Copy on listview doesn't update listview (refresh page is requiered)

### ISSUE THREAD

**Issue by AndriiDzendzia** [umbraco/Umbraco-CMS#15300]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

The list view doesn't update after performing a copy.

### Steps to reproduce

Create a doc type A with any textstring property. Create another document type B and configure as list view and allow to be created at root. Allow doc type A as child node type of doc B.

Create node of type doc type B, create multiple nodes of type doc type A.

Select one or more doc type A instances in list view, and click on 'Copy'.

### Expected result / actual result

**Expected result**
After 'Copy' was completed, you should see the new nodes in the list view

**Actual result**
The list view hasn't refreshed, for 'Copy' you can't see the new nodes in the list view

**Comment by kjac** [comment]
Hi @AndriiDzendzia,

Thanks a lot for reporting this 💪 I can reproduce it. Looks like an oversight in the [`performCopy`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js#L652) method.

I'm putting this up for grabs if anyone wants to try fixing it. 

As for fixing it, one should look to the `performMove` operation - particularly how it [reloads the view](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js#L614) after a successful move. For copying this should _only_ be done if the destination of the copied items is the same as the currently displayed content item. Otherwise the list view content won't change, and a reload is not necessary.

**Comment by CodeBunTes** [comment]
Unless anyone has any objections, I may have a look to see if I can address this one as a good first issue.

**Comment by kjac** [comment]
Hi @CodeBunTes,

By all means ❤️
