### ISSUE TITLE
GetByContentType(IPublishedContentType contentType) not working with VariByCulture nodes when called from controller

### ISSUE THREAD

**Issue by gardarthorsteins** [umbraco/Umbraco-CMS#15473]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.5

### Bug summary

If you try to fetch all nodes based on contentType from IPublishedContentCache and in a UmbracoApiController where the nodes have variByCulture on them no results will be returned.

### Specifics

We have this issue in at least version 9,10,11 and 12.

### Steps to reproduce

This code will always return no results if contentType is vari by culture
using var ctx = _umbracoContextFactory.EnsureUmbracoContext();
var contentType = ctx.UmbracoContext.Content.GetContentType("contentTypeAlias");
var contentItems = ctx.UmbracoContext.Content.GetByContentType(contentType);

### Expected result / actual result

I would expect to get the nodes back with default culture set.

---
_This item has been added to our backlog AB#36260_

**Comment by elit0451** [comment]
Thanks for reaching out @gardarthorsteins 👋 

I was able to reproduce the issue, so we will take a look.

Have a joyful new year! 🎊

**Comment by elit0451** [comment]
Hi again @gardarthorsteins,

Just wanted to stop by and clarify that you weren't getting any nodes back as the nodes you had in the content type you were looking for were probably children of another node in the Content tree. I tested it with both nodes on the root level and nested to another node, and I was getting only the root ones when the content type varied by culture. So great spot 💪 

This issue is fixed in https://github.com/umbraco/Umbraco-CMS/pull/15563
