### ISSUE TITLE
Home/end keys doesn't work correct with scale slider at crops

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#15578]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.6

### Bug summary

I noticed in Media Picker and Image Cropper the `home` and `end` keys doesn't seem to work correct here.

Arrows keys and PageUp / PageDown keys seems to work correct though and also possible to drag handle in slider to start or end.

In Slider property editor it does seem to work correct though.

### Steps to reproduce

- Select a defined crops in Media Picker and/or Image Cropper
- Focus handle in scale slider
- Hit `home` or `end` key - these should move handle to `start` or `end` position

**Comment by andr317c** [comment]
Hey Bjarne!
Thanks for posting this issue, I was able to reproduce this on version 12.3.6. It was a bit weird. For the MediaPicker the "End" button worked as intended but the "Home" button only went halfway and not to the start of the slider.
For the ImageCropper. the "End" button also worked for me. But the "Home" went to the end instead of the start of the slider. I will set this issue as an up for grabs 😄

**Comment by bjarnef** [comment]
@andr317c yes, I noticed that as well.
Sometimes it seems `home` moved to end it the current value.
In my test the `change` event didn't seem to returrn the start value.
However it the normal slider property editor it seems to work correct.

**Comment by nagolucky18** [comment]
I can look at this one.
