### ISSUE TITLE
Content Delivery API: return value "unsupported" in JSON for the member picker propriety

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco-CMS#15912]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

I've a document type with a member picker.
The json return unsupported for the member picker value.

### Steps to reproduce

In a controller:
   var cc = _apiContentBuilder.Build(_publishedContentQuery.Content(id));
   return Ok(cc);

<img width="446" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/661517/09850c95-cd05-48fe-b1de-d9a71601137f">

**Comment by markadrake** [comment]
I'm only adding this for context. 

[From the docs:](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api#member-picker)

> Member Picker
The Member Picker property editor is not supported in the Delivery API to avoid the risk of leaking member data.

**Comment by biapar** [comment]
Ok. I read into the docs. How to add only the member id with the custom code?

**Comment by Migaroez** [comment]
Hey Biapar, as noted in the docs, we do not serialize out the MemberPicker because of GDPR/security concerns.

You should however be able to expose certain fields yourself.

Create a new class that inherits from the core MemberPickerValueConverter, then overwrite/new the 
ConvertIntermediateToDeliveryApiObject method with your logic based on the following docs https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/custom-property-editors-support
Don't forget to explicitly make your class implement the `IDeliveryApiPropertyValueConverter`interface and remove the existing converter with a composer

```csharp
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors;
using Umbraco.Cms.Core.PropertyEditors.DeliveryApi;
using Umbraco.Cms.Core.PropertyEditors.ValueConverters;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;

namespace Umbraco.Cms.Web.UI.App_Data;

public class MyMemberPickerValueConverter : MemberPickerValueConverter, IDeliveryApiPropertyValueConverter
{
    public MyMemberPickerValueConverter(IMemberService memberService, IPublishedSnapshotAccessor publishedSnapshotAccessor, IUmbracoContextAccessor umbracoContextAccessor) : base(memberService, publishedSnapshotAccessor, umbracoContextAccessor)
    {
    }

    public new object? ConvertIntermediateToDeliveryApiObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, object? inter, bool preview, bool expanding)
    {
        // do your thing here
        return true;
    }
}

public class Composer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.PropertyValueConverters()
            .Remove<MemberPickerValueConverter>();
    }
}
```
