### ISSUE TITLE
Multiple MNTP on page use incorrect start node

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#15966]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.9

### Bug summary

On a page we have a education page and a school picker on a content node.

The school picker is configured to select from an archive and opens the archive by default as start node.

However the education page, which should just open from root, seems to open the current node as start node.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/5d5e49db-f04b-4683-8c4f-565d6cefe83d)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/b0581e6c-e283-475f-a496-5d4932366d40)

I think this may happen, because it request this in URL from listview `/umbraco#/content/content/edit/2833?list=2825&page=1&filter=&orderBy=updateDate&orderDirection=desc` and seems the MTNP may use 2825 (archive node) instead of root level.

It request from MNTP it has this - instead of the expected root level.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/f2060387-10af-4ff2-8dd2-367a8b7f719f)

### Steps to reproduce

Add two MTNP to node in listview which allow two different types on content nodes to be picked, but one from an archive and the other just at root as default.

**Comment by Migaroez** [comment]
Hey @bjarnef, I remember this behavior stumped me a bit as well a few years back when I was setting up some MNTP configuration for a big project. It all made sense after some investigation. Let me explain.

When the mini tree is opened in the picker window, the system highlights the current node to show where you are in the tree, to give you a reference point I suppose. This happens even if the current node is not a valid node as shown below. Think of this as unfolding the tree for perspective instead of actually selecting.
![image](https://github.com/user-attachments/assets/530c0403-7328-409c-842c-2fafb593a170)

Now combine that with the fact that to be able to highlight/show a node in a listview, you have to open that list view then you get the behavior that you described.

If your current node is outside of the tree structure of the configured root node, as is the case in your other example. Then the system can not highlight it and the root node is shown instead.

Now to put on my HQ hat again. 
Because the behavior is consistent and explainable and has worked like this for a long time, as far as I know as long as we have had listviews and an MNTP. This would be considered a behavioral change and not a bug. So, I would urge you to check whether this behavior is unchanged in v14 as some of these things have been reworked from the ground up and if hasn't or hasn't changed in the direction you would like it to have changed to open up a discussion regarding this topic instead. This way we can hopefully gather input from the community before we make a change that might impact many people's current way of doing things.
