### ISSUE TITLE
The rich text editor is not loading within the media type of Image.

### ISSUE THREAD

**Issue by AlperOren** [umbraco/Umbraco-CMS#16070]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

**version 13.0.3**

### Bug summary

Adding a property with the "Rich text" data type to the "Image" media-type, causes a JavaScript error  The error is  Umbraco-backoffice- Could not find **umbVariantContent** in the **$scope chain**

Image has several properties, the error only surfaces when adding the rich text editors. Please see attached images 

![1MediaType](https://github.com/umbraco/Umbraco-CMS/assets/4127074/f30c4541-62ad-4aeb-ad15-0c4318b68b9c)

![2MediaTypeImageProperties](https://github.com/umbraco/Umbraco-CMS/assets/4127074/b0960157-4d11-4b86-b8fb-b335c3fc7dc6)

![3MediaTypeImageEmbededRichTextEditorLoadError](https://github.com/umbraco/Umbraco-CMS/assets/4127074/63b9484b-21b0-4dd1-99c0-0d15c06607bc)

### Steps to reproduce

Add a media type of image
Add a few text fields 
Add a rich text editor
Make sure rich text editor does not fail to load

### Expected result / actual result

The rich text editors should render and load as normal as other properties such as text, textarea, numeric and etc.

**Comment by nhudinh0309** [comment]
Hi @AlperOren,
Thanks a lot for reaching out and report this 💪  
I was able to reproduce your issue on version 13.0.3. Afterward, I tried reproducing it on version 13.3.0, where the Rich Text Editor can loads and renders without any issues. Therefore, it appears that the issue has been resolved in version 13.3.0.😃 I recommend updating to version 13.3.0 in order to resolve it.
