### ISSUE TITLE
v14-rc1: Unsharp Umbraco logo

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16089]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc2

### Bug summary

I tried the recent RC and it seems the Umbraco logo is a bit unsharp although the original SVG logo seems to be sharp.

Chrome Version 123.0.6312.123

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/88a99c1f-0a86-4dcf-8d7f-8568fed36b97)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/bb4bc37b-5c9d-4861-a03e-5e53bbeee0ce)

When increasing the size a bit the quality seems to be better and in my opinion it is would be okay to increase the size a bit.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/73cb5883-c394-447c-909d-b1a0b4365a39)

It can also use a tool like https://svgomg.net/ and if copying the SVG markup, it optimize the SVG further.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/abe17770-eaa2-4abd-9d71-10a55e8880de)

### Steps to reproduce

Inspect Umbraco logo in header.

**Comment by bjarnef** [comment]
@elit0451 great ... I wrote v14-rc2, because it shows that at version and there a dotnet Umbraco Template rc2 available, but it seems there is only a rc1 on NuGet.
![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/9bd43d50-05be-4eb2-8dfc-c8453edf0439)

**Comment by elit0451** [comment]
I see 😀

**Comment by nielslyngsoe** [comment]
Hi @bjarnef 

Could you make a PR with this optimisation aka. POC to prove that this SVG optimisation would work?

Cause replacing the current one with an optimised one would reveal the improvement instantly, cause it is pretty bad now. :-/ 

Thanks :-)

**Comment by bjarnef** [comment]
@nielslyngsoe regarding SVG optimization it was mainly to clean unneccesary attributes etc. in SVG exported from Illustrater and thus reducing file size without affecting quality as seen with https://svgomg.net/

Regarding the rendered SVG it may be an issue/bug in Chrome.. it seems to be a bit sharper when rendered size is a bit larger.. maybe it is because because it is scaled down much from the original size.

**Comment by nielslyngsoe** [comment]
@bjarnef thanks, that was my interpretation as well, but I wanted to see what result you could get from doing so.

From my own knowledge, I would say its a question of ensuring the edges of the shape, primarily the horizontal and vertical edges fits with a pixel. So I think we could just adjust the size of the logo until it hits a good spot. Cause the current size of the popover is not set to anything defined, its just as it is, so that design can be adjusted.

also we can try append the shape-rendering ="crispEdges" attribute on the SVG. and see if that eventually solves the problem, I'm not sure how broadly its supported. :-)

**Comment by leekelleher** [comment]
I have fixes in PRs https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1822 and https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1823 for these issues.
