### ISSUE TITLE
V14-RC2 : Document types Cannot add properties directly to tabs.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16164]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When creating a document type in v14 you cannot add properties directyl to tabs. you first have to add a group to add the properties too.

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/328c1129-d8a7-4251-90fa-db78ed2a7996)

In umbraco v13 (and before) you can add properties directly to tabs. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/0bd6ef70-fbcd-458a-839f-b7db6b369224)

this is a change in structure and behavior ? and leads to lots more groups vs tabs in old setup.

### Steps to reproduce

- create a new document type
- add a new tab
- attempt to add a property to the tab without creating a group

**Comment by elit0451** [comment]
Hi there @KevinJump 👋 

Thanks for pointing this out! I can indeed reproduce this, we will have a look 🙂

**Comment by iOvergaard** [comment]
This seems to have been fixed somewhere along the way, but unfortunately I cannot find a PR to link back to. I'm going to chalk it up to 14.2, since it works on the latest nightly, but admittedly I have not tested it on 14.1.

![image](https://github.com/user-attachments/assets/1bd54542-3f9e-4dda-8089-6c9945ac8414)
