### ISSUE TITLE
V14-RC2: Icon picker datatype cannot be created

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16161]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

You cannot save a datatype of "Icon Picker" as the page errors on save.

### Specifics

When creating a new datatype of type "Icon Picker" you get an erro when you save : 

```
The targeted property editor was not found.
```

the datatype isn't saved.

### Steps to reproduce

- add new datatype
- select icon picker as the property editor
- save.

**Comment by Zeegaan** [comment]
Maybe @iOvergaard has knowledge on this one, I atleast don't see any definitions for it on the backend, so it is right in the sense that it doesn't exist at all 🙈

**Comment by iOvergaard** [comment]
Hi, I think it's a mistake if that ever showed up. The backend has no knowledge of an icon picker. I checked V13 and it seems there wasn't one there either. We will remove it from Bellissima.

**Comment by rmnaderdev** [comment]
For anyone who ends up at this issue due to getting this error while trying to create a new instance of their custom property editor, I was able to fix this error by creating a C# DataEditor class.

MyPropertyEditor.cs
```cs
[DataEditor(
    "MyPropertyEditor.Schema",
    ValueType = ValueTypes.Text,
    ValueEditorIsReusable = false)]
public class MyPropertyEditor : DataEditor
{
    public MyPropertyEditor(IDataValueEditorFactory dataValueEditorFactory) : base(dataValueEditorFactory)
    {
    }
}
```

Once I added this class and restarted my project, I was able to create a new instance of my custom property editor. I could not find in the documentation where this is mentioned in the Umbraco Docs, but I am not using the `umbraco-package.json` file to define the property editors. Instead I am defining the manifests in TS code and adding a single entry point to the `umbraco-package.json` like Kevin's [TimeDashboard Repo](https://github.com/KevinJump/TimeDashboard/commit/9ecae8152584ec1147591a1ca29426ec8bb2eb50#diff-bd69bc718f476c4d99790a77a251540f067855585221d29f077a293793e1eb8f). Thank you @KevinJump for your very helpful example!

**Comment by iOvergaard** [comment]
@rmnaderdev Yes, for new property editor _schemas_, you need to define the .NET equivalent on the backend, so the server knows how to persist the data. You can get around this using one of the built-in "plain" types, which comes with no configuration: https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-property-editor/adding-server-side-validation/default-property-editor-schema-aliases
