### ISSUE TITLE
Unable to create user with apostrophe in their username/email

### ISSUE THREAD

**Issue by ian-dowhile** [umbraco/Umbraco-CMS#16201]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

I am unable to create a user in the backoffice of Umbraco when the email is being used as the username, and the email contains an apostrophe, e.g. EmmaO'Haire@blah.com.

This was possible in previous versions of Umbraco, i.e. version 7.

I am able to create the account without an apostrophe, then later add the apostrophe back into the email address and save the account.  However, I am then unable to change the password assigned to the user account.  Also the user themselves cannot change their password once the apostrophe exists in the username/email field.

### Specifics

/umbraco#/users/users/users?create=true
/umbraco#/users/users/user/8?orderBy=Name&orderDirection=Ascending&pageNumber=1

### Steps to reproduce

Creating a new user:
1. Log into the backoffice and go to the users section.
2. Select the "Create user" button.
3. Complete the fields on the form that appears and enter an email address with an apostrophe (') in it.
4. Select the "Create user" form submission button.
5. An "invalid user" error message appears, then fades away.

To workaround the issue, you can create the user but remove the apostrophe, then go into the user account in the backoffice and add the apostrophe back into the email.  Umbraco allows you to save the user account and displays no error.  This account can then be used to log into the backoffice, however, either the user themselves or another user in the "administrators" group cannot change the user account's password, now the apostrophe is in the email address.

Trying to change the password.  As an administrator:
1. Log into the backoffice and go to the users section.
2. Go to the "Users" section.
3. Find and select the user with the apostrophe in their username/email address.
4. On the user account view, select the button "Change password".
5. In the window that appears, enter a new password and then enter it again to confirm the new password.
6. Select the "Confirm" button.
7. The change password window disappears and the error message "Validation: invalid user" appears.  The new password has not been saved against the account.

### Expected result / actual result

The email address is valid, so I would expect Umbraco to accept it and create the user.
Later, I would expect Umbraco to allow me to change the password of the user with email address, with the apostrophe in it.

**Comment by PanktiBodiwala** [comment]
Hi,

I'm on Umbraco v13.5.2 and still experiencing the issue. I can't create a new member with the email address that contains apostrophy in it. However I can save an existing member that has apostrophy in the email address. Here are the links that might help

New Member - https://www.loom.com/share/cce04428366145bca75d6eaac4c02da1?sid=e049fca2-a02a-44ec-ad9a-aab73fe5795b
Existing member - https://www.loom.com/share/e5dd63ba20cf498296763428c0f84f34?sid=dd572e53-6c40-40a7-a667-ada010ab89e3

Can I please check the fix is released in this version?

Thanks

**Comment by AndyButland** [comment]
Looking at the linked PR, the fix was to the template for when you create a new Umbraco project.  My expectation is that this wasn't added to the default setting as that could change behaviour for installations that haven't configured this explicity.

For an existing project, you should [update the configuration](https://docs.umbraco.com/umbraco-cms/fundamentals/data/members#technical) to include the character you need.
