### ISSUE TITLE
V14-RC3 Cannot right click to open action bar Content tree, Media tree, Settings tree, etc

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#16233]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

I'm not sure if this falls under the "Keyboard shortcuts" that might not be in the first roll of v14 but anyway.

In v13 you're able to right-click on content items, media items, in the settings tree, etc. to open the action menu. This is not possible in v14-rc3.

Personally I almost exclusively use this to open the action menu so it really messes with my usage of the backoffice.

Here is a quick example of the difference. Tab 1 is v14 tab 2 is v13:

https://github.com/umbraco/Umbraco-CMS/assets/24605285/098eaf66-815d-4a25-b7c5-9dc9078d81bf

### Steps to reproduce

1. Open a v14 instance
2. Right click an element in the tree

### Expected result / actual result

A right click opens the action menu

**Comment by andr317c** [comment]
Hey

Thanks for reporting this issue. I was able to reproduce it 🐛

**Comment by marcemarc** [comment]
I constantly right click!! didn't realise before quite how much! muscle memory!

**Comment by nielslyngsoe** [comment]
Hi @nikcio 

Thanks for reporting this issue — I know we are asking a lot of extension developers who are native in the Umbraco Backoffice. A completely new stack for the front-end and then asking you to change your habit of right-click. 🤯

I would like to share the reason for not implementing the right click feature, and then I hope you will find it reasonable or express your perspective. 😊

The main reason is that we should not mess with the users browser features, by overwriting the right click feature we have taken away the feature of the browser. Users might have browser extensions they need to interact with via the right-click menu. As well many users are used to right click for copying URLs or open a link in a new tab.

Additionally most users and especially new users will not know that they can right click. Many figure out cause they have a hard time finding what they where looking for, or get a tip from a friend.

And to summen up it is not generally popular to overwrite the right click action in browsers.

There is a slight opening for making an acceptable right-click feature which is limited to advanced web applications.
One would argue Backoffice is such, but let me elaborate on what such feature would cover. 

To justify taking over the browsers right click menu, it would have to be implemented across the application. In other words It should be a full take over, meaning the user should get a custom right click menu in any spot of the application.
Such menu should provide actions that are relevant to that spot. And most applications implement such would be so advance that there is no room to display actions else where leaving them only with this choice.

I would argue that is not our case, we strive to be simple. Meaning we should provide experiences that can be solved without right clicking. And we should be friendly and allow people to interact with their browser and/or the extensions of it.

The solution to the matter is that we now display two buttons, one showing all actions and a shortcut to the primary action.
This change makes both features available to all types of users(the once who do not know about right-clicking). And we still the same abilities as v.13, by a single left mouse-click.
![image](https://github.com/umbraco/Umbraco-CMS/assets/6791648/08e1fbe8-80fa-4318-aad0-5a64916a4905)

So at the end of the day, the question is to teach your self to left-click on a button, instead of right clicking. And this release is the sweet spot to make this change.

Thanks for reading, let me know what you think about the decision.

**Comment by marcemarc** [comment]
This makes perfect sense to me, it is just the muscle memory... it will fade in time, if you'd asked me if I used right-click in the backoffice I'd say no! but I was surprised how much I did :-P

The main thing is to remember to communicate this to editors when you upgrade them from v13, eg developers testing V14 - get it, and can see the technical implementation step forwards this indeed is - having a website handle right click in this way always felt unintuitive - and existing editors will be fine if they have it explained to them, before they try, managing their expectations. Otherwise, their first impression will be that there is something wrong, and they will lower their trust in the change.

The other thing we can do following on from this, is update documentation, to take out the instruction to 'right-click' from v14 docs...

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/dcd942b9-1660-4f89-9549-09ec919a1c5a)

So again people trying V14 for the first time and following along with the docs, don't think it is broken.. eg here we've updated the document screenshots:

https://docs.umbraco.com/umbraco-cms/fundamentals/data/members#creating-a-member

but kept the V13 instruction in the text to be 'Go to the Settings section, right-click Member Types and select Create.' 

I've added this as an issue on the tracker for the docs, https://github.com/umbraco/UmbracoDocs/issues/6156  we could mark it as up for grabs, and then someone in the community may have capacity to pick this up.
