### ISSUE TITLE
Save button has border radius on one side

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16362]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

I dont know whether this is by design but the "Save" button in doc types have a bottom and top left border-radius but not on the right

<img width="938" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/887a08ea-01c5-4543-a4a8-d87eb8117623">

### Steps to reproduce

As above

**Comment by JoJk0** [comment]
![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/692b429a-682d-45db-b955-d555c7cfb752)

Can confirm, it's more visible if CSS vars for corner radii is customized to be bigger.

![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/77f29813-f7fe-447e-84a6-1f75f5311fc9)

**Comment by leekelleher** [comment]
@iOvergaard I think this may be an underlying issue with UUI library's `<uui-button-group>` component?
https://uui.umbraco.com/?path=/docs/uui-button-group--docs

**Comment by iOvergaard** [comment]
Well, @leekelleher, this happens because the button group targets all elements regardless if they are buttons or not.

If you look at the DOM, you will see the host element for the little popup menu being present, and that it, in fact, gets the missing border radii attached, but since it is not a visible element if there are no items attached, it doesn't show the borders.

![image](https://github.com/user-attachments/assets/751c5b91-1bc0-4ee8-819e-bd46267547a1)

The solution is to either hide the element in the Backoffice, if there are no sub-menu-actions, or to ensure that UUI only targets "buttons", but I would be sorry to have to guess what constitutes a button.

We will have to look more into it.
