### ISSUE TITLE
V14.0.0-RC4: No button the create relation

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16409]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0-rc4

### Bug summary

It seems there is no button the create a relation:

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/d55ef205-4b35-43b0-b5f3-1912ae509711)

E.g. similar to creating a language or webhook.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/6f6daea5-2eda-448f-b838-caa7c8835b36)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/d3732f9c-7c20-4c72-86b2-022ccf1878ed)

### Steps to reproduce

I think the create button in relations has been there previously in RC versions. Maybe someone moved the cheese?

---
_This item has been added to our backlog AB#42169_

**Comment by iOvergaard** [comment]
Hi @bjarnef 

So I had a chat with the team about this. Apparently, this in a conscious decision because you don't gain anything from creating a relation type in the UI without also having some C# code to accompany it. So there is no button. Instead, you'll have to define it on the server and it should be available in the UI.

Let me know if you experience any problems with this approach!
