### ISSUE TITLE
Parent page shows list view and tree view at same time

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16493]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc5

### Bug summary

If you enable a collection (list view) on a parent page, it still shows those child items in the tree view

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/84796b2f-c5e6-4368-b740-0f647b777a82)

### Steps to reproduce

Create a parent type that is allowed at the root
Set the parent page to use a list view
![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/dc8a7183-38cd-4052-8c14-2f8ab0612eb3)

create a child type that can be a child of the parent type
Create the children under the parent.
See that the children appear in the list view and the tree view

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/e492d179-23c6-48a6-b5e6-eb96cbeb3f28)

### Expected result / actual result

I expected only the list view collection to show, not the tree view

---
_This item has been added to our backlog AB#42580_

**Comment by madsrasmussen** [comment]
Hi @prjseal 

Thanks for the bug report. 

In v14 it is by design that both the tree item children and the collection items are visible at the same time. We see the collection as an opt-in "upgraded" view of the children with extra information, ordering, and search capabilities. We think it makes perfect sense that it is now possible to navigate/use actions in the place that fits the user best.

If I remember correctly the List view was also introduced back in the day to solve a performance issue for tree items with many children. This has also been taken care of in the new backoffice with paginated trees.

**Comment by prjseal** [comment]
Hi @madsrasmussen 
That is not what the description says when you are adding the list view.

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/7add5170-995c-4318-b4fc-3d33657d8e78)

Paul

**Comment by NikRimington** [comment]
I would like to see this as an option so you can pick if it does/doesn't hide things from the tree - this caters for both scenarios. If you have a huge amount of content, it adds noise to the tree so list view helps keep the tree clean.

**Comment by philipdanielhayton** [comment]
+1 for being able to have the option to hide things from the tree if they're set as a list view.

**Comment by iOvergaard** [comment]
Hi,
Re-opening this issue to address the clarifications needed in the UI.

**Comment by leekelleher** [comment]
The Collections description has been updated to reflect this; https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2050.

**Comment by jmvivas** [comment]
I have a site with parent node with 9,500 child items, as it's likely to happen on news sites that are active or been around for a while. The tree on 14.3 feels a bit sluggish so it would be great to be able to go back to the previous versions behaviour.

**Comment by FransdeJong** [comment]
The solution of https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2050 feels like a cheat to get around the issue here.
Since the introduction of listviews the listview has hidden the tree view. We are running into the same issue as @jmvivas now where we have a huge amount of nodes.

I would prefer the old way of choosing between listview or treeview or at least a option to hide the tree view since in real world websites the tree can be way to much really fast.

This is a place where the new front-end is a step back from what we had and where it annoys the editor instead of helping them.

Could we please reopen this issue.

**Comment by leekelleher** [comment]
To note, the tree items are paginated (in v14+), set to a default of 50 items (with a "load more" button), so it wouldn't show all the child items.  This applies to all trees in the backoffice.

**Comment by FransdeJong** [comment]
@leekelleher 
Is that adjustable per tree? Or is it a global setting?
If it's adjustable per tree we could set it to 0 and have the same editor experience as we had for years.

**Comment by FransdeJong** [comment]
Looking at this from a different perspective. Would it be possible to check if a item is in "collection mode" when rendering the tree and have a TS controller that overrides and skips the tree rendering?

That way we can create our own fix. Although this fix would logically live in the core.

**Comment by dalyUSN** [comment]
I know I'm a little late on this one... I appreciate that this is marked against v14 and not v17, but it seems like this was the only place I could find a similar issue.

Is there a way to configure the number of items shown in the Tree Menu side of a List View Collection? 

When I visit an item in a List View Collection, the tree menu shows 2 items from the List View Collection with an expand to show more option by default. 

However, I would like to configure the number shown in the node tree once you visit an item from a List View Collection. 

For instance, I have a List View Collection that will never show more than 5 items. To me, it would make sense that when I visit one of those items, all 5 should be shown in the node tree, rather than just 2 with a show more option. 

At the moment, it feels and looks a little messy, broken and confusing to the user. 

What I see at the moment with no configuration: 

<img width="378" height="348" alt="Image" src="https://github.com/user-attachments/assets/c5156109-260a-4282-8070-7d7ee47fc3e3" />

What would it be like if I could configure the number to 5: 

<img width="381" height="391" alt="Image" src="https://github.com/user-attachments/assets/1381bba9-fd0e-47b3-bce4-5c1b035552ec" />

Cheers

_PS. Apologies in advance if I've missed where this is now configurable!_
