### ISSUE TITLE
UMB-XSRF-TOKEN cookie not set as HTTP Only

### ISSUE THREAD

**Issue by acasamassima86** [umbraco/Umbraco-CMS#16506]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.2

### Bug summary

Umbraco uses the UMB-XSRF-TOKEN cookie for CSRF protection. However, the cookie is not currently set as Secure, meaning it can be transmitted over HTTP. This could allow an attacker to intercept the cookie and use it to forge requests to the Umbraco server.

### Specifics

Umbraco uses the UMB-XSRF-TOKEN cookie for CSRF protection. However, the cookie is not currently set as Secure, meaning it can be transmitted over HTTP. This could allow an attacker to intercept the cookie and use it to forge requests to the Umbraco server.

### Steps to reproduce

1. Open Umbraco Backoffice
2. Inspect the cookies in the browser developer tools
3. Observe that the UMB-XSRF-TOKEN cookie is not set as Secure (not HTTP Only)

### Expected result / actual result

The UMB-XSRF-TOKEN cookie should be set as Secure (HTTP Only)
Additional notes:

This issue has been reported previously: https://github.com/umbraco/Umbraco-CMS/issues/4138

**Comment by NguyenThuyLan** [comment]
Hi @acasamassima86 , thanks for reporting this. 
The reason that UMB_XSRF_TOKEN cookie not set as HTTP Only because the value needs to be read in JavaScript to exsure a correct XSRF token is supplied when doing API request, see MS docs: 
https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0#javascript-ajax-and-spas
