### ISSUE TITLE
v14 Adding User Group section permissions require logout/login

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16523]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0

### Bug summary

After adding permissions for a given section to a User Group, any user in that group must logout and login again for the section to show up.

### Steps to reproduce

Add permissions for a new section to a user (even the currently logged on). Reload page notice no section. Logout, login and notice that the section apperas.

### Expected result / actual result

Section show at least be visible after reload, even better right after save.

**Comment by iOvergaard** [comment]
Hi @enkelmedia, thanks for testing. You are right, it requires logging out and in again because you need to be issued a new token. Perhaps we could make it more obvious by logging you out if you change your own user group, or let you know that you need to log out in the UI some how. Do you have any thoughts in this regard?

**Comment by bergmania** [comment]
Should be fixed by #16552
