### ISSUE TITLE
Management API specific swagger config affecting other APIs (e.g. Content Delivery API)

### ISSUE THREAD

**Issue by lauraneto** [umbraco/Umbraco-CMS#16556]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

For V14, some adjustments were made to the Swagger configuration to support the Management API.
Unfortunately, some of these settings are being applied globally when they should be scoped to the Management API swagger document.

A clear example of this going wrong is the security scheme, where it shows the Management API authentication in the Content Delivery API swagger.

![image](https://github.com/umbraco/Umbraco-CMS/assets/12862535/8a6f5640-211d-49cf-957b-a82d2e1fce60)

While there are different files to configure the SwaggerGen options for the [Delivery API](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Cms.Api.Delivery/Configuration/ConfigureUmbracoDeliveryApiSwaggerGenOptions.cs) and the [Management API](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Cms.Api.Management/Configuration/ConfigureUmbracoManagementApiSwaggerGenOptions.cs), there doesn't appear to be actual logic to only apply the changes to the respective swagger documents.

### Steps to reproduce

Set up a new Umbraco project in V14, run it and access the Delivery API swagger in `/umbraco/swagger/index.html?urls.primaryName=Umbraco+Delivery+API` or `/umbraco/swagger/delivery/swagger.json`.

Notice that the Authorization (Security Scheme) is configured as the Management API one, which is not relevant for this API.
You can also compare the result of `/umbraco/swagger/delivery/swagger.json` from a V13 and a V14 instance.

### Expected result / actual result

Configurations specific to the Management API or Content Delivery API should not be applied globally and affect each other or other APIs, or at the very least, configuration that should apply to to all should move to a central place, so it's clear.

---
_This item has been added to our backlog AB#41957_

**Comment by kjac** [comment]
Hi @lauraneto,

Thanks for reaching out 👍 

Unfortunately, Swagger UI only allows for a global default OAuth client ID. In fact, the OAuth configuration as a whole (e.g. available security schemes, or whether to use PKCE for Authorization Code Flow) seems to be global in Swagger UI.

See also https://github.com/swagger-api/swagger-ui/issues/4690

We have chosen to use the Management API client ID over the Delivery API client ID for a few reasons:

1. We assume Swagger will be used a lot more for Management API experiments than Delivery API ones.
2. We also can't setup a default auth scheme for the Delivery API, since it requires a lot of moving parts (a member login implementation among other things). But if you set it all up according to [the docs article](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/protected-content-in-the-delivery-api), the Swagger UI will show both Management API and Delivery API auth options:

![image](https://github.com/user-attachments/assets/65e93d8b-317d-467b-b909-4dc6beec4cb7)

![image](https://github.com/user-attachments/assets/9bfdf426-30d9-4d3f-89d6-61604005ae67)

As you can see, Swagger UI applies `umbraco-swagger` as default client ID, because it's a global configuration 😢 but (again as per the docs article), you can change it to `umbraco-member` to test member auth in the Delivery API.

![image](https://github.com/user-attachments/assets/2ae4a613-d8aa-4919-8fcb-e6cdbfb44e5f)

If you _really really_ want to, you might be able to configure an additional Swagger UI on an alternative route, and include the Delivery API as an explicit Swagger Document with a custom auth configuration. I wouldn't recommend it, though, as it's not something we'll be supporting actively.
