### ISSUE TITLE
[BUG/FEATURE]: Trees/Menu Items: allow overriding default route convention

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16676]
I'm working on a custom tree but would like to reuse the parts that is already built in to the backoffice (extensibility, actions etc). From what I understand (which might not be right) that path to any menu item is more or less hardcoded here:

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/e5cb64c140073a356cc44036ce1c443fe1cc71e7/src/packages/core/tree/tree-item/tree-item-base/tree-item-context-base.ts#L375

I'm my scenario I would need to be able pass more information since in my case I would like the links to include two identifiers, and also maybe not use a full blown `workspace`.

As far as I understand the `UmbUniqueTreeItemModel` and `UmbTreeItemModelBase` interfaces does not contain anything that would allow me to set a path for a certain menu item which would be nice.

So I guess this is either a question: Is this possible?

Or its a feature request, can we add `path` or something to `UmbTreeItemModelBase` so that one can use a custom path for a menu item?

Another thing would be if I would like to link to something like: 

section/${pathname}/workspace/${entityType}/**view**/${unique}

**Comment by nielslyngsoe** [comment]
Hi @enkelmedia 

I agree with you, we have considered to make this configureable when we started the development. But we mainly try not to implement something until we see the clear need for it. And it has turned out to be just fine to use Workspaces for everything. Even things that just acts like a overview, is fine to have as a workspace. You will see that when you explorer our code.

A workspace might sound like something big, but it does not have to be.

You can make a very simple workspace, using no kinds. Just pointing to an element, with the content of your needs.

So with that I will close this issue, let me know how it goes and if this does not fulfill your needs. Thanks
