### ISSUE TITLE
[BUG]: Block Configuration - Change Background & Icon colors to color pallete picker

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#16702]
**Describe the bug**
Block configuration, change Background & Icon colors to a visual color pallete picker as opposed to two freeform text fields.

**To Reproduce**
1. Create a block list editor doctype
2. Add a block/element type
3. Configure picked block/element type
4. Try to set a color for icon and background

**Expected behavior**
A UI to help pick and choose a color for the background and icon color

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1389894/cb177dd8-256e-4894-b01f-ee07a84b0c85)

**Desktop (please complete the following information):**

**Additional context**

**Comment by nikcio** [comment]
I checked up on this issue and it seems to have been fixed in the current commit: https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/block/block-list/workspace/views/block-list-type-workspace-view.element.ts#L52-L63

Commit: https://github.com/umbraco/Umbraco.CMS.Backoffice/commit/8c72d2e5943a245b7c6c6e23e7e8dda542d5649e

Building from source screenshot:
![image](https://github.com/user-attachments/assets/139c3451-23af-42e5-ba1b-e84e8b9da390)

**Comment by warrenbuckley** [comment]
Thanks @nikcio will close this then
https://github.com/umbraco/Umbraco.CMS.Backoffice/commit/8c72d2e5943a245b7c6c6e23e7e8dda542d5649e
