### ISSUE TITLE
More than 50 items in media folder results in Api error "Not Found"

### ISSUE THREAD

**Issue by ralphvanvugt** [umbraco/Umbraco-CMS#16716]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0 - RC

### Bug summary

When adding more than 50 images to a media folder or media root, you get an api error and thumbs are not loading anymore. 

### Specifics

Checked in all browsers on Windows and Mac. Results are the same everywhere.

https://github.com/umbraco/Umbraco-CMS/assets/2463054/d5a7c81a-52af-4631-9aef-961e91de96a0

### Steps to reproduce

1. Upload 50 images to a media folder
2. Add tjhe 51st image
3. You'll receive an api error

### Expected result / actual result

Be able to add more than 50 media items to a folder.

---
_This item has been added to our backlog AB#42058_

**Comment by NguyenThuyLan** [comment]
Thanks for reporting this. I can confirm it is an issue and we want to fix it.

**Comment by NguyenThuyLan** [comment]
The error happens on the endpoint: umbraco/management/api/v1/imaging/resize/urls
**Reason**: The request sends a list of ids via query string parameters, so if the number is too large ( > 50 ids), the request will be blocked because the query string is too long.
<img width="1058" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/38b291f5-bbdb-4789-931d-d2e8b56a420f">
<img width="1045" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/7fb2aa4b-b9bb-4dda-a33c-ef0bcdc9b288">
**Solution**: Request should send list of ids through body instead of query string
