### ISSUE TITLE
OpenIddict `code_challenge` error

### ISSUE THREAD

**Issue by ak2426** [umbraco/Umbraco-CMS#16782]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0

### Bug summary

Logging in via `localhost` works while logging in via `host.example.com` does not.

### Specifics

The error message after logging into `/umbraco/login` is as follows:

```txt
error:invalid_request
error_description:The mandatory 'code_challenge' parameter is missing.
error_uri:https://documentation.openiddict.com/errors/ID2029
```

### Steps to reproduce

On a fresh install of Umbraco 14.1.0, run the following command:

```pwsh
dotnet run --urls "http://0.0.0.0:80"
```

Verify that logging into:
 - <http://localhost/umbraco/login> works 
 - <http://host.example.com/umbraco/login> does not

### Expected result / actual result

After a successful login, I expect to land on the dashboard. Instead, I see the error message listed above.

**Comment by elit0451** [comment]
Hi @ak2426 👋 

Thanks for reaching out! I was able to reproduce it, we will have a look 🙂

**Comment by elit0451** [comment]
One thing though, can you clarify why are you running `dotnet run --urls "http://0.0.0.0:80"` and then expecting to access `http://host.example.com/umbraco/login`?

**Comment by iOvergaard** [comment]
Hi @ak2426 

Looking through this, you may be hitting a few different issues.

**code_challenge is missing**
I haven't seen this error before, but it could happen if the authorization request didn't come from the backoffice, i.e. if you went directly to the login screen on /umbraco/login and tried to log in. The Backoffice client needs to form a correct handshake in its local storage before attempting a login due to the PKCE addition to OpenId. Therefore if you access `/umbraco` first, it can form the correct code challenge for the login screen.

Are you still seeing the error if you do that?

**Accessing Umbraco from another host**
Umbraco stores the first request it gets as its' application URL. It then takes that information and marks that host as an allowed redirect URL in the login provider. From the looks of it, you are not hitting this error specifically, but it may be worth it for you to specifically set your backoffice host URL in `appsettings.json`. You can do it like this:

```json
{
  "Umbraco": {
    "CMS": {
       "Security": {
         "BackOfficeHost": "http://host.example.com"
       }
    [the rest]
  }
}
```

This might help alleviate any confusion running Umbraco in a place where it can't see its real host, for example in a Docker environment.

**Comment by iOvergaard** [comment]
@ak2426 The BackOfficeHost parameter must match the one you are accessing Umbraco from. However, Umbraco should be able to resolve any relative requests, so there might be something we need to look into.

Another note, if you want to use regular HTTP, you need to ensure the `UseHttps` option is false (see more here #16614).

**Comment by uppercuut** [comment]
Any Update on this ? 
I Have Put this 

 "BackOfficeHost": "http://host.example.com"
 
 and this to false : UseHttps 
 
 it did not work 


I think (Think) it has something to do with cookies cross site with http

**Comment by miflun** [comment]
Had the same issue, I simply switched to HTTPS in my IIS and it worked
My domain was working on http://localhost:65322, however when i tried on http://mywebsite.local I was getting error "The mandatory 'code_challenge' parameter is missing"
I have used SSL Certificate 'IIS Express Development Certificate'. I believe this certificate was created through dotnet cmd
>dotnet dev-certs https --trust

**Comment by NileshMasterly** [comment]
I am also facing the same issue, I tried all the above solutions, but none of them worked.

**Comment by IbrahimMNada** [comment]
any update on this ?

**Comment by NileshMasterly** [comment]
Update the web.config as shown below; it worked for me.

<system.webServer>
    <rewrite>
        <rules>
            <rule name="HTTP to HTTPS redirect" stopProcessing="true">
                <match url="(.*)" />
                <conditions>
                    <add input="{HTTPS}" pattern="off" ignoreCase="true" />
                    <add input="{REQUEST_URI}" pattern="^.*/umbraco" negate="true" />
                </conditions>
                <action type="Redirect" redirectType="Permanent" url="https://{HTTP_HOST}/{R:1}" />
            </rule>
        </rules>
    </rewrite>

    <modules runAllManagedModulesForAllRequests="false">
        <remove name="WebDAVModule" />
    </modules>

    <httpProtocol>
        <customHeaders>
            <clear />
            <add name="Access-Control-Expose-Headers " value="WWW-Authenticate"/>
            <add name="Access-Control-Allow-Origin" value="*" />
            <add name="Access-Control-Allow-Methods" value="GET, POST, OPTIONS, PUT, PATCH, DELETE" />
            <add name="Access-Control-Allow-Headers" value="accept, authorization, Content-Type" />
            <remove name="X-Powered-By" />
        </customHeaders>
    </httpProtocol>
    <security>
        <requestFiltering>
            <requestLimits maxAllowedContentLength="524288000"/>
        </requestFiltering>
    </security>
</system.webServer>

**Comment by peteringemann** [comment]
I am getting this error too.
Upgraded from working 13.x to 14.latest. 
I use the host file to redirect to 127.0.0.1 when debugging.
I only run http. None of the above suggestions works.

**Comment by IbrahimMNada** [comment]
after some debugging , The Issue is resulted from PKCE when developing on a non https server. 

so the fix for this would be simply if the configuration `UseHttps` is set to false we should not call this extension method 
`RequireProofKeyForCodeExchange()` on `ConfigureOpenIddict` ==> `AddUmbracoOpenIddict`

**Comment by IbrahimMNada** [comment]
Please take a look at this PR 

https://github.com/umbraco/Umbraco-CMS/pull/17319

hope you approve and merge it soon x)

**Comment by nul800sebastiaan** [comment]
I've closed the PR with a workaround in the comments. https://github.com/umbraco/Umbraco-CMS/pull/17319#issuecomment-2470676808 

Ultimately, it's an unsafe setup and you need to be very careful what you're doing here, we intend to help you do the right thing so for now we don't want to support things that might accidentally leave you open to an easy security attack.

**Comment by nul800sebastiaan** [comment]
Additionally, a workaround in code has been posted to the PR which will work for existing sites as well.
