### ISSUE TITLE
Medi Picker is no longer auto selecting media that's been uploaded

### ISSUE THREAD

**Issue by husnain-majeed** [umbraco/Umbraco-CMS#16786]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.0

### Bug summary

We recently upgraded our Umbraco instances from 10.x.x to 13.4.0 and have come realize that a vital feature seems to have been lost. 

When someone upload's an image in the media picker property - of one of our doc types, the image is not auto selected like it used to be. Instead the user has to manually search for the file and select it.  (See GitHub links below for further insight) 

Link to visual example from before the solution feature was added: https://github.com/umbraco/Umbraco-CMS/issues/6844
Link to the solution feature that seems to no longer be working: https://github.com/umbraco/Umbraco-CMS/pull/6995

### Specifics

This happens regardless of it its an existing content using the doc type, or if it is the first version of it that's being created. 
We are also using a conditional displayer to show or hide the media picker in our parent doc type and then inheriting from it.

Overview of parent doc type:
![Screenshot 2024-07-17 115905](https://github.com/user-attachments/assets/a84bbff0-edd6-49f3-b622-85e44929ad71)

Overview of child doc type:
![Screenshot 2024-07-17 120412](https://github.com/user-attachments/assets/6e6a7a4e-049c-494c-9ec7-2d1a8cf4f249)

Conditional displayer:
![Screenshot 2024-07-17 115851](https://github.com/user-attachments/assets/29f86617-fa63-4dbd-847c-22dd25cbc259)

Media picker config:
![Screenshot 2024-07-17 115816](https://github.com/user-attachments/assets/afe51d99-c401-498b-9bd5-1b17f55322eb)

 have tried different browser and incognito tab

### Steps to reproduce

Recreate a doc type / media picker with configurations show in above screenshots. 
Add a content node using the doc type and during so upload an image to the media picker.

**Comment by DempseySbaiz** [comment]
We have the same issue.
Our customer is complaining (and correctly so) that an update caused them to lose this functionality.
It's not very user friendly that you have to re-select the uploaded file.

**Comment by bjarnef** [comment]
I noticed this as well on some of our recent projects. Not sure when it was broken though.

**Comment by gjensonksl** [comment]
I think this might be the place to mention this.  We noticed that between 13.0 and 13.4.1 that when uploading any image using drag and drop into a media folder the file type ends up as File rather than Image.  This prevents the Image Media Selector from correctly identifying the media for use and prevents it from being selected.  Also because of this images are not displayed in the folder or media selection sidebar with thumbnail images which makes user selection very bothersome.  We'd really like to see this dealt with since we have a good number of marketing folks that need this to function as before.  Our production site is using 7.8.1 and it works nominally as expected.  I can provide further details if needed.
