### ISSUE TITLE
Custom properties added against image media types not returned in content delivery API

### ISSUE THREAD

**Issue by chestermentor** [umbraco/Umbraco-CMS#16804]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1 

### Bug summary

Hi

I am using the content delivery API and I am trying to access some custom properties added against a image media type, there is a properties object present but it's empty.

### Steps to reproduce

Add custom property to image media type e.g. alt text

![Screenshot 2024-07-19 at 14-01-37 Edit Example3 - (Loca](https://github.com/user-attachments/assets/3966d03f-1d03-497f-8bdb-337b7b51cb46)

Review the content delivery API output when accessing this media item, you'll see that alt text is not present in the properties object (I assume this is where it should be returned) e.g.
```
{
	"0": {
		...
		"crops": [
			...
		],
		"id": "9630c03c-aa98-4796-af31-f5a9d011d073",
		"name": "Example3",
		"mediaType": "Image",
		"url": "/media/hladbfuy/example3.jpeg",
		"extension": "jpeg",
		"width": 2020,
		"height": 1200,
		"bytes": 223582,
		"properties": {}
	}
}
```

### Expected result / actual result

The custom property to be returned against the media item (likely in the properties object)

**Comment by kjac** [comment]
Hi @chestermentor,

This is by design. Properties of linked resources (like content and media pickers) are not included in the Delivery API output by default.

You can apply [property expansion](https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/property-expansion-and-limiting) to include these properties in the output. This is sometimes preferable over performing extra fetches for the linked resources.
