### ISSUE TITLE
Invalid Zero Length check expression

### ISSUE THREAD

**Issue by MikeAlhayek** [umbraco/Umbraco-CMS#16811]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

contrib branch

### Bug summary

I noticed many invalid expression when checking for a zero elements in a collection.

Here is explanation

```
List<string> items = null;

if(items?.Count == 0)
{
    // This will evaluate false since null does not equals 0.
}

if(items?.Any() ==false)
{
    // This will evaluate false since items is null. which is translated to items != null && items.Count == 1
}
if(items == null || items.Count == 0)
{
    // This will evaluate true since items either null OR is not null and it's count is 0.
}

if(items?.Count > 0)
{
    // This check is okay because null items will return false and if the Count is 0 will also false.
}
```

### Steps to reproduce

n/a

**Comment by JasonElkin** [comment]
Hi @MikeAlhayek,

To repeat the comment I made on the PR (and for anyone else finding this): Nullable Reference Types have not necessarily been applied consistently, or well, across Umbraco's codebase. There are definitely some some code smells here, and help fixing them is appreciated.

However, raising it as bug report like this won't help with triaging or fixing the issue unless there are more specific details about the problems caused by the code in question. i.e. if there are no steps to reproduce or difference between an expected/actual result then what _is_ the bug?

If you're going to PR fixes yourself that'd be amazing and you don't necessarily need to raise an issue if so long as you add details of the bug to the PR (reproducible, before/after etc.). Otherwise, if you'd like some help from HQ or the community then please do create bug reports detailing the specific issues.
