### ISSUE TITLE
Media search does not search child items Umbraco 13

### ISSUE THREAD

**Issue by nehanupur0507** [umbraco/Umbraco-CMS#16968]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

When using the search on the media tab, searching for a media item by name only searches the currently viewed folder, but not any of its descendants.

### Specifics

It also looks like this behaviour has been around for a while: https://our.umbraco.com/forum/using-umbraco-and-getting-started/87008-media-search-not-searching-child-folders

Previously another issue has been raised for this:
https://github.com/umbraco/Umbraco-CMS/issues/12102

Solution provided for this was a workaround, i.e. the global search. and also it says, that this is an indented behaviour. 
Are you planning to provide a fix for this behaviour?

### Steps to reproduce

To reproduce, create folder X within the media section. Then create a child folder Y. Then add some content to that child folder Y

When you search the name of the content in folder Y, it will correctly filter the content and show up the content. However, if you do this same search in the parent folder X, it does not find the content.

### Expected result / actual result

The media search should search all child folders of a folder so that a user can actually find the content as expected, at the very least showing folders that contain content with that search query in.

**Comment by Noman-Paul** [comment]
Thank you for raising this @nehanupur0507 
Looking forward to hear back from Umbraco Support.

**Comment by NguyenThuyLan** [comment]
Hi @nehanupur0507 , I discussed with the team and also agree with the reason for closing the issue previously "this is how list views work, and is consistent across the board; list views can span a great number of items (specially for content), in which case "deep search" would produce rather confusing results given the lack of structural context in the search results view."
Well, we will consider rephrasing the text to "Type to filter..." instead of "type to search..." or improving the Global Search, making it aware about the current location of the UI
