### ISSUE TITLE
Restricted Public Access and having "install" in the first url segment

### ISSUE THREAD

**Issue by EvelinaBDC** [umbraco/Umbraco-CMS#17017]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

When using Restricted Public Access on a page and the first url segment includes "install" the member is shown the Login page even though the member is logged in.

### Specifics

I have this site tree:
StartPage -> "Installation" (Restricted Container Page (no view)) -> Article (Restricted Access from parent)

When logged in member goes to nameofsite.com/installation/article they are shown the Login page.

If the Installation page has another name not including "install" it works as intended.

If the page name is "install" we get redirected to nameofsite.com/Account/AccessDenied?ReturnUrl=%2Fumbraco

### Steps to reproduce

Create a page named "Installation" (or another name where the name starts with "install") as a child to the Start page and set a restricted public access on it attached to a Login page. Then create a child page to the "Installation" page where the page inherits the restricted public access from its parent. 
Go to the child page and Login, you are then met by the Login page again. 
If you create a different child page to the Start page with a name not starting with "install" and set the same restricted public access  on it, create a child page that inherits the restriction and go to that child you can then see that you are logged in and everything works fine. 

### Expected result / actual result

Expected result: I expect logged in member not to be shown the restricted public access Login page when first url segment starts with "install".

Actual result: Logged in member is shown the Login page when the first url segment start with "install"

---
_This item has been added to our backlog AB#44373_

**Comment by ronaldbarendse** [comment]
This is most likely due to `/install/` being in the default list of [reserved paths](https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings#reserved-paths): https://github.com/umbraco/Umbraco-CMS/blob/7a39314586c8ffe935e21b22fc541495454a7fd8/src/Umbraco.Core/Configuration/Models/GlobalSettings.cs#L14-L16

This URL path is used for the Umbraco installer, but that is only routed to a controller when Umbraco is in the 'install' runtime state. When Umbraco is running normally, this URL is not routed anywhere, but is also excluded from the regular Umbraco request pipeline, thus not authenticating members, etc.

Overwriting the default `Umbraco:CMS:Global:ReservedPaths` configuration value to `~/app_plugins/,~/mini-profiler-resources/,~/umbraco/,` should fix your issue.

**Comment by AlexanderWagner82** [comment]
Hi @ronaldbarendse 

Unfortunately it didn't solve the problem. When the member logs in on restricted page /installation/xyz they're still redirected to /installation/xyz with the login page view.
