### ISSUE TITLE
"Vary by culture" toggle missing for properties on document type

### ISSUE THREAD

**Issue by gab-trifork** [umbraco/Umbraco-CMS#17111]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

When configuring properties on a document type, the toggle to allow properties to vary by culture is missing.

(Downgrading to 14.1.2 makes the toggle come back)

### Steps to reproduce

Set up a blank Umbraco project using `dotnet new umbraco` and follow the steps for adding culture varied content:
https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/variants

When on the step `To allow a property on the Document Type to be varied it will have to be enabled for the property:` notice that there is no toggle for enabling "vary by culture" for the property.

### Expected result / actual result

The toggle is there, letting me decide whether properties are variant or invariant

**Comment by iOvergaard** [comment]
Hi @gab-trifork, this issue is serious, but I'm having difficulty reproducing it. The toggle should be shown as long as the document type itself is also marked as "Allow vary by culture" in the "Settings" tab:

<img width="596" alt="image" src="https://github.com/user-attachments/assets/e4b2a288-d963-4a5c-b7bd-46d55292d304">

Will you let me know if that works, please?

**Comment by gab-trifork** [comment]
Hello @iOvergaard

I have that enabled.
<img width="592" alt="prop" src="https://github.com/user-attachments/assets/497136c2-1f04-4922-896b-b1f6effbfc0b">
<img width="1396" alt="doc type" src="https://github.com/user-attachments/assets/b66adf9a-bb1f-4dde-9a33-2a93d9409a5e">

**Comment by gab-trifork** [comment]
Sorry, I have 2 Umbraco projects and it turns out I accidentally ran the incorrect one, generating a new project using `dotnet new umbraco` is in fact NOT enough to reproduce. I am trying to figure out where it is going wrong.

**Comment by iOvergaard** [comment]
Good and bad news at the same time, @gab-trifork. Do let me know what you figure out!

**Comment by gab-trifork** [comment]
Okay, so I have managed to do a minimal reproduction.

1. `dotnet new umbraco`
2. `dotnet add package usync.complete`
3. `dotnet run`
4. theres no vary by culture on the property

if you stop the server and delete the usync package again, the button will reappear

my deps:

``` 
<ItemGroup>
  <PackageReference Include="Umbraco.Cms" Version="14.2.0" />
  <PackageReference Include="uSync.Complete" Version="14.2.0" />
</ItemGroup>
```

**Comment by iOvergaard** [comment]
@gab-trifork great, I can certainly reproduce that. Thank you so much for the reproducible steps.

The variation toggle is gone when `usync.complete` is installed, and when you remove `usync.complete` and restart the server, it reappears. It's difficult diving into minified code coming from other libraries to see where it goes wrong. Still, I could see that they make more contexts available in the document type editor and I _think_ they might be overriding some of the built-in services in that area.

[usync.complete 14.2](https://github.com/Jumoo/uSync.Complete.Issues/releases/tag/v14.2.0) was just released last week and this bug might have flown under their radar until now. Honestly, I would report it directly to them on their [Github issues tracker](https://github.com/Jumoo/uSync.Complete.Issues/issues) and refer back to this thread.

The technical explanation is as follows: The UI component needs to know that the context bearing the token `UMB_CONTENT_TYPE_WORKSPACE_CONTEXT` has an observable property called `variesByCulture` which gets set when you activate the corresponding toggle in the "Settings" tab in normal circumstances. Otherwise, the variation toggle won't show up for properties.

**Comment by gab-trifork** [comment]
@iOvergaard
Thanks for the quick responses, and sorry for the inconvenience - had I noticed it only happened with uSync I would have opened the issue there instead.

**Comment by iOvergaard** [comment]
It's fine, @gab-trifork. Cheers!

**Comment by iOvergaard** [comment]
It's fine, @gab-trifork. Cheers!

**Comment by KevinJump** [comment]
Hi, 

We've tracked this down in the uSync.Complete code, for reference (and maybe as a place to look if it happens with someone else). we had a missing condition. 

as in we had a workspace context manifest that didn't limit the workspace context by condition. 

```ts
const context: ManifestWorkspaceContext = {
	type: 'workspaceContext',
	alias: 'usync.publisher.server.workspace.context',
	name: 'Publisher workspace context',
	js: () => import('./server-workspace.context'),
};
```

we added the correct condition and that fixed is. 

```ts
const context: ManifestWorkspaceContext = {
	type: 'workspaceContext',
	alias: 'usync.publisher.server.workspace.context',
	name: 'Publisher workspace context',
	js: () => import('./server-workspace.context'),
	conditions: [
		{
			alias: 'Umb.Condition.WorkspaceAlias',
			match: USYNC_PUBLISHER_SERVER_WORKSPACE_ALIAS,
		},
	],
};
```

the context itself is not doing anything 'suspicious' (not from my eyes anyway). so not 100% sure why it breaks this and only this bit of the datatype but that does look like what it was doing 🤷
