### ISSUE TITLE
[v14.2] Backoffice - Can't create Document Type Composition

### ISSUE THREAD

**Issue by Borc92** [umbraco/Umbraco-CMS#17173]
### Umbraco version:

14.2.0

### Bug summary

With the freshly instaled version of u.14, there is no posibility to create an Composition under Document Types

It is even missing in the documentation in the printscreen of "Create doc type":
https://docs.umbraco.com/umbraco-cms/fundamentals/data/defining-content/default-document-types

In the documentation text from the same link is still mentioned as a default document type, so I asume that is a bug...

It is a problem to create more complex pages with the current fresh install because of this... (missing in backoffice structure and consequently in the frontend as a models builder interfaces...)

### Steps to reproduce

Settings -> Document Types -> "Create an item under Document Types", ther is no Composition!

### Expected result / actual result

Expected result (version 13):
![image](https://github.com/user-attachments/assets/fa0d8e37-6fca-4cc7-9180-1dd73332770d)

Actual resoult:
![image](https://github.com/user-attachments/assets/5bf2ec49-0b71-4c9d-8fa5-3c0cc315b65e)

**Comment by iOvergaard** [comment]
Hello, @Borc92. You are correct in that the documentation is outdated. The procedure is as follows:

1. Create two document types
2. Go to the document type that should "inherit" the other
3. Click "Compositions"
4. Select the other document type and save that


https://github.com/user-attachments/assets/42f78695-cefe-4205-85b2-2357eeb05fd7

Let me know if that works for you.

**Comment by iOvergaard** [comment]
Yes, I see that there is a difference there. I have submitted a PR to the documentation to describe in more detail how to create compositions. As a rule of thumb, the version-specific (breaking) changes are described in [this document on the umbraco docs](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific), but this specific change was not described in any detail there.

I believe the "Composition" option in V13 was not anything special other than a tool to create two document types with an inherent relationship. There never was any special "composition" type to my knowledge at least.

I'm happy if this works for you!

**Comment by Borc92** [comment]
Hei @iOvergaard

I checked in v13. Yes the Composition element was/is not a special type, it is basicaly an Document type that is Element with a diferent icon... So the same could be said about the doc-type element, you can just create an Document type and flag it optios as "Is Element type"...

My thought is that it was a good implementation for creating a new doc-type specificly for Composition... And maby when porting backofice frontend it accidentally slipped away... :)

![image](https://github.com/user-attachments/assets/dad41b20-bd92-46a4-9c47-1bd28abb1972)

**Comment by iOvergaard** [comment]
Yeah, they are all just different configurations of the same thing - different things toggled on and off. We thought the Composition type was a little misused in that it could quickly spam out a lot of document types, that were left unattended. We would rather have that people consciously create the compositional relationships between document types.

There is an active discussion on the subject at #16351, if you'd like to contribute with your thoughts. It contains our reasoning for the choice to leave it out :-)

**Comment by marcemarc** [comment]
> I believe the "Composition" option in V13 was not anything special other than a tool to create two document types with an inherent relationship. There never was any special "composition" type to my knowledge at least

@iOvergaard think you are misunderstanding!!, - which might explain why you have accidentally removed this option with oput understanding why it was there - there was an option in the'old old menu' to do what you describe - create two related Document Types -, but the composition option here on the menu isn't that! - the introduction of the menu that introduced the composition option removed that confusing two Doc Type option!

Having compositions listed here is mainly to introduce the concept 'before' you create the document type :-P

Previously people 'new to Umbraco' would see the Composition as an option, and think ooh, what's that? ahh, so I can create 'Document Types' to compose other Document Types 'neat' and they are called Compositions, super.

Under the hood a 'Composition' is exactly the same as a 'Document Type' - but that isn't important for people building sites, but knowing about the Composition approach IS, and having a 'word', that describes exactly the thing is soo much easier for discussing site architecture - eg I'm going to create a 'Composition' vs I'm going to create a 'Document Type Without A Template That As Long as it Doesn't itself have other Compositions, can be used as a Composition'

With this change in the new backoffice - people find out about the concept of composition 'after' they have created the Document Type which is too late!- or they must read the documentation first! which then has to be kept updated :-P

Generally it's better to have experiences where people can understand what they need to do from using the system [Citation needed!]

When you've come to redo the backoffice from scratch, and you've tried to rethink things to implement an MVP - I think there the misunderstanding has crept in that because the Composition is implemented in the same way as a Document Type - that this **implementation fact** was more important for people to learn than the existence of the **strategy of compositions**!! - Which is true if you are a developer working with the source code and trying to build a new backoffice - but not true if you are a developer new to Umbraco, trying to learn Umbraco from scratch to build a good implementation.

**Comment by iOvergaard** [comment]
@marcemarc 
> think you are misunderstanding!!, - which might explain why you have accidentally removed this option with out understanding why it was there - there was an option in the'old old menu' to do what you describe - create two related Document Types -, but the composition option here on the menu isn't that! - the introduction of the menu that introduced the composition option removed that confusing two Doc Type option!

I wonder if you've seen [Niels' reply to the discussion you started](https://github.com/umbraco/Umbraco-CMS/discussions/16351#discussioncomment-9573577)? It was a conscious choice to omit the option, as he explains:

> Point being, the users overview of options is established at this point, and it will deceive them as the Composition will be interpreted as something different than a Document Type. But it is not — Instead I would love that we come up with a solution that underlines that a Composition can be made with anything. Even Element Type can be used as a Composition, Even Document Type with Template can be used as the base for a composition.

I think that the confusion that led to this current issue report is the very thing Niels addresses - people may think it is something special, whereas in fact you can create compositions with just about anything in there.

As Niels goes on to explain, we are not forcefully excluding any kind of supporting UI in this area in the future, but we need to consider what the best approach is:

> I do like the intentions and if there is a time where we can move the cheese it is now, which is why we have taken the opportunity to remove it, so there is room later to make a intuitive feature that actually briefs new users on their opportunities

**Comment by marcemarc** [comment]
Thanks @iOvergaard I have seen it now, thanks, replied there - hopefully I have closure now! Compositions are something special! :-P
