### ISSUE TITLE
Value gets changed for other language when vary by culture is enabled on a blocklist.

### ISSUE THREAD

**Issue by andersreus** [umbraco/Umbraco-CMS#17249]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

When adding language variations to a text string in a blocklist, the value for one language overwrites the value for the other language.

### Steps to reproduce

1. Create a fresh v.14.3.0
2. Create a document type with a blocklist and toggle "Allow as root" and "Vary by culture"
3. Add a textstring element type to the blocks and toogle "Vary by culture"
4. Add a second language
5. Create the root content node and add domain for the second language that was added
6. Write content in the first language, then save and publish
7. Write different content in the second language, then save and publish only that variant.
8. Inspect the first variant and see the value of that one also changed to the value of the second one.

Gif showcasing the issue:
![blocklistvarybyculture](https://github.com/user-attachments/assets/e476787a-32aa-4887-95fd-5857d79ee171)

### Expected result / actual result

Expected the first variant to stay the same.

---
_This item has been added to our backlog AB#46443_

**Comment by NguyenThuyLan** [comment]
I was able to reproduce this on v15.0.0-rc3

**Comment by kjac** [comment]
Hi @andersreus,

Thank you for reaching out, and not least for the detailed description 💪 

What you're experiencing is by design. Umbraco 14 and below does not have a concept of varying blocks in an invariant block editor.

The good news? It's a feature in Umbraco 15 🥳 

Check the docs here: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-level-variance
