### ISSUE TITLE
Change a editor on a property, changes it multiple places

### ISSUE THREAD

**Issue by Welander1994** [umbraco/Umbraco-CMS#17297]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3

### Bug summary

if i have two properties that use the same editor type, and I change one of them to something else it will also change the other one.
I would understand if you have a configured editor and you have applied that to multiple properties that it will change everywhere if I changed the configuration of it.
But if I switch from standard editor on a property to another standard editor, it should not change on other properties,
Let's say I have two properties that both are textstring, and I change one of them to use RTE instead, it will change both of them, is this intended behavior?

### Steps to reproduce

https://github.com/user-attachments/assets/c857647d-cb83-4903-be1f-25c24d0bc6e1

---
_This item has been added to our backlog AB#45093_

**Comment by Welander1994** [comment]
It looks like what is happening is that when I try to change to another editor, it updates/edits the one I'm on instead of switching.

**Comment by leekelleher** [comment]
@Welander1994 Thank you for raising this issue. 🙏 

I'd to clarify the functionality, it is intentional, a long standing feature. The main difference in v14 is the missing labelling around it.  For example, in v13, the property's selected Data Type had **Edit** and **Change** actions, where as in v14 the title acts as the Edit and the Change action is present.

![Screenshot 2024-11-07 092958](https://github.com/user-attachments/assets/7613050f-b53f-40db-b140-569139c0ed07)

Then within the edit Data Type modal, in v13, a notice was labelled at the top: "**All Document Types using this editor will get updated with the new settings.**" to signal the intent.

![Screenshot 2024-11-07 093018](https://github.com/user-attachments/assets/f9e28934-9719-412e-a5ee-3361aa6228d2)

For v14, we should have the equivalent messaging. 

Although we may not re-introduce the separate **Edit** action/button, as clicking on the reference title (to open/edit) brings UI/UX consistency with how that component is reused in other areas, e.g. for various Picker editors, etc.
