### ISSUE TITLE
Markdown doesn't render in block list item labels when using inline editing mode

### ISSUE THREAD

**Issue by dmiller21283** [umbraco/Umbraco-CMS#17313]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

Umbraco Flavored Markdown does not render in block list item labels when using inline editing mode. The markdown does render correctly if inline editing mode is not enabled.

### Steps to reproduce

1. Create a document type
2. Add a block list property editor
3. Select an element as an available block
4. Under Block appearance, in the Label field, add markdown to display a field value in the label (ex: {= title }
5. In content, create a document with the block list editor
6. Add an item to the block list providing a value for the field used in the label
7. Save it to see that the label is not rendered

### Expected result / actual result

Expected result:
Markdown should render in the label. (the following screenshot is the block list with inline editing disabled)
![image](https://github.com/user-attachments/assets/ace3fe3b-56b3-4905-86fb-d790d1e57df3)

Actual result
Markdown is not rendered in the label (the following screenshot is the block list with inline editing enabled)
![umbraco results](https://github.com/user-attachments/assets/5aeb2592-c728-43fd-99e7-0cb849481b40)

**Comment by IbrahimMNada** [comment]
I will release a package
For this specifically

And i will mention it here when uploaded

**Comment by IbrahimMNada** [comment]
kindly check this url for the packages that will help you achieve what you wanted 

https://github.com/IbrahimMNada/Umbraco.Markdowns/blob/main/Umbraco.Markdowns.BlockList.DyanmicLabels/README.md

**Comment by dmiller21283** [comment]
I installed the latest package and it's working with the properties from a link picker 
`{> category[0].name}`

However, when use it with a child property of the element, it doesn't work.
`{> heading}`

![image](https://github.com/user-attachments/assets/4ca1ebbe-20f3-44f3-aef9-b36f32dc1c6f)

**Comment by IbrahimMNada** [comment]
Can you please open an issue with enough context , pretty sure i will figure something out

**Comment by IbrahimMNada** [comment]
> I installed the latest package and it's working with the properties from a link picker `{> category[0].name}`
> 
> However, when use it with a child property of the element, it doesn't work. `{> heading}`
> 
> ![image](https://private-user-images.githubusercontent.com/5545005/378974539-4ca1ebbe-20f3-44f3-aef9-b36f32dc1c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTgwNjgsIm5iZiI6MTcyOTY1Nzc2OCwicGF0aCI6Ii81NTQ1MDA1LzM3ODk3NDUzOS00Y2ExZWJiZS0yMGYzLTQ0ZjMtYWVmOS1iMzZmMzJkYzFjNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjNUMDQyOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDc3MGU4M2U2MzIxNmExZTIxNDE0ZjljYjE1NDE0YTEyMzZhZDAxZTZiMjY1OTlhYTBmNjA0N2M1N2QyYTQwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.p253KHce-nN5YVhe6RLmQT-tYhWnY-pvsvWwBVHZN9k)

seeing this renderd row like this , gives me the feeling the umbraco markdown is not working for this section so i wanna know more details about it

**Comment by leekelleher** [comment]
@dmiller21283 To let you know that the original/underlying issue (of UFM not rendering for Inline Blocks) has been resolved, (in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2423), which is due for 15.1.0, (as the feature was made after the 15.0-rc went out, so is part of the following release), I appreciate it's a frustrating delay.

To note, the fix is unrelated to the property drilling that @IbrahimMNada's extension offers.

**Comment by Nuklon** [comment]
> @dmiller21283 To let you know that the original/underlying issue (of UFM not rendering for Inline Blocks) has been resolved, (in [umbraco/Umbraco.CMS.Backoffice#2423](https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2423)), which is due for 15.1.0, (as the feature was made after the 15.0-rc went out, so is part of the following release), I appreciate it's a frustrating delay.
> 

That makes little sense as other features are added. Now we get a v15 release that's essentially useless for a lot of people. Can this be backported? The change seems to minimal.

**Comment by nielslyngsoe** [comment]
Hi @Nuklon

You can say that about any of the v.14 releases. We are still in the process of becoming feature parity with v.13, meaning a few things are missing, mostly features that relate to the Editing Experience. Things that are important for end customers, but also things that is not absolutely necessary during development. So the releases enables you to get started developing a v.15 project and in the coming period the missing features will take part.

From a release protocol perspective this feature was not ready when 15.0-RC got released meaning it will come as part of 15.1. And luckily we have accelerated that release, of the same reasons, meaning there will be a 15.1-RC 14days after 15.0.

I hope that will work for you.

How does your process look and where are you in your development process?

**Comment by ZaibiMohammed** [comment]
Hello everyone,

I’m encountering several known limitations with in Umbraco 14 and I’d like to know if they’ve been addressed in recent releases or if any fixes are planned:

Generic interpolation in Collection Views

The {=x} syntax wasn’t rendering the correct value in Collection Views—this was supposedly fixed by issue #16776 (https://github.com/umbraco/Umbraco-CMS/issues/16776).

Question: Is this fix included in version 14.2.0 or later, and has anyone tested its stability in production?

Nested property access

Using {=contributor.name} on Nested Content or Content Pickers still returns an empty string, as noted in issue #17082 (https://github.com/umbraco/Umbraco-CMS/issues/17082).

Question: Has support for nested property interpolation been added since then? If so, in which version?

UFM rendering in inline Block List editing

In inline editing mode for Block Lists, UFM labels {=…} remain unrendered (you see the raw syntax), whereas they work correctly in the overlay editor—see issue #17313 (https://github.com/umbraco/Umbraco-CMS/issues/17313).

Question: Are there plans to enable UFM rendering in inline editing as well?

Any feedback, workarounds, or pointers to pull requests would be greatly appreciated. Thanks in advance!

**Comment by leekelleher** [comment]
@ZaibiMohammed As mentioned above, https://github.com/umbraco/Umbraco-CMS/issues/17313#issuecomment-2457267747, this particular issue was resolved for Umbraco 15.1.0.

As for some of the other issues you've mentioned, many of them would be resolved with the upcoming UFM: JavaScript-like Expressions syntax, (see #19685 for details), in Umbraco 16.2.0 (scheduled for release on September 4th).
