### ISSUE TITLE
Invalid JSON (cuts in half) from Content Delivery API

### ISSUE THREAD

**Issue by alekos-captureone** [umbraco/Umbraco-CMS#17352]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

When we fetch some pages' content from Content Delivery API, the response is "cut" at some point, resulting to invalid/unreadable json.

### Specifics

https://stage-capture-one-cms.euwest01.umbraco.io/umbraco/delivery/api/v2/content/item/de/explore-features?expand=properties[$all]&take=1100

Let us know if you need access to the backoffice.

### Steps to reproduce

GET request this url: https://stage-capture-one-cms.euwest01.umbraco.io/umbraco/delivery/api/v2/content/item/de/explore-features?expand=properties[$all]&take=1100

JSON response should be valid

**Comment by NguyenThuyLan** [comment]
Hi @alekos-captureone , thank you for reporting this issue.
It would be great if you can share the structure and how large of your content then we can reproduce it easier

**Comment by alekos-captureone** [comment]
Hello! I have shared in the first post under "Steps to reproduce" the url that is getting cut. 

The page has 4 modules 
![image](https://github.com/user-attachments/assets/ec94779a-7409-4459-afba-f9027f1a7ef3)

and some of the modules have some depth
![image](https://github.com/user-attachments/assets/45d711bf-426d-4cd4-9f5e-f0719a4ee106)

If you need access to the backoffice to see the actual content, let me know.

**Comment by NguyenThuyLan** [comment]
Hi @alekos-captureone , It seems that your response body API exceeds the maximum limitation so the received response is truncated. The maximum limitations can depend on many factors, including configuration settings and system limitations. Depending on the server you can configure it in different ways:
Eg:
```
public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.Configure<KestrelServerOptions>(options =>
        {
            options.Limits.MaxResponseBufferSize = 1024 * 1024 * 10; //10 MB
        });
    }
}
```
Or instead of choosing the expend as all properties, get only the properties you need. This will help reduce response size and your json response can be intact.
