### ISSUE TITLE
We only have "da" as language in our installation, but "en-us" shows up in the UI

### ISSUE THREAD

**Issue by nikolaj-kaplan** [umbraco/Umbraco-CMS#17394]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

Danish is the only language configured.
![image](https://github.com/user-attachments/assets/a455f7fb-4423-4862-a993-552740e0387d)

But we still see en-us in the UI:
![image](https://github.com/user-attachments/assets/e1d86ddf-b029-45a3-916a-e58bd49d845f)

I assume this is the reason why, but I don't know how to solve it:
![image](https://github.com/user-attachments/assets/f18d333f-823b-4fae-bb1e-c9d4b32684e9)

### Steps to reproduce

I haven't tried to reproduce from scratch. But I would assume that you should:
1. Configure Umbraco to only have Danish as language
2. Create a document
3. Go to the info tab.

### Expected result / actual result

"en-us" should never show up anywhere in the ui. If we need at fallback language, it should be a language that is actually present in the language list.

---
_This item has been added to our backlog AB#45483_

**Comment by leekelleher** [comment]
@nikolaj-kaplan Thank you for raising this. The hardcoded `en-US` was definitely an oversight.

The good news is that this has already been resolved, but across 2 fixes:
- https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2478 fixes the **Publication Status** (to only show the status of the current variant). This will be available in v15.0.0.
- https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2497 resolves the **Links** showing the correct cultures. Because this added a new feature (after the 15.0-rc went out), it will be available in v15.1.0.

I'll close off this ticket, but feel free to re-open it if there is more to discuss.
