### ISSUE TITLE
V15: Document types configured as list view will still list documents in the node tree

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#17463]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc3

### Bug summary

If a document type is configured as a list view, the documents are still listed in the node tree.

![image](https://github.com/user-attachments/assets/eb183f0f-79ff-4949-b369-9a353adcfd28)

![image](https://github.com/user-attachments/assets/8817ff56-d2e3-4291-8714-94fe59877685)

### Steps to reproduce

Configure a document type as list view and create documents under that type

**Comment by nielslyngsoe** [comment]
Hi @DanielToft 

Thanks for highlighting this. This is though fully on purpose, enabling a Collection gives the user the ability to get a better and more refined view on its children's, by its filtering and sorting options.

But the concept is not intended to hide children in the tree — this was the fact in previous versions because the architecture did not support having a large number of child items in the tree.
But now that we do support such we decided not to hide the children. Technically because we now have pagination in the tree.

This gives the user ability to still navigate via the tree. See where they are at in the tree and do what they are used to in the tree. And when needed they can open the collection for a more refined view.

Since you reported this issue I assume you have opinions, so let me ask what you think about this approach and if there is a perspective you think isn't covered?

I may add the UX of pagination in the tree will get a bit more polish in the future but it does what is needed at this stage.

Thanks in advance

**Comment by DanielToft** [comment]
Hi @nielslyngsoe 

Thank you for clarifying this. I did not know that this was a feature. I was just worried about the potential performance issues when having a lot of documents, but it sounds like you already have taken care of this and I think this is a good solution. I'm looking forward to try this out. 

Thank you,
Daniel

**Comment by jcrittenden** [comment]
@nielslyngsoe @leekelleher I'm a little late here, but thanks for the explanation above from November. My only complaint is that when clicking a document from list view, it opens the document in a modal/sidebar/partial window. It would be nice if it opened the document fully, like in previous versions, and like when clicking from the tree.

**Comment by markadrake** [comment]
> ... this was the fact in previous versions because the architecture did not support having a large number of child items in the tree. But now that we do support such we decided not to hide the children. Technically because we now have pagination in the tree.

The reason for the guideline of "not showing too many items under a tree" might have originally stemmed from a technical limitation. However, I would argue that a tree structure with thousands of children does not offer a helpful or effective user interface (even with pagination included).

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/collection-bug-in-version-16/5628/2

**Comment by arknu** [comment]
@nielslyngsoe There was very good UX reason for editors why you _don't_ want the children showing in the tree when a list view is configured. This should really be an option when enabling a list view. That way we can have the best of both worlds. And the amount of duplicate issues reported here should show you that the current behavior is not the correct design for all cases!

**Comment by markadrake** [comment]
That's okay, I'm sure somebody will release an Umbraco Package I can download from Nuget, add to my dependency chain, complete a PR, run CI/CD, deploy to staging, approve and push to production–just in time to discover the security vulnerability and have to repeat it all over again.
