### ISSUE TITLE
v15.0 backoffice dashboard missing match property in conditions

### ISSUE THREAD

**Issue by jbppraxis** [umbraco/Umbraco-CMS#17690]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15.0

### Bug summary

Our custom dashboard is not showing up in the backoffice. We need to provide a match condition but it cannot be found. I tried to figure out if I should do something differently but without success.
![image](https://github.com/user-attachments/assets/6d7a6d7e-6d67-431d-87cc-687432fbce57)

### Steps to reproduce

Add a custom dashboard, add the mainifest.ts file se it happen.

### Expected result / actual result

We cant compile the ts file. 
As a workaround we have added the @ts-ignore and everything is working as exspected.

---
_This item has been added to our backlog AB#46721_

**Comment by nielslyngsoe** [comment]
Hi @jbppraxis 

The architecture for Extension Manifest Types have changed in v.15.0, this makes them better for extension, but requires a change coming from v.14. Now it is recommended using a global type called `UmbExtensionManifest`.

In order to get this type in your project, you must add it to your tsconfig, you can read more on that matter in this announcement: https://github.com/umbraco/Announcements/issues/22

The reason why I mention this is because the specific type does not know about the available Condition Types, and there for it makes sense that the Condition Type is failing on you in this case.

Once your project is setup, this should be resolved — Please let me know how it goes and sorry for the inconvenience, its for the better.

**Comment by jbppraxis** [comment]
I will close it for now.
