### ISSUE TITLE
Cannot use content templates in list views

### ISSUE THREAD

**Issue by tnielsenskybruddk** [umbraco/Umbraco-CMS#2927]
I have a list view and have allowed a child document type which has a content template.

If I try to add a new child from the content tree everything works perfectly. The content template picker slides in and I can choose the content template.

But if I use the create button above the list view I do not get a content template picker. It just create a blank node.

I am using a Umbraco 7.10.4.

![contenttree](https://user-images.githubusercontent.com/3634628/45158887-9fb70900-b1e5-11e8-85b4-b28dd433dda6.png)
![listview](https://user-images.githubusercontent.com/3634628/45158888-9fb70900-b1e5-11e8-99fa-ca267ae9d9d6.png)

This issue is a copy from the old [issue tracker](http://issues.umbraco.org/issue/U4-11436).

**Comment by nul800sebastiaan** [comment]
Looks like the "Create" button needs to be extended if content templates are available and there should be an down-arrow available to give the option of creating a page from a content template.

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Note that the workaround for now is to right-click on the root node of the list view and choose "Create"
![image](https://user-images.githubusercontent.com/304656/45165861-fe847e80-b1f5-11e8-9cf0-cd0d5163cdda.png)


You also get the content template choice when you "Create" from the top-right action menu.

![image](https://user-images.githubusercontent.com/304656/45165924-18be5c80-b1f6-11e8-9bc1-ab984a9a0ddd.png)

**Comment by KimHolzmann** [comment]
@tnielsenskybruddk  @nul800sebastiaan 
Hopefully I will finish this tomorrow :-)
I just have the dropdown button left to do now.
But have some other stuff from the morning, I have to do first.

**Comment by KimHolzmann** [comment]
Have done the PR now.
The logic and functionality works.
 
But someone needs to do the rest (sorry).
1. The button styling must looks like the others.
2. As it is now there is three buttons - but only one must been shown depending the ng-if statments.


One if there is only one allowed documentType
![image](https://user-images.githubusercontent.com/8200579/46531615-2c64ed80-c89e-11e8-8568-b4a6e5fdab4e.png)

On if there is only one documentType AND bluprints
![image](https://user-images.githubusercontent.com/8200579/46531721-84035900-c89e-11e8-8e54-4806479f2899.png)

And the last one - if more than one documentType AND blueprint
![image](https://user-images.githubusercontent.com/8200579/46531769-aeedad00-c89e-11e8-81af-223ddeaf0c80.png)

**Comment by jaandrews** [comment]
@KimHolzmann You can avoid the need for styling changes by tweaking how the content blueprints are selected. Instead of showing the blueprints in the dropdown, you can show them in a panel like the other creation buttons do when the create button is clicked. The potentially tricky part is skipping the doc type selection, as the doc type has already been set by the list view. The two pieces are both controlled by **"Umbraco.Editors.Content.CreateController"** in the same view, so you may need to create a copy of this view and then strip out the doc type selection.
