### ISSUE TITLE
Tags split incorrectly in 7.12.2

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#2949]
I created some pages with Umbraco 7.11.4 based on a document type that contain a property of type "Tags". After an upgrade the 7.12.2, tags are incorrectly split. For example, a page had the tag "Pension", now it has the tags "p", "e", "n", "s", "i", "o", "n".

Reproduction
------------

* Create a page with Umbraco 7.11.4 that has a "tag" property
* Upgrade to 7.12.2

After some tests, it looks like the issue is not because of the upgrade but simply because the tag controller is broken. The following scenario also fails:

* Create a new page 
* Type a tag in a "Tag" property
* Press "enter" to create the tag
* Several tags are then created (one for each letter of the tag).

**Comment by ssougnez** [comment]
I'm using Google Chrome 68. I attached a [screencast](https://github.com/umbraco/Umbraco-CMS/files/2366198/cast.zip) to show the issue.

Basically, when I display the page (created with 7.11.4), you can see that the tag is incorrectly split. 

* If I try to delete the last tag, nothing happens. 
* If I try to delete the first tag, the context menu disappears but confirming the deletion creates an error in the console.
* If I type something to create a new text and press Enter, another error appears in the console.

The property is simply an "Umbraco.Tags" property editor.

Note that I think it's just a controller issue because when I check the result of "GetById" call, the tags are returned correctly. For example:

![tags](https://user-images.githubusercontent.com/10199821/45292597-f8441a00-b4f5-11e8-94b5-e8b830ed4670.png)

Another precision, when I save the file, I lost all my tags. So if I save, then refresh, tags are empty.

**Comment by nul800sebastiaan** [comment]
@ssougnez I suspect (also after seeing #2950) that something went wrong during your upgrade. All of your datatypes that were of type `Umbraco.Tags`  and previously were not configured with a particular storage method (the default), should have been updated to store tags as Storage Type being CSV.

So: there's 3 Storage Types:
- None (the default before 7.12)
- CSV (if "none" was selected before, it would store tags as CSV)
- JSON - the new default for NEW tags datatypes in 7.12+

During the upgrade a migration should have ran that changes the option "None" to "CSV".

Maybe try setting the version in web.config to 7.11.1 and then run through the upgrade installer again, it will start automatically when you change the version. That should run the migration again.  
This is the migration for it: https://github.com/umbraco/Umbraco-CMS/blob/2d7918843303689b6c9c2164be34a53bd5c019ac/src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenTwelveZero/SetDefaultTagsStorageType.cs

**Comment by Jack-RNM** [comment]
@nul800sebastiaan we've had the same issue upgrading a site from 7.6.1 -> 7.12.3. I checked the database for the migration you mentioned and it looks like it hasn't run, as I believe there should be a value for dataTypeNodeId 1041:
![image](https://user-images.githubusercontent.com/12048193/48348727-0d663200-e67a-11e8-9221-9889d7e75469.png)

Changing the web.config version back does not appear to do anything, and neither does manually adding the Csv prevalue. I've also tried deleting the tags property from the document type and creating a completely new property and editor with storage type JSON, which does save the tags without splitting them up in the CMS, but throws a JsonReaderException exception when attempting to access the property value in a view. This looks to be because the tags are actually still being stored as CSV:
![image](https://user-images.githubusercontent.com/12048193/48349103-2d4a2580-e67b-11e8-8201-dc5b49830c17.png)
