### ISSUE TITLE
Newtonsoft.Json > v11.0.0 support

### ISSUE THREAD

**Issue by niallmccabe** [umbraco/Umbraco-CMS#2951]
Certain packages such as Google's ApWords API require Newtonsoft.Json version 11.0.2 or higher. As of writing v7.12 only supports < v11.0.0. This mismatch causes a missing assembly error.

Is there a plan to support the latest version of Newtonsoft.Json in upcoming releases?

Reproduction
------------
Install a package that requires Newtonsoft.Json v11.0.2

**Comment by nul800sebastiaan** [comment]
Hi @niallmccabe - You're always welcome to try and update dependencies but remember that this is untested and your mileage may vary. 

You can use the command `Update-Package Newtonsoft.Json -IgnoreDependencies` to make sure the latest version installs. The latest version is a new major version and might have breaking changes. We do have very good results with `Newtonsoft.Json` since we don't use any of their advanced APIs, so most of the time upgrading it shouldn't be a problem.

**Comment by dalibor983** [comment]
@nul800sebastiaan I did what you said, I upgrade Newtonsoft.Json with `Update-Package Newtonsoft.Json -IgnoreDependencies` but now I cannot update any other package because I always got this error:
```
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'UmbracoCms.Core 7.12.2 constraint: Newtonsoft.Json (>= 10.0.2 && < 11.0.0)'
```

**Comment by Rizen-Kris** [comment]
why is there a maximum version of newton?
