### ISSUE TITLE
Allow custom items to be ignored by the database schema healthcheck

### ISSUE THREAD

**Issue by richarth** [umbraco/Umbraco-CMS#2959]
Lots of packages are creating custom tables, columns, indicies and constraints.  A very common example of this is Umbraco Forms.

When you run the database schema healthcheck it warns about all of these custom items as it's not expecting them.  I think it would be helpful to be able to specify which of these custom items you would like to ignore and for the healthcheck to be updated to exclude the Umbraco Forms items by default.

**Comment by kjac** [comment]
@richarth which health check is this? I can't see any DB schema healthcheck in the core.

**Comment by richarth** [comment]
It's one of the data integrity checks

**Comment by nul800sebastiaan** [comment]
I've had to remove this health check for now since there was too many problems and confusion with it. I would love to add it back at some point but it needs quite a bit of work to make it work well:

1. Error messages need to either have a "Fix" button or at least a description of how to fix the error
2. Number 1 above needs to be done for every possible error that can come out of this check, this is not a trivial task
3. Custom table should obviously not be listed in this overview, we were only ever trying to check the built-in CMS schema

See: https://github.com/umbraco/Umbraco-CMS/issues/3132

I'll close this for now until someone can work on a check that can actually provide a way to properly fix the possible errors.

**Comment by kjac** [comment]
That explains my confusion 😀
