### ISSUE TITLE
Umbraco Site is down

### ISSUE THREAD

**Issue by tranphuongyd** [umbraco/Umbraco-CMS#2981]
Hi everyone,

Our production site just have issue yesterday. It's down, all requests to this site will get time out. So we was restart the application, then works fine now. But we need to know the reason and try to resolve it. I just have check the logs at that moment and attached here, please see the image below. Umbraco version is 7.5.6
Could you please help us check this issue. 
Thanks,
![45461308-95889380-b72c-11e8-9c00-cac3927ced5f](https://user-images.githubusercontent.com/7795756/45494269-dfa85e00-b79a-11e8-85d1-35787254d63e.png)

**Comment by tranphuongyd** [comment]
hi @nul800sebastiaan, I don't think it's not a bug. Because all the logs saying that's behind the UmbracoCMS.

**Comment by nul800sebastiaan** [comment]
Possibly. 
If you have steps to reproduce the bug in the latest version of Umbraco then you should definitely post them here so we can have a look at that. Until that time, there's not much we can do if we can't reproduce it. 😊

**Comment by tranphuongyd** [comment]
Haha, you can see 2 logs at the bottom that's from a automatic job "Remove all items older...", then after this function the site is down.

**Comment by nul800sebastiaan** [comment]
Alright @tranphuongyd - I'm sorry your site went down, it happens sometimes and it doesn't always mean there's a bug in Umbraco. You're on a version of Umbraco that is almost 2 years old and numerous improvements have been made since then. I would advise you first to upgrade to the latest version and then see if the same problem still occurs for you. 

If this is still a problem for you then the only thing we can realistically do is to ask you how exactly to reproduce it. Reproduction means: you set up a clean version of Umbraco and the exact same problem occurs. If that is the case then the developers at Umbraco HQ should also be able to reproduce the problem, at which point we can identify the cause of the problem and attempt to fix it.

We have a great many sites running that have the exact same items in the log  "Remove all items older...". These sites don't go down immediately after that, so we cannot reproduce the problem reliably at the moment.

Does that make sense to you?

**Comment by tranphuongyd** [comment]
Hi @nul800sebastiaan , that make sense I think. 
Many thanks for your support!
