### ISSUE TITLE
User invite flow review

### ISSUE THREAD

**Issue by agrath** [umbraco/Umbraco-CMS#2993]
We have had a number of issues with inviting users to Umbraco which are reported as 'we can't log in' and 'the invite doesn't work'
I'm collecting all the issues here and thoughts and will then raise a PR to fix them once we have a clear course of action on each.

### Bug summary
User invites have a few issues and the flow breaks sometimes
1) Invites tokens expire after 1 day and this is not configurable
2) When a token is expired, the initial invite link just dumps you at the login page with no error
3) You can perform a password reset request on an invited account, but following the successful flow, the user cannot log in and the account still shows as 'invited'
4) There is no way in the backoffice to remove an invited user (you can only disable them) and start over, however you can manually set their password which allows them to log in

### Specifics

Checked in Chrome specifically with a 7.12 instance of Umbraco.

Issue 1 - increase the token expiry from the default of 24 hours to 3 days (72 hours) and add a configuration variable to change this. 
Issue 2 - when an invite link is clicked and the invite token has expired, validate this and show an error message to the user. Prevent redirect to login. There appears to be handling for this already but it is not working. 
Issue 3 - either prevent the forgot password reset flow from working on an invited account OR make it so that if you do this flow on an invited user it clears the invite status of the account and allows the user to log in afterwards
Issue 4 - Allow an invited user to be removed from the admin area; e.g. if the email address was entered wrong or similar.

@nul800sebastiaan can you please review my suggested fixes before I begin working on the PR and alter the proposed functionality where applicable?

**Comment by nul800sebastiaan** [comment]
1. The less config we have the better, changing to 72 hours is fine.
2. Yes please.
3. I don't see a reason why forgot password shouldn't work, obviously you've been invited, we only expire links because emails float around servers and we want to make sure someone who can read them can abuse them after a while.
4. I think that's already possible in 7.13 (`dev-v7` branch), make sure to test first.

**Comment by kows** [comment]
I just wanted to add in on 3 since I just tried a similar flow myself.
Step by step:
* Invited email
* Received invitation mail but did not open
* Trigger reset password
* Worked & was logged in
* Cloud dashboard states profile is not activated and redirects me to 'Profile'
* Here I can click 'Activate profile' which pops up a form asking for an 'Activation token'.
Where do I find this token?
User seems to be able to login to backoffice.

**Comment by nul800sebastiaan** [comment]
@kows That is the Cloud procedure, which is different from what is built into Umbraco Core.

**Comment by agrath** [comment]
Thanks @nul800sebastiaan 

1. I'll increase but not add config
2. Will find and fix
3. I will take the action of clearing the invite state in this flow, it is worth noting this works perfectly if your invite token hasn't expired, but if your original invite token has expired and not been redeemed there is no way for the user to gain access via redemption or reset.
4. Okay i'll test and confirm before doing any work on this

Thanks for reviewing this proposal before I build & PR it, just wanted to clarify the expectations :)

**Comment by agrath** [comment]
@nul800sebastiaan 
1 - done
2 - fixed
3 - fixed
4 - already fixed

also found another bug which is that when you click the invite link this makes the account switch to disabled which means invites can't be resent and the account shows incorrectly in the admin, so fixed that too.

**Comment by readingdancer** [comment]
We had an issue recently where I invited a user and for whatever reason their email was not working, hence they were not receiving any emails from the site.

I said "oh it's ok, I'll just setup a password for you" only to realise that it is only possible to delete a user or re-send the invitation, I think the admin user should still be able to setup a password as my only option for this user was to delete the invited user and re-create them using the "create user" option.

**Comment by agrath** [comment]
@readingdancer I agree, that should be a different issue though

**Comment by BatJan** [comment]
I'd like to add the following 2 issues - Please let me know if it's preferred that I move these into separate issues. Ok, here goes

1. When using the invite function it's possible to assign a user to a user group. But it's not possible to pick starting nodes for content and media. This can only be done once the user is invited. I suggest we should make it possible to add the start nodes as a part of the invite flow.

2. Once a person clicks the invitation link at the end of the flow it's possible to select an avatar. Below the avatar there is a green "Proceed" (Can't remember the text now) button and a skip link. It seems a bit weird since either of them will do the same thing - Namely take you to the backoffice whether you select an avatar or not :)

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3000

@readingdancer @BatJan make sure to create additional issues so they can be addressed! 👍

**Comment by nul800sebastiaan** [comment]
@readingdancer Actually in 7.13 we already have a "resend invite"! 🙌 

![image](https://user-images.githubusercontent.com/304656/46257914-6ad76280-c4c2-11e8-9be2-1afc2c2ff093.png)

**Comment by BatJan** [comment]
@nul800sebastiaan Ok, so do you prefer that I create 2 separate issues then or should I keep it in one?

**Comment by readingdancer** [comment]
@nul800sebastiaan I'll add a new ticket, ref your last comment, the "resend invite" does not help if the end users email is not working :)

From my original msg: "they were not receiving any emails from the site"  :)

**Comment by readingdancer** [comment]
For reference, I have just created an issue for my suggestion to allow an admin user to reset a users password when they are in the "invited" state. https://github.com/umbraco/Umbraco-CMS/issues/3105

**Comment by nul800sebastiaan** [comment]
Forgot to close this one, fixed in https://github.com/umbraco/Umbraco-CMS/pull/3000
