### ISSUE TITLE
Angular and C# updates to support tree sections and tree syncing

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3087]
child of #3090

Angular and C# controller updates to support tree sections and tree syncing.

See https://twitter.com/thechiefunicorn/status/818436035940061184/photo/1 for reference.

**Comment by warrenbuckley** [comment]
The PR for this to review is here - https://github.com/umbraco/Umbraco-CMS/pull/3200
@Shazwazza are you able to review this please - as you helped me out loads on this already anyway.

**Comment by Shazwazza** [comment]
Next thing to do is to fix up tree syncing with the new structure, we'll save that for sprint 96

**Comment by warrenbuckley** [comment]
@Shazwazza what was the status of this - I totally forgotten where we left this

**Comment by Shazwazza** [comment]
We need to make tree syncing work it's broken. As noted above - we will get this done this sprint, i'll have a look

**Comment by Shazwazza** [comment]
@warrenbuckley for re-review:

* Have a peek at the code changes, there's quite a bit but the underlying logic isn't so different, i added lots of code comments to the TreeRootNode class to try to describe the different types there. The tree.html now checks if there are groups rendering, if not it continues like it did before, else it renders the groups. 
* Tree syncing should work for all nodes now, the tree always works from one final root node per section so that's why i needed to change it back to have a single root node
* Test each section, it should all work, the users section is now a full screen section (no tree)

**Comment by warrenbuckley** [comment]
All good and tested & merged.
Added a small note about the tree hiding to perhaps use `appState.setGlobalState("showNavigation", false)`
