### ISSUE TITLE
C# controller updates for 'Add bulk publish descendants button'

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3093]
child of #3335
requires #3336

Add controller endpoints to support bulk publishing.

Similar functionality to what we had in the old webforms dialog.

* We will need new ContentController endpoints 
* We will need to wire up the new angular changes to send the right data to the controller
* Call the ContentService.SaveAndPublishBranch method for bulk publishing

**Comment by Shazwazza** [comment]
What needs to happen is the ContentController.PostPublishById needs to accept a model containing: Id, bool for descendants, bool for drafts and a string list for variants. This endpoint can then be used for the publish endpoint for both variant and invariant.

**Comment by warrenbuckley** [comment]
Question @Shazwazza - currently `PostPublishById()` is only used for ListView when doing a bulk publish of a collection of nodes.

Is the goal to update this POST method as you described to replace `PostSave` which is what is currently used to do a publish for invariant & variant content.

So is the goal then to have one POST endpoint to rule them all, which will deal with the following

* Save (one or more cultures)
* Save (invariant node)

* Publish (one or more cultures)
* Publish (invariant node)

* Publish with descendants - exclude drafts (one or more cultures)
* Publish with descendants - exclude drafts (invariant node)

* Publish with descendants -plus drafts (one or more cultures)
* Publish with descendants - plus drafts (invariant node)

Or have I totally misunderstood your notes for this Shan?

**Comment by Shazwazza** [comment]
I believe you have misunderstood my comment 😛 that said, I didn't think about this in context of editing a content item. That sort of changes things. So partially you are right and partially we need the functionality I described. Let's chat next week!

**Comment by warrenbuckley** [comment]
@Shazwazza ping me when your free next to talk about this please then :)

**Comment by warrenbuckley** [comment]
Requires this task to be done first - https://github.com/umbraco/Umbraco-CMS/issues/3336

Before this can continue

**Comment by Shazwazza** [comment]
Testing notes:

There are some known issues: #3708, #3709 so all testing should be done against variant properties only, if you only edit invariant properties this will not work.

* [ ] Make sure tests pass
* [ ] Create document type(s) with only variant properties and give one property a 'mandatory' requirement
* [ ] Create a content tree structure with this doc type, do not publish anything, leave some documents invalid based on the mandatory property
* [ ] Go to the root node of your structure and choose to publish descendants without clicking "include drafts" - choose whatever languages you want to test - this will only publish the root since all of your descendants don't have a published version - the success message will be the same as if you just published this single document - make sure the changes are visible on the front end
* [ ] Do the same again but choose "Include drafts" and choose all languages, you will get a message like the following (based on how many docs you have and how many invalid, etc...)  - make sure the changes are visible on the front end
![image](https://user-images.githubusercontent.com/1742685/48681921-9db3f200-ebf9-11e8-8280-74480c241901.png)
* [ ] Change some descendant property values and press Save for these to create new drafts
* [ ] Go to the root node, choose publish descendants and without clicking "include drafts" - you will get a success message with the correct count of documents published based on how many new drafts you created - make sure changes are visible on the front-end
