### ISSUE TITLE
Navigation property editor

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3133]
Currently developers are building navigations in all sorts of different ways. Some are using their own thought up conventions which varies in each specific implementation of an Umbraco site. There's rendering children/descendants based on `umbracoNaviHide` .. there's people's own `showInTopNavigation` + `showInBottomNavigation` + `hideInWhateverOtherNavigationWhereItWouldOtherwiseShowUp` properties with true/false settings on every single content item cluttering up the editor interface ... and there's also various packages that tries to solve this by making it easier to define navigation.

Navigation rarely matches a content structure 100% 1:1 which is why they're resorting to doing this kind of stuff... I'd like us to challenge that and come up with something better than what is currently out there - and (better yet!) something we can actually say is a recommendation and a _best practice_ to follow so hopefully it will become the one single way developers _want_ to build navigation in Umbraco sites.

The Cogworks.Meganav package is a good example of someone trying to overcome the issue of defining a custom navigation structure for a site that doesn't necessarily follow the site structure ... to be used as a mega menu navigation in the frontend.

Whether this is the right solution or not is not my call - but I think we should look into this as a feature request/idea as it is definitely an area where we could improve and provide some standards instead of everyone just trying to find the silver bullet on their own.

**Comment by markadrake** [comment]
Navigation is tough even with years of experience coding websites, and years of experience implementing them into the Umbraco CMS.

Some things to consider:

- UI Patterns (dropdown, off canvas, mega menu)
- Types of Content (links, icons, custom HTML content)
- Responsiveness (conditional logic, on/off for breakpoints)
- Back Office (where to edit, content node, own section)
- Deployments (courier, umbraco cloud)

We've used Cogworks.Meganav to take care of basic navigation menus. I have some feedback from devs and clients that I'd like to share with them eventually or contribute back to the package eventually.

To add custom HTML into a meganav however is another challenge. Last website we released wanted this opportunity, so we actually added a property on 1st level content nodes to provide HTML to fill this spot in the meganav. Right now the client only uses it for images, but they can actually use Stacked Content to add any front-end component we've created in this spot.

![image](https://user-images.githubusercontent.com/713355/46567453-07ee2d00-c901-11e8-9d9e-a0a557425fc9.png)

I think it's a great idea to consider. I really like Cogworks.Meganav. I think it will be difficult due to the dynamic nature of navigations and menus - but perhaps we can start by researching implementations (easy, moderate, and complex) and together build a package for just this kind of thing?

**Comment by clausjensen** [comment]
@leekelleher about initially building the menu - I talked a bit to Sebastiaan about this and maybe it could be an idea to add in a few options for adding items to the menu, such as _Add children_ / _Add descendants [and how deep?]_. This would make it possible to simply add from _root item_ - with all descendants, 2 levels deep.

And there you go - you have your initial menu structure that you can then remove unwanted items from or edit afterwards. It would be just for the initial set-up to make it less cumbersome to add everything.

**Comment by emma-hq** [comment]
Hola folks,

This wonderful idea has been on the table for a while now. I'm going to close the issue as we've made such advancements in the UI and there have been some wonderful packages too. If there's a need to look at this area again, we can always raise another issue with the latest release in mind. 

Emma

**Comment by markadrake** [comment]
I don't think there is a one-size-fits-all solution to this, but I'd like to say since solutions do exist there may be an opportunity to expand the docs for Umbraco. 

**How do I build a top navigation for my site?**

Seems like there could be a set of recipes for common things like this added to the documentation. If there's an interest. Not many of us FEDs around here.
