### ISSUE TITLE
Restrict rights per tab in node

### ISSUE THREAD

**Issue by vonbarnekowa** [umbraco/Umbraco-CMS#3221]
Would be nice to restrict access to certain tab in a node to some users.

**Comment by nul800sebastiaan** [comment]
Hi @vonbarnekowa - so far we've resisted building in super specific permissions like this because we haven't found a really good use case for it yet. If you feel like you have the perfect use case that would benefit most users of Umbraco then we're all ears!

Until then, I will close this issue. As an alternative, you can hook into events to do this, for example: 
- https://our.umbraco.com/forum/umbraco-7/developing-umbraco-7-packages/57017-Umbraco-7-Event-RemoveHide-tab-for-User-X#comment-292141
- More documentation about this: https://our.umbraco.com/documentation/reference/events/EditorModel-Events
