### ISSUE TITLE
Internal properties on PublishedContentRequest prevents custom ContentFinderByRedirectUrl

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#3318]
Connected to this issue: https://github.com/umbraco/Umbraco-CMS/issues/3317 

I was trying to implement my own version of the ContentFinderByRedirectUrl but during this I could not set these properties on the PublishedContentRequest:

contentRequest.Cacheability
contentRequest.CacheExtensions 
contentRequest.Headers 

Since they are internal, I guess that the access to these properties would also be good when building other custom implementations in the field of redirects. Could we make them public? Is there any resone for them being internal at the moment?

---- Edit -----

I did find out that I could set these by going to the HttpContent but that does not really feel right =D

```
HttpContextBase cb = new HttpContextWrapper(HttpContext.Current);
cb.Response.Cache.SetCacheability(HttpCacheability.NoCache);
cb.Response.Cache.AppendCacheExtension("no-store, must-revalidate");
cb.Response.AppendHeader("Pragma", "no-cache");
cb.Response.AppendHeader("Expires", "0");
```

**Comment by nul800sebastiaan** [comment]
I am not sure if there's any need to keep these internal, let's see what @zpqrtbnk has to say about that though.

**Comment by nul800sebastiaan** [comment]
Thanks Stephan! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ronaldbarendse** [comment]
@zpqrtbnk What's the reason for having these properties on the `PublishedContentRequest`, instead of setting them directly using `contentRequest.RoutingContext.UmbracoContext.HttpContext.Response`? So at least the new instance and singleton access (`new HttpContextWrapper(HttpContext.Current)`) is not needed to get to the response cache/headers...

The only reason I can come up with is allowing cache options and headers to be overridden in other `IContentFinders`, but that's currently not the case within Umbraco (and because they're `internal`, can't be outside of Umbraco). Otherwise it's just a shorter way to get to the cache/headers, but does that justify the additional properties (code maintenance, allocation/memory, etc.)?

The `UmbracoModule` just copies these properties to the request here:
https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web/UmbracoModule.cs#L327-L334

**Comment by kjac** [comment]
Right... there's no reason why this issue needs to linger when it's so simple to solve. PR in #4269.
