### ISSUE TITLE
MemberService Saved event fired 3 times v7.12.3

### ISSUE THREAD

**Issue by mariojsnunes** [umbraco/Umbraco-CMS#3320]
Summary
------------
Saving a member on the backoffice will fire Saved and Saving events 3 times (I haven't tried other events).
MemberService.Saved += (sender, e) => SavedMember(sender, e, helper);

I believe this is happening in older versions as well, found forum posts back from 2015 with no solution, like this one:
https://our.umbraco.com/forum/developers/api-questions/71297-memberservice-saved-event-firing-3-times

Reproduction
------------

1- Save the member on the backoffice.
2- Have a breakpoint on the SavedMember funcion.
MemberService.Saved += (sender, e) => SavedMember(sender, e, helper);

This is my code:
```
private void SavedMember(IMemberService sender, SaveEventArgs<IMember> e, UmbracoHelper helper)
{
     foreach (IMember member in e.SavedEntities)
     {
             // Check it's a new member
            if (member.IsNewEntity())
            {
                MemberManager.SetMemberProperty(member);

               ApplicationContext.Current.Services.MemberService.Save(member, false);
           }
     }
}
```
### Specifics

Umbraco v7.12.3
I need this to set some default properties on member creation.

This is what is happening when I create a new member:
The first time it triggers the event, the function .IsNewEntity() returns true while the other 2 times it returns false.

The property is set on the first event (checked Properties[key].Value)
On the following event triggers, the property is null again (I deduce this is because the property is null on the backoffice).
Since it is null, and the event is triggered again, it overrides the first and in the end, the property is not set.

My workaround is to change `member.IsNewEntity()` to
`member.CreateDate.CompareTo(DateTime.Now.AddSeconds(5)) < 0`

This way I can set the property only when the member is created and on all 3 times the event is fired so it will not be overridden with null.
BUT it's ugly and might cause future hard-to-trace bugs.

**EDIT:** If I create a member programmatically with ApplicationContext.Services.MemberService.CreateMemberWithIdentity(), the Saved event is triggered only once.

### Expected result

I expect the event to be fired only once, if not possible:
- All 3 events should have IsNewEntity() return true, or
- The last two events must not set the property to null

### Actual result

The property is set on the first event (checked Properties[key].Value)
On the following event triggers, the property is null again.

**Comment by Shazwazza** [comment]
Creating a member is done in various phases (probably 3 ;) . There is no way to have the event fire once because that's not what is happening. The member is created, a password is then assigned (another phase) and the membership provider updates it (another phase).

> The property is set on the first event (checked Properties[key].Value)
On the following event triggers, the property is null again (I deduce this is because the property is null on the backoffice).
Since it is null, and the event is triggered again, it overrides the first and in the end, the property is not set.

I think this is the actual problem, not so much that there are multiple events. We need to understand what it is you are trying to do, would you be able to post a code snippet to show what is not working or describe further what property you are trying to set and when it is returning null again?

**Comment by mariojsnunes** [comment]
> I think this is the actual problem, not so much that there are multiple events. 

I agree.

> We need to understand what it is you are trying to do, would you be able to post a code snippet to show what is not working or describe further what property you are trying to set and when it is returning null again?

I am trying to set a property when a new member is created.

```
private void SavedMember(IMemberService sender, SaveEventArgs<IMember> e, UmbracoHelper helper)
{
     foreach (IMember member in e.SavedEntities)
     {
             // Check it's a new member
            if (member.IsNewEntity())
            {
                MemberManager.SetMemberProperty(member);

               ApplicationContext.Current.Services.MemberService.Save(member, false);
           }
     }
}

public void SetMemberProperty(IMember member) {
   member.SetValue("propertyKey", "propertyValue");
}

```
Since I only want to set the property when the member is created I validate the `member.IsNewEntity()`.
But since it returns true only on the first event trigger, the property is then overriden with null on the following 2 saved events.

Any ideas on how should I solve this or what am I doing wrong?

Thanks for the help!

**Comment by nul800sebastiaan** [comment]
@mariojsnunes I think you'll need to hook into the `Saving` event instead of the `Saved` event, that's where things seem to go wrong for you. 

I'll close this for now as it doesn't look like we have an actual bug here, if you require more help, I'd encourage you to refer to this issue in a new post on the forum at https://our.umbraco.com
