### ISSUE TITLE
Roles.GetRolesForUser(username) return null on Saved event.

### ISSUE THREAD

**Issue by mariojsnunes** [umbraco/Umbraco-CMS#3321]
Created a new member with groups set.
If I run `Roles.GetRolesForUser(username)` on the Saved event, it returns null

Reproduction
------------

- Create a new member with groups set.
- Catch the Created event.
- Run `Roles.GetRolesForUser(username)`
- The groups are not returned.

### Bug summary

`Roles.GetRolesForUser(username)` is returning empty for newly created members.

### Specifics

Umbraco v7.12.3

### Expected result

Should return the member groups.

### Actual result

No groups are returned.

**Comment by Shazwazza** [comment]
The `Created` event isn't what you think it is, here are the notes: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Services/MemberService.cs#L1364

Pretty sure this is removed in v8 (and should be deprecated in v7). It's kind of a silly event since it's only raised if the MemberService.CreateMember or MemberService.CreateMemberWithIdentity is used even though those methods are not actually necessary to save a new IMember. 

I think you just want to use the `Saved` event.

**Comment by mariojsnunes** [comment]
**Sorry, I meant the Saved event.**

I am creating a new member on the backoffice with groups set.

Then I catch the Saved event.

`MemberService.Saved += (sender, e) => SavedMember(sender, e, helper);`

```
private void SavedMember(IMemberService sender, SaveEventArgs<IMember> e, UmbracoHelper helper)
        {
            foreach (IMember member in e.SavedEntities)
            {
                // Check it's a new member
                if (member.IsNewEntity())
                {
                    System.Web.Security.Roles.GetRolesForUser(member.Username); **// Is Empty**
                }
            }
        }
```
The groups are not returned when I run `Roles.GetRolesForUser(member.Username).`

**Comment by mzajkowski** [comment]
This issue is still present in 8.9.1. Any info on potential causes? @Shazwazza
