### ISSUE TITLE
What about async methods in IFileSystem?

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#3323]
Currently I am working on a new version of the AzureBlobStorageProvider for version 8. So far I have realised the new media path segments, but still going through each method. 
I read some articles about asynchronous methods in general and as far as I got it, the phsyical file systems should benefit from asynchronism - especially _remote_ systems like Azure Blob Storage. 

Today I realised that the current _PhysicalFileSystem_ does not use async methods and the IFileSystem does not specify them. I tried to find some hints in the existing issues, but did not find much concrete about your expirience, plans or ideas.
Just issue #1774 is about some (old) code where an async method was removed, but the few comments are not very helpful. And maybe this was about an obsolete issue(?)

What do you think: Is it worth to investigate this further? Am I right that this should be in the core to do it properly? _(Looks like async / await needs to bubble up th call chain, otherwise it might get cumbersome)_

Yours
Dirk

**Comment by Shazwazza** [comment]
Umbraco internally doesn't use async unless it's within a controller. To do this would require us to create a different IFileSystem interface like IFileSystemAsync which would mean a whole lot of underlying plumbing ... but the async methods will still probably not be used in most cases since in many of the cases where IFileSystem is used, its in a non-async context.

Indeed Umbraco would benefit by having more operations done in async contexts but we can't just switch since async needs to happen from top to bottom so it would require that we make async methods for almost all Service/Repositories (which in turn use IFileSystem). Of course async would be great to use in the Service/Repositories too since we can use async Database calls as well, but again, this would be quite a substantial undertaking to do.

We haven't done this in v8 either but if we want to try going down this path, i would recommend that it start in v8 and not v7 since there will be so many changes required.

**Comment by nul800sebastiaan** [comment]
I will close this but I've added the "idea" label to indicate that while we think it's a great idea, we don't have the capacity to execute on this in the near future. The "idea" label allows us and future contributors to find the great ideas at a later time when there is time.

**Comment by JimBobSquarePants** [comment]
I'd like to vote to get this reopened. All IO operations should really be Async unless you have a really, really, really good reason not to.
