### ISSUE TITLE
Unable to find suitable version for font-awesome

### ISSUE THREAD

**Issue by janvanhelvoort** [umbraco/Umbraco-CMS#3430]
After update font-awsome to 4.7, bower can't complete. #3326 
bootstrap-social#~4.8.0 has a dependency on version 4.2 of font-awsome. 

I want to update  bootstrap-social to version 5, other depencies collide.

for now, rollback to font-awsome will solve the problem.

Reproduction
------------

Latest version of the dev7 branch, run the build.bat, run the site, the installer screen can't find multiple dependencies.

If you run: `bower install` inside `/src/Umbraco.Web.UI.Client`, you will get the error: `Unable to find suitable version for font-awesome`. If you change the version for `bootstrap-social` to `5.1.1`, bower can't install `boostrap-social` with error: `Unable to find suitable version for boostrap-social`

### Expected result

I want to install umbraco v7 local

### Actual result

The installer won't work because missing web dependencies

**Comment by dawoe** [comment]
I can confirm this issue with the bower install.

However I am able to go through the installer when I run the build script on the latests source and use the generated zip file to install Umbraco.

It seems bootstrap-social needs font-awesome 4.5 and umbraco wants 4.7.


But instead of rolling back. Maybe the bower json can be extended with this.  So font-awesome 4.7 will be used :
```
"resolutions": {
    "font-awesome": "~4.7"
  }
```

Dave

**Comment by janvanhelvoort** [comment]
Hi Dave,

I will look at it, and will update the pull-request.

Jan

**Comment by janvanhelvoort** [comment]
Hi dave,

It works, i have updated the pull request.

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3431
