### ISSUE TITLE
Change date picker property editor to use flatpickr instead of bootstrap-datetimepicker

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3439]
child of https://github.com/umbraco/Umbraco-CMS/issues/3694

In v8 we want to remove as many dependencies on bootstrap and jquery as possible. We have chosen flatpickr as the alternative for the bootstrap-datetimepicker library. We have already used flatpickr in the new scheduling dialog so you can look there for inspiration. 

The task should also include clean up of all bootstrap-datetimepicker files.

**Comment by bjarnef** [comment]
@madsrasmussen maybe we could also consider some of the options to be configurable as in this old PR for the bootstrap datepicker: https://github.com/umbraco/Umbraco-CMS/pull/984

I think flatpickr has many of the same options and also allow selecting a date range and multiple dates.

**Comment by madsrasmussen** [comment]
@bjarnef Yes, but I would like to keep the task as simple as possible for a v1. Then we can always improve with some better configuration in a later version.

**Comment by bjarnef** [comment]
@madsrasmussen sounds great!
When talking about simplicity, is there any reason why we both need a `Umbraco.Date` and `Umbraco.DateTime`? I guess these have been there since v4/v6, but isn't both storing a DateTime in database? :)
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Constants-PropertyEditors.cs#L37-L45
