### ISSUE TITLE
List views bulk actions - angular/controller updates

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3470]
_From @Shazwazza on October 29, 2018 2:56_

child of #3329
requires #3469
requires #3093

Right now the list view bulk actions call a controller endpoint one at a time. We will continue to do this in v8.

This means that for unpublish, angular will call the ContentController.PostUnpublish which currently supports passing in cultures. However angular will need to be updated to call this endpoint differently depending on if the item being unpublished is variant or invariant. If it is variant, then the cutlures need to be specified, if invariant then no cultures should be specified.

For Publish, the controller will need to be updated for it's PostUnpublishById method, but this could/should be taken care of in: #3093 (https://github.com/umbraco/Umbraco-CMS/issues/3093#issuecomment-433296767), then angular will need to be updated to call this endpoint differently depending on if the item is variant/invariant just like we'd do for the above with Unpublish.

_Copied from original issue: umbraco/Umbraco.Private#259_

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3502

This PR adds functionality to show a publish/unpublish dialog based on the selected items in the list view. It also wires up the unpublish dialog to unpublish based on the selected languages. The publish dialog doesn't do any publishing because it is waiting for two tasks to be finished first.

How to test:
* Create a list view which contains both variant and invariant nodes.
* Select some variant nodes and publish them. Make sure you see a dialog where you can select which languages to publish.
* Select some invariant nodes. Make sure you see a confirmation dialog before you can publish.
* Select a combination of variant and invariant nodes. Make sure you see a dialog where you can select which languages to publish.
* Make the same tests for unpublishing and make sure the correct languages get unpublished.

**Comment by madsrasmussen** [comment]
@RobertCopilau  Great testing!

I have pushed two updates.
* The labels are now clickable 
* Notifications + publishing status now shows messages.

Publishing isn't working. The endpoint needs to support cultures before we can do testing on that one. So right now we only need to test that the dialog opens correctly. Unpublishing should work though.

I also found another bug. The list view doesn't refresh after publish/unpublish. I will look into that.

**Comment by madsrasmussen** [comment]
@RobertCopilau I have pushed some updates to the branch. 

* The list view now updates after publish/unpublish.
* I have swapped the native browser prompt when deleting an item from the list to use an Umbraco overlay instead. It now also shows the same "info"-box as the tree delete dialog when it also deletes all languages.

**Comment by RobertCopilau** [comment]
The code looks good and it works!
Merging...
