### ISSUE TITLE
Upgrading via Nuget always changes preserveExifMetaData setting ImageProcessing.config

### ISSUE THREAD

**Issue by DanDiplo** [umbraco/Umbraco-CMS#3514]
When Upgrading Umbraco via Nuget then `/config/imageProcessor/processing.config` _always_ gets overwritten and changes the value of `preserveExifMetaData` to `true` when it was previously set to `false`. 

This has happened for every Umbraco upgrade I can think of since this setting was added in Image Processor. It happens even if I tell Nuget to not overwrite changes for any files.

Reproduction
------------

Edit `processing.config` and set the processing directive to:

`<processing preserveExifMetaData="false" metaDataMode="None" fixGamma="false" interceptAllRequests="false" allowCacheBuster="true">`

Now upgrade Umbraco via Nuget.

Check `processing.config` and you will see:

`<processing preserveExifMetaData="true" metaDataMode="None" fixGamma="false" interceptAllRequests="false" allowCacheBuster="true">`

This was also flagged in https://issues.umbraco.org/issue/U4-9763

I'd help fix this, but no idea about Nuget transforms!

**Comment by nul800sebastiaan** [comment]
I've (tentatively) set this to `up-for-grabs`. It is definitely something we want to force upon installation, but it would be nice if we could leave it unchanged for an upgrade, though I'm not sure if that will be possible.

Note, this relates to: 
- https://issues.umbraco.org/issue/U4-9333
- https://github.com/umbraco/Umbraco-CMS/pull/1667

**Comment by DanDiplo** [comment]
Probably also worth noting that the latest version of [ImageProcessor.Web.Config](https://www.nuget.org/packages/ImageProcessor.Web.Config/) now has an additional option called `metaDataMode` (added in https://www.nuget.org/packages/ImageProcessor.Web/4.9.2.19 )

This controls how Exif data is preserved. So it can be set to just preserve the copyright Exif metadata whilst stripping out the other bloat (I've seen Exif data over 1MB in size!). ie. set `metaDataMode="Copyright"` alongside `preserveExifMetaData="true"`. This would probably make a sensible default.

**Comment by Shazwazza** [comment]
Yes but I believe that setting can't be directly used by umbraco until the PR for bumping the runtime to 4.5.2 is merged in. Of course other people running 4.5.2+ can upgrade to that version but we can't ship with it until we change. Essentially that change fixes the exif preservation so it keeps the bare minimum instead of copying potentially MBs of info.

**Comment by Jeavon** [comment]
It's possible that a xdt file is created that's shipped in the Nuget package instead of the config file, this would solve the issue with Nuget upgrades. 

Once 4.5.2 is supported and the package updated although the number of people changing the defaults will be less, Umbraco upgrades will still revert changes in the config file.

@nul800sebastiaan are there already other xdt files in the Umbraco nuget package?

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
