### ISSUE TITLE
Software requirements missing

### ISSUE THREAD

**Issue by jachaines** [umbraco/Umbraco-CMS#3548]
There doesn't appear to be any documented requirements on what is needed for installing and working with the source code version of Umbraco. I wasn't aware i needed gulp, node etc

Can we please have an idiots guide.

**Comment by kristianschneider** [comment]
There is [this](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/BUILD.md) . It that sufficient or did you have something else in mind?

**Comment by jachaines** [comment]
I had already looked at that document which included a lot of useful help, however some prerequisite would have been helpful i.e. gulp, node with minimum version

**Comment by MMasey** [comment]
If looks like the issue @jachaines was having was potentially due to already having an older version of node & npm installed on his computer. Although the build script for Umbraco installs these if they don't exist it will not update them, even if they are outdated, which could cause issues with the frontend build if npm can't install the modules correclt.y

It might be worth having a defined minimum version for node and npm somewhere in the docs.
It could also be beneficial to throw a warning of something in the build script to inform the person they they need to update their global version of node or npm (and update it for them maybe?)

Including @warrenbuckley as we were talking about this at the uk fest hackathon.

**Comment by nul800sebastiaan** [comment]
FYI: all you need is the latest version of Node (v10) and which comes with a compatible version of npm.

As Mike already notes: if those don't exist on your machine already, the `build,ps1` script will download and use a local copy (won't be installed globally for your machine). 

So really.. All we should specify is: Use Visual Studio 2017 v15.3+ (which is mentioned here, but could be clearer: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING_DETAILED.md#building-umbraco-from-source-code). Additionally, it's helpful if you have Node v10 installed but this isn't a requirement.

**Comment by nul800sebastiaan** [comment]
I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by MMasey** [comment]
PR submitted #3743
