### ISSUE TITLE
package-lock.json can be updated by running npm install

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco-CMS#3553]
Due to a change in the way npm works, the package-lock.json file will be trumped by the package.json file. This means that any dependancies with a `^` before their verison will potentially get a newer version when `npm install` is run. 

This can mean that each different packages may be installed for each person.

This can be fixed by removing the carats before the version. e.g.
```
 "devDependencies": {
    "autoprefixer": "^6.5.0",
 }
```
becomes
```
 "devDependencies": {
    "autoprefixer": "6.5.0",
}
```

This may not be an actual issue, as it's strictly speaking the intended functionality of the package-lock.json.

**Comment by dawoe** [comment]
Hi Mike,

Thanks for raising the issue. I'm not a node and npm wizard myself. So I will try to get some input from HQ.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by MMasey** [comment]
Thanks Dave,

Since opening this issue, I've been doing some more research into how the package.lock actually works, and should be used. This article has a nice summary of how the `^` impacts the package being downloaded. https://bytearcher.com/articles/semver-explained-why-theres-a-caret-in-my-package-json/

Essentially, whenever someone does an `npm install`, if a version number includes a carat e.g. `^1.0.0`, it will look for the latest change that is backwards compatible and non-breaking and get that instead. It will then update the `package.json` and `package-lock.json` files to reflect the latest downloaded files. 

Ideally when this happens, the updated `package.json` and `package-lock.json` file should be commit. Obviously as people are often doing work on Umbraco and running the Build script, the libraries requested by the `package,json` will be check quite frequently, and as such, the person may commit them to the PR they are working one, which may not be ideal.

I wonder if there is a way to automate this so that once a day or something, the `npm install` script is run, and if the are any updates to the requested files, it will commit the change to the main dev branch. That way it would be easier to ensure that the latest non-breaking version of the npm packages are installed, without someone having to remove the change from there repo when working on a PR.

I'm not sure if i've explained that very well, or if it's even relevant, but figured i'd give my "2 cents" just in case.

**Comment by PeteDuncanson** [comment]
As a follow on from this (not sure if this should be a separate issue or not) I've had the build server fail due to a conflict in package-lock.json for #4871 

Looking into it some more its a issue with the lock files differing and it needs to be regenerated (see: https://docs.npmjs.com/files/package-locks#resolving-lockfile-conflicts).

However there is a package (https://www.npmjs.com/package/npm-merge-driver) we could install as part of toolchain which would automatically fix these merges for us and never again would anyone have to have any headaches like I did :)

I'd propose we add this into the build so its a fire and forget thing and one less thing other folks don't have to learn about, its just works (tm)

**Comment by nul800sebastiaan** [comment]
We've been experimenting with not having `package-lock.json` included in the repository at all for the past few months and this seems to be working well. I'll close this issue, since we no longer need to worry about it! 👍
