### ISSUE TITLE
Visual studio ESLint errors

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/Umbraco-CMS#3562]
Occasionally when building an Umbraco solution the errors list is populated with (ESLint) errors

![image](https://user-images.githubusercontent.com/6782865/48206160-a557d900-e365-11e8-9f91-37ac129fac87.png)

Is this is something, that should be fixed? As it would require add a `.eslintignore` in the root of the project excluding /umbraco/** and /umbraco_client/** directories.

The main issue with this is it is a file that a developer may wish to edit for their own project needs.

I'll do a quick PR either way :)

Matt

**Comment by nul800sebastiaan** [comment]
@madsrasmussen Maybe it's better to fix these errors though?

**Comment by madsrasmussen** [comment]
Do you have eslint installed globally? It looks like it is using a global config instead of the local one for Umbraco. I think our eslint config is very very tiny right now. I actually think we only have one rule for comma dangles :) We will add more rules as we move forward so we don't break the entire code base in one go.

**Comment by nul800sebastiaan** [comment]
Since this fix only affects VS and not the gulp setup, this seems fine to add, I'll merge.
