### ISSUE TITLE
Clarify "reuse" and "available editors" when picking property editors

### ISSUE THREAD

**Issue by jacklawry** [umbraco/Umbraco-CMS#3564]
A brief description of your feature request goes here.

Update to swap the tabs when creating a property so Reuse is the default action. 

The tabs have also been renamed to "Use existing" and "Create new" to make these options clearer.

How can you help?
-------------------------------

Pull request to be submitted shortly.

**Comment by kjac** [comment]
I'm glad I'm not the only one that's annoyed with the current default 👍

**Comment by nul800sebastiaan** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3567

**Comment by jacklawry** [comment]
Sorry @nul800sebastiaan I forgot to link to the PR!

**Comment by nul800sebastiaan** [comment]
Hi @jacklawry - I think we talked about this at the UK festival already and at the time I could not remember why this feature works the way it works. 

I've discussed this with Mads now and got some new insights: we did some actual UX testing with people who were not super familiar with Umbraco and it turns out they got very confused when they kept reusing existing datatypes. They would add the same datatype to a few document types, change the configuration of the datatype and then suddenly all of the other content items with that datatype changed too.

We understand it's a bit painful sometimes when you realize that you could have re-used some datatypes. Maybe that's a great idea for a package to refactor datatypes in use on document types. Some functionality to be able to say: look, where I've used these 4 different datatypes, just use this one.

We do really like the renaming of the tabs however: "Use existing" and "Create new", so I would encourage you to strip everything else out of this PR and leave the new names in place. Might be easier to create a clean PR for that though.

Hope that makes sense, thanks!

**Comment by jacklawry** [comment]
Hi @nul800sebastiaan Here is the PR for the text only https://github.com/umbraco/Umbraco-CMS/pull/3836 

I think that perhaps if this gets added then it would be worth user testing again as the labels were very confusing... Then this swap of the tabs could also be added?

**Comment by nul800sebastiaan** [comment]
@jacklawry The confusion was not so much the labels but people not knowing the implications of re-using existing ones. That said, there is some friction here and we'll need to look at removing that friction some other way, no idea how, but it will likely be a larger change than changing the order of tabs :-)
