### ISSUE TITLE
Granular permissions are not inherited from tree view to list view children

### ISSUE THREAD

**Issue by nicklite** [umbraco/Umbraco-CMS#3602]
Summary:
Granular permissions are not inherited from top level tree view to list view children

Steps to reproduce:
1, Created a new user group with the following settings:
 - Set "Sections" to "Content" in "Assign Access" section
 - Content start node to the "content root" node in "Assign Access" section.
 - Select a parent node that has list view children in Granular Permissions and enable "Browser node". See screen shot, I selected "Home"
 - Save new group

2, Assign a user the group and log in as the user.
3, Navigate to the parent node which has listview to display children.

Expected Results:
Displays the children with the same setting as the parent.

Actual Results:
No children appear in the list view.

Images:

![image](https://user-images.githubusercontent.com/44985698/48381280-18839580-e740-11e8-8639-a6036f22da0f.png)

**Comment by nul800sebastiaan** [comment]
Hi there @nicklite ! I'm not sure how to reproduce, if I don't have permissions to "Browse node" on the ancestors of "Artist", I do not even see "Artist" in the tree, because I'm not allowed to browse "Stories".

![3602](https://user-images.githubusercontent.com/304656/48771878-eb486180-ecc2-11e8-998c-3e483bb04bac.gif)

I am not sure what you're trying to do exactly, but I'd recommend you ask on the forum how to get it done first: https://our.umbraco.com
