### ISSUE TITLE
Build docs for v8

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3611]
For some reason v8 build scripts don't build the documentation anymore, need to port v7 Build-UmbracoDocs.ps1 as a method in v8 build.ps1.

BUT also need to rethink how it's done - do we really need to rebuild the whole solution in Debug mode just for docs?!

**Comment by zpqrtbnk** [comment]
Work in progress on issue 302 on that other tracker ;-(

**Comment by elit0451** [comment]
PR: umbraco/Umbraco-CMS#5272

Changes have been made to `build-docs.ps1` ->  this is the script only responsible for generating the API documentation of v8.

However, I've added updates to build.ps1 which will enable us to generate both C# and Angular API documentation directly through that script by calling the corresponding functions.

In order to test just add `{ Local = $local; WithDocFx = $true }`, on ln https://github.com/umbraco/Umbraco-CMS/blob/173df80e3d6a6a01da47661d3b0353f8ae12f469/build/build.ps1#L34

After that open Powershell cli from the root CMS folder and execute the following commands: 
-  `$uenv=build/build.ps1 -get`
- for the C# docs run `$uenv.PrepareCSharpDocs()`
    - you will find **csharp-docs.zip** in the _build.out_ folder
- and for Angular - `$uenv.PrepareAngularDocs()`
    - **ui-docs.zip** will be located also in _build.out_ dir
- extract the zip files, open in VS Code (for example) and fire them up ;)

**Comment by Shazwazza** [comment]
[AB#497](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/497)

**Comment by elit0451** [comment]
Testing process:

- Execute `$uenv=build/build.ps1 -get -doc` to get the environment variable and download Docfx
- for the C# docs run `$uenv.PrepareCSharpDocs()`
    - you will find **csharp-docs.zip** in the _build.out_ folder
- and for Angular - `$uenv.PrepareAngularDocs()`
    - **ui-docs.zip** will be located also in _build.out_ dir
- extract the zip files, open in VS Code (for example) and fire them up ;)
