### ISSUE TITLE
Handling missing values and no fallback

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3662]
When there is "no value" we want to fall back to something else - but how can you indicate that a value is "intentionally empty" ie "no value" actually means "no value, please don't fallback"?

child of https://github.com/umbraco/Umbraco-CMS/issues/3661

**Comment by zpqrtbnk** [comment]
It *is* partially done already. I think each property value converter can implement `HasValue` so that... you can ask the converter whether a value is actually a value or not. So a converter may decide to report a null value as a valid value. Basically... now the burden is on the converters. If we're OK with this, then we prob only need to verify and close.
