### ISSUE TITLE
Move navigation/traversal/methods of IPublishedContent to a IPublishedContentService

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3667]
We need to cleanup navigating the tree with `IPublishedContent`. The model `IPublishedContent` should be as POCO as we can make it so that the logic for traversing/navigating is done via a new service.

This is an important step for unit testing and for implementing IPublishedContent and what will be the new service. 

We will still have methods on IPublishedContent to traversal for better backwards compatibility for and for easier API usage. These methods will be extension methods that will need to use a service locator to resolve the underling service. So things like `content.Children()` will still be possible.

And while we're at it, we should clarify the `Root()` vs. `Site()` vs. whatever other navigation methods we may want to support.

child of https://github.com/umbraco/Umbraco-CMS/issues/3661

**Comment by zpqrtbnk** [comment]
Note: there was a `temp8-3667-move-navigation-methodes-from-ipublishedcontent` branch in progress, which I have deleted, as changed in #5170 already do most of what it did, ie migrate from properties (`.Children`, `.Parent`...) to methods (`.Children()`, `.Parent()`...).

And then, Working on this as part of #5170 - at the moment, *everything* related to navigation is done via extension methods, but `Parent()` and `Children()`. Now would be the right time to move these to extension methods too, but I am having doubts.

I am not entirely sure what is the value of moving `Parent()` and `Children()` out of `IPublishedContent`, considering that in most cases, the `IPublishedContent` instance owns what is needed to navigate to parent and children. To be somewhat efficient, that navigation depends on the cache implementation (today, NuCache), because each cache may manage the tree differently.

So, any `Children()` extension method would need to invoke the current `IPublishedSnapshotService`, asking that service to get the children.

And the service (at least for NuCache) would end up using some internal stuff in its `PublishedContent` implementation. So basically: the `PublishedContent` still contains everything, because that is the efficient way to do it, but instead of getting it directly we go through various steps.

Thoughts?

**Comment by Shazwazza** [comment]
I think the main point of this was that IPublishedContent could just be a POCO, it is the separation of model vs service instead of the model being the service. I think we are too far gone with v8 to consider doing this properly. We still need to limit the breaking changes of #5170 once it is where we want it to be - we can't go 1000% percent here and just change everything.

**Comment by zpqrtbnk** [comment]
For #5170 there's a PR already I a really would like to *not* change more things, there's already a lot there.

For `IPublishedContent` being POCO ... I would like to keep it out of #5170, plus it would require some thinking (see my post above) - suggesting, if everyone's OK, that this goes back to long-term backlog.

**Comment by Shazwazza** [comment]
Yup i agree, will have to review the other bits this week

**Comment by Shazwazza** [comment]
I'm going to close this issue then and tag with idea for later
