### ISSUE TITLE
Pass on query string

### ISSUE THREAD

**Issue by FabianoAgosti** [umbraco/Umbraco-CMS#3725]
Hello, 

Is it possible to pass on query string to the built-in URL tracking functionality in Umbraco? We have a client that has renamed some nodes and these nodes also have paramater string in the URL, especially when an user comes from an ad (gclid paramater passed in the URL). When a redirect happen from the old URL to the new URL, those paramaters are not passed across. Is there a solution for this?

Regards, 
Fabiano

**Comment by nul800sebastiaan** [comment]
Currently this is not possible, at the moment you would have to manually create redirect rules in your web.config I'm afraid. But it's a good feature request, I never thought of that before!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
I just realized there's a previous issue created for this, I'll close this one in favor of the existing feature request, thanks!
