### ISSUE TITLE
UmbracoVirtualNodeRouteHandler - does not return configured 404 page

### ISSUE THREAD

**Issue by Andrei-** [umbraco/Umbraco-CMS#3726]
Trying to use an instance of UmbracoVirtualNodeRouteHandler to handle some virtual urls, similar to a webshop scenario where you have url's like /products/id
So I inherit UmbracoVirtualNodeRouteHandler  and override the specific method "FindContent()" and it works fine when the product is found and I return a publishedcontent result.

But when I try with a wrong id, like /products/[non-existing-id-here], then I don't return any publishedcontent and I expect to get the 404 page (configured under settings) as result. 

I can see in umbraco source code that if no content is returned by FindContent(), then the base class will use NotFoundHandler which does not check/return a 404 page

Am I wrong to expect my 404 page here when id is not resolved? Or am I missing something?
(I'm on v7.12.2)

**Comment by dawoe** [comment]
Hi @Andrei- 

How did you configure your 404 page ? Can you give some details about that. So we have good steps when we try to reproduce this issue.

Dave

**Comment by Andrei-** [comment]
Hi Dave,
It's just standard 404 page configuration under /config/umbracoSettings.config with the guid of an umbraco node:
![image](https://user-images.githubusercontent.com/6005180/48858890-e10a8e00-edbc-11e8-9165-9e253af04872.png)

**Comment by Andrei-** [comment]
ups, closed by mistake

**Comment by dawoe** [comment]
Hi @Andrei- 

Using the config for 404 is actually obsolete.
https://our.umbraco.com/Documentation/Reference/Config/404handlers/

Maybe you can try to implement a content finder for that like is recommended : https://our.umbraco.com/Documentation/Reference/routing/request-pipeline/IContentFinder

If it than still does not work we can dig deeper to see what the issue is

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by Andrei-** [comment]
Hi Dave,

Well, that's a bit of a surprise, I can't find any documentation about 404 config in umbracoSettings being obsolete. The link you pasted says that custom 404 handlers are obsolete, but I don't have any custom 404 handlers. Doesn't say anything about umbracoSettings for 404 page.

Anyway, this sounds like a step backwards, it felt pretty sweet to just provide an id in configs and have the 404 page resolved. Now we have to implement custom code to solve this problem? And the custom code would probably do the same - redirect to that 404 node? Hmm..

**Comment by dawoe** [comment]
You are correct...the documentation is about the handlers. They are obsolete.

Will try to reproduce and will get back to you on how to solve or see it as bug

**Comment by dawoe** [comment]
Hi @Andrei- 

I did some investigation and I found a workaround for you. The issue is that when you use virtual or custom routes you entirely bypass the umbraco request pipeline. So it does not execute the code for getting the 404 page configured in the settings.

So you can use this code in your routehandler for when the id not matches. It will get the content page based on the id configured in settings.
```
 if (idNotFound)
        {
            var errorPages = UmbracoConfig.For.UmbracoSettings().Content.Error404Collection.ToList();

            if (errorPages.Any())
            {
                var page404 = umbracoContext.ContentCache.GetById(errorPages.First().ContentKey);

                if (page404 != null)
                {
                    return page404;
                }

                
            }

            return null;
        }

```

Then in your controller that handles your virtual route you can do this : 

```
if (model.Content.DocumentTypeAlias == "errorPageDocTypeAlias")
        {
            Response.StatusCode = 404;
            return this.View("ErrorPageTemplate", model);
        }   
```

This will solve your problem. But I am going to see if somebody from HQ can see if it is a bug or expected behavior.

@Shazwazza @zpqrtbnk can you provide some input

Dave

**Comment by Andrei-** [comment]
Hi Dave, 

Great, thank you, your last comment helped nicely, I got it working. I guess the missing piece in my puzzle was how to serve the 404 page in my virtual node handler. 
And I don't have a custom controller for this, I use the default umbraco controller, called RenderMvc (I think). 
So in case I don't find a 'product', I return 404 page as content and change the route action to match 404 page template. As for the status code, that can be also set in the virtual handler by overriding another method (PreparePublishedContentRequest) which allows tampering with the PublishedContentRequest object.

My problem is solved, but I'm not sure this is the expected behavior for the UmbracoVirtualNodeRouteHandler when content is not resolved.

**Comment by nul800sebastiaan** [comment]
This issue has been open for a while now and v8 came out since then. If this is still an issue on v8, make sure to open a new issue for it so it can be looked at!
