### ISSUE TITLE
When Picking Compositions for a Document Type, show the folder groupings

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3740]
> If you have hundreds of compositions, and you have organised them into meaningful folders, it would be good when you are picking those compositions on a document type, to be able to see those folders... (currently using colours!)

Originally from @marcemarc https://issues.umbraco.org/issue/U4-11274

Would love to see this.

**Comment by kjac** [comment]
This is a really good idea. But given the complexity of compositions (i.e. avoid circular references, can't choose existing compositions etc.), it's not a particular good fit with the existing tree components.

Maybe a means to mend this would be to add a path below the doctype name - along the lines of this?

![image](https://user-images.githubusercontent.com/7405322/48900995-4c536f00-ee54-11e8-8753-a5fae0bbe176.png)

I'm sure I could be persuaded to fix that up 😄

**Comment by skttl** [comment]
Maybe have them divided into sections by folder, then :)

Right now, they are sorted alphabetically, which makes compositions (and other foldered types) scattered all over the list, depending on their names.

**Comment by kjac** [comment]
I understand what you're getting at. But I'm pretty sure that for the vast majority of the installs out there, it'd be much easier to find the applicable doctypes when they're sorted alphabetically instead of grouped by some folder structure. On a global scale I assume having so many doctypes is an edge case .

**Comment by marcemarc** [comment]
@kjac The idea follows from taking a more atomic approach to document type design, in the move away from inherited document types, towards compositions. To get the real benefits of compositions you break them down into smaller atoms and molecules to compose your document type organisms - but the backoffice 'curating' experience of compositions is very simplistic. (I use pink, and the fragment icon for compositions to make them easier to locate in this huge list). Because the Document Types now have a tree, that allow for the creating of folders, to organise the different types of document types, it sort of makes sense when you go to pick from these items, to have the same experience as when viewing this tree, take advantage of your organising folders (not nested doc types - just folders)

So original issue is just related to try and make the experience of using compositions a favorable one, it is the recommended approach, but there are lots of little ways we could make using compositions better...

![image](https://user-images.githubusercontent.com/260802/48904698-1a8fd780-ee57-11e8-87f3-2c3913232982.png)

**Comment by kjac** [comment]
@marcemarc I totally get both the approach and the idea and I'm not at all opposed either. 

Just remember that there's also a UX downside to having a tree: When editing the compositions, how can I see which ones are currently selected, if they're hidden inside closed folders... Do we need a list of "currently selected compositions" on top of the tree? 

If so, are we really making things simpler in the first place?

But if we keep the current list, shouldn't we be adding that list of "currently selected compositions" anyway, to aid the overview of those who have a gazillion "molecule" doctypes?

And so on, and so on 🤔 

Again - I'm definitively not against having a tree for selection. It's a very appealing thought. I simply wonder if we can do something equally effective with less effort - specially when we also have a search field available in the dialog.

**Comment by marcemarc** [comment]
@kjac yes, tree may not be the best solution, as devs we often express a solution rather than the problem.

So problem is really: 
a) distinguishing compositions from document types, when picking them to compose a document type
b) easily seeing which compositions have been selected for a document type, to enable you to remove
and it feels like the problem kicks in when you have to scroll the existing dialog...

the existing folders might feel best/obvious for a) but lousy for b) - perhaps it's more analogous to a 'content picker experience', where you can pick items, but you don't have to open the picker again to see which items have been picked

**Comment by kjac** [comment]
@marcemarc yes and yes. Provided we:

1. Somehow find a way to communicate the complications with existing compositions, circular dependencies and inheritance in the content type picker (i.e. why some content types are unselectable).

2. Find some place to display the currently active compositions. Unless we show them in the first dialog, and then spawn a second dialog to pick the additional compositions. Which is a bit... ergh?

Maybe I just have a problem killing my darlings on this one 😲 but as a fix of lesser magnitude than where this seems to be headed, this might work? 

![image](https://user-images.githubusercontent.com/7405322/48922851-c7934000-eea9-11e8-952f-94f985e89421.png)

Obviously the dialog would scroll to near infinity in your case with the items growing in height. But again, there is a search bar *right* there.

**Comment by kjac** [comment]
@marcemarc let me see if I understand you correctly. You're thinking:

1. List the currently picked compositions in the first dialog (slide-out-panel, call it what you want 😄) with a "Remove" option for each and an "Add" button to add more compositions. 
2. The "Add" button triggers a new dialog with the list of applicable compositions and a filter option to narrow down the list of compositions.
3. Bonus points for making the filter option span the folder names as well.

**Comment by skttl** [comment]
Yes, compositions is a folder. In this have a structure like

- Document Types (the tree)
  - Compositions
  - Grid editor items
    - Forside

Where I have my compositions in the `Compositions` folder, grid editors in `Grid editor items`, specific frontpage grid editor items in `Forside`, and then all the rest in the root of Document Types.

**Comment by kjac** [comment]
@marcemarc what's your take on @skttl's suggestion?

**Comment by marcemarc** [comment]
@kjac it's definitely an improvement!

If we consider the two journeys and the problems...
a) we can find easily any 'compositions' folder that contains the compositions that someone might have to pick, if no folders exist the fallback is the same as what we have
b) At first it doesn't necessarily seem like an improvement on easily seeing which compositions are picked... however if someone is using folders for 'compositions/molecules' then they'll all be in the same place, so yes it will be an improvement :-) 

if I type in the search filter the name of my foldername... will it filter to that folder's contents?

Only niche, thought is if someone goes 3 or 4 folders deep... it will kind of scale still, but also 'edge case'

Second thought is if HQ feel like the interaction isn't in keeping with the rest of the backoffice - and therefore the two step slidey out panel approach is more consistent UX - but it could be argued, for now, replacing what we have with this, is a good step forwards, and the original method of picking them 'isn't' necessarily an example of a consistent UX experience either?...

**Comment by kjac** [comment]
It's definitively doable:

![compositions-grouping-demo-1](https://user-images.githubusercontent.com/7405322/48984661-e8080800-f0fe-11e8-8c07-dd801a0cc6b6.gif)

Before I start ironing out all the kinks, maybe @nul800sebastiaan should have a look at the proposed solution?

**Comment by nul800sebastiaan** [comment]
Thanks, good discussion so far! I'll need to gather some feedback from HQ before you move on indeed. We'll get back to you!

**Comment by nul800sebastiaan** [comment]
@kjac Reviewed, the proposed solution is good! 👍

**Comment by kjac** [comment]
@nul800sebastiaan awesome! I'll dig out my PoC branch and finish it ... that's one more PR for the Christmas calendar secured 😁

**Comment by skttl** [comment]
![alt text](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif "yay")

**Comment by kjac** [comment]
PR in #3900
