### ISSUE TITLE
Performance testing of invariant/variant switching

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3741]
Need to perform a "manual test" of switching between variant/invariant for a document type when there's a lot of content of that document type.

We do not need exact numbers for this test. It is more a matter of knowing whether we have anything to be concerned about.

Need to test in sites with 1000, 10,000, 20,000, 50,000 nodes of the type that we're switching from variant to invariant and the other way around.

**Comment by RobertCopilau** [comment]
Have an issue when switching after upgrading to latest Umbraco nightly.
If I switch the doc type from var to invar and back to var, the properties that were var, become invar in the second language in the editor but they are still var in the doc type.

This might be because when I upgraded to latest version of Umbraco, my whole setup kinda broke, can't delete nodes, getting timeouts when saving a doc type but the changes I did still propagate after the timeout.
I will try again on a brand new solution and see if the issue persists.
