### ISSUE TITLE
Make Examine loosely coupled

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#3780]
Currently both the Core and the Web projects reference Examine directly. Ideally these would reference something like a ISearchManager  and/or ISearchService. Then all functionality directly dealing with Examine would happen through these interfaces. Things like UmbracoTreeSearcher should then become something like IUmbracoTreeSearcher with an ExamineUmbracoTreeSearcher implementation.

This would allow for Examine to be more easily swapped out to say [Elastic](https://24days.in/umbraco-cms/2017/elasticating-examine/), Azure Search, Solr etc. Making the search system pluggable would have benefits on multi-server environments. As well as improving start up time on new instances.

There are a few TODOs already in the code alluding to this https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web/Components/DatabaseServerRegistrarAndMessengerComponent.cs#L36

Realise this might not be a massive priority, but it'd be a breaking change so if missed in v8 it will be v9 before we could do anything about this

**Comment by Shazwazza** [comment]
Yes, i have my own fork that does much of this and i have a prototype with Examine and Umbraco running against Azure Search. That said it is quite a huge amount of work due to maintaining compatibility. 

I am working on the v8 + Examine integration now and I plan on making this happen but this will probably not become a reality for v7 at this stage.

I'll close this now since it's part of the work I'm doing now.

**Comment by Shazwazza** [comment]
Also note - Examine IS an abstraction, it is extremely hard to make a search service that supports all of the aspects of search we need without a larger abstraction like Examine. 

There is already ISearchableTree in v7 which you can plug and replace to change the back office search (this is not list view search since that is database driven at the moment).

**Comment by Shazwazza** [comment]
The LuceneIndexer is tightly coupled but it's based off of IIndexer, the problem with Umbraco is that it is coupled to the LuceneIndexer not the IIndexer or a similar abstraction.

Parts of Umbraco might still be coupled to Lucene Syntax (but maybe not, well see) but Examine providers for Azure Search and Elastic Search can 'just work' with that syntax which means people can still use Examine's FluentApi (which is an abstraction). It could be possible to use another query syntax as well if you implemented the abstraction in a different way but I think that the majority of cases would either use Azure Search or Elastic Search or Solr which are all Lucene based anyways, but if people really wanted to they could implement something. 

My prototype was based on a WIP in v7:  https://github.com/Shazwazza/Umbraco-CMS/tree/azure-search and based on https://github.com/Shazwazza/Examine/tree/azure-search , keep in mind this was just proof of concept but it works.

Examine changes and v8 stuff is being done here: https://github.com/umbraco/Umbraco-CMS/pull/3760, https://github.com/Shazwazza/Examine/tree/v1.0

**Comment by mortenbock** [comment]
@Shazwazza I posted some thoughts on Our before finding this issue. 

https://our.umbraco.com/forum/contributing-to-umbraco-cms//94836-provider-model-for-search-and-indexing

Is there a way to help on this, or maybe to start implementing an early Elasticsearch provider in order to give feedback on the interface?
