### ISSUE TITLE
Disabling URL tracker also disables redirects

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#3802]
The built-in automatic redirects can be disabled (using the 'Disable URL tracker' button that updates `web.routing@disableRedirectUrlTracking` value in umbracoSettings.config). This can come in handly when you want to change some URLs without creating automatic redirects. But while the URL tracking is disabled, the existing redirects aren't redirected anymore (and will return 404s).

Also, the `RedirectUrlManagement` section/dashboard is visible (by default) to all users that have access to the content section, so an editor could quite easily disable all redirects (which is a SEO nightmare). The existing redirects are greyed out, but still visible, so you'd expect they're still working. Managing the existing redirects also isn't possible when the URL tracking is disabled, so deleting them after disabling is not possible. Besides all this, the AppPool recycles after enabling/disabling, as the umbracoSettings.config is edited...

Reproduction
------------

### Specifics
Umbraco 7.12.4 (but probably since the introduction of the URL tracking)

### Steps to reproduce
* Add some automatic redirect by changing content names or moving content in the tree: automatic redirects should be added and are working.
* Disable the URL tracker (using the back-office button or `disableRedirectUrlTracking` setting).
* Revisit any of the original URLs (keep in mind browsers may cache permanent redirects): instead of redirecting, you get a 404 error.

### Expected result
The existing redirects should still work while the tracking (e.g. automatically adding new redirects) is disabled.

### Actual result
No redirect happening, untill URL tracking is enabled again.

**Comment by nul800sebastiaan** [comment]
Yes, when you disable the URL Tracker it does exactly what it says: it disables all of it. But sure, the dashboard could do with a good UX update. 

Only admins can use the Disable button so that is not a concern (this gets checked server-side in `ToggleUrlTracker`).

We're working towards a solution where admins and possibly editors can remove redirects on nodes themselves (make sure to chime in with your SEO nightmares here: https://github.com/umbraco/Umbraco-CMS/pull/2511) and that will be the solution for the problems you mention in this issue.

And make sure to read more about this in @marcemarc  great blog post: http://tooorangey.co.uk/posts/301-redirection-in-umbraco-it-s-a-rum-do/

For now, I'll close this issue.
