### ISSUE TITLE
Media - Sort by media type and name

### ISSUE THREAD

**Issue by skidmow** [umbraco/Umbraco-CMS#3865]
It would be a great feature if we could sort media items by media type (e.g. Folder, Image etc.) and node name, where media type takes priority. This is a logical structure that many are used to from applications like Windows Explorer.

From my experience policing the usage of the media folder for large websites is very difficult. When you have many editors, they will rarely use folder structures that have been created for them and will dump everything at the root of media. Sometimes this is because they can't find the folder they need as it's hidden half way down a scroll of 500+ items, so they just create at root level.

If you reactively try to create/sort folders to organise this, it is difficult to sort the media to ensure the folders are at the top. The result of this is that the media section often becomes neglected where nothing is organised and there are many duplicate items.

**Comment by nul800sebastiaan** [comment]
@skidmow  Maybe I'm misunderstanding your request but the grid view of the media list view does exactly that?

![image](https://user-images.githubusercontent.com/304656/50083651-bc0b0e80-01f4-11e9-844e-05a307b821c5.png)

However, I've just noticed that the default list view we create has the grid view as the second choice, the default is a list which is a little less organized. Could be good to change the default to be a grid view

![image](https://user-images.githubusercontent.com/304656/50083729-eeb50700-01f4-11e9-999a-a882444ea77b.png)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by skidmow** [comment]
@nul800sebastiaan This is interesting as I'd never actually used this grid view. It's definitely a good workaround if we can make it the default view, however I still don't think it sorts (pardon the pun) the actual sorting issue. The tree view is still visible on the left hand side and whether preferable or not, users will use it to look for media items. They could browse that list and struggle to find what they want as it is not easily sorted. You could argue that this would be a user education issue, rather than system, but the tree has been there forever and we are creatures of habit.

**Comment by nul800sebastiaan** [comment]
Agreed, for now, we're not going to easily solve that issue. At the moment you could write your own saving handler that does an sort as soon as you add something new, then you can implement any sorting rules you want yourself.

In v8, we're anticipating a larger overhaul of the media section in which issues like this will also get focus.

**Comment by kjac** [comment]
PR in #3946

**Comment by nul800sebastiaan** [comment]
@skidmow As noted in 
https://github.com/umbraco/Umbraco-CMS/pull/3946 - the functionality I intended to have is already implemented that way so we won't change anything for now. As for the tree issue, that's on our list for a grand redesign in v8 @skidmow - thanks for the suggestions!
