### ISSUE TITLE
Close infinite editors with the esc key

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3895]

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3896

The PR implements a global way to close infinite editors with the ESC key so each infinite editor doesn't have to do the implementation themselves. This also means that it requires a "close" callback function on the infinite editor for this to work. We have to do it this way so we make sure that if any logic has to be run when an infinite editor is closed still works.

How to test:
* Open a couple of infinite editors (Ex. add a property to a doctype)
* Make sure you can close them using the "Esc" key.

**Comment by madsrasmussen** [comment]
I am closing this PR again as it is not the correct solution. We will have to control the shortcut from within each infinite editor so we are sure that all logic that needs to be run is run.

It can probably be solved the same way as with any other shortcut in infinite editors just to bind the keyboard shortcut to the close button by using the "shortcut" attribute and bind it to "esc".

**Comment by elit0451** [comment]
Shortcuts to the close buttons on infinite editors are being added. PR: https://github.com/umbraco/Umbraco-CMS/pull/3933

Remark!
After closing an editor that isn't the first one opened, the 'esc' shortcuts for the rest of the editors don't seem to work! Suggestions will be appreciated!

**Comment by RobertCopilau** [comment]
@elit0451, it turns out that we have to rebind the keyboard shortcuts after the animation is done upon closing the editor with the esc key.
The reason is that the editor is not removed until the animation is done.

I found out that a  0 ms timeout around `rebindKeyboardShortcuts();` does the trick.

Also, found out that the esc shortcut does not work on media picker editor - a quick inspection on the close button showed me that there is no shortcut added.

**Comment by elit0451** [comment]
Changes added  👍
