### ISSUE TITLE
Audit entry is incorrect when scheduled publish is cancelled

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#3913]
If publishing is cancelled in an event handler, the audit trail on the info tab still displays a 'Save and Publish performed by user' message, despite the publish not occurring.

Happening on version 7.12.1

Reproduction
------------
### Steps to reproduce

 - add an event handler for the ContentService.Publishing event
 - in that handler, cancel the publish:

``` csharp
public class BeforePublishEventHandler : ApplicationEventHandler
{
    protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext context)
    {
        ContentService.Publishing += ContentService_Publishing;
    }

    private static void ContentService_Publishing(IPublishingStrategy sender, PublishEventArgs<IContent> e)
    {
        e.Cancel = true;
    }
}
```

- schedule a node to publish, or save and publish 
- wait for publish time to pass
- check info tab 

### Expected result

Audit trail should have a new entry describing the scheduled publish failure

### Actual result

Audit trail has a new entry 'Save and Publish performed by user'. When the publish is called from the Save and Publish button, a notification is displayed with an appropriate message, but the audit trail is not accurate.

**Comment by kjac** [comment]
I have been digging into this and I can reproduce it. Question is what to do about it.

It's ultimately the same code  (`ContentService.SaveAndPublishDo`) that publishes content both from the UI and the scheduler, and `ContentService` is not aware of the context it's being executed from (nor should it be).

Ideally the audit trail should contain context specific messages - *Save and Publish performed by user* for publishing triggered by the UI and *Save and Publish performed by scheduler* for publishing triggered by the scheduler. And of course likewise for failed/cancelled publishing. 

The problem then is making `ContentService.SaveAndPublishDo` aware of the executing context to log the correct audit trail events, without adding a contextual dependency in `ContentService`. The only way to do that is by parameter, which ultimately introduces a breaking change in `IContentService`.

Alternatively the scheduler can do the audit trail logging, but then we'll end up with double logging because `ContentService.SaveAndPublishDo` will still add the current audit trail events.

@nul800sebastiaan maybe this is one for HQ to decide upon?

**Comment by kjac** [comment]
@dawoe in all fairness I also see it as *Save performed by user*. The issue still stands, though; the publishing was cancelled but all the the audit log says is "I saved your content and it went well".

**Comment by nathanwoulfe** [comment]
@dawoe @kjac I'll check against latest today. 

For clarity - I'm seeing the save message in the audit after scheduling, then the save and publish after the scheduled attempt. I'd expect that if successful since the scheduler explicitly calls SaveAndPublishWithStatus, although it might be more appropriate for the scheduler to only publish, not save, as there may be pending changes made between scheduling and publishing. 

Regardless, will check against latest.

**Comment by Shazwazza** [comment]
v8's audit trail messaging and some of the internals of how it works have already been changed in v8. Please have a look if you get some time. There are no more messages that end with 'performed by user'
