### ISSUE TITLE
Layout for install local package needs some adjustments

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3961]
The layout of the "install local package" page needs some adjustments, when comparing to the layout in v7.

![image](https://user-images.githubusercontent.com/2919859/50738818-6664c900-11d8-11e9-9570-bcdfadccb1d4.png)

Furthermore I think it would be great to make the entire drag area clickable and not just the link inside this area. This is also valid for the media/image cropper upload.

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef ! As it turns out this is already fixed in a different branch that we're working on this week, I didn't know, sorry!

I'll close this one and the PR, thanks very much for the help!

We might get back to the part about the dragover if that doesn't work yet, not sure about that one at the moment.

**Comment by bjarnef** [comment]
@nul800sebastiaan can you check if the "dragover" class works in the other branch?
