### ISSUE TITLE
Test v7-v8 Migrations

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3973]
Test that it is possible to migrate from 7.12 (or 7.13... latest released) to 8 without problems.

**Comment by JoseMarcenaro** [comment]
In my case it's not working - database upgrade from 7.12.4 (latest release) to 8.0.0-alpha.58 fails with message:

> The database failed to upgrade. ERROR: The database configuration failed with the following message: Object reference not set to an instance of an object. Please check log file for additional information (can be found in '/App_Data/Logs/UmbracoTraceLog.txt')

I'm using the currently latest commit in branch temp8 (436fa261f by Stephan today). 
Logs are attached: [Logs.zip](https://github.com/umbraco/Umbraco-CMS/files/2734569/Logs.zip)

**Comment by JoseMarcenaro** [comment]
Hi Stephan - thanks for the update.  
I just tried it with your last commit to temp8, and it goes much farther.

But it fails in this code (KeyValueService.cs, method GetValue(string key)

            EnsureInitialized();

            using (var scope = _scopeProvider.CreateScope())
            {
                var sql = scope.SqlContext.Sql().Select<KeyValueDto>().From<KeyValueDto>().Where<KeyValueDto>(x => x.Key == key);
                var dto = scope.Database.Fetch<KeyValueDto>(sql).FirstOrDefault();
                scope.Complete();
                return dto?.Value;
            }

I extracted the SQL statement and tried it on SSMS, and this is what fails:

            SELECT [umbracoKeyValue].[key] AS [Key], [umbracoKeyValue].[value] AS [Value], [umbracoKeyValue].[updated] AS [Updated]
            FROM [umbracoKeyValue]
            WHERE (([umbracoKeyValue].[key] = 'Umbraco.Core.Upgrader.State+Umbraco.Core'))`

with this error:
`Invalid object name 'umbracoKeyValue'.`

That is because there is no 'umbracoKeyValue' table in my v7.12.4 database.

If this is only a matter of upgrading to a later v7 release, I'll be happy to do that. 
But let me know if I can add any information to help you guys move forward with the migration.

Thanks for all your great work!

**Comment by clausjensen** [comment]
Closing this task as we have tested and are aware migrations do not currently work and needs more work done.

**Comment by FyinInc** [comment]
@clausjensen any ETA?

**Comment by clausjensen** [comment]
@FyinInc unfortunately no ETA yet. There won't be a beta for gold partners, as when we have something ready and working, it will simply be available to everyone.
