### ISSUE TITLE
v8 allow thirdparty trees to be grouped

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#4088]
Might depend a bit on how Trees are loaded in v8 (#3236)

At the moment if you add a new tree to a section it is put in a 'Third Party' group within the section, While this makes sense from an umbraco point of view (it's thirdparty code) it might not for an editor'.  e.g The functionality might just be part of the site they got delivered - it's not 3rd Party its' part of their site.

so for example i should be able to add a new tree to the settings group in the setting section ? 
or create a new group name if desired ?

Also allowing third party trees to go into named groups would allow for new groupings for apps, possibly removing the need for extra sections in some circumstances. ?

**Comment by nul800sebastiaan** [comment]
Thanks @KevinJump - needs some discussion at HQ, I'll get back to you!

**Comment by nul800sebastiaan** [comment]
Whoop! All good, fully support the fact that there should be "Settings", "Templating", "Third party" (for people who don't care about being in that area, but also "uSync" (random example.. 😉), "Translation manager", "My crazy plugin", etc.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by KevinJump** [comment]
Hi, I just went to look at this, but I think it's already done.

It looks like it was in this commit ad026e25d71218a624a356ea06d8bda35394bf68 by @zpqrtbnk 👍 

I've checked and you can add a custom tree group to a non-core tree control 

so I think this can be closed?
