### ISSUE TITLE
Replacing the ILogger implementation

### ISSUE THREAD

**Issue by mortenbock** [umbraco/Umbraco-CMS#4169]
Is there a reason that the logger resolver does not allow replacing?

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Logging/LoggerResolver.cs#L17

The method is there, but it is internal.

I would like to make my own ILogger implementation.

**Comment by zpqrtbnk** [comment]
The `ILogger` implementation cannot be replaced through the `LoggerResolver` `SetLogger` method because the logger is created and registered early in the boot process. The logger is one of the few things that are registered and used so early, that even in v8 it cannot be replaced via the traditional "composition" process.

In order to replace the logger, one has to override the *boot manager* ie create a class inheriting from `WebBootManager`, and override `InitializerLoggerResolver` with something looking like:
```
protected override void InitializeLoggerResolver()
{
  LoggerResolver.Current = new LoggerResolver(new MyOwnLoggerImplementation())
  {
    CanResolveBeforeFrozen = true
  }
}
```
And then one has to replace the global.asax class (which is `UmbracoApplication` by default) with a class inheriting from `UmbracoApplication` and overriding the boot manager:
```
protected override IBootManager GetBootManager()
{
  return new MyBootManager(this);
}
```
Yes, this is convoluted. Don't we all love v7? And, to make things worse, it won't even work. Problem is, `CanResolveBeforeFrozen` is internal. And required, here. 

Conclusion: at the moment I don't think one can replace the logger in v7.

If we want to enable this, we should modify `LoggerResolver` so it sets `CanResolveBeforeFrozen` in its constructor, and then this should work:
```
protected override void InitializeLoggerResolver()
{
  LoggerResolver.Current = new LoggerResolver(new MyOwnLoggerImplementation());
}
```

Making sense?

**Comment by mortenbock** [comment]
Thanks for the feedback Stephan.

It does make sense. I just did an experiment, and I can set the `CanResolveBeforeFrozen ` via reflection, so by using the BootManager approach, I am no longer getting any log files on disk, and can log where I wish.

It solves my current usecase, but it would probably be great if the ILogger could be replaced without reflection in the future.

**Comment by nul800sebastiaan** [comment]
Replacing the logger will be possible in v8, for v7 for your use cases it seems like just updating the log4net config with your own appenders should be enough. Maybe there's a really good usecase but for now we'll spend our efforts elsewhere instead! :-)

**Comment by mortenbock** [comment]
By "future" I did mean v8 :) Good to hear that it is already solved there.
