### ISSUE TITLE
V8 - Consistent naming accross property editors

### ISSUE THREAD

**Issue by mclausen** [umbraco/Umbraco-CMS#4182]
I ran across some inconsistent naming for property editors.

![capture](https://user-images.githubusercontent.com/3600782/51530968-6e5d7380-1e3c-11e9-8502-6abfa1ce4b1d.PNG)

**Expectation**
I expect all corresponding property editors to have the same name regardless whether they are under different sections.

**Comment by kjac** [comment]
@mclausen you're seeing this because you have an existing Checkbox datatype named "True/false". It's probably the default Checkbox datatype that was created when you installed Umbraco.

In 7.12 the name was changed to "Checkbox", and thus it looks like this by default on new installs:

![image](https://user-images.githubusercontent.com/7405322/51537390-b1284700-1e4e-11e9-8fb5-656add4e0a5e.png)

**Comment by nul800sebastiaan** [comment]
Kenn is correct, it will be .. "eventually consistent" ;-)
