### ISSUE TITLE
Security - Sensitive Information Returned to Client -  Doesn't seem possible to disable Template Rendering errors to be returned to the client

### ISSUE THREAD

**Issue by camelofcode** [umbraco/Umbraco-CMS#4231]
For security it is desirable not to return any errors containing strack traces etc. to the client, as these can be used by attackers for information gathering.

We are running an Umbraco site and have proper error handling configured so all thrown errors are caught and logged, with the user only shown an error page with no sensitive information.

However, it seems that if an exception occurs during template rendering, the exception is written out as if it were the template. See line 64 here: https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web/UmbracoComponentRenderer.cs

From the code it is not apparent if there is any way to disable this.

Macros seem to have this functionality with the MacroErrors section of umbracoSettings but there does not seem to be anything to disable this for templates. Ideally I would like to have the same ability to choose whether they are rendered, silently ignored, or thrown to reach our global error handler.

If this already exists, please advise how to configure as we have a fail on a penetration test due to this.

**Comment by nul800sebastiaan** [comment]
Hey there, @camelofcode - make sure to discuss this on the forum isntead: https://our.umbraco.com/

Thanks!

**Comment by camelofcode** [comment]
Not sure how, just hanging when trying to post it.

**Comment by clausjensen** [comment]
@camelofcode you're very welcome to submit a pull request adding the feature to disable this just as it is possible with the macros. I completely get your situation and think that it would be a great configuration options to have. It is however not on our list of prioritizations for the Core team right now.

You are of course also welcome to submit this as an issue for us to consider through your support agreement (that I assume you have since you're asking for us to support you).
