### ISSUE TITLE
Introduce more primitive types

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#4236]
We need to introduce more "primitive" types instead of using String, int, Guid everywere.

Eg. `string culture = null` should be `CultureID culture = null`
Same for stuff like:
- Alias
  - Content
  - ContentType
  - ...

This way we could clean up the usage of `PublishedContentExtensions` to not have methods with optional parameters hiding other methods.

**Comment by Shazwazza** [comment]
out of curiosity which methods are hiding other methods? I don't see any squiggly lines about that :P

**Comment by bergmania** [comment]
We had 5 methods in `PublishedContentExtensions` where we had to rename them to avoid the hiding.

Also it is quite hard to figure out e.g. where we use cultures as long as we just use strings.

**Comment by Shazwazza** [comment]
Ah right, just discussed a bunch of this with @clausjensen and gave some ideas, he can chat to you when he's back. We used to use CultureInfo for culture but it was super annoying. We have some other possible options but there's pros/cons to it all.

**Comment by zpqrtbnk** [comment]
We had 
```
Children(this IPublishedContent content, string culture = null)
Children(this IPublishedContent content, string contentTypeAlias, string culture = null)
```
Which was a conflict. That was solved with
```
Children(this IPublishedContent content, string culture = null)
Children(this IPublishedContent content, string contentTypeAlias, string culture)
```
But that was not really consistent, as we then had methods with optional culture and others with non-optional cultures. I refactored it a week ago (really though I'd commented here already?) into
```
Children(this IPublishedContent content, string culture = null)
ChildrenOfType(this IPublishedContent content, string contentTypeAlias, string culture = null)
```
So it's more explicit, and consistent.

...

So, about introducing primitive types, we need to be very careful with this. Although it's nice from an architecture point of view, it can be painful when developing a site - and we want developing a site to be *simple* - and using a string for cultures is something that all devs understand. For instance compare

`content.GetValue("foo", "fr-FR")` with `content.GetValue("foo", CultureInfo.GetCultureInfo("fr-FR"))`

I think we should try to expose as little "technicalities" as possible, but find clever and elegant solutions instead. Making sense?

**Comment by bergmania** [comment]
I have never talked about `CultureInfo` as a "primitive" type. IMO thats way too big. 

I talk about a custom `CultureId` implementation, where we could implement implicit conversion from e.g. string.  In that case it is still very simple for the developers to use, but  give us alot of benefits in the core of Umbraco.
It is also possible to implement custom json converters and model binders for MVC, such this is not visible for the serialized models.

This can be implemented in a generic way, if we only use classes and not structs. Otherwise we could autogenerate the implementations from a simple file.

**Comment by bergmania** [comment]
I think the ideas are cool.

I really support combining information that are related in one type. I wonder why we don't already do that for paging information. We have many methods injecting both `pageNumber` and `pageSize`, instead of a single type. Sometimes 0-indexed and sometimes 1-indexed. 😭

I also find it problematic that the validation of the types are not handled on initialization, but deep down in the services/repositories, e.g. culture id (`string`). That's not developer friendly.
If I pass in "Lorem ipsum........" as the `string` for a culture, I should have feedback about the validation immediately. This is also only possible using it's own primitive.

**Comment by zpqrtbnk** [comment]
Liking some of the ideas. It sure would make the APIs way cleaner (yea, the `pageNumber` and `pageSize` things...) and I've started to do something similar with the `Ordering` thing (look in services). Now it all comes down to making it super simple and elegant to use, for developers.

For reference, the `Ordering` thing is a class, which represents the field to order by, the direction, and the (optional) culture to consider. It has some static methods, so that the syntax when using it is:

`repository.GetPage(query, pageIndex, pageSize, out var totalRecords, Ordering.By("UpdateDate"));`

This could surely become something like

`repository.GetPage(query, Paging.Get(start, take), out var total, Ordering.By("UpdateDate"));`

The idea is that it's discoverable. When I type `Paging.` or `Ordering.` Intellisense shows me the different options, I can have help, etc. Not sure it works that well with implicit casting but may be wrong.

*And let's ignore the extra allocations for now - considering these things are quite small and meant to be used as function args, esp. `Paging`, it would probably make sense for them to be `struct` and not `class`.*

Now about the culture thing... would this work too? I'm not too fond of the `{ "fr-FR", "segment" }` thing, just because of all the "frontenders" out there. Can we find something more... discoverable?

`model.Value("alias", Variant.Select("fr-FR"));`

Right, `Variant.Select` is ugly but you get my point, we want something simple and explicit. Ideas?

All in all - would be very nice if we can figure it out - And then of course - that's a massive (though pretty repetitive) change in all our APIs - but why not - only it has to be done... soon.

**Comment by Shazwazza** [comment]
I think we should change this to a SPIKE to see what can be done in a day, it would be interesting but it might prove to be irrelevant if the implicit casting is in place which causes the overloads to be shadowed anyways.

**Comment by bergmania** [comment]
I agree this could be a SPIKE, but even if the we still have to cast explicitly, I think this is important. The codebase is full of methods with multiple parameters of the same type:

E.g. `IContentService`:
- ` void DeleteBlueprintsOfType(int contentTypeId, int userId = Constants.Security.SuperUserId);`
- `IEnumerable<IContent> GetVersionsSlim(int id, int skip, int take)`
- `IEnumerable<int> GetVersionIds(int id, int topRows)`
- `IContent Copy(IContent content, int parentId, bool relateToOriginal, int userId = Constants.Security.SuperUserId);`
- `...`

I still think is a major improvement to have custom `primitive types`, like
- ` void DeleteBlueprintsOfType(ContentTypeId contentTypeId, UserId userId = Constants.Security.SuperUserId);`
- `IEnumerable<IContent> GetVersionsSlim(VersionId id, PagingInfo pagingInfo)`
- `IEnumerable<int> GetVersionIds(VersionId id, int topRows)`
- `IContent Copy(IContent content, ContentTypeId parentId, bool relateToOriginal, UserId userId = Constants.Security.SuperUserId);`
- `...`
