### ISSUE TITLE
Stop having version in web.config appSettings

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#4238]
Stop having version in web.config appSettings. This forces a recycle of the app pool, when there are changed.

**Comment by Shazwazza** [comment]
@zpqrtbnk has wanted this for some time (I thought we already had an issue for it) but he actually wanted to remove having the Umbraco version in a file entirely, but there's quite a few challenges with that.

Is this more to just move it outside of the web.config into some standalone file? If so, what is the use case? We also want to do this for the CDF version at some stage but at the end of the day, the app domain needs to recycle when that is changed anyway to clear the current in-mem cache.

**Comment by zpqrtbnk** [comment]
Use case is: `web.config` is in Git and deployed - but if I upgrade from `8.2.2` to `8.2.3` I have to make sure the version in `web.config` still says `8.2.2` so it triggers the upgrader - and then the file has changes on the live environment which need to be merged - awkward.

So, on my site: I upgrade to `8.2.3` on my machine, it works, I'm happy, I want to push the changes, *but* I need to remember to revert the version in `web.config` before commiting.

Also, I don't know how ppl upgrade LB sites, but basically you'd have to push one server with `8.2.2` to trigger the upgrade, and push the *other* servers with `8.2.3` to make sure the upgrade does not trigger multiple times?

Things to consider:

With the new migration system, you can ship `web.config` with `8.2.3` and if there are migrations between `8.2.2` and `8.2.3` the upgrader would still run - otherwise, the upgrade would be transparent - a good thing.

And, since ultimately the migration status is in the database, in a LB environment we know can be sure the upgrade would run only once.

Moving the version into a non-config file would mean it's available on disk but never in Git.

And then, what's the need for this version?

Another thing to think about: the migration system in 8 is a database-level thing, ie it happens *once* in a LB enviromnent - could we have "migrations" that need to run on *each* server, too?

**Comment by Shazwazza** [comment]
Yup so this is the same issue, all good.

We currently don't and IMO shouldn't have migrations running on individual servers - if that needs to be done the Cache Refreshers should be used ... and is basically how that would work today anyways. I think this would add quite a big layer of complexity we'd need to support.

Upgrading in LB now is yes, sort of a PITA because you need to know what you are doing:

* Put up holding page on replica servers
* Run the upgrader on the master site
* Ensure the build you pushing to your replica servers contains the correct version without the holding page and push

But you are right, what is the need for the file? I guess it comes down to re-learning some techniques. In v7 you could use it for testing to re-force a migration, in know in v8 this isn't the same thing and you can do that by modifying the DB if you needed to. Not sure of other scenarios. 

Cloud however will need to be updated to support this so we'll need to make sure it's done on their end too.

**Comment by zpqrtbnk** [comment]
yup - which is why... maybe at that point we need to start listing "higher level" tasks such as, "re-learn and re-thing how to maintain versions & do upgrades"

**Comment by poornimanayar** [comment]
I stumbled upon this issue quite accidentally while I was trying to figure out the process of database building upon the installer screen. The whole reason behind it was to simplify the db automation process with CI-CD pipelines on the project and this was one point which was making it quite tricky.

**Comment by bergmania** [comment]
Fixed in the netcore project
