### ISSUE TITLE
AppSetting causing YSOD on Cloud

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4251]
child of https://github.com/umbraco/Umbraco-CMS/issues/4250

Appsetting - setting `umbracoDisableElectionForSingleServer=true` gives a YSOD in default Umbraco v8 - we set this by default on Cloud sites - shouldn't this still work?

**Comment by zpqrtbnk** [comment]
Any chance we can get some details about the YSOD?

**Comment by mikkelhm** [comment]
```
[BootFailedException: Boot failed: Umbraco cannot run. Sad. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Exception: panic: registar.
   ved Umbraco.Web.Components.DatabaseServerRegistrarAndMessengerComponent..ctor(IRuntimeState runtime, IServerRegistrar serverRegistrar, IServerMessenger serverMessenger, IServerRegistrationService registrationService, ILogger logger, IndexRebuilder indexRebuilder)
   ved DynamicMethod(Object[] )
   ved Umbraco.Core.Components.ComponentCollectionBuilder.CreateItem(IFactory factory, Type itemType)
   ved System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   ved System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   ved System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   ved Umbraco.Core.Components.ComponentCollectionBuilder.CreateItems(IFactory factory)
   ved Umbraco.Core.Composing.CollectionBuilderBase`3.CreateCollection(IFactory factory)
   ved LightInject.PerContainerLifetime.GetInstance(Func`1 createInstance, Scope scope)
   ved LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   ved LightInject.ServiceContainer.<>c__DisplayClass147_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   ved LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   ved LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   ved LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
   ved LightInject.ServiceContainer.GetInstance(Type serviceType)
   ved Umbraco.Core.Composing.FactoryExtensions.GetInstance[T](IFactory factory)
   ved Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)]
   Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) +339
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91
```

**Comment by mikkelhm** [comment]
![YSOD.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e538d2b6bcc0011dd14b0/125516c66e82c728ace21e0d46d1a7b507c0cfeb9ffbb049a15ee4d6730472712c56a77c23d0e72eeb112e515f5e4fa9440d5610aafc9b37b4f46d2ede0356b49b381d66cc2f13acb2831abb09be218f4c84b7bd824cd2a5.PNG)

**Comment by zpqrtbnk** [comment]
thnks

**Comment by mikkelhm** [comment]
I hope the above is enough - to reproduce, i grabbed the latest .zip from the build, then initialized umbraco(started and ran through the installer).

Then i added
`<add key="umbracoDisableElectionForSingleServer" value="true" />`

And then the error is there

**Comment by zpqrtbnk** [comment]
I can see why it happens, yes - now trying to figure it out

**Comment by zpqrtbnk** [comment]
Oh my, this is a hackish thing - so when that setting is set, we replace the `IServerRegistrar` with a dummy one that pretend there is only 1 `Single` server - makes sense, no need to do complex things if we *know* there's only 1 server.

(assuming of course that there can never be 2 instances of the same site, running at the same time, on different servers, on Cloud) 

Problem is, we still try to initialize what we assume is the original `DatabaseServerRegistrar`, hence the exception. I can change the code, so we skip the initialization if it's not the expected registrar type. Fine.

Meanwhile, we still register the `DatabaseServerMessenger` as an `IServerMessenger` in `CoreRuntimeComposer`, and replace it with `BatchedDatabaseServerMessenger` in the appropriate web component. Which means we *still* write cache instructions to the database, and we still process these instructions.

But, that is a good thing. Because, during an app domain restart, the old domain can end up writing instructions that will need to be picked by the new domain.

**Comment by zpqrtbnk** [comment]
Pushed commit https://github.com/umbraco/Umbraco-CMS/commit/e8cb30fbc4cb5ee71aec1ed5a6e29b7681aed8ab which should fix the issue - for review by Shan

**Comment by Shazwazza** [comment]
Not quite working since we are causing a circular loop with the RuntimeState.ApplicationUrl and the SingleServerRegistrar.GetCurrentServerUmbracoApplicationUrl since both are relying on each other. I'll investigate and fixup.

**Comment by Shazwazza** [comment]
It needed a null check, see rev 16b655fd6277572627861cd73d12514ea3563895

all works now
