### ISSUE TITLE
v8: Tree groups should not be sorted alphabetical

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4285]
In v8 it introduces new tree groups (or multiple root tree nodes) in e.g. settings sections.

I have localized these to Danish, which looks like this.

![image](https://user-images.githubusercontent.com/2919859/51807360-1d0f1300-2286-11e9-80f9-e46493201d00.png)

I think it is important the order is the same independent of the language. Furthermore maybe the core tree groups should (by default) be ordered first, e.g. Settings, Templating and then Third Party. Not sure about the latter one, but I seems to be a tree group as well.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI/Umbraco/config/lang/en_us.xml#L1687-L1689

**Comment by nul800sebastiaan** [comment]
Ha! Interesting.. ;-)

Yeah:

1. Settings
2. Templating
3. Third Party
4. Maybe more.. 

Not sure if we want people to be able to re-order "Third Party" to be below other groups at some point. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@nul800sebastiaan it seems it needs to order in these groups.
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Constants-Applications.cs#L150-L157

Not sure if it also will be possible to create tree groups in custom sections or re-use and existing tree group for another package, e.g. if you wanted to add an extension to Analytics package.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web/Trees/TemplatesTreeController.cs#L18-L21

Maybe it should have a `TreeGroupOrder` /  `TreeGroupSortOrder` property?

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web/Services/TreeService.cs#L39-L44

**Comment by mattbrailsford** [comment]
Just to say, it would be good if we could have custom tree groups as package developers. For example, in tea commerce we will have settings to configure and it would be nice if these could be under a "commerce" group, rather than just lumped together with other 3rd party package developers.

**Comment by mattbrailsford** [comment]
@nul800sebastiaan I think before anyone attempts a PR it would be good to know what would be accepted? Or you wanting groups to be restricted to those defined in core? Or are you happy to allow package devs to declare their own sections?

**Comment by bjarnef** [comment]
@mattbrailsford when you say `sections` I guess you mean `tree groups`? :)

**Comment by abjerner** [comment]
Unless something has changed since the last time I looked, it wasn't possible to create a custom tree in the two default groups. But wouldn't it make sense to add support for this as well? Say I have a package that does something template related, it would make sense to have the custom tree under **Templating** instead of under **Third Party**. 

And while we're discussing this, is **Third Party** a good name? The distinction between "native" and third party may not matter to end user. So perhaps the default tree group should be named **Other** instead of **Third Party**?

As a package developer, I could see some benefit of grouping our packages under a common tree group - eg. **Skybrud**. But then again, this distinction may not matter to the end user, so I would be fine with just **Third Party** / **Other**. Still, there could be better use cases where custom tree groups make better sense. When I first started playing around with trees in V8, I was a bit surprised that you couldn't specify a tree group.

**Comment by mattbrailsford** [comment]
@bjarnef oops, sorry, yes, I meant "Or are you happy to allow package devs to declare their own **groups**?"

Sorry for any confusion.

**Comment by mattbrailsford** [comment]
@abjerner I think if it does become allowed to create our own groups, we need to set some boundaries. I don't think naming the group your company makes sense, I think it has to come from the expectations of the user, not self promotion. For example, I could easily say I want a **Tea Commerce** group, but to a user, this doesn't really mean anything, where as a group of **Commerce** makes much more sense becuase it defines the context of the trees within it.

**Comment by abjerner** [comment]
@mattbrailsford yes, that was my point. So we're talking a fixed set of groups? Eg. **Commerce**, **Statistics** etc? Or just advising devs to stick with group names that have a broader use?

**Comment by mattbrailsford** [comment]
@abjerner I guess this is ultimately down to HQ, hence my question. If it is to be a core set, I'd be tempted to define as many as we can that people might want, and then let people submit a PR if more are needed 🤷‍♂️

**Comment by abjerner** [comment]
@mattbrailsford yes, I was just thinking out loud. IMO that seems like the right approach 👍

**Comment by bjarnef** [comment]
It would be great to solve this since it is a bit confusing the tree groups are sorted different when logging in with users with different languages. A great task for [![label: hacktoberfest][~hacktoberfest]](../labels/hacktoberfest/contrib--2019)

[~hacktoberfest]: https://img.shields.io/badge/hacktoberfest/contrib--2019-b73542.svg

**Comment by nul800sebastiaan** [comment]
There's a fun workaround suggested in the related issue by the way: https://github.com/umbraco/Umbraco-CMS/issues/8439#issuecomment-658404322 🙈 

I don't think we want to dictate what these groups are named as, it would be hard to police and almost impossible to come up with a list of names that we think is sufficient.

**Comment by emma-hq** [comment]
Hey folks,

No one has picked this issue up for a contribution and we have a workaround (see Lennard's comment with regards to prefixing the translations of the treeHeaders with 1 or more spaces). I'm going to close due to lack of interest from grabbers. 

Emma
