### ISSUE TITLE
v8: Add edit link on macro parameters

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4291]
On macro parameters it is not clear how to edit existing parameters. You can click the entire container to open "edit mode", but if you click a few pixels off the "Remove" link, it opens "edit mode".

I think it would be more clear to add an "edit" link next to "remove" link, which also would make it more consistent with pickers.

![image](https://user-images.githubusercontent.com/2919859/51870592-5a41d680-2354-11e9-980f-c36245792cbb.png)

**Comment by nul800sebastiaan** [comment]
Indeed, that would be good, like we have on the content picker configuration, just an "edit" link.

![image](https://user-images.githubusercontent.com/304656/51892566-a3207c00-23a2-11e9-8f6a-41d1d5d48249.png)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
Also it would be great to show the editor type, e.g. "Textbox".
Maybe as the description text as in `umb-node-preview` component.
