### ISSUE TITLE
v8: Subview querystring parameter

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4314]
The users section add a querystring parameter `subview=users` og `subview=groups` to url.
On the current section you can the refresh/reload page and it stays on current "page".

However it doesn't seem to be consistent troughout the UI, e.g. for subviews under document types, macros, relation types, style sheets etc. don't add querystring parameter, so when refreshing page, it just opens the first (default) subview.

Furthermore in the new packager section it takes a different approach and add different url segments for each subview:

```
/umbraco#/packages/packages/repo?mculture=en-US
/umbraco#/packages/packages/installed?mculture=en-US
/umbraco#/packages/packages/local?mculture=en-US
/umbraco#/packages/packages/created?mculture=en-US
```

It would be great to make this consistent instead of three different ways to handle subviews.

**Comment by nul800sebastiaan** [comment]
Ah yes, consistency, that would be lovely! But I guess we're not in a perfect world yet. 

I've marked this as an idea to come back to in the future, thanks!

**Comment by Shazwazza** [comment]
This routing for packages is on purpose and is explicitly done this way otherwise navigating the packages section yields very ugly URLs.

There is a reason for this madness
* The packages section consists of 4 different editors
* The users section should have it's routing fixed to be like packages - because each is a different editor
* The other places mentioned like doc types, stylesheets, content, etc... are *not* different editors, they are the same editor which is why they are not route-able like that. It would be possible however to add query string (I call it "deep linking") to these sub views when the sub views are within the same editor

So the 'feature request' here is: 

> Make sub views that are part of the same editor to be able to be deep linked via query strings

(I'll fixup the user section, that's an easy one)
