### ISSUE TITLE
Need to update the IContentService api SavePublishing APIs

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4324]
Need to update the IContentService api SavePublishing APIs as they are confusing

The review and PR are all part of https://github.com/umbraco/Umbraco-CMS/issues/3640

**Comment by Shazwazza** [comment]
Here's the changes:

* `PublishResult SaveAndPublish(IContent content, string[] cultures, int userId = 0, bool raiseEvents = true)` added so that you can save/publish multiple cultures at once without having to know how the original `SavePublishing` method works. This streamlines the APIs for common use for developers. Have updated most original refs to `SavePublishing` to use this method.
* Renames `SavePublishing` to `CommitDocumentChanges` - Is this better? I changed this because I don't think that the name `SavePublishing` is good and in most cases people will not use this method so I wanted to separate the logical naming of methods since this won't show up among the other "Save" methods. I've updated the code comments on this too. This is the underlying method used by all Save operations but we don't actually use this in the core ourselves anymore. So the question is: Do we keep it on the interface?? 
   * If we remove it then we cannot publish/unpublish in a single operation (but not sure people really need that)
    * If we remove it then a specific test that 'requires' this fails: `Can_SaveRead_Variations` with the comment `that HAS to be SavePublishing, because SaveAndPublish would just republish everything!` and I've tested just calling SaveAndPublish and it fails, but since we don't use `CommitDocumentChanges` anywhere in core now still not sure if we want it on the interface?
   * Is it the right name choice if we do keep it?
* Removed the `IContent.ChangeContentType` methods. a) they don't belong there, b) we don't support changing content types yet in v8, when we do we can revisit how this should work
 
### Proposal....

I'd love to change a lot of the `IContent` APIs, these methods/properties are weird: `PublishCulture`, `UnpublishCulture`, `WasCulturePublished`, `PublishTemplateId` (not used publicly!?)

`PublishCulture`, `UnpublishCulture` are only used internally (except for a single place in the ContentController, but we can work around that). `WasCulturePublished` is *only* used in the ContentService and by the ext method `GetCulturesUnpublishing` which is also *only* used in the ContentService and only within the `CommitDocumentChanges` method!

So lets say we keep `CommitDocumentChanges`, instead of accepting `IContent` as a parameter, we can accept a new type like `IContentVariationBuilder`. This class can contain `PublishCulture` and `UnpublishCulture` methods. 

`WasCulturePublished` can just be removed, since this is only used inside of the ContentService, can't we 'just' check in the DB for any document culture publish states?

`PublishTemplateId` maybe this is useful at some stage but we don't use it, so not sure

Lastly we should also create an IContentService.Unpublish overload that accepts multiple cultures - we can do this post v8.0 though

Thoughts?

**Comment by Shazwazza** [comment]
More notes:

Removing `WasCulturePublished` was fairly easy, though i need @zpqrtbnk help to figure out something to do with a unit test failing with dates. This method was the 'oddest' of the bunch so it's good we can remove that.

Looking at removing the other ones isn't so simple because we have so many internal methods on Content/ContentBase and a lot of these methods are doing a very good job at just trying not to allocate the `ContentCultureInfosCollection` but IMO this is causing far more problems than that single allocation is worth. 

We have these internal methods: `SetCultureInfo`, `SetPublishInfo`, `SetCultureEdited`, `SetCultureEdited`, `AdjustDates`

And these internal setter properties:
`VersionId`, `Published`, `Edited`, `PublishDate`, `PublisherId`, `PublishTemplateId`, `PublishName`, `Blueprint`, `PublishedVersionId`, `PublishedState`

It seems to me that we can avoid a lot of this complexity/overhead by: 

* Making these public get/set properties
* Making the ContentCultureInfosCollection on IContent and IContentBase public get/set so they can be set by the repo and simply used the way it is meant to be instead of trying to hide it underneath all of these methods

I have a feeling that when Deploy needs to properly support sending variants that these methods/properties may need to be public anyways.

Then we have these weird `virtual` declarations everywhere which i've removed since they are not overridden and if we really want them overridden, they can be done by explicitly implementing the interface

So I've pushed these changes, IContent and IContentBase are far simpler, there's no more internal methods and setter properties which are only used by the repository, all of the methods mentioned above are now on an extension method class (internal for now since they are really only used by the repo)
