### ISSUE TITLE
v8 - Remove "Password answer" and "Password question" from Member type

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#4350]
When introducing Umbraco v8 to some new editors they all came with some questions about the Member-section in Umbraco. They all asked what was the functionality of "Password answer" and "Password question" on a member profile. 

The only answer I had was that I had no idea, and I've never used it before. I know it's probably part of the standard .NET Membershipprovider, but I would love to see these properties to be removed by default, because I don't think anyone ever uses it (nobody I know of), and I don't think anyone should use it as well :)

**Comment by Shazwazza** [comment]
Yes it's part of the old .NET membership provider stuff. We can't 'just' remove them because the membership provider needs to have all of this data else it doesn't work. I'd prefer to entirely remove membership providers but we won't be able to do that with our time constraints and that will need to wait until v9. It is possible that you can enable this functionality in Umbraco so we can't 'just' remove them. 

It would prob be possible to hide these properties based on the settings of the membership provider, this could either be done in the core from the MembersController to filter out these properties or you can do that from an event EditorModelEventManager.SendingMemberModel

**Comment by clausjensen** [comment]
Closing this issue for now
