### ISSUE TITLE
V8: Disable collapse/expand of property groups

### ISSUE THREAD

**Issue by hartvig** [umbraco/Umbraco-CMS#4359]
In v8 the organization of property groups changed from being divided into tabs, to be on the same page. However, in the transition, the ability to collapse/expand the groups was accidentally introduced and should be removed as it doesn't serve any useful purpose.

**Comment by readingdancer** [comment]
Just a thought on this one, if you have a long page of properties with multiple property groups and the editor is interested in the first and last property group, being able to shrink the others out of the way could be useful?

I personally feel that as it works, it would be better to leave it in and see how people use it. When you have a large enough user base, you could survey real end users to see if they use it or not. 

Even better still, if there was some what to collect anonymous analytics of how Umbraco is used that could be really helpful ( getting off track ).

I actually like them as they are and would like the ability to expand and contract them all in one go so that I could see an overview on the page, instead of having to click a drop down menu each time.

Just my 2 cents, pence etc :)

**Comment by warrenbuckley** [comment]
All merged in
