### ISSUE TITLE
v8: Need ability to set the order of sections

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4375]
I'm working on a commerce package for v8, and thinking of how an editor would use the system, I think it would be advantageous if my section could be placed to the right of the media section.

Of course most editors won't have access to all sections, but they may have access to users + members so it would still be beneficial to be able to move the section such that they are ordered by "most used".

**Comment by abjerner** [comment]
When adding a dashboard, you can specify a weight by which the dashboard is sorted among other dashboards in a given section. This is possible both from C# and package.manifest files.

I believe something similar could be done for sections. Let's say the content section has a weight of 10, media section has a weight of 20, settings section as a weight of 30 and so forth. In Matt's case, he could then add a TeaCommerce section with a weight 25 to add the section right between the media section and the settings section.

Furthermore we can manipulate the collection of dashboards sent to the backoffice UI through an event in the `EditorModelEventManager` class. Custom dashboard may be added in somewhat random order, so we can use the `OnSendingDashboardModel` event to further control the order and rendering of the dashboards. I think a similar `OnSendingSectionsModel` event would make sense, and give a bit more control to those who might need it.

I think both approaches could solve Matt's issue with the order by which the sections appear.

**Comment by kjac** [comment]
PR in #4395

**Comment by Shazwazza** [comment]
I added a note to the PR: https://github.com/umbraco/Umbraco-CMS/pull/4395#issuecomment-460166134

The gist is that we have a lot of collections created by 'collection builders' and we want to avoid adding 'sort order' properties on these collections because ultimately there will be some collisions and if it's absolutely necessary we already have a 'weighted' collection. 

In c# you can already change the explicit order of sections on startup which we would prefer people use if they want to have fine grained control over such things.

**Comment by kjac** [comment]
@Shazwazza I'm cool with that, but just a friendly reminder: This means we'll diminish the extension experience for non-dotnet-devs, compared to what was possible in V7.

**Comment by Shazwazza** [comment]
Yup all good, just want to mention how things are put together. I think we'll find a few of these things as we start to get people using v8 :) I'd love to start out with the basics/fundamentals in place and then build a consistent way to allow the non-dev/package manifest package devs to handle things like this. Just don't want to rush the fix since we might want to have a look at the overall collection builder process and how that integrates with package manifests .

**Comment by kjac** [comment]
@Shazwazza excellent ... and I couldn't agree more. I'll close the PR.

If you have time, maybe you could share a gist for future reference on how to manipulate the section order on startup?

**Comment by mattbrailsford** [comment]
@Shazwazza +1 on @kjac request for a code example

**Comment by Shazwazza** [comment]
Yup :) I've got a reminder in my inbox for tomorrow (gotta sleep 💤 )

**Comment by mattbrailsford** [comment]
Thanks to @zpqrtbnk's blog post https://www.zpqrtbnk.net/posts/composing-umbraco-v8, I figured out how to control the order:

    public class MyWebComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Sections()
                .InsertBefore<SettingsBackOfficeSection, CommerceBackOfficeSection>();
        }
    }

Important things to note here is that `Sections()` is an extension method so isn't instantly "discoverable" which I find kind of annoying. Secondly, I wanted to `InsertAfter` which currently seems to be named `AppendAfter` which just seems weird so I raised an issue for that 😁 (See #4406)

**Comment by Shazwazza** [comment]
I will close this issue, in the future we should revisit ordering without c#. As for extension methods there isn't really an easy work around for that - because both Web and Core projects expose different features we can't have concrete methods on the Composition for both Web/Core,  further to that devs will be adding their own extension methods since you can't change the concrete implementation.  All ext methods have been moved to the root namespaces for the Umbraco.Web and Umbraco.Core project to make them easy to discover since in the vast majority of cases these namespaces will be imported already.
