### ISSUE TITLE
v8: Rename label property editor alias

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4379]
I think the label property editor alias should be renamed from `Umbraco.NoEdit` to `Umbraco.Label`.
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Constants-PropertyEditors.cs#L107-L110

Furthermore is there a reason we need both `Umbraco.Date` and `Umbraco.DateTime`?

Isn't it enough with `Umbraco.DateTime` and then configuration of data types "Date Picker" and and "Date Picker with time" decides whether is should save time or not?
Maybe based on the "Date format" or a toggle button in the configuration.

https://issues.umbraco.org/issue/U4-4556

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea, I'll have to discuss with the team soon, will get back to you!

**Comment by bergmania** [comment]
PR for the Label: https://github.com/umbraco/Umbraco-CMS/pull/4604

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/4604

@bjarnef We talked about the `Date` / `DateTime` one and figured we could keep `Umbraco.DateTime` and if the Date format includes `HH`, `H`, `mm` and `m` then we should show the time picker, if it doesn't then we should hide it. That way you don't need to know when you configure it that you have to enable "add time picker" (or whatever it would be called).

And now that I've scrolled up.. you said the same thing 🤦‍♂️ 
Very well, that sounds like a good way to go!

**Comment by bjarnef** [comment]
@nul800sebastiaan how about seconds `ss` and `s` (maybe also `h` and `hh`?) if using time picker in flatpickr? https://devhints.io/moment

It seems flatpickr supported it from this commit: https://github.com/flatpickr/flatpickr/commit/b2dd5772b409f9cd062c6e43f27ec31c2ec58de6

But it is probably rarely you use a time picker without hours or minutes.

**Comment by bergmania** [comment]
PR for date/datetime: https://github.com/umbraco/Umbraco-CMS/pull/4608

**Comment by nul800sebastiaan** [comment]
@bjarnef Yep, I meant to add `hh`! 

I am not sure we allow you to pick seconds at the moment. But could be added in the future. It seems a bit overkill though, but people might want to use that at some point too.

**Comment by nul800sebastiaan** [comment]
`DateTime` / `Date` have been merged together now, thanks for the suggestion @bjarnef !
