### ISSUE TITLE
v8: Reinstate ability to add sections / trees programatically

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4394]
In v7 both the `SectionService` and `TreeService` both had `MakeNew` methods that allowed you to define a section / tree at runtime. This was important functionality for my Fluidity package which uses a fluent API to create these. It would be good if methods were added back in to support this way of registering sections / trees.

**Comment by mattbrailsford** [comment]
I think MakeNew for trees does make sense (for fluidity at least) as we reuse the same tree controller but it is given a config to know what entities to render. 

Is there a way of registering a tree in v8 that isn't just via an attribute? ie, can one be registered the same way a section can be registered? If so, it might just be for fluidity that we have to pass it a composer so that it can compose the sections / trees dynamically.

**Comment by Shazwazza** [comment]
hrm.... this could be interesting. 

Whether we can do exactly what you want now or do some work arounds, i'm unsure of (I guess this the interesting phase of software dev!). Best i can do is explain (and rubber duck) how things work and we can go from there.

So trees are c# controllers and controllers are all created with DI of course. Tree's are scanned for based on tree controller's found that are attributed and from this meta data a simple class is created: `Umbraco.Web.Trees.Tree`. This just contains metadata along with the `TreeControllerType`. 

The new ITreeService resolves all of these `Umbraco.Web.Trees.Tree` instances which are primarily used for rendering root nodes for trees within a section (done via proxy). Below a root node, requests are made directly to the controller's endpoint and the controller is of course still created with DI (this is pretty much the same to how v7 works, just without the DI ... unless you've configured DI :P ).

So... how can you create the same controller type with different configuration? You can't really, provided you only have a controller `Type` to work from. You could of course have a controller with a constructor that accepts some configuration object and it will be injected if you register it, but there's still only the single controller `Type` so that's not really going to work unless you can somehow dynamically set the configuration object that is being injected based on something. Since tree nodes are rendered via requests and various tree things are controlled by any custom query strings, perhaps being able to pass in some query string values would work and probably be more flexible.

So what are some other options? Well, we have a TreeCollectionBuilder which we can make it possible to add to a custom `Umbraco.Web.Trees.Tree` metadata object. If this were done, then you wouldn't want to attribute your tree controller since instead you'll be manually adding it's metadata object to the collection instead of automatically type scanned.  We could potentially then add a custom dictionary property to `Umbraco.Web.Trees.Tree` which when resolved would append these key/values to the query string of the tree controller. That way you could manually register any number of `Umbraco.Web.Trees.Tree` objects that point to the same `TreeControllerType` but have different tree aliases and custom query strings passed in for each request. AHA ... actually I think we already pass up the tree alias in the query string anyways! So if that's the case, then all we'd really need to do is add a method to manually register a `Umbraco.Web.Trees.Tree` and then in your single tree controller type you can do different things depending on the tree alias passed in?

... sorry that was a lot of info :P thoughts?

**Comment by mattbrailsford** [comment]
@Shazwazza wow, that was a lot 😁

I think your suggestion of having the ability to add to TreeCollectionBuilder is exactly right. The tree controller can stay the same, and use the querystring param of the tree alias (which is what I use in v7) to determine which "tree contents" to render.

I've raise issue #4408 to expose Trees() on the WebCompositionExtensions so I think that should solve that, and I've found out how to add a section via the Sections() collection already, so those should be all that's needed.

**Comment by mattbrailsford** [comment]
I'm gonna close this issue off then, as #4408 will solve this.
