### ISSUE TITLE
V8: Document Type in active view after deletion

### ISSUE THREAD

**Issue by jmoumbraco** [umbraco/Umbraco-CMS#4489]
This issue is not new to Umbraco 8, works in similar ways in latest Umbraco 7.

Having a Document Type active/open in edit mode when deleting it doesn't change the screen upon deletion. The Document Type remains open as if it was not deleted.

This is confusing in terms of the status of the deletion. It also enables the user to click the save button, which results in an error.

Suggested behavior: Navigate to the main Document Type screen after deletion.

![ux_del_content_type_screen](https://user-images.githubusercontent.com/37339188/52486621-e9a08280-2bbb-11e9-8e97-769e160065a9.PNG)

**Comment by nul800sebastiaan** [comment]
I've also noticed the same problem in the content and media section, which is even a bit worse because we helpfully "remember" the last thing we were working on in those sections, so each time you switch to a different section and back to content/media, the URL still contains the id if the item that has been deleted and you will see a similar error as the one in this screenshot.
