### ISSUE TITLE
v8: Default datatypes

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco-CMS#4571]
Maybe it is time to have a look at the default datatypes that are created when doing a blank install?
Some of them make sense, since they do not have any configuration on the datatype, but some og them are just clutter.
I.e. why is Approved Color created and Slider is not? I agree that Slider should not be created, since it depends on the context it is used, but so does Approved Color and many other of the created datatypes.

My suggestion:
Only create datatypes that are actually used somewhere else on a clean install.
Put those datatypes in a folder marking why they are there.

**Comment by nul800sebastiaan** [comment]
Hi @AllanKirk, this list has historically and quite randomly grown into the list it is today. For v7 we're going to keep it like it is right now, but in v8 we're going ship with each datatype by default. That way new (and often also experienced) users can actually discover them. 
We have had talks of putting them in folders / groups instead of making a long list but that's a bit further out in the future. We have some other ideas in this area as well.

Of course if you're annoyed with some datatypes being there/not being there you could write a bit of code to create your ideal setup for each new project you create. :-)

Anyway, I'll close this for now but hope you have a bit more insight in our future ideas for now!
