### ISSUE TITLE
v8: IFactory should itself be resolvable

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4590]
I'm creating a pipeline implementation where the pipeline acts as a factory to create the task instances. My pipeline is registered with the `IFactory` but, it needs itself an instance of `IFactory`. It should be possible to define my factory with a `IFactory` constructor parameter and it be resolved to the `IFactory` implementation. Currently the only option is to use `Current.Factory`.

**Comment by zpqrtbnk** [comment]
We kinda have to do this type of things now-ish - hence moving to in-progress.

Discussion: `IFactory` used to be resolvable, but for some reason I always felt it a bit... anti-pattern-ish. It's a feeling, I cannot explain. So, whenever we need it in something, at the moment, we register this something with a factory method:

```
composition.Register<ISomething>(f => new Something(f));
```

I have no idea whether self-registering the factory would be a Bad Thing (TM) or not. I am open to discussion.

Ping @lars-erik

**Comment by mattbrailsford** [comment]
@zpqrtbnk that's currently what I'm having to do. But I did speak with @lars-erik on the v8-di slack channel and he thought it was resolvable. Like you say, whether it "should" be allowed is probably another question 😁

**Comment by lars-erik** [comment]
Containers usually know of themselves for the factory registrations.
For instance:

    concreteContainer.Register<IAbstraction>(factory => new Thing(factory.Resolve<X>()))

Factory would be concreteContainer, and it knows it.

Since IFactory is "ours" and not the container's, and we expose `Register<T>(Func<IFactory, T> factory)` we need to make IFactory known to the container, otherwise the container won't know what to pass to the factory method.

At least that's how it goes with Castle, but I don't quite remember how/if Lightinject tackled it. I'm sure MS.DI will need it to be registered.

**Comment by zpqrtbnk** [comment]
PR #4950
