### ISSUE TITLE
[v8] Container registration allows you to create invalid registrations

### ISSUE THREAD

**Issue by aaronpowell** [umbraco/Umbraco-CMS#4726]
The way the type restrains are in the container (well, `IRegister`) in v8 allows you to create registrations for type resolution that is invalid and you'll only find out at runtime when the container tries to set everything up.

Given types like this:

```csharp
class IA { }
class A : IA { }
class B { }
```

You can do this:

```csharp
	composition.RegisterFor<IA, A>();
	composition.RegisterFor<IA, B>();
```

The 1st is fine, the 2nd isn't, but you don't find out until the container tries to run.

We can configure this with generic argument constraints though, and I'll send a PR to cover that. I've also improved the docs to describe `TService` and `TTarget` (as I had my understanding of them backwards).

**Comment by zpqrtbnk** [comment]
Mmm... it goes like this:

* `register.RegisterFor<TService, TImplement, TTarget>()` registers `TImplement` as an implementation of `TService` to be used by `TTarget`
* `factory.GetInstanceFor<TService, TTarget>()` gets a `TService` that has been registered to be used by `TTarget`

So the idea is that, if I want to register two implementations of `TService`, one to be used by `Target1` and one to be used by `Target2`, I would `RegisterFor` each implementation, and then use a `TargetedServiceFactory` in `Target1` and `Target2` to retrieve the proper implementation.

Note: this is, essentially, to work around MS.DI not supporting named services. Underneath, on the LightInject container, this is implemented via named services.

So... there is no relationship between `TTarget`  and `TService`, really. The latter is just any kind of service that the former would want to use. The `TTarget : TService` constraint would work in Core today, because we inject a `IFileSystem` into *another* `IFileSystem`, but that is just a special case. The general case would allow injecting anything into anything.

And then, yes, if you register something "weird" it will fail at runtime.

Thoughts?

**Comment by aaronpowell** [comment]
Oh right, that's rather confusing from the way it's implemented and why I made this change. I was trying to work out how to register a type as the base interfaces and that was the only method I could find on `IRegister` to do it.

If that's not what it's meant to be used for then sure - doesn't make sense!

**Comment by PerplexDaniel** [comment]
@aaronpowell Isn't it the case you just want to use `composition.Register<IA, A>()`? That is, use `Register` rather than `RegisterFor`? Perhaps I am wrong about your exact use case, but assuming your `IA` is actually an interface that you want the DI framework to resolve for you as an instance of `A` when you request it in a constructor or so, then `Register<TService, TImplementing>` is probably what you want instead. Then the constraints you want to add would also make more sense.

`RegisterFor<TService, TTarget>` seems to serve another purpose judging from @zpqrtbnk's comments.

**Comment by aaronpowell** [comment]
I wasn't aware there was a `Register<TService, TImplementing>` until I dug into the code again last night, it appears to not be on the `IRegister` interface but on an extension method... Why wouldn't it be on the interface?!

**Comment by PerplexDaniel** [comment]
Fair question, though though be fair to Umbraco as well there is a `void Register(Type serviceType, Type implementingType, Lifetime lifetime = Lifetime.Transient)` on the `IRegister` interface. The extension just makes it more convenient to use. The extension method just [calls the other one](https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Core/RegisterExtensions.cs#L14):

```cs
/// <summary>
/// Registers a service with an implementation type.
/// </summary>
public static void Register<TService, TImplementing>(this IRegister register, Lifetime lifetime = Lifetime.Transient)
    => register.Register(typeof(TService), typeof(TImplementing), lifetime);
```

I assume the idea was to keep the interface as small as possible, but I do agree having the generic `Register<TService, TImplementing>` on the `IRegister` interface would make a lot of sense. In fact, all of the methods of `Umbraco.Core.RegisterExtensions` would seem like proper methods on the interface. 

Anyway, I'm sure there was an idea behind providing those as extensions, perhaps @zpqrtbnk can shed some light on that.

**Comment by aaronpowell** [comment]
I'll close this issue, as the issue I posted about isn't valid.

I still think it's weird that the generic-based reigster method isn't part of the interface, I know it's just a proxy to the non-generic but the generics one can be used to enforce type safety (which it doesn't anyway), and really, it's a lot cleaner to write using generics than to write your own `typeof` calls.
