### ISSUE TITLE
v8: "Display at tab number" setting for list view missing

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#4746]
In 7, you can define the tab index for the list view tabs, on document types with list views.

In 8, the list view is a content app, which seemingly always gets placed first.

I don't know if Content Apps have an index you can fiddle with, but I think we should be able to have Content (or other content apps) before the list view.

V7:
![billede](https://user-images.githubusercontent.com/3726467/53402615-5ab0aa00-39b2-11e9-8eff-3d521533a33d.png)

V8:
![billede](https://user-images.githubusercontent.com/3726467/53402669-787e0f00-39b2-11e9-8252-a7b6d3e88901.png)

**Comment by nul800sebastiaan** [comment]
I've put this one on the list for our periodic meetings at HQ and will let you know what the outcome is.

**Comment by nul800sebastiaan** [comment]
Thanks @skttl - this is something we didn't really think about. We discussed it at HQ and came to the conclusion that we need an additional toggle on the list view: "Show content app first". That would cause the content app to be the first app instead of the list view.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5074

**Comment by robinisaksson** [comment]
Hi,
This feature is not working in Umbraco Heartcore.
After Setting "Show Content App First" to true, it still goes to the list view, NOT the content app.
