### ISSUE TITLE
V8 - variant does not fallback

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#4773]
Variant language does not do fallback to main language.

Reproduce de issue:
1 - Install Umbraco 8.0
2- Create a document type with a description rich text editor and enable permissions create as root and set children this same document.
3- Create a content node with description and some children.
4 - Set a template to navigate through the content and show description. Everything is ok.
5- Create spanish language, set as main language and english set to do fallback to spanish.
6 - Set some host names to change language.
7 - Navigate the page and every content show the same text for each language, OK.
8 - Set document type as variant changing.
9 - Set description property type as variant changing.

Problem 1 - Name fallback - With this configuration should exist an english version for the content node, with name and url doing fallback to spanish, but they show empty. Until you save the content with an english name. Leave the description empty.

Problem 2 - Description dont fallback to spanish when empty.

**Comment by zpqrtbnk** [comment]
Problem 1 - that is intentional - the name is what defines whether a document exists at all, for a given language - if you don't set an english name, we consider that your document is not published for english - ie, we consider that only the spanish version exists - therefore, no fallback

Problem 2 - fallback is not automatic - if you render `@Model.Description` you will get the description for the current language, or nothing - to enable fallback, you have to use the following syntax: `@Model.Value(x => x.Description, Fallback.ToLanguage)`

Now this later syntax may be cumbersome if you plan to have fallback everywhere. In which case you may want to substitute the `IPublishedValueFallback` implementation with one that wraps the built-in `PublishedValueFallback` but forces the `fallback` value (which is `Fallback.None` by default) to `Fallback.Language`).

Making sense?

**Comment by teeto** [comment]
Thanks @zpqrtbnk , then what is the purpose of the fallback configuration at the language settings? i supposed that once i configured the fallback language that would occure automatically

**Comment by zpqrtbnk** [comment]
when you do `@Model.Value(x => x.Description, Fallback.ToLanguage)` you ask for fallback to the fallback language, which has been defined in the UI - so that is the purpose of the configuration: to indicate on *which* language to fall back to. But fall back-ing (is that a word?) is not automatic.

**Comment by teeto** [comment]
OK now i get it. I thought that should be automatic. Thanks!
