### ISSUE TITLE
'Delete' Function of Media items wrongly ascribed to the item creator

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [umbraco/Umbraco-CMS#5031]
When a Media Item is deleted, the Audit Log reports the initial delete as "Move Media to Recycle Bin performed by user", correctly ie the audit log records the user who pressed 'delete'.

**But** the actual delete action is ascribed to the original creator of the Media Item , not to the User who who pressed 'delete'. "Trashed media with Id: 39369 related to original parent media item with Id: 38807"

_Expected results:_ the delete action for Media items shows as the user who preformed the delete (not the item creator).

_Note:_ documents/pages actions are correctly reported in the Audit Log - where both the Move to recycle Bin and the 'Trashed,,,, " ie the actions are allocated to the same person.

Using Umbraco v7.12.3. Not  browser specific.

_This has also been confirmed by Dan Diplo_ (whose AuditLog Viewer displays the audit trail that Umbraco records in the umbracoLog table in the database):
"I did a little test to confirm this. 
- If  you deleted a media file then, as you say, it shows the correct "trashed" user information.
- If you delete a single file from the media recycle bin (ie. right click and select 'Delete' to just delete that one image) then that also displays the correct user.
- However, if you empty the recycle bin then it doesn't show the correct user as the one who deleted the item from the bin. When I tested it, it showed the admin user (who was also the creator).

regards Fiona

**Comment by nul800sebastiaan** [comment]
I can see in umbracoLog table that it's logging user 0 indeed, so that seems to be a bug. Tested on 7.14.0.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
I can reproduce this... and a few other related things. I'll push a fix soon 👍

**Comment by kjac** [comment]
Ooookay... so. This is no bug 😆 

The log entry *Trashed media with Id: [node id] related to original parent media item with Id: [parent id]* originates from the relation builder. It's pretty badly worded, but it means: *I added a relation between the trashed media and the original parent media*. 

The log entry is logged as originating from the original creator of the content, because it's not an action performed by the current user (OK, strictly speaking it is, but conceptually it isn't). Perhaps it should be logged as originating from SYSTEM or user "0", but... definitively not the current user.

You'll see the same thing happen when copying content nodes.

Perhaps the wording could be different to avoid future mistakes. Note that this would also include the wording in the rest of the relation builder handlers.

**Comment by HistoricEnglandDigitalTeam** [comment]
Ok thanks for looking into this Kenn.
