### ISSUE TITLE
Rollback details are missing on pages converted using ‘Change Document Type’

### ISSUE THREAD

**Issue by jmwebed** [umbraco/Umbraco-CMS#5072]
We’re using Umbraco version 7.6.13 assembly: 1.0.6582.36857. We have two types of landing page, and we’re retiring one of them. To make the process of switching the old pages into the new version quicker we used the ‘Change Document Type’ option. Unfortunately this lost the Rollback history. We don't know how to get the Rollback history back.

Reproduction
------------

### Bug summary

After we converted the page using 'Change Document Type' the Rollback history has become very limited. It only lists:

- Name of page
- Dates and times of changes
- Who made the change

There are no other details from the previous version of the page under either ‘Diff’ or ‘Html’ view. This includes published information on the public website, and the author notes only visible to Umbraco users in the back office.

### Specifics

Screenshot of the Rollback history on a converted page.
This screenshot is from Google Chrome Version 70.0.3538.102. We've also checked Internet Explorer Version 11.0.9600.19301 with the same result.
![umbracorollbackmissing25mar2019](https://user-images.githubusercontent.com/48923325/54941415-afe5ca00-4f24-11e9-804d-5fb9bb453c7b.jpg)

### Steps to reproduce

These were the steps taken to convert the page from old to new style.

1. Select the old landing page in Umbraco edit screen
2. Go to 'Action' button
3. Select 'Change Document Type'
4. Choose ‘landing’ from the dropdown list of document types
5. Choose 'Map to property fields' that we want to copy across
6. Press 'Save'
7. Make any changes necessary to the content
8. Preview
9. Save and publish
10. Checked the Rollback history – any details about the previous version of the page using the old document type have gone

### Expected result

On Rollback history, we would expect to be able to scroll down a list of each field, its settings and content, including the text and links and any notes we had made. On the 'Diff' view to see the updates highlighted in red and green, with old text crossed through. On the 'HTML' view to see the active URLs we included in the content.

### Actual result

None of the additional information is visible about the content, text, links, notes on the old version of the page from before we changed the document type. We can tell the page has been updated many times over the last four years, but not what changed on the page.

This means we cannot:

- Check what the page used to say
- Rollback to old versions of the content

How can we restore the rollback history of a converted page?

Thank you.

**Comment by clausjensen** [comment]
Due to the way this feature is implemented, changing a document type of an item currently makes any sort of rollback history unusable.

When changing a document type of an item, you basically change the schema of how this particular item stores its data. As an _item_ can only have *one* document type (this field is not kept as a part of the version as it was never the intention that this should be able to change) - this means that we are basically copying all the existing data into the corresponding new fields of the newly selected document type.

We only do this for the current state of the data and not for all the old versions that may be stored.

It may be possible to fix this by having all the data of the old versions of the content moved to their corresponding new fields as well. This is however not a priority currently, but I will flag the task as up for grabs in case someone wants to take a look at it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
