### ISSUE TITLE
A problem with deleting and renaming images

### ISSUE THREAD

**Issue by CodeartIT** [umbraco/Umbraco-CMS#5143]
When I upload image in media section via Umbraco backoffice and If i rename or delete it there, changes dosent apply on my project in visual studio.

So for example i have image in backoffice with name cats and if I decide to rename it in backoffice from cats to cat1, this changes wont apply on visual studio and if i delte it i can still see the image with old title in visual studio.

**Comment by CodeartIT** [comment]
Now i noticed that images will be deleted from visual studio if i clean recycle bin but rename is still the problem if it is the problem.

**Comment by Shazwazza** [comment]
Renaming a media item doesn't rename the media file. Also, what version are you using? 
I think this issue is related with regards to the recycle bin https://github.com/umbraco/Umbraco-CMS/issues/2931

**Comment by CodeartIT** [comment]
I am using Umbraco 8.0.1 
Here is the image of same image in backoffice and in visual studio
![Screenshot_11](https://user-images.githubusercontent.com/47372432/55550279-224e6b00-56d8-11e9-981c-3d0566b409a9.jpg)

**Comment by Shazwazza** [comment]
Yes renaming a media item doesn't rename files. There is nothing stopping a media item from having multiple files, similarly a content item can contain files directly too and those files do not get renamed based on the content name.

This is the expected behaviour. 

It would probably be possible to hook into the media saving event and manually achieve this if that's what you want to do, though media is referenced in the back office by it's name, not the file name so to a user the file name generally doesn't matter.
