### ISSUE TITLE
V8: open media-item in media-picker by clicking its name

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5172]
I would like to be able to open a media-item in media-picker by clicking its name.
And thereby remove the "edit"-icon appearing when hovering a media-item.

Current look:
![image](https://user-images.githubusercontent.com/6791648/55629218-f653e800-57b2-11e9-82b3-a0319c7b84e3.png)

**Comment by kjac** [comment]
@nielslyngsoe folders need all three options in the media picker:

1. The "selected" state for selecting a folder (if not disabled on the data type).
2. The "open" link (the folder name) to browse the folder.
3. The "edit" button (the pen) for opening the folder in infinite editing.

![image](https://user-images.githubusercontent.com/7405322/55668354-7b99d400-5869-11e9-8560-bb823f0df851.png)

Since we can't get rid of the "edit" option for folders, wouldn't it be weird to remove it for files?

As an alternative suggestion, how about removing the hover underline on the file names, and fix the picker so clicking the file name selects the file?

**Comment by nielslyngsoe** [comment]
Hi @kjac 

Good one, would have been a failure to remove it, this just underlines that we need to revisit the UX of the media-picker for good.

Thanks

**Comment by kjac** [comment]
Yep.

> As an alternative suggestion, how about removing the hover underline on the file names, and fix the picker so clicking the file name selects the file?

Want me to fix that up as an intermediate fix while a UX redo is pondered?

**Comment by nielslyngsoe** [comment]
@kjac, I think that could be part of the right solution.


Let me summarise how I think we can make the experience more simple and intuitive:

- Lets get rid of the option to edit a media-item and media-folder from the media-picker selection-dialog (it has offen shown to cause confusion when people hit it by accident)
- When a media-picker is configured to allow folder-selection, we would have to select folders as the default action and thereby use the folder-name as the way to open the folder. (If folder-selection isn't enabled we will just open the folder when clicking it everywhere).
- Media-item file-names should not have an action, and thereby the underline for the name should be gone, and the action when clicking anywhere should be to select the item. (the same goes for folders if folder-selection is disabled)
- on the media-picker property-editor we would keep the remove and edit-shortcut on each item, and this will be the way if you want to change the focus-point... So you would need to pick it for the media-picker first, and then the option to edit will be available.

I hope that makes sense, I will be off for some days and will be able to make a PR around 23th of april, if anyone comes before me they are welcome.

Thanks

**Comment by kjac** [comment]
Thanks for the feedback. I'll get on it 😀

**Comment by kjac** [comment]
@nielslyngsoe PR in #5241
