### ISSUE TITLE
V8.0.1: Node remains in the index after being unpublished

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco-CMS#5218]
I encountered an issue where a content node will remain as a document in my ExternalIndex after being unpublished, which means I will get it in my ISearchResults if I query for its NodeTypeAlias. All its values will be null if I convert it to an IPublishedContent, obviously. Since it is unpublished.

Reproduction
------------

1. Create a new document type and allow it as root.
2. Create a content node with some name
3. Check your ExternalIndex - the node is there, which is expected.
4. Unpublish the content node and check your index again.. you will notice that it is still there.

![image](https://user-images.githubusercontent.com/4366314/55853464-9322d680-5b61-11e9-97b1-1c9612e4eb0c.png)

The node will be gone as a document if you rebuild your index.. but you don't wanna do that everytime you unpublish. ;-) 

This item has been added to our backlog [AB#1533](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1533)

**Comment by linuselander** [comment]
I can reproduce the issue that @hartviglarsen describes. I located the problem to a predicate that determines which indexes should be affected when unpublishing a node. From my tests, it seems as if it selects the _InternalIndex_ and _MemberIndex_ as eligible candidates for the node removal. My interpretation of the logic is that it should rather be removing the node from the _ExternalIndex_.

I created a pull request #5695 that solves the issue in every situation that I have managed to set up (including the exact steps described in this issue). From what I can tell, it also solves the issue described in [UmbracoDocs #1737](https://github.com/umbraco/UmbracoDocs/issues/1737).

However, @nul800sebastiaan seems to be able to reproduce the issue even after applying my patch (as he describes in his comment to the pull request). Perhaps someone has an idea what other logic might be in play here, because I am not able to reproduce the issue with the patch applied.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5695

**Comment by ElipazSoftware** [comment]
Hi, After upgrade to ver 8.1.1 the ExternalIndexer still returning unpublished content. 
 
![Capture](https://user-images.githubusercontent.com/16882672/62571421-f74c7180-b899-11e9-8609-608207b67259.PNG)

![image](https://user-images.githubusercontent.com/16882672/62571449-07645100-b89a-11e9-9fa9-390c0a9246a9.png)

Netanel

**Comment by Shazwazza** [comment]
Did you rebuild your index?

**Comment by ElipazSoftware** [comment]
Hi Shannon,
Yes i rebuilt my index (ExternalIndex) few times, moreover i downloaded new 8.1.1 instance just for testing that issue and its also happens there.

**Comment by Shazwazza** [comment]
@ElipazSoftware which is odd since this issue wasn't present for rebuilding indexes, only for when re-indexing an individual node. 

So to reproduce is just have something unpublished and rebuild your index and the item is still there? Anything else specific? does publishing and then unpublishing the node still remain? is it a variant or non variant ... basically please provide steps to reproduce.

**Comment by nul800sebastiaan** [comment]
Thanks @ElipazSoftware this has just led me to realize we had not merged the related pull request in to 8.1.1! 🤦‍♂️

I have just [done that now](https://github.com/umbraco/Umbraco-CMS/commit/0517f2913438638ace044e063facc74d12fb670f) and this will be released in 8.1.2, coming soon. I apologize for the confusion!

While we're at it, it is almost never necessary to rebuild indexes, can you elaborate on that, why would you need to rebuild them on a daily basis? I mean, yes, I understand that this bug forced you to, but you seemed to have other reasons?

**Comment by ElipazSoftware** [comment]
Hi Sebaastiaan, thanks for that!!!
the only reason we rebuilding the index on daily basis is due to this bug, no other reason.
we just want to update the indexer about published and unpublished content changed by the editors that day.
glad to know that  ver 8.1.2 will resolve this issue.
Thanks a lot guys
