### ISSUE TITLE
Ability to delete the logfile on a running application

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco-CMS#5236]
In v8 there is a lock on the log file preventing me from deleting the logfile. This wasn't the case with v7.

I've run into issues with this on cloud where I can't simply stop the application and delete it. Cloud support asked me to twice to wait until tomorrow to see my corrupted logfile is solved when a new file is created.

This is time consuming and it would be a lot better if we could simply delete the file or somehow delete the file from Umbraco.

**Comment by bergmania** [comment]
As far as I understand, Serilog opens the log files in a way that allows other applications to open, read and write the file, but not getting an exclusive lock on it (as I expect is needed to delete it).

I could be possible to delete the file from Umbraco, using the following steps:

1. Dispose the existing logger
1. Delete the file
1. Re-construct the logger

But if the underlying problem (the corrupt json) was fixed, I don't see this to be relevant, opinions?

Otherwise we have to implement our own serilog file sink, that closes the log file after writing and is  native async such that the end user is not hit by the overhead by open and close the file.

**Comment by FransdeJong** [comment]
I think it has to do with a way of working. In the beginning of a project we have had cases of some errors spamming the log. The easiest way was always to delete the file and find the error on top.

Maybe it's a case of getting used to the new way of working, if the file can't get corrupted anymore that is.
