### ISSUE TITLE
Full path for DocType on Nested Content configuration

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#5294]
Some times we have doctypes with different aliases but same name because they live in different folders in the DocTypes tree. It would be good to see that path structure in the doctype selector when configuring a nested content property.

How can you help?
-------------------------------
I can work on this myself but I want to know if this is a feature everybody else consider useful.

**Comment by skttl** [comment]
I have thought about that too. I think the Nested Content config could use an overhaul, and this is a good start. We also recently added the full path to the composition dialog.

**Comment by hfloyd** [comment]
Also I think the Nested Content datatype config should store  GUIDs for the doctypes used. In V7 if you change the alias of a Doctype, it loses the configuration, and if you update the configuration to re-select the doctype, any content nodes using the Datatype lose their data.

**Comment by nul800sebastiaan** [comment]
Hey @skartknet - we had a bit of a chat about this at HQ this weke, we definitely agree that it should be a bit more clear what you're selecting. We want to expand it a little bit though:

When you hit "Add" then configuring the NC config

![image](https://user-images.githubusercontent.com/304656/57146150-f7356500-6dc4-11e9-94e8-fe86ecc5b6a3.png)

It would be good to pop up the doc type picker, like we have when adding child nodes on a  doctype for example:

![image](https://user-images.githubusercontent.com/304656/57146143-f43a7480-6dc4-11e9-8f16-56d77c59a388.png)

Meanwhile I think @nielslyngsoe has already been busy adding a bit more metdata to that modal dialog so it is easier to figure out which document type (I mean: element type!) you're picking exactly.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by skartknet** [comment]
That sounds good @nul800sebastiaan , I can work on it.

**Comment by skartknet** [comment]
PR on https://github.com/umbraco/Umbraco-CMS/pull/5540

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5540
