### ISSUE TITLE
Multiple Media Picker not available as macro parameter

### ISSUE THREAD

**Issue by Tobelemo** [umbraco/Umbraco-CMS#5335]
The Partial View Macro File snippet "Gallery" recommends the use of the property editor "Multiple Media Picker". 
This property editor is not available as an option in the "Editor" dropdownlist when adding parameters to a macro.

**Comment by kjac** [comment]
Hi 😊 thanks for reporting!

This has been fixed already, see https://github.com/umbraco/Umbraco-CMS/pull/5278

**Comment by kjac** [comment]
... disregard my last comment 😊

**Comment by nul800sebastiaan** [comment]
Yeah, that seems like an oversight! The media picker can be configured as a multiple media picker as well, but I'm not sure how we'd do that for a macro parameter editor. 🤔

**Comment by kjac** [comment]
I had a stab at it really quick the other day but since the multinode treepicker doubles as multiple content picker for macros, there is no easy fix for this. The required fix sadly involves a new dedicated value converter for a new macro parameter property type.

**Comment by AlphaDelta** [comment]
I've had success with the following:

![image](https://user-images.githubusercontent.com/2088238/61604627-6c168d80-ac96-11e9-8c13-f58ef4212d2c.png)

**Result:**

![image](https://user-images.githubusercontent.com/2088238/61604412-8603a080-ac95-11e9-99c9-dfc0eb98d385.png)

I am unaware of the full implications of extending `MediaPickerConfigurationEditor` and overriding `DefaultConfigurationObject`, negative or otherwise.

**Comment by nul800sebastiaan** [comment]
PR to fix this: https://github.com/umbraco/Umbraco-CMS/pull/6149
