### ISSUE TITLE
There needs to be a way to see if Umbraco is processing tasks in the background.

### ISSUE THREAD

**Issue by alikazai** [umbraco/Umbraco-CMS#5344]
Imagine working on a project and you press save or any other button, but nothing seems to happen. so you decided to press it again, and again, until you give up, without knowing that Umbraco is actually processing this in the background and you just needed to wait.

A number of times this has happened to me either if there is a slow connection or one of the plugins added to Umbraco was processing, but sadly I cant see whats happening behind the scenes until I go to the logs and notice my actions still being processed.

**Comment by nul800sebastiaan** [comment]
This is a good point, to make sure that all of these places get fixed, I would suggest you open an issue for each place where you run into this problem so that we can fix these areas one by one.

The reason it's good to make an issue for each one of them is that we could start fixing a few of them now and in the release notes it will say: `Fixed: There needs to be a way to see if Umbraco is processing tasks in the background.`. The expectation is that it will then be implemented throughout.. which it really isn't. Small issues are also easier to fix. 

Makes sense? I'll close this one and look forward to more specific reports as to where this functionality is missing. Thanks! 👍

**Comment by alikazai** [comment]
Thanks

**Comment by nul800sebastiaan** [comment]
As an example, we recently fixed it for the notification panel: https://github.com/umbraco/Umbraco-CMS/pull/5097
