### ISSUE TITLE
Video not playable in Umbraco 8 backoffice

### ISSUE THREAD

**Issue by Rabea-M** [umbraco/Umbraco-CMS#5349]
Umbraco 8 backoffice video not playable. Before this when you click on a video in Media tab, the video opened in a new tab, but now that's not work, anyone has any idea why that is so?
This is the current video uploaded which is not even clickable
![Screenshot_19](https://user-images.githubusercontent.com/41620110/56787479-0e4ce380-6816-11e9-86fc-fd54e26b8fcc.png)

**Comment by nul800sebastiaan** [comment]
Hmm, I see no reason why it shouldn't be clickable. I know for images we set up the image cropper so you won't be able to click those, but other files can just be clickable.
For now, you can click the filename in the "Info" app (top right).

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Rabea-M** [comment]
Sebastian for now it doesn't even open from info tab but rather downloads the video

**Comment by nul800sebastiaan** [comment]
@Rabea-M Hmm, not in my case. Maybe your browser doesn't know how to deal with an mp4 or maybe you should look into how mime types are set up in your app.

**Comment by Rabea-M** [comment]
I am using chrome and all default settings, video was uploaded directly to media folder but  maybe something missing at my end. Thanks for the help

**Comment by kjac** [comment]
PR in #5355

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5355
