### ISSUE TITLE
Passing parameter to Macro Gallery now working

### ISSUE THREAD

**Issue by GionataAladinoCanova** [umbraco/Umbraco-CMS#5385]
Hi

@Model.Value("gallery") return
System.Collections.Generic.List`1[Umbraco.Core.Models.PublishedContent.IPublishedContent]
instead (example) 1150

Umbraco.RenderMacro("HomePageGallery", new {mediaId=@Model.Value("gallery")})
obviously not working

**Comment by abjerner** [comment]
Hi @GionataAladinoCanova and welcome to GitHub 👍

Is it correct to assume that the `gallery` property is either a content or media picker? For a while now, these have returned a list of `IPublishedContent`. So based on the information you have provided here, it sounds like Umbraco is actually working as intended.

In your case, the issue is that your macro expects an ID instead of a list of an `IPublishedContent`. Therefore you should either update your macro accordingly, or change the code from your example a bit so you grab the ID from the first `IPublishedContent` in the list (given that the list isn't empty).

If you're unsure how to change this in your code, the [**Our Umbraco community forum**](https://our.umbraco.com/forum/) is a good place to ask questions like these 😉

**Comment by GionataAladinoCanova** [comment]
Hi and thanks for reply!

I create "New partial view macro from snippet " and select "Gallery"
On relative Macro I create paramenter mediaIds with Media Picker Editor

The call @Umbraco.RenderMacro("HomePageGallery", new {mediaIds = @Umbraco.Field("GalleryField")})
fails!
