### ISSUE TITLE
v8: BackOffice Freezes on Large Operations

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5475]
As reported in [this blog post](http://tooorangey.co.uk/posts/go-figure-8/),

>Publishing super large amounts of content (5000) or copying a section of the tree, locked the NuCache.db (we're running 8.02 with the cache fixes in), and this stopped content trees from loading in the Backoffice - this is almost certainly because the SQL server was maxed out, I know effectively it's a DOS against the SQL db!, and more digging to be done here to try and report the issue coherently on the tracker, but in V7, if the db was maxed out, there wasn't quite such a catastrophic effect on the site... anyway in this project people won't be publishing that amount of content on a regular basis... and getting the Publication Queue in place for V8 would be worthwhile if they did.

Need to focus on the symptoms here: triggering a large amount of changes freezes the backoffice, because the content tree does not load anymore.

I believe the mention of "NuCache.db" here is misleading.
* The ".db" files are low-level files that are managed by a library that supports shared accesses and should not be a problem.
* NuCache has been designed to support shared read/write accesses without problems. **We may want to run some more tests just to be sure**. But it's already been load-tested in the past.
* NuCache is the presentation layer and should not have impact on back-office tree loading.

OTOH v8 has better transaction and concurrency control, and relies on some database-level locks to prevent concurrency issues that could happen in v7. Some of these locks are coarse-grain - such as, write-locking the entire content tree.

For instance, if you are importing documents under an existing document, we cannot let anyone move or remove that document. So... we are safer that v7.

In *theory* write-locking the tree does not prevent other transactions from reading. But it could be that we have an issue, and an unexpected consequence could be that the entire tree is non-readable during the operation, which would be an issue indeed.

**Need to test and repro.**

**Comment by Shazwazza** [comment]
Here's notes from our investigation and proof of concept:

## Research / POC Notes


### Introduction

This proof of concept was about to report some information to the user, while waiting for long running operations. This proof of concept did not try to minimize the long running operations. Due to the fact that, no matter how much we optimize, we can always increase the number of items we handle and end up in a long running operation. Therefore it is important to give the end user information while waiting.
That said, we still should try to optimize the underlying operations to lock more fine-grained and/or execute faster.

### Findings

#### Unintended locking

When we have a write lock on the content tree and executes a big operations (moving 1500 items to recycle bin), the backoffice is blocked both for read locks on content tree (expected), but also read on the content without a read lock (unexpected).

To resolve this, we can change the default isolation level from REPEATABLE_READ to READ_COMMITTED. REPEATABLE_READ is only needed for the umbracoLock table, and can be handled by query hints (See PR).
Note: For SqlCE query hints is not supported, so we need to continue running every query in REPEATABLE_READ.

By default READ_COMMITTED still locks, but it opens up for using READ_COMMITTED_SNAPSHOT on the Sql Server. This is a technique that uses snapshots instead of locks to keep transactions separated. The primary benefit of this is to minimize the waiting between transactions. The drawback is more memory usage. Whether this is a major problem needs further investigation.

An alternative to implementing the distributed lock our self in a database table, could be to use the one build into SqlServer. E.g. the following library uses this technique under the hood. https://github.com/madelson/DistributedLock. (This probably does also not work using SqlCE)  

#### Lock timeout

The current settings is to wait the default time for locks. On SqlServer this is infinite but the http request still times out. On SqlCE the timeout is 5 seconds.
This means the behavior is pretty different between these.

We can however specify a lock timeout when we acquire the lock (See PR).

#### Spy in the lock table

If we provide a reason when we acquire the write lock, we can use this information when other queries times out due to a lock timeout. '
By querying the umbracoLock table in ReadUncomitted isolation scope, we can read the reason and provide this information to the UI.
Please note this is not possible on SqlCe due to lack of ReadUncomitted isolation level. 

Tree under long running operations: (Current behavior):

TODO: Insert image

With POC behavior:

TODO: Insert image

### Missing things to make this PR into a real thing
* Handle timeout exceptions nice everyware in backoffice client and retry
* We need to decrease the timeout time to provide the info about what we are waiting for, but the UI needs to show this info and retry everywhere.
* Update all write locks to have a reason (In PR we have a lot of usages that use the fallback default reason)
  * Add constants
  * Add translations for at least en-US
* Handle LockTimeoutExceptions is backend, and populate with a reason
  * We need to handle when the LockTimeoutExceptions  occurs, and spy in the lock table and return the reason on the exception.
* Update umb-load-indicator to support a message
  * We should update the indicator to native support a reason for the waiting.
* Should handle the timeout issue in angular using an angular interceptor and having a new way to display these messages in the back office. We don't want to have to replicate all this code throughout the JS, just in one place
* We should look into loading the recycle bin separately as to not block the whole tree since that takes an explicit read lock
* Think about how we deal with the try/catch(LockTimeoutException) in c#, since we don't really want to have try/catch for every single read we do

### Problems / Things that make it difficult

When a LockTimeoutException occurs, we need to know which lock to spy for. E.g. ContentTree.
This can probably be hard to know.

### Pull Request - Work in progress

https://github.com/umbraco/Umbraco-CMS/pull/6029

**Comment by nul800sebastiaan** [comment]
Fix for this in PR https://github.com/umbraco/Umbraco-CMS/pull/6688 was included in v8.2.1.
