### ISSUE TITLE
Starter Kit Caused Content Loss

### ISSUE THREAD

**Issue by UnsungHeros** [umbraco/Umbraco-CMS#5595]
Uninstalling the starter kit caused site data loss.

Reproduction
------------

### Steps to reproduce
Create a Document Type called Contacts 
Create content that utilizes that Document Type(the more the better)
Install the starter Kit
Uninstall the starter kit

### Expected result
The starter kit to be uninstalled

### Actual result
While the starter kit is indeed uninstalled, I have lost 30 of my contacts[fortunately this was a staging site] from the site because the contacts Document Type I made was removed.

**Comment by nul800sebastiaan** [comment]
Thanks for reporting @UnsungHeros - this is expected behavior and we don't have plans to change this. When you uninstall any package you would expect the data that it installed to go away, so we remove document types and anything that was originally installed with the package. When a document type no longer exists, we can't preserve the content related to that document type any more either, so it will be deleted.

**Comment by UnsungHeros** [comment]
Maybe I should ask this differently.  Should the package install process be checking for the existence of document types and property names BEFORE even attempting to install the package and warn the user?  I understand that the behavior is expected, but the actual process might be missing an initial step.
