### ISSUE TITLE
[U8] Can't User New User Groups

### ISSUE THREAD

**Issue by 0Neji** [umbraco/Umbraco-CMS#5641]
I'm trying to set up a new user group which has restricted permissions and access content nodes, however when I try to login as this user I'm presented with the Umbraco Back Office but with no menu, no content tree. I do see my user icon but if I click it, I'm immediately returned back to the login screen.

Reproduction
------------

Tested on an existing Umbraco 8 project and a fresh install. To test on fresh install:

1. Create new project/install of Umbraco 8 via NuGet
1. Login and go to `Users`
1. Go to `Groups` (top right)
1. Click `Create group`
1. For testing purposes, I used the following details
     Name: Test
     Sections: Content
     Content start node: Content root
     Default permissions (checked if listed, unchecked if not): Browse Node, Delete, Create, Publish, Unpublish, Update, Copy, Move, Sort
1. Save
1. Create new user (replicated with both invite and manual creation)
1. Assign new user the `Test` user group
1. In a private browser window, try to login as the user.

### Specifics

Umbraco Version: 8.0.2
Browser: Tested on latest version of Chrome, Brave, Firefox (all on Windows 10)

### Expected result

Expected successful login with access to only the selected nodes/section.

### Actual result

When I login I see:

![image](https://user-images.githubusercontent.com/4700480/59268212-1fc24180-8c44-11e9-9d0c-46f129a7c601.png)

And the console shows the following errors:

![image](https://user-images.githubusercontent.com/4700480/59268227-29e44000-8c44-11e9-857a-49bfae6ed305.png)

It looks like for whatever reason, the user doesn't have access to the JS files it needs to load the CMS fully. I've also tried the same user works with the 'Administrator' user group and login is allowed, works as normal.

**Comment by nul800sebastiaan** [comment]
Looks like something is requiring a media start node to be set, even if you have no access to the media section. From your errors, it seems like it might have something to do with the tours.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by AndyButland** [comment]
Started to have a look at this.  The problem seems to be that the default claim types for a back-office user require a start media node - see [here](https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Security/UmbracoBackOfficeIdentity.cs#L118) - which if absent, triggers an exception [here](https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Security/UmbracoBackOfficeIdentity.cs#L105).

So a workaround for now would just be to set a media start node.  If the user doesn't have access to the media section, they still won't be able to access it.

**Comment by kjac** [comment]
@AndyButland is spot on here. I do believe the best course of action is to make the start nodes mandatory for user groups; see PR #5911 for more info.

**Comment by kjac** [comment]
#5911 didn't work out; new PR in #5917
