### ISSUE TITLE
Both view and content models are PureLive, with different versions error when making change to doctype

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco-CMS#5671]
[Forum thread for reference](https://our.umbraco.com/forum/umbraco-8/97731-error-causing-the-application-to-restart-after-a-doctype-change).

_I've tried this on v8.0.1 and v8.0.2 and am able to replicate the issue. When making changes to a doctype and refreshing the front end of the website I am receiving the following error:_

Cannot bind source content type Umbraco.Web.PublishedModels.PcGridLayout to model type Umbraco.Web.PublishedModels.PcGridLayout. Both view and content models are PureLive, with different versions. The application is in an unstable state and is going to be restarted. The application is restarting now.

**Description:** An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.   

**Exception Details:** Umbraco.Web.Mvc.ModelBindingException: Cannot bind source content type Umbraco.Web.PublishedModels.PcGridLayout to model type Umbraco.Web.PublishedModels.PcGridLayout. Both view and content models are PureLive, with different versions. The application is in an unstable state and is going to be restarted. The application is restarting now.

_I've been able to fix the error by waiting for the application to restart or touching the web.config before I load the front end of the site._

Also, I'm curious if this might be related to [fix this issue too](https://our.umbraco.com/forum/umbraco-8/97235-possible-caching-error-umbracowebpublishedmodelsimage#comment-308507)?

**Comment by nul800sebastiaan** [comment]
Thanks @bkclerke ! We have done work in the past to make this error at least detailed and a bit more friendly and we thought it should not happen any more but apparently there's still a race condition where this gets triggered. 
Is there a way you can easily reproduce this error?

**Comment by bkclerke** [comment]
Yes! I just setup a local instance of v8.0.2. It has no starterkit and using SQL CE to just get it up quickly. I created a homepage doctype with a template. Put 2 test properties on it. No problems with the front end of the site loading when I make changes with only 1 doctype in there. When I created a second doctype and saved it (1 test property), i refreshed the front end of the site and I see the error:

_Cannot bind source content type Umbraco.Web.PublishedModels.Home to model type Umbraco.Web.PublishedModels.Home. Both view and content models are PureLive, with different versions. The application is in an unstable state and is going to be restarted. The application is restarting now._

My Home template is using the default inherit and using content models that are created with a template and I simply added Model.Title and Model.BodyText to them to render the two properties I made on my homepage. The second doctype I only added 1 property on, title / textstring, with no template and after saving and publishing I was able to hit the error. 

Hopefully that helps.

**Comment by tormnator** [comment]
I've had similar issues in Umbraco 7 for quite some time. They're not easily reproducible, I haven't been able to create a sequence of steps. I'm using VS 2017, and ModelsBuilder in AppData mode. Sebastiaan, you're mentioning a race condition, do you have more details?

I have added some code to detect the error when it happens (no work around), and here is a screenshot:
![image](https://user-images.githubusercontent.com/15617453/59701474-f4df6c80-91b2-11e9-8040-6cecba7094b3.png)

**Comment by clausjensen** [comment]
The reason for this happening is the use of the models generated by modelsbuilder, to populate the object-based cache in V8. Whenever a document type is saved - all models are regenerated (recompiles everything - also classes that haven't actually changed).

What we do is to then tell the cache that it should regenerate the cached data for the document type being saved - which causes the data in the cache to be repopulated, which is also why you should see that it sometimes seems like it actually just works.

The problem is however that since all model classes have been regenerated - the objects in the cache (not of the exact type that we have been clearing cache for) are no longer .NET-class-wise made using the same _types_ as the types we now have and therefore we see the issue of not being able to bind the data between these two types. Although the types may look and seem very much like the same type - they are considered different types due to being recompiled.

What we need to do is to ensure that whenever we have to regenerate all models - everything that was using the old models (in the cache) needs to be cleared so it can be repopulated with the correct types.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5767

**Comment by bkclerke** [comment]
Thank you so much for being awesome and fixing this issue. You guys are amazing! :)

**Comment by giacomolanza** [comment]
I encountered the same issue in Umbraco Version 8.9. Every time I make a change to a doctype I receive the same error described by @bkclerke. Here is a screenshot:

![Image 2](https://user-images.githubusercontent.com/10447223/104455531-b46eed00-55a7-11eb-85b2-bc7fc64b3863.jpg)

I need to delete the /App_Data/TEMP folder and reload the site to make it works. As commented by @nul800sebastiaan this issue hould have been fixed.
This is my ModelsBuilder configuration:

`<add key="Umbraco.ModelsBuilder.Enable" value="true" />`
`<add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" />`
`<add key="Umbraco.ModelsBuilder.ModelsDirectory" value="~/App_Code/Umbraco.Web.PublishedModels" />`

How is it possible? Thanks.
