### ISSUE TITLE
📮 Being able to set public access settings on multiple nodes

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#5726]
I would like to be able to select multiple nodes to be protected at a time. This would make it easier and less error prone, when dealing with multiple protected pages.

Currently I have to right click every node, select Public Access, select group based protection, click next, open the member group dialog, click the desired group, click submit, open the node picker for the login page, click the desired page, click submit, open the node picker for the error page, click the desired page, click submit, and then click save. At least 14 clicks for each page I need protected (luckily child pages inherit the settings :)).

Would be great if you could make a general public access setting, where you pick the pages you need protected, the groups to allow, the login page and the error page, it would only be ~15 clicks in total. And even less if you have to add new groups to the protection, or switch the login/error page.

**Comment by nul800sebastiaan** [comment]
Interesting, this is the first time I hear of a requirement for multiple different areas of a site needing the same member-based protections. Can you elaborate on why you need 15 areas to be protected and why they can't be under a single root node? I'm asking because I have no imagination of course haha! 😉

My gut feeling says: this would probably be a great idea for a package, to have a dashboard that has a content picker and allows you to set publish access up for those nodes in one go. 

But as I said I'd love to hear more about the requirements.

**Comment by skttl** [comment]
My use case is kind of a public facing extranet, where only specific pages need to be protected. 

![billede](https://user-images.githubusercontent.com/3726467/60177057-39ed4980-9818-11e9-8b75-91bc4fadd463.png)

As you see from the tree, some pages are not protected and are meant to be open for all users, while the protected ones are only for known users.

I could (as you wrote) have put them all in a folder node, and set the rules on that. That would work in my case, but then I have a URL-part that doesn't do anything other than making my life easier.

It also won't cater for the situation where you would have different content sets per user group. Think like an extranet where you have pages for marketing, sales, production team etc.

**Comment by nul800sebastiaan** [comment]
Sure, the URL part should be easy to fix though with a `UrlSegmentProvider`.

> It also won't cater for the situation where you would have different content sets per user group. Think like an extranet where you have pages for marketing, sales, production team etc.

Wouldn't they be in different member groups and therefore you'd need to apply different things per node anyway?

**Comment by skttl** [comment]
Yeah, but then you would need (for easy updating) a folder for marketing, a folder for sales etc. And what to do with overlapping pages? Like if you had some kind of "sales material page", that should be available for both marketing and sales?

It's probably not going to be easy to figure out the UI. Should it be defined from membergroups in, content in or something else?

You could have a set of "public access" rules where you set
- content (which pages are protected)
- groups (which groups have access)
- pages for login/error

But then another headache comes. What if you have the same content in two rules, but the rules have different pages. Which page to show? Or should you be allowed to have the same content in different rules?

This is probably going to get hairy :)

Regarding the UrlSegmentProvider, I would need to make my own contentfinder too, right? Then I would have that logic to maintain too.

**Comment by nul800sebastiaan** [comment]
I think we're talking in hypothetical scenarios now, I would really like to stick to real life usage scenarios. As I said earlier, we haven't seen this request before. I recognize that updating 15 nodes right now is a bit painful but also.. how often is this going to happen? 

We're all for making things much easier but only if it makes sense for a lot of people, if it only impacts a few users who have to do this once a year, we need to consider the impact of having to maintain code that's barely used vs. making life easier for a few. 

> Regarding the UrlSegmentProvider, I would need to make my own contentfinder too, right? Then I would have that logic to maintain too.

If you'll permit me to be a little bit flippant: it's a luxury problem to have the option to do what you need. 😉
On a serious note: since you don't have to deal with SEO etc, I would think an extra URL segment would be the least of your problems. 😊

**Comment by skttl** [comment]
Just one more thing that could fail at some point :)

I get that this issue probably is quite hypothetical - let's just keep things as they are, until theres a bigger demand for it. As I wrote in the previous comment, it's probably not a small task to do :)
