### ISSUE TITLE
Accidental click outside of a dialog closes the dialog, and changes are lost

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#5727]
When you are deep into a dialog (like the public access dialog), and by accident, clicks outside of it, it just closes and forgets all about what you where doing.

A warning or a confirm dialog would be really nice here :)

https://i.imgur.com/8DO3gZ8.gifv

**Comment by nul800sebastiaan** [comment]
Absolutely!

**Comment by kjac** [comment]
I did something similar to another dialog not so long ago. I will have a look at applying that to public access as well. A generic solution across all dialogs is probably going to clash miserably with the current solution for content.

**Comment by kjac** [comment]
In the latest codebase I can't reproduce click-outside-to-close:

![public-access-click-outside](https://user-images.githubusercontent.com/7405322/60254543-72e7f580-98ce-11e9-9a9b-0165d7f065e9.gif)

However the point of this issue is still valid if you accidentally hit "close" after spending time setting it all up. PR #5733 addresses this.

**Comment by kjac** [comment]
Disregard my last comment. It seems to be a bug in the latest codebase... I'm on it.

**Comment by kjac** [comment]
New PR in #5740
