### ISSUE TITLE
v8: Rollback clear image cropper and grid

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5791]
In Umbraco v8 with latest changes in `v8/dev` branch, when I select rollback and select an older version, but without clicking submit button (rollback), but just close the dialog and go back to the content tab the image cropper and grid no longer shows any values.

But when I refresh the page the values image cropper image and grid data are shown.

![2019-07-04_22-18-07](https://user-images.githubusercontent.com/2919859/60686591-18403200-9eaa-11e9-9043-1162e29c0a4e.gif)

**Comment by PerplexDaniel** [comment]
Yes, excellent @bjarnef! I was about to make a new issue and PR with essentially the same but thought "let's see if someone else already did this" ;-)

This applies to all property editors that have their value stored as JSON, so it's quite a big deal.
It it still present in 8.6.1 and [the latest `v8/contrib`](https://github.com/umbraco/Umbraco-CMS/commit/b2a9e17c90ab5c9d2bfa7c7b6d2e738a152073e0).

@nul800sebastiaan Can we please merge the linked PR into v8 soon-ish? Mainly it's about [this commit](https://github.com/umbraco/Umbraco-CMS/pull/5792/commits/b20737a9af76e92a511417d7166c903deee4a191) which does an `angular.copy` of the original property. There are 4 other commits in there with useful stuff but the core bug is fixed by just doing an `angular.copy`, which therefore could also be cherry-picked instead.

Full commit of @bjarnef with the fix is below (just to show it's tiny):

```javascript
// copy existing properties, so it doesn't manipulate existing properties on page
oldProperty = angular.copy(oldProperty);
property = angular.copy(property);
```
Considering #7950 we would just have to change that to `Utilities.copy` instead and we're good to go.

**Comment by bjarnef** [comment]
Oh, it has been a while since I submitted that PR.. almost forgot about it 🙈 

It seems `Utilities.copy` still use `angular.copy()` under the hood, but sure it would be great to use the utility function here instead.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/utilities.js#L21

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5792

**Comment by nul800sebastiaan** [comment]
Ah forgot to update to Utilities.copy - done in 9be4775acfe63d53a8a4bc1557ea7a5268301138
