### ISSUE TITLE
Error in ConvertTinyMceAndGridMediaUrlsToLocalLink when upgrading from v8.0.x to 8.1.0

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#5846]
For reference, see this forum thread: https://our.umbraco.com/forum/using-umbraco-and-getting-started/98108-error-while-upgrading-umbraco-802-to-81

The cause of the issue is that we're trying to read the JSON data from all of the grid items in the content. If the property on the document type at some point was switched from a Rich Text Editor to a Grid datatype you might have old data that is just plain HTML. We're trying to read this data by deserializing the JSON, but of course.. it HTML, not JSON. So it fails.

---
_This item has been added to our backlog [AB#1695](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1695)_

**Comment by nul800sebastiaan** [comment]
Note: as a workaround, you could go in the database and clear all datatypes that should contain grid data but don't right now. **Please make database backups if you go down this road!**

**Comment by bergmania** [comment]
@nul800sebastiaan, what do we expect as outcome of this task?

1.  Just a better error message telling the user to clean up the corrupt data manually?
1.  Skip the corrupt data in this migration?

The underlying problem is, that you is allowed to change the underlying property editor on a data type to another property editor with a incompatible storage format.
