### ISSUE TITLE
V8/8.1: Tags erased when you "save and publish" an existing page

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#5855]
### Bug summary

I have a composition with a tags field. When I unpublish a page that uses the composition, the tags remain intact. When I "Save and Publish" the page the tags field is not saved. Re-entering the tags and re-saving the page works as expected.

### Specifics

* Happens in Umbraco 8.1
* Testing in Brave and Google Chrome on macOS Mojave
* Rebuilding the page cache does not help
* Editing the page after the tags have been cleared allows me to save new tags, so it appears to only happen when publishing a page with existing tags

### Steps to reproduce

* Edit an unpublished page with tags, click the "Save and Publish" green button; unpublish/publish in a list view works fine

### Expected result

* Tags should remain intact during publish/unpublish

### Actual result

* Tags do not get saved on re-publish unless the tags field is empty.

**Comment by stevemegson** [comment]
I think this is happening when the tags data type is configured for CSV storage and the page is saved without editing the tags. The unpublishing and re-publishing steps aren't directly related, except that publishing an unpublished page is a common reason to open a page and then save it without editing any properties.

The tags editor receives the CSV value from the database, and because no changes were made this value is sent back to the server untouched when the page is saved. But `TagPropertyValueEditor.FromEditor` expects to receive a JArray, and discards the CSV value.

**Comment by argentini** [comment]
I am using CSV, so that makes sense.

**Comment by argentini** [comment]
CONFIRMED: Only happens with the CSV storage option.

**Comment by nul800sebastiaan** [comment]
This is fixed in https://github.com/umbraco/Umbraco-CMS/pull/5966 and will be released with v8.1.1 (tentatively scheduled for early next week).
