### ISSUE TITLE
Umbraco 8 should honour the casing of views as entered by the user and not lowercase the first letter of a View file name

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/Umbraco-CMS#5922]
When I create a new View in Umbraco it makes the first letter of the filename lowercase (it also removes any leading underscores, but that's another matter).

This happens in v8.1 and also happened in earlier v8 versions

Umbraco should create view files using the casing entered by the user

**Comment by NikRimington** [comment]
It should be easy to override the name, or configurable to say "partials" for example, all have a leading _
There are more questions around this for me rather than just saying it should respect what is typed as, for example, I still like the convention of _layout for my master template. Then I want my main templates to all start with a capital and my partials to start with an _ and lowercased first letter.

Configuration options for these things would be great imo :-)

**Comment by callumbwhyte** [comment]
As the alias generated by the back office when creating a template or view is pascal case, the files that created are too. It feels a little wrong as Visual Studio creates these as title case by default.

I’m pretty sure this is a bug in V8, as in V7 all templates and views had title case aliases - unless this is an intentional feature and I’ve missed something?

Should hopefully be moderately easy to fix the alias generation code in the backoffice to make these title case by default.

**Comment by deMD** [comment]
@callumbwhyte You mean the alias is camelCase I assume? 

I feel like files should follow Mvc conventions, which means all normal views should be PascalCase and all Partial views should be prefixed with an '_'.

**Comment by DanDiplo** [comment]
Agree. I found it annoying in 7 they stopped allowing an underscore, but forcing case (especially when it goes against Microsoft conventions) is just plain naughty. Stop it at once.

**Comment by ronaldbarendse** [comment]
Because filenames can't contain certain special characters (see [`Path.GetInvalidFileNameChars()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidfilenamechars)), this is probably why it uses the alias (as that's already sanatized).

Might be better to just remove the special characters from the template name to use as filename, so this also allows the leading underscore.

**Comment by kjac** [comment]
This has been addressed in #4889 - unmerged as of now, but at least there's a fix 😄

**Comment by nul800sebastiaan** [comment]
Closing this as the PR was merged for v8.7.0 https://github.com/umbraco/Umbraco-CMS/pull/4889
