### ISSUE TITLE
Custom Exception classes don't conform to best-practices

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#5947]
As discussed with @Shazwazza in PR https://github.com/umbraco/Umbraco-CMS/pull/5895, custom `Exception` classes in Umbraco currently don't all conform to the best-practices. See also:
- https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229064(v=vs.100)
- https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable
- https://stackoverflow.com/questions/94488/what-is-the-correct-way-to-make-a-custom-net-exception-serializable

This might not directly cause bugs or issues, but it's a small effort to just get it right 👍

**Comment by ronaldbarendse** [comment]
@Shazwazza This should probably also get the `category/breaking` label, right?

**Comment by Shazwazza** [comment]
Marked as breaking due to different exceptions being thrown in some scenarios, the mapping is:

* `DuplicateKeyException` -> `ArgumentException`
* `ArgumentNullOrEmptyException` -> both `ArgumentNullException` and `ArgumentException`
* `FileSecurityException ` -> `UnauthorizedAccessException`
* `WontImplementException` -> `InvalidOperationException`
