### ISSUE TITLE
Change name of Computed field for Grid in Examine

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#6036]
As I am working on Elastic search which is strongly typed base, I notice a small issue with handling of a computed grid field. As Umbraco is storing computed field on key "{property.Alias}" and if we try to make strong type model of that using "." as determination of children we finish with something like that:

```
GRIDALIAS = 
{
"Computed Value of Grid",
"Full Width": ["Value 1 of Full Width"]
"Article": ["Value of Article"]

}
```

I am proposing to change the key to "{property.Alias}.Computed", because in that way we will finish with:

```
GRIDALIAS =
{
"Computed": "Computed Value of Grid",
"Full Width": ["Value 1 of Full Width"]
"Article": ["Value of Article"]
 
}
```

Maybe someone has a better idea and could share that with me :)

**Comment by bielu** [comment]
@Shazwazza as we spoke on twitter and you write on one of the challenges:
"The main challenge with that is that people would no longer just be able to search on the field name like they are used to with other properties." 
I have 2 ideas about how solved that problem:
1.  Make fallback in examine engine to .computed field by default when someone will search by field name
2. Move rows to be stored using different name property name like "GridAlias_Rows".
What do you think about that?

**Comment by Shazwazza** [comment]
@bielu 

1) but how? The only way i can see that happening is if you make extension methods for searching the grid specifically. Examine itself cannot be changed to deal with this so it needs to be done in Umbraco somewhere. If people use raw Lucene searches then there's no way to automatically deal with this. 

2) Changing how things are indexed is a breaking change, the only way to deal with that is backwards compatible config switches where if they don't exist they will use the old behavior and if they do exist they will be toggled based on the value (i.e. for new version releases we'd enable the config switches so that upgrades are not affected). Can you elaborate more on this and how this solves the problem?

**Comment by bielu** [comment]
@Shazwazza 
1. Good point about using raw Lucene. Hmm, it means is no good way to solve that without breaking change and causing a lot of issues.
2. About how this solving my issue, it will solve that issue via moving grid rows properties to a different key than GridAlias and in that case we after casting to JSON we don't have a definition like described in first post but something like that:
`GRIDALIAS = "Computed Value of Grid",
GRIDALIAS_ROWS{
"Full Width": ["Value 1 of Full Width"]
"Article": ["Value of Article"]
}`
It means I am not hitting again a problem with the double definition of GridAlias field in the index. 

From my perspective, we could in both solution use switches as you suggest and make breaking change with compatibility mode and allows to use more complicated engines like Elastic which use the following structure:
![image](https://user-images.githubusercontent.com/2244074/62539358-f50ff600-b84c-11e9-9de1-30983e5742de.png)

**Comment by Shazwazza** [comment]
@bielu So would it be accurate to say that the real issue is 'just' that there's a '.' in the field name and if we changed the '.' to another char like '_' that this would work for you?

**Comment by bielu** [comment]
@shawazza yes it will be accurate.

**Comment by Shazwazza** [comment]
@bielu great! in that case i'm sure we can make this work one way or another. The thing responsible for putting the names into the index is the grid property editor itself and it's `GridPropertyIndexValueFactory` class. So there's a few ways we can make that work:

### Work around

You can work around this issue with events to change any '.' notation in field names to '_'. You could use the event on `BaseIndexProvider.TransformingIndexValues` to do that. IMO if this works for you that would be the easiest way to handle this and you can ship your package with this change without worrying about any umbraco compatibility since your package would be in control.

### Else ....

There's plenty of other things we could do from having yet-another-config value for this, or having  new `GridPropertyIndexValueFactoryOptions` class that can be configured on startup which is passed to `GridPropertyIndexValueFactory`,or making the `GridPropertyEditor.PropertyIndexValueFactory` set-able on startup so you can entirely replace it's `IPropertyIndexValueFactory` implementation, or having some event built in to `GridPropertyIndexValueFactory`, etc... 

But I think `TransformingIndexValues` will be able to solve this for you and it seems like a fine extensibility point on it's own?

**Comment by bielu** [comment]
@Shazwazza I start working on workaround as you suggest is any reason why we didn't propagate that event BaseIndexProvider.TransformingIndexValues to IIndex?

**Comment by Shazwazza** [comment]
@bielu that one is probably a mistake, i can't recall any particular reason it wasn't brought down to the interface :/

**Comment by bielu** [comment]
@Shazwazza I think I found why you didn't make that an interface because in your Azure Search you didn't implement that event :). I solved that with indexing and I am closing that issue.
