### ISSUE TITLE
Custom routes break umbraco backoffice

### ISSUE THREAD

**Issue by ekovandbor** [umbraco/Umbraco-CMS#6045]
Forum topic: https://our.umbraco.com/forum/umbraco-8//98388-custom-routes-break-umbraco-backoffice

Umb version is 8.1, the same was in 8.0.2
In general: it looks that simple as described on forum. routes work just fine, but...
lot of functionallity in backoffice start using my routes and get 404. (in doc types the most, network tab totally red). So to use backoffice i have to comment out route lines... and add them back for site. Kinda frustrated thing. Any suggestions?

Would be cool to get some comments on forum topic.

**Comment by nul800sebastiaan** [comment]
You're mapping `{controller}` to your own routes, which would indeed break Umbraco routes. You should probably make your routing more specific to the routes you need for your custom app.

As this is more of a general MVC question and not Umbraco-specific, I'll close this issue.

**Comment by stevemegson** [comment]
Although the solution does boil down to "don't define routes that clash with others", v8 did make this harder. In v7 you could define your custom routes in OnApplicationStarted, after Umbraco has defined its own routes. Then nothing you define can break Umbraco's routes (it can break your content, but that's your own content and your own problem).

In v8, all IUserComposers are composed before Umbraco's routes are defined, so any custom routes you define take priority over Umbraco's routes. You can work around that by defining an IComposer rather than an IUserComposer, and using ComposeAfter to ensure that Umbraco's routes get defined first. However, that does feel like a hacky workaround that shouldn't be the "right" way to define a custom route.

**Comment by nul800sebastiaan** [comment]
It might be that's how it's supposed to work, and we should then document that properly so people can figure out what the best thing to do is. I'll ask around and return with some advise here.

**Comment by ekovandbor** [comment]
@nul800sebastiaan, would be great to get some 'proper' way how to add routes. the way which worked with v6 and v7 umbraco - breaks v8. But this exactly peace of code from your documentation how to add custom routes :)

**Comment by nul800sebastiaan** [comment]
Could be good to point out where our documentation is wrong @ekovandbor  :-) Got a link?

**Comment by ekovandbor** [comment]
Wrongly remembered, you dont specify .MapRoute or .MapHttpRoute, but it is expected to work in the same way as .MapUmbracoRoute. This is what i thought about:

https://our.umbraco.com/documentation/Reference/Routing/custom-routes

**Comment by stevemegson** [comment]
I don't think the documentation is technically wrong if we're looking at v8 in isolation, it's just that the behaviour is different from v7 in a way which can be surprising.

Perhaps there's a place for something like an "IUserFinalComposer" interface that's closer to the behaviour of OnApplicationStarted, then Umbraco can be in charge of ensuring that the order is correct. Using ComposeAfter on your own IComposer achieves the same thing, but the fact that WebFinalComposer sets up Umbraco's routes seems like an implementation detail that we shouldn't be relying on when registering custom routes.

**Comment by ekovandbor** [comment]
Can you please specify exact type to be used in ComposeAfter. was trying to compose after WebFinalComposer, but got runtime exception.

**Comment by stevemegson** [comment]
@ekovandbor, it's `WebFinalComposer`, but it's also important that you're using `IComposer` rather than `IUserComposer`.

WebFinalComposer specifies `[ComposeAfter(typeof(IUserComposer))]`, so you end up with a circular dependency if you try to make an IUserComposer compose after WebFinalComposer. That's probably the source of your runtime exception.

**Comment by Shazwazza** [comment]
Hi all, I hear what you're saying and there's certainly some ways we can make this better and more flexible. v7 definitely has it's own issues with routes but I think people were just used to that.

Routes should be declared in this order: _The most specific to the most general_

Umbraco doesn't add things like a default route like this:

```
routes.MapRoute(
    name: "Default",
    url: "{controller}/{action}/{id}",
    defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
);
```

which is the most generic route. In many cases developers might want this route or a similar generic route which should be added to the end of the route table.

In v7, if you wanted to add this, you would do that in `ApplicationStarted` and that would be fine because Umbraco would have already added it's more specific routes already. *But* what if you wanted to add your own more specific route than Umbraco's? Well then you would have to `Insert` that route in the route table at a higher index. In v8, an issue we solved with the `WebFinalComponent` is to ensure that WebApi's `EnsureInitialized` is called very last after all routes have been created, something that is not solved at all in v7. (see https://github.com/umbraco/Umbraco-CMS/issues/4775)

In v8, with the `WebFinalComponent`, Umbraco's routes are added 'last' meaning the above logic is sort of switched around but also means that WebApi's `EnsureInitialized` is called very last which is a good thing. So there are ways to work with v8 now: If you want a more specific route than Umbraco's you can add routes with an `IUserComposer`. If you want to add more generic routes, then yes you will need to have something like:

```cs
[ComposeAfter(WebFinalComposer)]
public class MyRouteComposer : IComposer { }
```

This will work fine for, but as mentioned above we still ideally want `EnsureInitialized` to be called very last and with the above that won't happen. 

So how do we fix this? We want to have an easy way for people to be able to add more specific routes than the ones Umbraco creates and we want to have an easy way for people to be able to add more generic routes too all while ensuring that `EnsureInitialized` is called last. 

## Proposals

I 'think' that typically people not requiring adding more specific routes than Umbraco's and generally are adding more generic ones. It's also possible to `insert` more specific routes higher in the route dictionary after routes have been added to it, so in theory we only need one place for users to add routes which would be after Umbraco create's it's routes since if people wanted to `insert` more specific routes at that time they could and at the same time easily `append` more generic routes. 

### Solution 1

We 'just' move the routing done currently in `WebFinalComponent.CreateRoutes` back to `WebInitialComponent`. Then if you use `IUserComponent` you'll be adding routes __after__ Umbraco has created it's own and you'll be able to `insert` ones too. Then `WebFinalComponent` will execute after and call `EnsureInitialized`.

I think this will still work fine with the issue solved in https://github.com/umbraco/Umbraco-CMS/issues/4775 for using webapi attribute routing with `GlobalConfiguration.Configuration.MapHttpAttributeRoutes();`

But is this then an 'unbreaking' change? I don't really think so because to work around this problem people are probably going to be using the [ComposeAfter(WebFinalComposer)] which would still work with this scenario.

### Solution 2

We create a `WebRouteComposer`,  `WebRouteComponent` and an `IRouteComposer`. We move the `WebFinalComponent.CreateRoutes` into the `WebRouteComponent.CreateRoutes` and then ensure that `WebRouteComposer` is declared with

```cs
[ComposeAfter(typeof(IUserComposer))]
[ComposeAfter(typeof(ICoreComposer))]
```

so that it runs after `IUserComposer (to maintain current compatibility), and then we change `WebFinalComposer` (which now only deals with `EnsureInitialized`) to be declared with:

```cs
[ComposeAfter(typeof(IRouteComposer))]
[ComposeAfter(typeof(WebRouteComposer))]
```

so that it runs after creating Umbraco routes (WebRouteComposer) and after any custom routes (IRouteComposer).

Then developers can user `IRouteComposer` specifically for creating routes. 

__However__ this is all a bit ugly since it's just working around the problem purely to maintain route order compatibility with 8.1 that people don't like in the first place :/ and there is really nothing different at all between an `IUserComposer` and an `IRouteComposer` apart from when they execute so in my opinion that is confusing to try to explain when you would use one or the other (and in this case, when you would ever use an `IUserComposer` then?)

---

In my opinion this could be easily solved with solution # 1 and it is the most straight forward and clean solution and i don't really think it brings 'unbreaking' changes. Solution # 2 is ugly because we are just adding stuff to avoid potential `unbreaking` changes and also adds to confusion with APIs.

But i would like to know your thoughts?

**Comment by ekovandbor** [comment]
Leaving here proper answer, which works.

This peace of code is not working, result is the same as with iUserComposer:
```
[ComposeAfter(WebFinalComposer)]
public class MyRouteComposer : IComposer { }
```
It works only with combination of ComponentComposer:

```
[ComposeAfter(typeof(WebFinalComposer))]
    public class RouteComposer: ComponentComposer<RouteComponent>
    {
    }

public class RouteComponent : IComponent
    {
        public void Initialize()
        {
            RouteConfig.Register(RouteTable.Routes);
            GlobalConfiguration.Configure(WebApiConfig.Register);
        }

        public void Terminate()
        {            
        }
    }


```

**Comment by Shazwazza** [comment]
I wrote this as shorthand

```cs
[ComposeAfter(WebFinalComposer)]
public class MyRouteComposer : IComposer { }
```

You would still need to fill in the actual logic to add your component as per a normal component, see docs https://our.umbraco.com/documentation/Implementation/Composing/ . You can of course use `ComponentComposer<RouteComponent>`  which is the shorthand version for an `IComposer` that doesn't add anything to DI.

**Comment by stevemegson** [comment]
Solution 1 makes sense to me. I wasn't sure whether any of the routing in `WebFinalComponent` relied on things that might be registered with an `IUserComposer`. If they're all "core" routes then I don't think solution 1 breaks anything.

**Comment by Shazwazza** [comment]
@stevemegson , or anyone - does anyone feel like whipping up a PR for this? the change would be super easy to do for Solution # 1 above

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6074
