### ISSUE TITLE
Umbraco Multi Url Picker - Recursive not working in RTE

### ISSUE THREAD

**Issue by shaishavkarnani** [umbraco/Umbraco-CMS#6111]
We tried Umbraco Multi Url Picker - Recursive option in a macro and tried to access in RTE. But it is not able to pickup the parent value if current node is empty.

So, we tried with this work-around as recursive is not working. It always show HasValue as True even if node has empty Multi Url Picker.
```
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web.Models

<div id="usefulLinks">
    <div class="page-header">
        <h2>Useful links</h2>
    </div>

    @{
        var links = Model.Content.GetPropertyValue<IEnumerable<Link>>("usefulLinks");
        if (!links.Any())
        {
            links = Model.Content.Parent.GetPropertyValue<IEnumerable<Link>>("usefulLinks");
        }

        if (links.Any())
        {
            <ul style="padding-left: 2em;">
                @foreach (var link in links)
                {
                    <li><h5><a href="@link.Url" target="@link.Target">@link.Name</a></h5></li>
                }
            </ul>
        }
    }
</div>

```

**Comment by stevemegson** [comment]
You've identified the underlying bug here - `HasValue` is always true for a Multi Url Picker. V7's test for HasValue is equivalent to `String.IsNullOrWhitespace`, but a Multi Url Picker stores `[]` for an empty list. V8 solves this problem by allowing an `IPropertyValueConverter` to provide its own implementation of `IsValue`.

The simplest fix would be to always treat `[]` as not-a-value. That would be a breaking change if anything else depends on `[]` being a valid value, though.

**Comment by nul800sebastiaan** [comment]
Yep, Steve hits the nail on the head, unfortunately when we implemented HasValue for this, we didn't consider the value might be an empty json array. However, changing this now to work better is a breaking change.

I believe this workaround is working for you? It is a totally legitimate way to do querying of the multi URL picker and we'd encourage you to keep using it! 👍 

I'll close this for now as I believe there's nothing more we can do here without making breaking changes unfortunately.
