### ISSUE TITLE
Data type usage stats

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#6161]
I am trying to prevent unnecessary duplicates of data types, specifically caused by the document type editor offering "create new" before "reuse".

And also prevent breaking changes to existing data types (like if you were to remove the root node on an MNTP for example)

Could it be possible to show which document types a data type is used on, and which data types have the same configuration?

That way the user can be instantly aware of any doctypes that might break from changing an existing data type, and which data types to reuse instead of creating a new one.

I have a very crude mockup of how it could look (it should obviously be prettier).
![billede](https://user-images.githubusercontent.com/3726467/63408524-8a83bc00-c3ef-11e9-9f26-5da1d808d43a.png)

In the overlay in the document type editor, you could also have the possibility to reuse existing editors listed.
![billede](https://user-images.githubusercontent.com/3726467/63408816-26adc300-c3f0-11e9-8caa-e36cda8dd5ba.png)

**Comment by kjac** [comment]
I think usage information is a brilliant idea 👍 

Duplicate detection however is a not a trivial task and thus subject to be rather error prone - specially as the detection must happen live while editing the datatype. And while I agree with your take on duplicate datatypes, I'm not entirely sure this opinion is shared by HQ. 

Let me know if you would like some help with this 🙂

**Comment by skttl** [comment]
I know HQ doesn't want reuse as the default, this is why I thought some information was needed when people were about to create duplicates :)

I would love to submit a PR - but waiting for HQ approval of the idea.

**Comment by nul800sebastiaan** [comment]
I think, currently, we're much more interested in auditing after the fact than live detection of duplicates. [Media item tracking](https://github.com/umbraco/rfcs/pull/17) is just the first new thing we want to work on, later on we know we want a more complete tracking tool like "Nexu".

We'll discuss it at HQ soon!

**Comment by nul800sebastiaan** [comment]
Hey @skttl - For now, we don't have plans to build the feature as suggested into Umbraco as it might be more confusing for newcomers than it is helpful.

We think the idea is very interesting though and it would make for an interesting package, let's call it a "refactor dashboard". 

Imagine a dashboard and what you could do on that is a similar thing you're doing now: "this configuration is the same for these 3 datatypes". But instead of offering live suggestions, while creating the datatype, you could offer to do a refactor in this dashboard.

- Maybe you're perfectly fine with having 3 datatypes that have the same configuration, but you wish one of the configuration options was different for all 3 datatypes (for example: "Show open button" needs to be enabled for all 3 of  them). Press a button and.. presto! All 3 datatypes are updated with the new configuration.
- Maybe you want to keep things really DRY: press a button and.. presto! All 3 datatypes are now just 1 datatype and the document types on which they are used are updated to use the consolidated datatype.

**Comment by leekelleher** [comment]
Cross-referencing PR #6625
