### ISSUE TITLE
If Grid Module contains object in value, then Grid Layout property is not in Examine Index

### ISSUE THREAD

**Issue by SoerenDeger** [umbraco/Umbraco-CMS#6164]
We using a lot of custom Grid Modules in Umbravo v8.1.2. But the Property of "Grid Layout" is not every time in the examine index.

It seems, that the grid layout property is always not indexing, if $scope.control.value contains an object instead a string.

At first I add a custom Grid module with an object in value:
![screen1](https://user-images.githubusercontent.com/7769446/63423763-4a333680-c40d-11e9-9976-8d03e9af6cd9.jpg)

In Examine Dashboard the grid property is missing:
![screen2](https://user-images.githubusercontent.com/7769446/63423764-4a333680-c40d-11e9-94c8-7fb83650b565.jpg)

At second, I add a custom Grid module with a simple string in value:
![screen3](https://user-images.githubusercontent.com/7769446/63423767-4a333680-c40d-11e9-85a6-cd9c5200a5d8.jpg)

Now, the complete Grid Layout property is in Examine Index:
![screen4](https://user-images.githubusercontent.com/7769446/63423769-4a333680-c40d-11e9-8640-7bef570ef31c.jpg)

This is the Grid Module "Anchor" with a string in value:
![screen5](https://user-images.githubusercontent.com/7769446/63423770-4acbcd00-c40d-11e9-94a4-d4ec41fd6762.jpg)

This is the declaration in the "Headline/Text" Controller with an object in value:
![screen6](https://user-images.githubusercontent.com/7769446/63423771-4acbcd00-c40d-11e9-90a8-8ba8e0468265.jpg)

**Comment by nul800sebastiaan** [comment]
Unfortunately only the first value is displayed in the backoffice, there's more info and a PR for this available in this issue: https://github.com/umbraco/Umbraco-CMS/issues/5994

**Comment by SoerenDeger** [comment]
@nul800sebastiaan I think this issue is related to #5994, but it's not the same. 

Now, I have enter this headline:
![screen7](https://user-images.githubusercontent.com/7769446/63427092-a3eb2f00-c414-11e9-89ff-c1b93bacad89.jpg)

But If I search in Examine Dashboard for this headline, I get null results:
![screen8](https://user-images.githubusercontent.com/7769446/63427280-13f9b500-c415-11e9-86ba-19fd9e9344e8.jpg)

The strange thing is, if I add the anchor module to the grid layout (field is shown again in examine management), I get already null results. But the raw grid_layout field contains the search text:
![screen9](https://user-images.githubusercontent.com/7769446/63427455-70f56b00-c415-11e9-9cfe-acfa8b5ab916.jpg)
![screen10](https://user-images.githubusercontent.com/7769446/63427456-70f56b00-c415-11e9-8714-09d6d2514b61.jpg)

**Comment by nul800sebastiaan** [comment]
Okay, we'll need to try and reproduce then.

**Comment by SoerenDeger** [comment]
@nul800sebastiaan Thank you! Now, I have tested this again with the code from the PR in 5994. The issue here still exists... The field is complete missing in examine index. It's not in the management dashboard and a search for the term has null results.

**Comment by stevemegson** [comment]
There are a couple of things going on here. The `__Raw.gridLayout` field isn't indexed, so your search won't find the text there. The text content of the grid should also appear in the `gridLayout` field, where it's indexed. You should see `Anchor 1` in that field in your example, and be able to search for it.

The grid chooses to ignore non-string values when building the value for `gridLayout`, since it can't know what the JSON represents. It could instead extract any string values within the object. Potentially this indexes some text that isn't user-facing content (like "h2" in your headline example), but arguably the current behaviour already does that with your anchor module - it can't really know what a simple string value represents either.

Secondly, if the indexer finds no text to include in the `gridLayout` field then it doesn't generate the `__Raw.gridLayout` field either. That's why adding the anchor module makes the `__Raw.gridLayout` field appear.  This would be a simple change that might avoid some confusion, though it wouldn't affect your search results.

**Comment by SoerenDeger** [comment]
Hi @stevemegson, thank you, this is all comprehensibly. But there must definitely be some way to index values ​​of grid layout objects. 
Otherwise nobody can use a working full-text search in V8 anymore if the grid layout is used with custom modules.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6201

Cherry picked for 8.1.4 742105594e274d913f9254a7d01daa946006e376
