### ISSUE TITLE
Ensure all helper methods properly HTML encode text

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#6275]
After reporting the `ReplaceLineBreakForHtml` method didn't properly HTML encode the text (https://github.com/umbraco/Umbraco-CMS/issues/6226), making it hard to use and therefore easily prone to XSS attacks, @sniffdk noticed this might also be the case with the `Truncate` method (https://github.com/umbraco/Umbraco-CMS/pull/6235#issuecomment-527029498).

Having looked at it, the `Truncate`, `TruncateByWords` and `StripHtml` methods all expect HTML input (the parameter name is `html` and they have overloads accepting `IHtmlString`), so these might only need some clarification not to pass in unencoded text.

A quick search reveals a lot of other methods also accept text input as `string` and return it **without HTML encoding it** as `HtmlString`/`IHtmlString`:
- `HtmlHelperRenderExtensions`
  - `If`
  - `ReplaceLineBreaksForHtml` (should be replaced by `ReplaceLineBreaks`, as done on `StringUtilities` in https://github.com/umbraco/Umbraco-CMS/pull/6235)
- `PublishedContentExtensions`
  - `IsEqual`
  - `IsNotEqual`
  - `IsDescendant`
  - `IsDescendantOrSelf`
  - `IsAncestor`
  - `IsAncestorOrSelf`
- `IndexedArrayItem`
  - `IsFirst`
  - `IsNotFirst`
  - `IsIndex`
  - `IsModZero`
  - `IsNotModZero`
  - `IsNotIndex`
  - `IsLast`
  - `IsNotLast`
  - `IsEven`
  - `IsOdd`
- `HtmlTagWrapperTextNode` (used on `Html.Wrap()`)

The documentation also doesn't mention how to correctly use these methods: by making sure you manually HTML encode the input before passing it into the method. And even if it did, this can easily be forgotten.

**Comment by nul800sebastiaan** [comment]
Honestly, I can't see a way to do this properly in a non-breaking way, without having ugly overloads of all of these methods. 

I also can't see that we would be willing to introduce a breaking change by fixing all of these methods up in one go. 

While I do recognize the possibility of a XSS problem occurring, this also means that you have a malicious content editor providing this content or someone specifically targeting an editor to get the script in the CMS somehow. The scenario is rather unlikely. 

I'm not sure what to do here so I'll take it to the team and see what their recommendation is.

**Comment by sniffdk** [comment]
It was actually @nul800sebastiaan that noticed the Truncate etc. methods 😄 
I agree with Sebatiaan though, that scenarios causing XSS on those methods is rather unlikely. 
Still a good thing to run it by the team though, so they are at least made aware of the issue.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan I would recommend the following steps if you don't want any breaking changes:
- Obsolete the existing methods accepting a `string` text input and returning `IHtmlString` without properly HTML encoding it (with a clear warning)
- Create methods/overloads with an additional flag to encode the text (the original methods can call this with the flag set to false)
- Optionally add methods/overloads with `IHtmlString` as input, but you could also just `ToString()` the input and make sure it's not encoded (although that's more verbose and creates new instances of `HtmlString`)

IMHO the best, but breaking steps would just be:
- Change the return type from `IHtmlString` to `string`
- Add methods/overloads with `IHtmlString` as input

**Comment by Shazwazza** [comment]
For all of the methods mentioned that are currently returning HtmlString/IHtmlString, yes they should be calling `HttpUtility.HtmlEncode` within those to make sure that things like `valueIfTrue` is html encoded. This doesn't change the return type of the method so binary wise, this is not a breaking change, it is really only a breaking change for people that are expecting that it's not encoded ... which would in theory mean they have potential XSS issues, or the `valueIfTrue` type strings they are passing in are encoded, in which case this would be a functional breaking change. 

In my opinion that is the easiest/best breaking change since it doesn't require any rebuilds, it just needs some documentation and in theory would only affect people that are doing things like:

`Model.IsDescendant(child, HttpUtility.HtmlEncode(someValue))` and manually html encoding things to work around this shortcoming. 

Thoughts?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6545 👍 

Marked as breaking in case people rely on the previous behavior where HTML coming from these helpers did not return encoded html.

**Comment by benjaminc** [comment]
This fix breaks the grid, because the Bootstrap3.cshtml file uses the `If` method to conditionally add a container `div` around the content if it is a single-column.  Since the content is now HTML encoded, you end up with `<div class='container'>` in the visible text on the page, rather than as a DOM element.

Seems like you need to add at least an `If` method that takes an IHtmlString as the true and false values so that people who were relying on the previous behavior, including the Grid, can still use these methods.

**Comment by ronaldbarendse** [comment]
The grid views are a mess indeed, dynamics, casting of objects, mixed single/double quotes, duplicated code (between normal and fluid) and only shipping with Bootstrap 3 that's end-of-life since 24-7-2019: https://github.com/twbs/release.

The quick fix will be to change those lines to regular Razor statements and have it at least work for now:

```
@if (singleColumn) {
   @:<div class="container">
}
```
