### ISSUE TITLE
V8: Broken link in RTE media picker for media files hosted on S3

### ISSUE THREAD

**Issue by bengyap** [umbraco/Umbraco-CMS#6324]
We have an issue with the media files links in the RTE media picker. In details, we have installed the umbraco S3 plugin which uploads media files to the S3 bucket. In the result, the absolute urls of media files pointing to S3 are stored in our umbraco DB.

This worked fine in the 8.0.2 version. However since we upgraded to latest version 8.1.4, we noticed that media files links are broken in the RTE media picker because the links have become relative path instead of full url in 8.0.2 version. The relative path will not work for our case since our media files are hosted on S3.

When we select and insert a media file into RTE, we see broken link in the RTE as well as it inserts the relative path of the media file.

Also, fyi, the S3 plugin doesn't do anything when it comes to retrieving or displaying the media files, as the absolute urls (pointing to S3) are already stored in database. So I guess it's umbraco to handle the absolute urls of media files stored in the DB

**Step to Reproduce**

For Umbraco version since 8.1.0 with the Umbraco S3 plugin installed, login to the CMS backend.

1. Edit a page with a rich text editor, 
2. Go to the RTE, click media picker to insert an image

### Expected result

All media files stored in DB with absolute urls (pointing the S3), should appear in the RTE media picker sidebar, as well as after they are inserted to RTE.

### Actual result

In the sidebar displaying image list, images don't appear as they are broken links with relative path pointing to local site instead of S3. Clicking on the image, we can see relative path of the image in the "url" field. Inserting the image will result in relative path of image being inserted to the RTE, hence showing broken link in the RTE as well.  However after I save or publish the page, the inserted image appear in RTE with absolute url pointing to S3.

**Comment by nul800sebastiaan** [comment]
Is the conclusion here that, with the S3 plugin installed:

1. Publishing a page in 8.1 with a broken image link fixes the image link? Or do you HAVE to replace the image first?
2. In 8.1 when you upload a new image, everything works?

**Comment by rasmusjp** [comment]
I've located the problem, this method:

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Persistence/Factories/ContentBaseFactory.cs#L314-L327 

which uses this regex https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Persistence/Factories/ContentBaseFactory.cs#L13

to extract the path from the property, but it's only extracting `/media/` and what's comes after it.

There's a couple of solutions to this

1. Update the regex so it allows absolute urls
2. Since we know that the value could either be JSON (ImageCropper) or a string (Upload) we could check for that and just extract the value from the JSON or use the string
3. Add a new method to the property editor that returns the correct url (which is what the comment mentions).

I'm mostly leaning towards option 3.
