### ISSUE TITLE
v8 - Previewing without changing creates new version

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#6423]
This is the same issue as reported and fixed in v7 but the fix in v7 will not work in v8 so a different solution will need to be manually applied. 

v7 reported issues: 
* https://github.com/umbraco/Umbraco-CMS/pull/1943
* https://github.com/umbraco/Umbraco-CMS/issues/4917

Basically we need to detect if any changes have been made for content when it is saved and if there isn't any changes, then we should not trigger events, etc... and we should return a different status indicating that nothing changed and handle that correctly in the controller (see PR above for inspiration)

**Comment by gregwoodsit** [comment]
For us it wasn't obvious that the Preview actually saves at all (even when making a change). It was assumed this would be temporarily saved and was a surprise that it is added to the history of the page and a new version created.

Options I would think are:
- Don't save the page if user only uses Preview, only when explicitly using Save or Save & Publish
- Add a new status to the log to show Preview was used instead of Save
- Change the Preview button text to be Save & Preview

**Comment by c9mbundy** [comment]
As far as I can tell, it's not actually fixed in v7 either - v7.15.3 still creates a new version if you use preview, regardless of whether or not any changes were actually made.

**Comment by zpqrtbnk** [comment]
not sure I get it - in v8 there's always a published & a draft version, and unless you publish, saving should just update the draft version - so not sure I get what "creating a new version" means

OTOH yes it saves and therefore updates the draft version, and you usually want to trigger events etc to be consistent - some things need to happen when saving - but if no changes at all have been made then yes, should avoid saving (and probably not the case now = need to fix)

as for not saving at all, even when changes have been made, that would be great but requires changes to the cache layer to handle a "preview" content that does not come from db

**Comment by nul800sebastiaan** [comment]
I can't remember when this changed but we don't do this any more, Save & Preview updates the latest version now before previewing. So I'll close this issue as resolved.
