### ISSUE TITLE
Error when previewing pages (under a unpublished parent) on 7.15.3

### ISSUE THREAD

**Issue by kristoffer-tvera** [umbraco/Umbraco-CMS#6629]
When trying to "Preview" a child node of a unpublished parent, i get a 404, unless i "preview" the unpublished parent first.

There seems to be a relation to "Parent" that gets lost, or cut off, when unpublishing. 

Reproduction
------------

### Bug summary

My site structure has multiple levels of nodes. When using the "Preview-mode", I experience issues if the page I am attempting to preview, has a unpublished parent.

This problem only persists until I have clicked "Preview" on the unpublished page, and on all the ancestors between the unpublished page, and the page I actually want to preview.

### Specifics

My current umbraco version:
Umbraco version 7.15.3 assembly: 1.0.7180.24662

My site structure looks roughly like this:
![chrome_difAok6eaH](https://user-images.githubusercontent.com/1053212/66467297-86395e00-ea84-11e9-9569-eedaefd4a703.png)

I am currently route-hijacking all the nodes in the chain of pages that experience this.

I have a custom 404-page.

The site was upgraded (nuget) from 7.15.0 to 7.15.3, but I don't know if this issue was present on the site when it was running 7.15.0.

### Steps to reproduce

Create a root node (A)
Create a child node (B) on (A).
Create a child node (C) on (B).
Create a child node (D) on (C).

At this point, I can preview all pages.

Click "Unpublish" on (B).

At this point, I can not preview C or D.

If i click "Preview" on B, the preview stops giving 404 on C. 
If I then click "Preview" on C, the preview stops giving 404 on D.

### Expected result

Pages should be preview-able without having to chain-preview all the way down from the unpublished parent

### Actual result

My custom 404 page is displayed unless i click "Preview" all the way down from the unpublished parent, in the right order.

---
_This item has been added to our backlog [AB#3416](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3416)_

**Comment by nul800sebastiaan** [comment]
In 7.15 we added a new preview mode which might have a bug. 

For now you should probably try the legacy preview mode, you can switch to this by adding an appSetting to your web.config: `<add key="Umbraco.Preview.Mode" value="Legacy" />`

**Comment by kristoffer-tvera** [comment]
Thanks, @nul800sebastiaan, that solved my issue.

**Comment by stevemegson** [comment]
It turns out that `content.ClearDocumentXmlCache` also calls `content.ClearPreviewXmlContent`. So when a document is unpublished and we remove it from the in-memory XML cache of published content it is also removed from the in-memory XML cache for preview. Saving or previewing each ancestor repopulates the preview cache.

**Comment by AcidNoX** [comment]
Sorry to ask so long after this ticket has been closed. I'm experience a very similar problem but i'm on Umbraco 8.8.0.

The only diffference being that the child content nodes are page "components" (with no template) rather than child pages. But this sounds like the exact same problem.

Was the fix for this ported in to Umbraco 8?
