### ISSUE TITLE
V8: Tree node menu actions permissions are incorrectly recognized when assigning multiple User Groups

### ISSUE THREAD

**Issue by Icarium666** [umbraco/Umbraco-CMS#6647]
When dealing with multiple user groups, available node actions are incorrectly determined and may result in either too low or too high permissions (depending on the order in which groups were created).

Problem was observed and tested on Umbraco 8.1.4, however from what I could see, it still persists in newest version of the code.

Setup:

Content tree:
![image](https://user-images.githubusercontent.com/43412355/66563283-c28cbd00-eb5d-11e9-9767-30cca2b9d2e8.png)

User groups:
![image](https://user-images.githubusercontent.com/43412355/66563314-d33d3300-eb5d-11e9-9861-784423936437.png)

Permissions (left - RO, right - Ho):
![image](https://user-images.githubusercontent.com/43412355/66563673-91f95300-eb5e-11e9-8c5f-29867e552731.png)

Assigning both groups to a single user results in him seeing (and editing if possible) both nodes in content, however action menu items are only shown based on permissions of group with lower Id (since list of user groups is always sorted by Id). The root of the problem seems to lie in _UserServiceExtensions.cs_ (19):
`return userService.GetPermissions(user, ids[ids.Length - 1]).FirstOrDefault();`

**Comment by kjac** [comment]
PR in #6672

**Comment by Icarium666** [comment]
I'd like to apologise in advance if this comment should not be here but under above PR  instead.

Anyway, after checking, I noticed that proposed fix introduces different issue when explicit privileges are not being used - instead of not having enough privileges, user has too much power.

I think a proper explanation of situation is required:
Single Umbraco instance is used for multiple site hosting. All sites use similar layout, thus for editors convenience there was sample site created with Read-only permission group (example RO).
Additionally each site has its own group of editors that should not intefere with others. Thus they are assigned full access permission group (example Ho).
Since new sites are constantly created usage of explicit permissions is inconvenient. Additionally, such approach was working flawlessly in Umbraco 7.

From quick debugging session it seems that when gathering group privileges some information is lost when it comes to node for which we are checking. Please correct me on that if I'm wrong, however returned privileges seem to be defined as if they apply to provided node when in fact they should not (_UserGroupRepository.cs_ (135)). 

We are querying for permissions to node _1219_.  Thus when gathering all permission groups we get:
![image](https://user-images.githubusercontent.com/43412355/66750257-4f03ec00-ee8c-11e9-90d4-c0e19b4b203f.png)
![image](https://user-images.githubusercontent.com/43412355/66750354-85416b80-ee8c-11e9-8133-8fca8338240a.png)

However on returning result we receive:
![image](https://user-images.githubusercontent.com/43412355/66750484-dc474080-ee8c-11e9-9abe-647503293d1c.png)
![image](https://user-images.githubusercontent.com/43412355/66750507-e9642f80-ee8c-11e9-9200-858eaf4b4284.png)

Thus we are effectively getting permissions from node _3269_ instead.

**Comment by kjac** [comment]
@Icarium666 I'm not entirely sure I follow. If you create new editor groups for each site then #6672 should work just fine for you.

#6672 ensures that the permissions used when creating the context menus are the same as are used when figuring out what the current editor is allowed to do when editing content items. 

Permissions are cumulative... Meaning if an editor is assigned multiple groups, that editor should be granted the "sum of all permissions" across these groups. This is what currently happens when the editor edits a content item, but *not* when the context menus are created for that same content. And that's exactly what #6672 fixes.

**Comment by Icarium666** [comment]
@kjac Ok then, seems like I misunderstood it. #6672 does indeed consolidate availability of context menu actions with what is permitted when editing.

That would mean my problem applies to the permission system as a whole and that the system isn't as intuitive as it seems.
Given two user groups:
- content root set to node A with full permissions
- content root set to node B only with browse
I would expect that user granted with both of those groups cannot edit node B and it's descendants. Yet currently it is possible.
Guess I'll put this under discussion either as a separate issue or on umbraco forums.

Thank you.

**Comment by stevemegson** [comment]
@Icarium666 You can get that result by giving the user groups permissions under "Granular permissions" rather than "Default permissions".

The default permissions section gives a user those permissions on any node that they can see in the tree, so the default permissions granted to the first user group also apply node B and its descendants. If you instead grant the first user group granular permissions for node A, the permissions will only apply to node A and its descendants.

**Comment by Icarium666** [comment]
@stevemegson That was my first thought when I was thinking of a solution to my problem. However the "Granular permissions" did not apply to node descendants. Unless this behaviour was changed/fixed in versions later than 8.1.4

**Comment by poornimanayar** [comment]
PR in https://github.com/umbraco/Umbraco-CMS/pull/6672
