### ISSUE TITLE
An Authorization error while Unpublish,Delete and navigating to Developer Node a content. Am using umbraco v7.12.0

### ISSUE THREAD

**Issue by luqmanmoideen** [umbraco/Umbraco-CMS#6690]
Getting an Authorization error while Unpublish,Delete a content & Navigating to developer and some other nodes. I am not getting any issues while running on local server. 
I started this project with Umbraco v7.14.0 and because of my server doesn't support .exe files i downgraded my Umbraco v7.12.0 and got Umbraco functionalities works fine expect this Delete, Unpublish Functionalities. Since Delete and Unpublish functionalities are Essential please help me to overcome this.

Am getting 3 types of authorization error.

- While trying to Unpublish a content it saying :- **Authorization error: Unauthorized access to URL: /umbraco/backoffice/UmbracoApi/Content/PostUnPublish**

- While trying to Delete a content it saying:- **Authorization error: Unauthorized access to URL: /umbraco/backoffice/UmbracoApi/Content/DeleteById**
 
- While navigating to Developer node and some other nodes :- **Authorization error: Unauthorized access to URL: dashboard/feedproxy.aspx**

Attaching the screenshot below.

![image](https://user-images.githubusercontent.com/32329102/66810472-f6e0ee80-ef4c-11e9-8e03-50112f800b8b.png)

![image](https://user-images.githubusercontent.com/32329102/66810530-0eb87280-ef4d-11e9-9c08-7ea4c01260af.png)

![image](https://user-images.githubusercontent.com/32329102/66810576-2263d900-ef4d-11e9-99b6-71910c9e743c.png)

**Comment by nul800sebastiaan** [comment]
If you can still reproduce this problem in a clean install of v7.15.3 we can have a look. However, we've not gotten any reports like this before so I have to assume the problem is somewhere in your setup.

> I started this project with Umbraco v7.14.0 and because of my server doesn't support .exe files i downgraded my Umbraco v7.12.0 

We don't use .exe files, so I am not sure why you had to use an older version.

I would recommend you ask about this on our forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
