### ISSUE TITLE
UX Media Picker - V8 : auto selection for the uploaded images and then scroll down to them

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#6844]
When uploading images from the device using the media picker, the users might not know if the uploaded images are really uploaded or not, because there was no action happened after uploading the images. 

as we can see in the below example, I am uploading some images to my media folder:

![MediaPicker](https://user-images.githubusercontent.com/24841143/67550892-e75d6480-f707-11e9-93d7-6e781b0362c6.gif)

What I think that would be better if applied on the above process:

- When a user upload an image, we can place the recent uploaded images at the top of the dialog or at least we can apply an auto scroll to the bottom of the dialog, so the user can see the uploaded images.

- The uploaded images should be selected by default because it would be an extra step especially when we upload many images, we have to select them again.

**Comment by nul800sebastiaan** [comment]
Thanks, this has been discussed a few times and while we want to do a complete overhaul of how the media picker works in the future, for now it would be a great ideas to revert the sort order and get the newest files on top, so you can actually see them and pick them immediately after upload. 

It would also be a good idea to select the uploaded item(s) because clearly you uploaded them to do something with them. 

We'd love some help with this if you can!

**Comment by kjac** [comment]
I'm hosting a hackaton tomorrow; we'll have a look at this one.

**Comment by kjac** [comment]
Alright so... #6995 fixes this in part. At least it fixes the auto selection part...

I'm reluctant to start sorting the media picker differently. I'm worried it would be a big behavioral change for existing editors? 

Also scrolling automatically to the bottom of the media picker might introduce undesired CPU spikes on the server, as the client might start fetching thumbnails for every last image in the picker.

**Comment by saifobeidat** [comment]
@kjac Thanks for the PR!

as for the sorting, I think users will not even feel any change, imagine it, editors will upload images then the images will appear immediately, they will not scroll down to find the uploaded images because they saw them already.

Even though, I think it will be much clearer than uploading images and don't know where they went?

**Comment by kjac** [comment]
@saifobeidat I understand your position. I do however believe that we shouldn't just  change the sort order _after_ uploads. That kind of magic behavior is bad in my book. The way I see it, if we need to change the sort order we should do it from the very beginning. And that's why I argue the behavioral breaking change for existing editors.

**Comment by kjac** [comment]
Can't argue against the relieved sigh of thousands of editors! I'll get on it 👍

**Comment by kjac** [comment]
Strike that. Adding sorting to the entity repository is not something you "just do" 😢

**Comment by saifobeidat** [comment]
Hi @nul800sebastiaan , sorry but could give me an update for the kjac's PR.. when It can be merged?

**Comment by MosabAbuzaid** [comment]
Hi all i also have the same issue ten they closed my issue and tell me to come here 
and i would remind that we need to solve this in rich text editor too.
i hope that if you would to pull a release that will fix this issue.

**Comment by MosabAbuzaid** [comment]
i think that this solution stop working since i upgrade to 8.4

**Comment by emmaburstow** [comment]
Fixed in #6995
