### ISSUE TITLE
how do distributed call works in umbraco 8.2.0

### ISSUE THREAD

**Issue by emeraldium** [umbraco/Umbraco-CMS#6920]
Hi Guys

can you explain how distributed call works in version 8.2.0? i understood that there are no longer definition in umbracosetting.config, i also understood that sync is being managed via UmbracoCacheInstruction Table in the DB. can some one please explain how it works?

thanks E

**Comment by nul800sebastiaan** [comment]
Correct, that's been deprecated since v7.3.0 and we'd encourage you to use Flexible Load balancing on versions above 7.3.0 where this is all automated for you so you no longer need to configure it - https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/flexible


Makes sure to head out to the forums for further questions: https://our.umbraco.com
