### ISSUE TITLE
umbraco 8 UX suggestion: url for a content node (aka Links)

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7027]
hello

Currently, the url for a content node is located on the Info tab i.e. “Links”.

Is it possible (for convenience) that the Link is also located in the editor footer along with / next to the Save and Publish button?

I realise there might be multiple links for a content node if there are multiple hostnames etc, and that there are also multilingual considerations here such as 1:1 multilingual sites, but if the Link in the footer could just be the default/primary url then that can act as a quick shortcut for the content editor who may be using this hyperlink very regularly.

Thanks
Andrew

ref: original forum topic
https://our.umbraco.com/forum/using-umbraco-and-getting-started//99612-umbraco-8-ux-suggestion-url-for-a-content-node-aka-links

**Comment by nul800sebastiaan** [comment]
This is an interesting point, can you explain why they'd use the links over using the preview? How are they using the links to the page on a regular basis?

I talked to my colleague @nielslyngsoe about this and we think one possibility is to add it to the Publish button dropdown ("Publish and go to page") so as to be accurate, since you could click the link and see the previously published content item, without all the updates they might have just made, which could be confusing.

We'll have a chat about this subject at HQ though. Look forward to hearing your feedback in the mean time.

**Comment by emma-hq** [comment]
Hey @shearer3000,

Thanks for this one! We had a good chat about adding this to the Publish menu but felt it might overcrowd the menu and have decided to leave it as it is. The content editor using the preview is our preferred workflow and for those editors who are confidently using the back office and checking the page after publish, they have the option of the url in that info tab (which does, as you pointed out, use extra clicks) and refresh that page after changes. The URL that would sit next to the Save and Publish button would open a new window each time, which would then need closing and wouldn't be great for the editor either. 

With this in mind, I'm going to close this issue,

Emma
