### ISSUE TITLE
BackOffice "SameSite" cookie

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco-CMS#7035]
Not sure if this is a general Umbraco issue, or specific to Umbraco-Cloud, as I currently only use Umbraco-Cloud-7.

The Umbraco backoffice appears to be setting cookies that are activating the 'SameSite=None' warning in Chrome.

Google have stated that Chrome-v80 will start rejecting such cookies, and Chrome is currently at v78

https://www.chromium.org/updates/same-site 

Presumably, the cookie is required for some backoffice functionality.

Are there plans to deal with this?

---
_This item has been added to our backlog [AB#4921](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4921)_

**Comment by kjac** [comment]
@c9mbundy I believe the cookie originates from the "Getting started" dashboard - at least it does in V8:

![image](https://user-images.githubusercontent.com/7405322/68016756-826cb600-fc95-11e9-8bf3-f06be6b3ef47.png)

![image](https://user-images.githubusercontent.com/7405322/68016826-a7612900-fc95-11e9-919e-149a50c8788f.png)

If you log in as a non-admin i nV8, the dashboard isn't shown and the cookie warning disappears. Try removing the dashboard altogether?

**Comment by nul800sebastiaan** [comment]
That's also the warnings I'm seeing and I guess it doesn't really matter if those cookies get set or not in the future since they are not required for the backoffice to function correctly. 

Are you seeing any of these warnings for localhost / "yourdomain" cookies though @c9mbundy?

**Comment by c9mbundy** [comment]
Hi,

Yes, I am getting some localhost / "yourdomain" cookies, but it's a bit hard to nail down exactly when/where they are being triggered. My suspicion is that they are being set on the first time a UmbracoAuthorizedJsonController promise is actioned, but I'm only guessing at the moment. Subsequent views of the section/node that triggered the cookie warning does not seem to do it again.

**Comment by GitCorne** [comment]
Any progress on this? I have the same warnings on one of my Umbraco 8 on-premise instances. I'have checked some other Umbraco 8 on-premise instances (even from other companies) and it seems all of them are showing this 'A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute' message.

I was wondering how to prevent this messages from being in the console?

**Comment by Shazwazza** [comment]
# Test results

First i clear all cookies and application data from the site with chrome dev tools

I've enabled the chrome settings that will come into affect in v8 by 

> To test the effect of the new Chrome behavior on your site or cookies you manage, you can go to chrome://flags in Chrome 76+ and enable the “SameSite by default cookies” and “Cookies without SameSite must be secure” experiments. 

see https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

## Running on Umbraco Cloud

This particular cloud site does not have the default dashboard

* Loading backoffice (login screen), no cookies are set or warnings
* Once I login I get no warnings
* Test the above again using the `.s1.umbraco.io` suffix and no warnings

## Running on local host 8.6

* Loading backoffice (login screen), no cookies are set or warnings
* Once I log into the back office, i get 3x warnings:
  * A cookie associated with a cross-site resource at http://issues.umbraco.org/ was set without the `SameSite` attribute.
  * A cookie associated with a cross-site resource at http://nightly.umbraco.org/ was set without the `SameSite` attribute. 
  * A cookie associated with a cross-site resource at http://dashboard.umbraco.org/ was set without the `SameSite` attribute.

According to chrome dev tools, the cookies are set via images loaded for the dashboard

```
set-cookie: __cfduid=d8accd1d3df30264df4ef427f783887dd1580867869; expires=Fri, 06-Mar-20 01:57:49 GMT; path=/; domain=.umbraco.org; HttpOnly; SameSite=Lax
```

Another cookie is an ARRAffinity cookie set from Azure for the dashboard.umbraco.org site.

I have no clue how the issues.umbraco.org or nightly.umbraco.org cookies are being referenced. I can't see any requests, code, etc... that reference those addresses. 

# Conclusion

From what I can tell the samesite warnings that I am getting about the dashboard are fine, they will not affect anything and I assume that chome will stop issuing warnings once the new release is out, or at some stage. 

The behavior that Chrome will use if a SameSite value is not used will be "Lax" which is fine. 

In the back office we don't send requests with cookies to any other external domain, and with Lax, these cookie values would not be sent == OK. We also don't want people to be embedding the back office in iframes on other domains, since Lax means that the back office cookies will not be sent in that iframe if that is the case == OK. 

This is the key statement from the chrome blog post

> If you manage cookies that are only accessed in a same-site context (same-site cookies) there is no required action on your part; Chrome will automatically prevent those cookies from being accessed by external entities, even if the SameSite attribute is missing or no value is set. However we strongly recommend you apply an appropriate SameSite value (Lax or Strict) and not rely on default browser behavior since not all browsers protect same-site cookies by default.

Moving forward however, we should do this:

> However we strongly recommend you apply an appropriate SameSite value (Lax or Strict) and not rely on default browser behavior since not all browsers protect same-site cookies by default.

The only thing I think folks might need to be concerned about is their own front-end sites with members if they are trying to share cookies or sessions with members. In that case, Umbraco by default for Members still uses FormsAuthentication and session state. In those cases, configuration options can be applied, here's an MS article about that https://docs.microsoft.com/answers/questions/6842/announcement-samesite-cookie-handling-and-net-fram.html

But again, if you are not trying to share cookies between domains there's nothing to worry about.
