### ISSUE TITLE
Solutions for removal of Change Document Type

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#7044]
The removal of the Change Document Type feature in Umbraco 8 has hit me hard. I know there are reasons for this removal, but its absence leaves a significant pain point when expanding a site. On a site where nodes are heavily interlinked, the need to add a new property to a specific subset of a document type's nodes can open up a big can of worms by creating the need to re-create pages and then manually fix a bunch of broken references to the old UDIs and keys. In my case this has amounted to 5 recreated nodes causing hundreds if not thousands of broken references across a site.

I see three ways this can be rectified:

1. Bring back "Change Document Type", but without the content migration functionality. Changing the doctype would clear out the node's data entirely (maybe creating a backed-up copy), but it would retain the UDI and ID. The effort to re-enter the node's data is nothing compared to the re-linking effort of creating a new node. I believe this would sidestep the additional complexity caused by Umbraco 8's content variants.

2. Provide a way to redirect deprecated UDIs and IDs to new ones. The process for changing a doctype would then be to create the new node manually, carry over the data manually, and redirect the old node's ID and UDI to the new ones, thus keeping the old references working.

3. Provide a way to update references to an old UDI/ID stored in property values such as content pickers and Nested Content, to new replacement values, as a site-wide process.

Any of these options would do a lot to make up for the absence of the old Change Document Type feature.

**Comment by nul800sebastiaan** [comment]
Hi @Zweben - I assume you've read the discussions on issue https://github.com/umbraco/Umbraco-CMS/issues/5070.

The scenario you mention with "a lot of interlinking" I don't quite understand but it seems like you've hardcoded a lot of UDIs? Not sure. 

As noted in https://github.com/umbraco/Umbraco-CMS/issues/5070 - we have no plans for bringing back this functionality and alternatives

Maybe you will benefit from using Nexu (which has a pre-release available for v8 https://www.myget.org/feed/dawoe-umbraco/package/nuget/Our.Umbraco.Nexu) to find out where your content is used and to be able to replace it more easily with a new document.

I guess currently you would also be able to create the new content, with whatever data you need and delete the previous item, after which you can update the key of the new item in the database so that it reflects the already linked UDI.

**Comment by Zweben** [comment]
@nul800sebastiaan 

Thanks for the reply. The UDIs are not hard coded, they are stored in property values, mostly Content Pickers. Nexu looks good, but it looks like it provides tracking and not actual correction of broken UDI references. I also feel that it's a bit of a shame if the plan is to rely on 3rd-parties to address this.

Is it actually safe to change document/media keys directly in the database? Is changing "uniqueID" in "dbo.umbracoNode" the only requirement? If that works safely and carries over through Umbraco Deploy properly, that's a satisfactory solution for me.

**Comment by nul800sebastiaan** [comment]
@Zweben - we are working on all kinds of tracking like Nexu does currently, the first one we're tackling is Media tracking (https://github.com/umbraco/rfcs/pull/17) and out of that flowed Datatype tracking (https://github.com/umbraco/Umbraco-CMS/pull/6625). This means that tracking content items in the same way is something that can hopefully be done quite easily in the future as well (no tiimeline for that yet though). 

This will still require you to re-link all linked items manually but at least you can easily find where items are being used.

I don't want to claim editing anything in the database is safe, ever. So I won't. I would encourage you to make backups before refactoring and verify your changes while in the process. :-)

For now, I will close this issue and refer to #5070 for the implementation of the feature that you actually want, switching out a document type.

**Comment by Zweben** [comment]
Thanks, I will try the DB editing approach on a backed-up local environment next time.

That RFC and feature you linked to look great. I had planned to eventually make custom dashboards that do both of those things, but now there's no need.

**Comment by amitch17** [comment]
I found this issue when trying to change document types for a  set of content on an existing Umbraco 8 site.

I didn't have the interlinking issues, and it turned out to be relatively straightforward to reassign document types directly in the database.  So I wrote it up here: https://this.isfluent.com/blog/2021/changing-document-types-in-umbraco-8

(I don't mean to reopen this issue, just signpost a workaround for anyone else who googles their way here with similar requirements).
