### ISSUE TITLE
Clicking edit on media picker launches the save dialog

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#7185]
If you have a media picker and you click the edit (pencil) button the document is Saved or the Save dialog is launched (if it's a variant)!

See gif: 

![EDC6226A-8623-4637-8E65-67041DD59F43](https://user-images.githubusercontent.com/1742685/69197260-0aebc180-0b85-11ea-8768-4c184bcb0a5a.GIF)

If its invariant, clicking the pencil actually just automatically goes and saves the document without any warning.

Version: Latest dev/v8 branch (currently set to 8.4.0)

**Comment by kjac** [comment]
I can reproduce. For some reason this doesn't happen when the media picker is in multiple mode, though 🤔 I'll dig into it.

**Comment by kjac** [comment]
Right. I did suspect this... the buttons were turned into actual `<button>` tags instead of `<a>` tags in an effort to make the media picker more accessible (#6805). Depending on your property order and configuration this means that the browser might see the link picker edit media button as the first `<button>` element in the form and thus treat it as a submit button.

@MMasey this might be something you should bring back to the accessibility team? 

I'll push a PR momentarily to fix it.

**Comment by kjac** [comment]
PR in #7188

**Comment by hemraker** [comment]
Perfect @kjac, thanks a bunch for picking this up 🙌

**Comment by kjac** [comment]
Whoops this issue was closed a bit premature; #7651 fixes it though, so now it really should be closed
