### ISSUE TITLE
Add commitlint to mange quality of commit messages

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#7254]
I came across https://github.com/conventional-changelog/commitlint while working on GraphiQL client (https://github.com/PeteDuncanson/graphiql/blob/master/CONTRIBUTING.md#commit-message-conventions) and thought it was a wonderful idea/addition.

You can see how its added some sense to the commit history on GraphiQL itself here https://github.com/graphql/graphiql/commits/master you can also see how not everyone 100% follows it so its not the end of the world if they don't. This is good as I'm sure one of the first come backs will be "we don't want to put barriers in front of people contributing".

Anyway, I thought it was worth a look and a think about if it could be good add to. To me its like Serilog, its adds some structure and context to commit messages.

This slide deck is a lovely quick 2 minute quick read on what is it all about for those in a rush https://github.com/conventional-changelog/commitlint#benefits-using-commitlint

Finally it can help create change logs and track breaking changes which might otherwise slip through the net.

**Comment by nul800sebastiaan** [comment]
Hey @PeteDuncanson! I do really like the idea of conventional commits, I've heard about it a few times now and it's a cool concept. 

Currently we generate our release notes purely based on labels and issue/PR titles on GitHub. This has the added benefit of being able to  update them before we release as well so that the release notes make more sense. You wouldn't be able to do that with commit descriptions.

Additionally, this will require the same admin work while merging community contributions that is already being done: labeling things correctly with bug or feature, possibly fix up the title before it goes into the release notes, add a category label, etc.

So instead of duplicating that work, conventional commits would then need to be the way to do that instead of the current work done in GitHub itself. This would require a rewrite of how the release notes get pulled in on Our Umbraco as well.

With that in mind, the d-team at HQ is at the moment not ready to adopt a new way of creating release notes using conventional commits. 

I have shared the idea internally though for inspiration as I think it's a nice way of creating commit messages anyway that are more thoughtful then just "crap, this was still broken".

Thanks for the suggestion!
