### ISSUE TITLE
Saving a member 2 times after each other resets password

### ISSUE THREAD

**Issue by Emetico** [umbraco/Umbraco-CMS#7272]
Saving a member 2 times after each other resets password. We found out when we where playing around with member roles.

allowManuallyChangingPassword is set to true in the web.config

## Umbraco version

7.15.3

### Steps to reproduce

1. Install a clean 7.15.3
2. Add 10 member roles
3. Create a member
4. Add some roles to the member
5. Save 2 times in a row

**Comment by nul800sebastiaan** [comment]
Thanks! This duplicates https://github.com/umbraco/Umbraco-CMS/pull/6321

**Comment by nul800sebastiaan** [comment]
Ah but that hasn't merged yet, we should do that before releasing 7.15.4.

**Comment by davidpipkin** [comment]
Applying the change from #6321 does not resolve this for me.  There is no error but the password still resets on the 2nd save.  I am running 7.15.4.

**Comment by nul800sebastiaan** [comment]
So the fix for v7 was part of this PR, namely this line: https://github.com/umbraco/Umbraco-CMS/pull/6284/files#diff-e36877c6ef808b35eb2513e9eb3763d1R136

The PR had too much in it, so anything except for that line has been reverted. I can confirm that it's fixed using the repro instructions in #6321. 

I think you might need to update your ClientDependency.config version @davidpipkin - it sounds like your browser is caching the old javascript.
