### ISSUE TITLE
Need ability to include subfolders in media section v8

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#7305]
It's possible to include subfolders in mediapicker search, but that feature is not available in the main media section.

![image](https://user-images.githubusercontent.com/24841143/70534240-4f0a2a80-1b63-11ea-9ada-bb7ac53e2dd6.png)

it would be great to have a checkbox to include subfolders.

**Comment by nul800sebastiaan** [comment]
I'll check with some people at HQ if this is something we would want as well. For now you can also search from the search button in the top right of the screen to search all items: 
![image](https://user-images.githubusercontent.com/304656/70606839-a361e880-1bfd-11ea-93b2-3f5f9509c4bb.png)

**Comment by nul800sebastiaan** [comment]
Thanks for the suggestion @saifobeidat - this has led to quite the discussion at HQ as to how search is supposed to work and how we best show results. 

In the future we want to work on an overhaul of the media section to make it a lot better in general. We discussed to see if there is a quick fix for this issue, but unfortunately there isn't really (just slapping a checkbox in there is not a trivial task and we see the checkbox should not be shown next to the search field).
We also talked about the fact that the performance of this search field might not be suitable for searching in subitems, that also needs a review first.

So, there's many moving parts to this and we want to do this right, instead of quickly adding something in. 

That means that this issue will be added to our list of ideas for when we start working on a larger overhaul of the media section. 

I will close this issue, but we will refer back to closed issue with the `status/idea` label when we start working on the related project/category. So it's not closed forever, just being added to a special list.

Thanks for the inspiration so far @saifobeidat!

**Comment by saifobeidat** [comment]
Thanks @nul800sebastiaan, okay we will wait the media section overhaul, and is the overhaul listed in your roadmap ?

**Comment by nul800sebastiaan** [comment]
It is not on our roadmap currently, make sure to keep an eye on our blog for our product updates (latest one here: https://umbraco.com/blog/umbraco-product-update-december-4th-2019/). The blog will list the changes to the product roadmap as well (https://umbraco.com/products/roadmap/).
