### ISSUE TITLE
DI for multiple generic IService<T> fails, also multiple implementations of IService fails

### ISSUE THREAD

**Issue by ekovand** [umbraco/Umbraco-CMS#7347]
A brief description of the issue goes here.

https://our.umbraco.com/forum/using-umbraco-and-getting-started//100422-di-fails-to-resolve-iservicet

So multiple generic implementations cannot be injected as `IService<T>`, similar issue with multiple implementations of `IService` - it doesnt even resolve the first found implementation

Umbraco version: 8.1.0

**Comment by nul800sebastiaan** [comment]
Thanks... I honestly have no idea if this is an Umbraco problem, a LightInject problem or a DI general problem. 

You're also a few versions behind, so this might be fixed in 8.4.0 already, would be good if you could do some testing on 8.4.0 instead. Please let us know if you can reproduce in 8.4.0.

Other than that, maybe @lars-erik can cast his eye on this one and see if he understands what's going on?

**Comment by lars-erik** [comment]
This works differently in all DI containers. Some pick the first registered, some pick the last, some say "dunno,, cuz u have more than 1". I don't remember OTOH how this was solved in Umbraco, but I don't think it's supported or trustworthy via Composition. As long as something works differently in containers, it should be "unsupported" in Umbraco's abstractions to avoid compatibility issues.
  
I recommend either registering a custom factory method looking up concrete registrations, or registering your generic services directly with lightinject.  
You can get the concrete container from:

    (ServiceContainer)composition.Concrete

Unless you're building a package, then you should not do stuff Umbraco's DI abstraction doesn't support.

**Comment by ekovand** [comment]
That doesn't work in LightInject too. Think i too much worked in .net Core :)
Factory is the answer.

**Comment by nul800sebastiaan** [comment]
Great, I'll close this issue then.
