### ISSUE TITLE
Allow attributes to be added to Multi Url Picker items

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#7378]
I have a Multi Url Picker to manage footer links allowing me to create internal and external links. I have a requirement to launch a modal from a link in the footer. Although I can specify the anchor to be the modal's id e.g. href="#modalToOpen", when using the Bootstrap modal, you cannot specify attributes on the item e.g. "data-toggle="modal".

It would be nice to be able to add/manage attributes on an item in the Multi Url Picker.

**Comment by nathanwoulfe** [comment]
While I understand the reasoning, not sure adding this to the core picker is the best idea - for the majority of users, setting link attributes is not something they'd ever need to do, and probably shouldn't be expected to do. The picker should stay as generic as possible given it's a core control - this change assumes the picker content is being used to generate links in the html, which isn't always the case.

Instead, I'd consider using nested content to create items where the extra attributes are set via property values - eg a true/false to indicate opening in a modal.

This is very much an implementation-specific issue, which should be dealt with through clever code rather than core changes. IMO.

**Comment by abjerner** [comment]
Hi @Wiggee11,

As Nathan is already onto, this is a very specific use case that most users of Multi Url Picker wouldn't need. It's therefore best achieved using either Nested Content or one of the third party property editors that work similar to Nested Content.

As a result of this, I'm closing the issue. I hope this make sense 😉 

Anders, [Umbraco Core Collaborators team](https://our.umbraco.com/get-involved/the-core-collaborators/)
