### ISSUE TITLE
Umbraco Print Preview only Prints What;s On Screen and Not Entire Page

### ISSUE THREAD

**Issue by TomDaria** [umbraco/Umbraco-CMS#7402]
We are on Umbraco 7.11.3.  
After logging into the backoffice of Umbraco and previewing a content page that has 20 pages of content, when we choose print, we only get a print out of what's displayed on screen.

We are aware of a Chrome Extension ( https://www.cnet.com/how-to/how-to-take-a-screenshot-of-a-whole-web-page-in-chrome/) that provides this functionality but it requires you to save it as a PDF first and then print.  

Can Native Umbraco be designed to print the entire page contents and not just what's shown on the screen?

Thanks

Tom

**Comment by stevemegson** [comment]
This will be caused by the preview being shown inside an iframe. That would be a fairly major change, but there are a couple of workarounds.

If you edit the URL from `https://www.example.com/umbraco/preview/?id=99999` to `https://www.example.com/99999`, you'll get the preview content without the surrounding frame, and that should print normally.

If you have a particular need to print previews very often, you could include something like this in your template:

```c#
if ( UmbracoContext.InPreviewMode)
{
    <a href="#" onclick="window.print()" style="position fixed somewhere convenient">Print</a>
}
```

Since `window.print()` is called inside the iframe, just the iframe content will be printed.

**Comment by nul800sebastiaan** [comment]
Thanks for the help @stevemegson! Yep, we don't have any current plans to overhaul the preview functionality to not use an iframe, Steve's workaround is the way to go for now. 👍

**Comment by TomDaria** [comment]
Thanks but where would this code go?
