### ISSUE TITLE
Default-value of a Checkbox-property is not used in YesNoValueConverter

### ISSUE THREAD

**Issue by jerpenol** [umbraco/Umbraco-CMS#7409]
Hi,

I am seeing this issue on Umbraco version: 7 & 8 

If I add a Checkbox-property with a default value to an already existing and in-use Doctype, the default value is not used as a fallback in the ValueConverter of the property.

This is not a problem when the default value of the data type is ``` false ```, because in the ```Umbraco.Core.PropertyEditors.ValueConverters.YesNoValueConverter``` it ultimately (when ```source``` is ```null```) falls back to ``` false ```. However when the default value is set to ``` true``` the ValueConverter still defaults to ``` false ```, which is not expected.

The solution I see is adding some logic to the ```Umbraco.Core.PropertyEditors.ValueConverters.YesNoValueConverter``` which falls back to the default value of the data type when ```source``` is ```null```.

**Comment by kjac** [comment]
Hi @jerpenol,

This is by design and how Umbraco works. If you add new properties to your content types, you need to apply some defensive coding around their usage, as the content based on these content types won't be given any default values for these properties. 

On the upside this means that you *know* if an editor has actually filled out your property. This is useful in some cases, and thus adding a fallback to the datatype default value will be a behavioral breaking change. 

You can use `Model.HasValue(string alias)` to figure out if a property has been assigned a value. Get in touch with the people on [the forum](https://our.umbraco.com/forum/) if you need any help with this.

**Comment by jerpenol** [comment]
Hi @kjac ,

Thanks for your feedback.

My problem is I cannot know when a checkbox is not filled out, because it defaults to ```false``` in the ValueConverter as of now.
So this means the default value of the Checkbox is only to be used when creating new content? Because when I add the property after it is already in use, existing content is not modified at the moment, which renders the checkbox useless with existing content (unless you save your content one-by-one).

**Comment by nul800sebastiaan** [comment]
Thanks Kenn, that's indeed how it works. :-)
