### ISSUE TITLE
ContentApps Bug - Cannot save new content code when it has no properties.

### ISSUE THREAD

**Issue by DavidArmitage** [umbraco/Umbraco-CMS#7415]
When a content app has been installed it is not not possible to save a new content node which does not have any properties.

## Umbraco version 

I am seeing this issue on Umbraco version: 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by adam-werner** [comment]
David and I had a dialogue within the forum, https://our.umbraco.com/forum/using-umbraco-and-getting-started/100532-umbraco-8-content-app-issue-creating-new-pages-only-with-no-content-fields but I'll do my best here to bring across the information to track the bug.

**Umbraco Version**
8.4.0

**Reproduction**
1. install any custom content app package in an Umbraco instance (v.8.4.0)
2. create a new document type that has no properties except for the node name
3. from the content section, create a new page of the new document type created in (2)
4. with the new page, their is no "Content" app presented and the first custom content app is active preventing the entering in of a name for the new page and having the "Save and publish" button not displaying

![Error](https://user-images.githubusercontent.com/1880591/71754048-9a59e500-2e52-11ea-9f9e-834326da5ebb.png)

**Expected result**
We would anticipate the ability to enter in a name and click the "Save and publish" button without any issue.

**Actual result**
The user is presented the custom content app right away and gives the impression that this page cannot be named and saved.

**Comment by kjac** [comment]
Hi @DavidArmitage and @adam-werner,

Thank you for taking the time to create an issue report 👍 

I'm afraid this behavior is by design. As you correctly mention, the Preview/Save/Save and publish buttons are removed for all other content apps than "content" and "info". 

The reasoning behind this is that content apps aren't supposed to edit the content - they should only be reactive to the current content. As content apps can contain anything including various update methods for custom content app data, a "save" option in the bottom bar would quickly become quite confusing to the editors.

In your concrete case I get why this design decision is annoying. There are ways around it, though. You can change the order of the content apps, thus forcing your custom content app to arrange itself to the right of the info app (thus enabling the name input and the save buttons). Or you could disable your custom content app for these content types. All of this is documented really well on https://our.umbraco.com/

**Comment by DavidArmitage** [comment]
Hi Ken,

Positioning the content app after the info icon would work a treat. I did
actually read up how to do that but the documentation said that the content
apps will only get displayed between the content and the info icons.

How do I go about getting the icon to display after the info icon?

"weight": 0, // optional, default is 0, use values between -99 and +99
to appear between the existing Content (-100) and Info (100) apps



Kind Regards

David



*David Armitage | Technical Director*
*w: *www.recsitedesign.com
*p: *02 8007 5669 (AU)
*p: *0114 360 9118 (UK)
*e: *david@recsitedesign.com

**Comment by adam-werner** [comment]
@kjac - 

I understand the reasoning behind preventing the field and Save and publish not being available for a content app -- no issue there.

As @DavidArmitage mentioned, the documentation only indicates that the weight can place a custom content app between the Content and Info.

You indicated that "Or you could disable your custom content app for these content types."   The manifest would allow us to prevent display for a content type that we would know the name of as seen under "[Limiting according to Content Type](Limiting according to Content Type)", but building a custom content app, I don't think we can guarantee what those names could be of document types with no properties.

What is interesting is that the Content app itself seems to recognize it shouldn't show in these document types with no other underlying properties other than node name.  I imagine that that logic could probably be applied to the display of custom content apps.  I think that logic may be in place in the Umbraco source rather than the code that can be contributed with a custom content app.  I may be wrong and perhaps we can affect that change with code we contribute in a custom content app, I think we would just need to see that documented (although, I think it would be in almost all custom content app's benefit for that code to be included).

**Comment by DavidArmitage** [comment]
Ho Guys,

Just to jump in again here.

I have been working on an umbraco site all day and the amount of times i
have used content nodes without any properties is a lot more than you can
imagine.

I purposely installed one of my content apps and it was dam annoying.

I am aware it may be possible to fix this for the content apps I am
building by possibly adding my app to the right of the info app. I am still
get to confirm of this is possible or not.

At this stage I am more worried about other content apps in the package
library that I didn't build. To be honest I would definitely be reluctant
to install these apps because of this design. I would at least be trying to
override any third party apps default functionality to rod of this but
which I don't think users would be happy doing.

I imagine it should be an easy fix.

My thoughts are not to add save buttons to content apps. Instead either...

1. If there are no properties simply dont get rid of the content tab.

2. Or if there are no properties then default to the info tab rather than
the first content app.


Kind Regards

David

**Comment by adam-werner** [comment]
@kjac --

Would you be able to point @DavidArmitage and me in the right direction regarding these follow-up questions we had?  

We also found that disparity in the documentation you pointed us and how that doesn't seem to fall 
 in line with the direction you provided us.

**Comment by kjac** [comment]
@adam-werner I believe this is not a bug in Umbraco. Perhaps the "content" content app will be reintroduced for property-less content sometime down the road, when custom content apps become more widely adopted, but I sincerely doubt it'll be accepted as a PR right now.

Off the top of my head I would suggest you add a property to those content types as a workaround. Maybe using Editor Notes or similar packages. 

As always, the good people on [the forum](https://our.umbraco.com/forum/) might also be able to help you.
