### ISSUE TITLE
Optimizing GetPage in DocumentRepository in regards to loading variants

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#7419]
Part of the PR here: https://github.com/umbraco/Umbraco-CMS/pull/7316 optimizes the loading of variants (meaning variants will not be loaded by `GetPage` (https://github.com/umbraco/Umbraco-CMS/pull/7316/files#diff-39985053fbc2e8898e93128ed5086323R843) 

This however causes a handful of tests to fail in `ContentServicePublishBranchTests`.
It makes pretty good sense both why this optimization was done, but also why the same thing now causes these tests to fail. Unfortunately neither Shannon or I have noticed the failing tests on the initial PR before it being merged. 

I have so far re-enabled the loading of variants here to ensure any further PRs submitted will not fail just due to this.
We should however look into whether it is possible to pull this param further out to allow the optimization to be used when appropriate (list views for example) and then allow variants to be loaded when they are needed (like in our test case here).

---
_This item has been added to our backlog [AB#4339](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4339)_

**Comment by Shazwazza** [comment]
@clausjensen 

I've fixed this in rev: 9a192131d650f37209627fcd096356c9ac77dd9e

We can't actually do the further optimizations that was in the original PR because it is actually a breaking change and it wouldn't be very clear why people would not be able to use some `IContent` items for persistence. 

So the lookups are now the same as they were prior to these changes but the code is in place (i.e. in the `MapDtosToContent` method) to be able to optimize these lookups. Of course the real 'fix' was adding the msising DB indexes.

I've added a big note in the DocumentRepository in the above rev:

```
// TODO: This method needs to return a readonly version of IContent! The content returned
// from this method does not contain all of the data required to re-persist it and if that
// is attempted some odd things will occur.
// Either we create an IContentReadOnly (which ultimately we should for vNext so we can
// differentiate between methods that return entities that can be re-persisted or not), or
// in the meantime to not break API compatibility, we can add a property to IContentBase
// (or go further and have it on IUmbracoEntity): "IsReadOnly" and if that is true we throw
// an exception if that entity is passed to a Save method.
// Ideally we return "Slim" versions of content for all sorts of methods here and in ContentService.
// Perhaps another non-breaking alternative is to have new services like IContentServiceReadOnly
// which can return IContentReadOnly.
// We have the ability with `MapDtosToContent` to reduce the amount of data looked up for a
// content item. Ideally for paged data that populates list views, these would be ultra slim
// content items, there's no reason to populate those with really anything apart from property data,
// but until we do something like the above, we can't do that since it would be breaking and unclear.
```

Ideally in the future we do something like this since we can make these lookups much faster and it makes a lot of sense to have readonly versions of models.
