### ISSUE TITLE
Inserting a macro in the rich test editor (RTE) in the Grid makes it disappear on Save & Publish

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#7461]
The scenario is simple and reproducible, as mentioned here:
https://github.com/umbraco/Umbraco-CMS/issues/6846#issuecomment-546675121

> If you click into another area of the RTE after inserting the macro, it will save / publish with no issues, but if you insert the macro into the position you want within the RTE and then save, it gets stripped out / removed.

We're seeing this in all versions (or at least I went back to 8.4.0, 8.3.0, 8.2.2 and 8.1.5). 

![7456](https://user-images.githubusercontent.com/304656/72422206-4b7d4b00-3782-11ea-9a4e-aca9e7a9be45.gif)

**Comment by nul800sebastiaan** [comment]
Note that @InfiniteSpirals seems to have made some progress here, so it would be good if someone can follow that trail and see where it leads! 

https://github.com/umbraco/Umbraco-CMS/issues/6846#issuecomment-574193567

Quote:
> I've spent a few hours looking at this and I think it's not triggering change tracking when the macro is inserted into the RTE on the grid. The .on('Dirty') handler that inserting a macro fires has a null ref to args.currentForm. However, I don't understand enough of this to know that is the actual cause.

**Comment by stevemegson** [comment]
It looks like it is indeed linked to change tracking. The RTE updates the model with its contents when the `change` or `blur` events fire. When inserting a macro, the editor loses focus when the dialog opens to pick a macro. When a macro is chosen and we add the markup to the editor, the `change` event doesn't fire. If you save now, the model doesn't yet know that the macro has been inserted. Clicking anywhere in the RTE ensures that there'll be another `blur` event at some point, which updates the model.

**Comment by mattou07** [comment]
Can confirm on my end after adding the macro and clicking out of the RTE. It allows the Macro to stay after clicking Save. Thanks, @stevemegson saved me from getting a headache.

**Comment by xdjoshuaaz** [comment]
Hi all,

I have spent some time looking into this today as it is a likely blocker going forward for a project of mine. I'm not familiar with AngularJS but I have a fix for this issue.

Changing the dirty event handler to call `syncContent()` like the other nearby event handlers (e.g. blur, change, ObjectResized) fixes this bug, so I've made a PR containing this change @ #8437. 

Additionally, the `args.currentForm` property is null as `angularHelper.getCurrentForm(scope)` (called and passed through [here](https://github.com/umbraco/Umbraco-CMS/blob/fe12f35d79edb2665707fc32f93c985f1a5701b0/src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js#L90)) will not be able to find the form in the isolated scope belonging to `gridRteDirective`. The isolated scope is declared [here](https://github.com/umbraco/Umbraco-CMS/blob/fe12f35d79edb2665707fc32f93c985f1a5701b0/src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js#L4) [AngularJS docs on scope inheritance [here](https://docs.angularjs.org/api/ng/service/$compile#-scope-:~:text=%7B...%7D%20(an%20object%20hash)%3A%20A%20new,isolate%20scope%20to%20its%20children%20elements)].

I've resolved `args.currentForm` being null in my PR by calling `angularHelper.getCurrentForm(scope.$parent)` instead so that the GridController's scope is used to search for the form (where is form property is called `propertyForm`). I believe this change is fine for `gridRteDirective` as it's only used by the RTE grid editor (and I guess 3rd party consumers shouldn't rely on it?)

Thanks,
Josh

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/8437

**Comment by AndersBrohus** [comment]
It has indded been reintroduced @Gavlar50 - We are experiencing in 13.3.2 :)

**Comment by nickwelsh1** [comment]
Also experiencing the issue in Umbraco 13.0.3. 
The workaround of click in the RTE after inserting a macro works but must be communicated to all users.
Firefox also doesn't appear to be affected.
If `RichTextEditor` in `appSettings.json` is configured as `"ValidElements": "*"`
(which would be insecure) then it appears that inserting a macro will save.

**Comment by TrilochanTripathi-01** [comment]
Unfortunately "ValidElements": "*" setting also not works for me. But yes Firefox seems to be unaffected. I'm using umbraco13.4.1.

**Comment by benbracedigital** [comment]
We have a client's site that is affected by this so another vote on getting this fixed please.
