### ISSUE TITLE
Make Backoffice validation less "aggressive" when saving content

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco-CMS#7484]
As a general rule people are using red validation message when submitting a form/whatever to show the user that an error occurred and that no action was performed.

However, when you `Save` a content node in Umbraco without filling out mandatory properties, we're showing red validation messages (_and_ turning the `Save` button into an `X!`) _even though the content was actually saved_.

Since I've been using Umbraco for quite a while now I know that the content was saved.. but if you're new to the CMS you might not be aware of this.

**But why didn't you just fill it out? It's mandatory!** Because sometimes when I create/set up a page I don't have all the info _right now_.. So I save the node so I can return to it later.

I'm confident that we can avoid confusing editors by making the validation more friendly when you're "just" saving a node. 🙂

![ku50EBAtQ4](https://user-images.githubusercontent.com/4366314/72793456-c3dc8400-3c3a-11ea-9188-b0ac80f68d9c.gif)

**Comment by nielslyngsoe** [comment]
Great feedback!

The first and maybe most important change would be to change the Save-button response to a checkmark so you can see that the save was successful. Then we should display a notification, in green, saying "Content was saved but it contains invalid content".

A quick thought could be to use our yellow color for the feedback messages, this could be an easy way to make the errors appear less aggressive, but still visible.

**Comment by kjac** [comment]
Just a heads up on this one. A lot of property editors actually do not allow saving if their values are invalid. In fact this was streamlined somewhat lately to make even more property editors prevent saving content that's invalid (Nested Content obviously not being among them as this example shows).

While I appreciate the idea of being able to save (but not publish) invalid content, I think the concept deserves a well considered approach and some overall rules/guidelines from HQ. A few points come to mind:

1. Should it always be possible to save invalid content?
2. If so, should we enforce this option by simply not validating content when saving? Or perhaps take a different validation approach when saving?
3. How will this affect scheduled publishing?
4. ...and how does all this affect 3rd party property editor implementations?

**Comment by Shazwazza** [comment]
Yep like what @kjac says, there's 2 types of validation - server side and client side. The http request will not be made if client side validation fails, but if we want to bypass that, then it may be possible to just ignore that validation failed and proceed with the request anyways and then deal with the combined validation errors of both client + server side validation in some way. 

If no client side validation exist for a property editor but server side validation does, then currently you can Save invalid content. The problem lies with cilent side validation and how we can deal with that while also ignoring it and making a save request and merging the combined validation results.

Scheduled publishing is only validated with server side validation based on property editors `IDataValueEditor.Validators` (which includes processing the property type level required/pattern validators)

**Comment by kjac** [comment]
What @Shazwazza said 😛 

@nielslyngsoe I believe you should put on your UX glasses and come up with a grand plan to aim for with this. Then based on that we could identify the correct course of action.

**Comment by nielslyngsoe** [comment]
So we both have technical difficulties and UX issues. I think we need to clarify what options we have available and then we will return. Thanks for your inputs!

**Comment by DanDiplo** [comment]
You definitely should be able to "save" (not publish) a document even if there are validation errors. It's fine to warn about these, but I'd always want the document to save so it can be edited at a later date. Maybe a warning at the top of the page could be displayed if a document is in a saved but invalid state? This could also inform them that scheduled publish would fail because of this.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9691
