### ISSUE TITLE
Anonymous type leaking from ContentPropertyDisplay.Config["items"] prevalue collection

### ISSUE THREAD

**Issue by dhymik** [umbraco/Umbraco-CMS#7515]
This is with Umbraco 8.

When trying to access the list of prevalues set for a property editor like `Umbraco.RadioButtonList`

    var preValues = myContentPropertyDisplay.Config["items"];

then the type of `preValues` is `object`, with a reflected type of

    System.Collections.Generic.Dictionary`2[System.String,<>f__AnonymousType7`2[System.String,System.Int32]]

Due to the anonymous type used, it is impossible to cast to a decent type for further processing. See [this](https://our.umbraco.com/forum/using-umbraco-and-getting-started/100831-how-to-access-dictionary-inside-of-an-object-type-returned-by-contentpropertydisplayconfig-items#comment-100831) Our issue for further details.

May I suggest to add and use a simple type like this instead of the anonymous type:

```
public class UmbracoPropertyEditorPrevalue
    {
        public int sortOrder { get; set;  }
        public string value { get; set; }
    }
```

If you think this is a good idea, I am happy to try and prepare a PR.

**Comment by nul800sebastiaan** [comment]
I don't think all datatypes have this structure for prevalues, which is why it's being stored in a generic dictionary. 

However, I'm sure it could be easier to get prevalues from datatypes then it currently is. I'll ask around as to what we could do for that in Umbraco.

**Comment by abjerner** [comment]
Hi @dhymik,

I can see your use case, and why anonymous types are bad in this situation. But the models available through `EditorModelEventManager.SendingContentModel` are primarily for the UI, which is likely why it is as an anonymous type.

Anyways, an instance of `ContentPropertyDisplay` has a `DataTypeKey` property, which can be used for looking up the data type via the data type service, and get a strongly typed configuration that way. So would something like the snippet below suffice?

```csharp
ContentPropertyDisplay propertyDisplay = e.Model
    .Variants
    .SelectMany(v => v.Tabs)
    .SelectMany(t => t.Properties)
    .FirstOrDefault(p => p.Alias == "radioButtonList");
if (propertyDisplay == null) return;

var dt = _dataTypeService.GetDataType(propertyDisplay.DataTypeKey);
if (dt == null) return;

var config = dt.ConfigurationAs<ValueListConfiguration>();
```

I agree that in an ideal world, `.Config["items"]` shouldn't be an anonymous type, but I also believe what you're trying to do is an edge and I don't think Umbraco will be able to give it a high priority. But if this is something you'd be able to submit a PR for, we'd be happy to have a look at it 😉 

Unfortunately we can't just return an instance of `ValueListConfiguration` right away because the properties are a bit different from what is returned now. But introducing a new class for the items should be fine, as it wouldn't be a breaking change if decorated with the right attributes.

**Comment by dhymik** [comment]
Hi @abjerner,

thank you for taking the time to answer so detailed. The code snippet you provided does the trick.

May I quote this on Our.Umbraco in the forum thread where I asked about this issue first?

Again, thank you.

**Comment by abjerner** [comment]
@dhymik great to hear that helped 😄 

Please feel free to post my answer in your thread 😉
