### ISSUE TITLE
NetCore: Move PublishedCache from Umbraco.Web into .Net standard project

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#7551]
Currently the PublishedCache (NuCache) implementation makes use of a [b-tree package](https://github.com/csharptest/CSharpTest.Net.Collections) that's available only for .Net Framework.  A [fork](https://www.nuget.org/packages/CSharpTest.Net.Collections-NetStd2/) exists for .Net standard.

This task requires:

- Migration of the `PublishedCache` folder from the `Umbraco.Web` project to a new infrastructure project.
- Update reference to the .Netstandard fork of the b-tree implementation
- Discover and resolve dependency issues from the migration.

**Comment by bielu** [comment]
@AndyButland did you look into how that fork was done? and actually I don't really understand the decision in Umbraco to use package which was last time updated in 2014, and not sure if it is a good idea to use a fork of the package which is abandoned.
In my opinion migration to .net standard should replace that package with something which is with less Technical debt than that one.

**Comment by AndyButland** [comment]
Hi @bielu - yes, that's something that's been discussed a little, and needs to be some more (I should have added it as another note for reviewers to consider, so thanks for raising).  I do a agree to an extent about the time of last update being a concern, but, that said, for something like this - i.e. a data structure/algorithm - it is more likely that when it's done, it's actually "done", and doesn't need upgrades (for example, it's got no dependencies that it needs to keep up to date with).   And I guess Umbraco has kind of proved it does what is needed via it's use of it for a couple of years.

I'll be honest though, the code and concepts in that package are rather outside my comfort zone, so it'll need others to consider that.

**Comment by Shazwazza** [comment]
The reason we are using this package is because it is stable. We've been in touch with the author of this package and it is used in a plethora of .net software since it is the only real/tested implementation of bplustree in c#. Sometimes software 'just works' and this is one of those cases, so yes it hasn't been updated since 2014 because as it is, it works great. The author has said he no longer works on it but is happy for anyone to take it and use as they wish.

**Comment by Shazwazza** [comment]
That said, we are not tied to any particular file based cache mechanism. Please remember at this point in time the content cache is 100% in memory, the only reason for a file based cache is fast reloading for app recycles. And Yes, in the future it would be amazing to not have all of this in memory and we can lazy load stuff in memory or just not even have content cache in memory - but we cannot do that yet until routing is completely refactored because all of routing, url generation, url handling, etc... requires all content to be in memory because there's a performance overhead of looking all of this up and it happens at runtime. Rebuilding the routing engine is a whole other project but just mentioning this now so we don't get ahead of ourselves with trying to think of new file based caching mechanisms - I know I can hear people say 'redis' ;) - but that's not going to get us any further until routing is changed.
