### ISSUE TITLE
NetCore: Rewrite the nonodes.aspx as MVC

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7707]
## Background History
For the .NET Core transition, we cannot have webforms endpoints anymore. Today Umbraco still have the `nonodes.aspx`. This page is used if no nodes are published.

## Task
This task is about rewriting the current `nonodes.aspx` into MVC.
Furthermore, we need to be able to override this page, as some packages do this today.

## Details
`UmbracoInjectedModule` ensures Umbraco has at least one published node. If not the path is rewritten to  `~/config/splashes/noNodes.aspx`.

We need to to take this URL from a configuration. This configuration interface must live in `Umbraco.Core`, and the implementation (Can be a hardcoded or added to GlobalSettings for now) must live in `Umbraco.Configuration` .

The default value must point to a url, that handles this using a new MVC controller.

The view can be located in the Config folder like the `nonodes.aspx` is today. But we are open to alternatives.

All the legacy stuff in the current `nonodes.aspx` can be cleaned
- Jquery shouldn't be nessasary
- The special handling of IE <= 8
- Current.* should not be used.

The PR can be started from the [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev) branch.

**Comment by Shazwazza** [comment]
In my opinion, this should be handled as a custom MVC route and all that needs to be done is a razor view and I think optionally the location of this razor view should be configurable... like an appsetting or similar.

Also by having this as an MVC route, it means that other developers if they chose too, could modify this named route to totally replace the nonodes functionality ... think Umbraco Deploy since it does this currently but unfortunately needs to entirely replace nonodes.aspx that we ship with which isn't ideal.

**Comment by AndyButland** [comment]
Will take a look at implementing this.
