### ISSUE TITLE
Package System should be separate from Content Import/Export

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7787]
From my perspective, all parts of software should follow a single principal rule and package system is actually double responsibility:
* Managing Packages
* Content Import/Export possibility.

I am not really sure why it was merged to one module, but definitely should be separate. As you shouldn't be a force to create a package when you want just export content. The separation will also allow for better maintenance of both features. 
just for reference, I made a small poll about that:
https://twitter.com/bielu1/status/1235514061997125632
and from that what I could see that it is not only my feeling something here is definitely wrong.

**Comment by nul800sebastiaan** [comment]
Hi @bielu,

Packages can contain content and that  is why the two are linked. We don't necessarily support content export/import and that is not something that we want to support out of the box necessarily due to the many complications this has with all kinds of dependencies that are required to import/export content well. 

The packaging system is due for updates in the near future, as you know but there's no plans to create a separate content export/import feature. I would like to know more about what you're trying to accomplish though.

We encourage you to use products like the upcoming Umbraco Deploy or uSync, or use the packaging APIs (due for a refactor soon, as said) and build your own system on top of that.

**Comment by bielu** [comment]
> Packages can contain content and that is why the two are linked.

They should be linked, it is why I created that issue.


> We don't necessarily support content export/import and that is not something that we want to support out of the box necessarily due to the many complications this has with all kinds of dependencies that are required to import/export content well.

You actually do that using the package system...


> The packaging system is due for updates in the near future, as you know but there's no plans to create a separate content export/import feature. I would like to know more about what you're trying to accomplish though.

Actually I pointed out that in one of the comments to RFC, but I was aware no one is actually looking into all 40 comments in RFC, and I think it is more related to the core of Umbraco as that feature it is here already it is actually about the separation of them...



> We encourage you to use products like the upcoming Umbraco Deploy or uSync, or use the packaging APIs (due for a refactor soon, as said) and build your own system on top of that.

But why you recommend using additional tools when a tool is here in the core, but need little of polishing?

**Comment by Shazwazza** [comment]
> but I was aware no one is actually looking into all 40 comments in RFC

... we actually do look at all comments :) 

RFCs take some time to digest, update, etc... just because there's no immediate response or updates doesn't mean we aren't paying attention.

Content import/export for package data will continue to use a similar approach ... but sure the code is old can can do with a bit of a revamp, etc.. which would be part of the package change initiative. It would be relatively trivial to have the modules more separated (you should have seen this before v8!) Deploy and uSync are a content/schema import/export serializer/deserializer products that take care of many complexities that the core import/export will never do like dependency graphs, etc... Content import/export that exists within the core will still be focused for package creating and installation.

**Comment by bielu** [comment]
> ... we actually do look at all comments :)

And probably only HQ :) 



> RFCs take some time to digest, update, etc... just because there's no immediate response or updates doesn't mean we aren't paying attention.

I understand that and in my opinion, it is partially out of that RFC.



> Content import/export for package data will continue to use a similar approach ... but sure the code is old can can do with a bit of a revamp, etc.. which would be part of the package change initiative. It would be relatively trivial to have the modules more separated (you should have seen this before v8!) Deploy and uSync are a content/schema import/export serializer/deserializer products that take care of many complexities that the core import/export will never do like dependency graphs, etc... Content import/export that exists within the core will still be focused for package creating and installation.

Yeah but actually I am looking from the perspective of a normal user, not a developer, it would be nice to have a simple feature to import/export content, which would actually simplify migration from another CMS! As in WordPress quite often if the website is done correctly I could easily map properties to XML format which I actually need nad here would example for the use case to separate import/export. For now, to do the same I have export xml and later make from simple xml package and upload and test package, a lot not necessary steps IMHO.

**Comment by Shazwazza** [comment]
Yup sure. The export stuff isn't really that tangled within the package system, the import stuff is less tangled and we'll need to make more changes/fixes/enhancements to this code with the upcoming package changes anyways i'm sure.
