### ISSUE TITLE
*MINOR BUG* "Your recycle bin is empty" text clipped

### ISSUE THREAD

**Issue by lukehook** [umbraco/Umbraco-CMS#7801]
## Umbraco version

I am seeing this issue on Umbraco version: 8.5+

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When selecting an empty Recycle Bin content node. The "Your recycle bin is empty" is slightly clipped by the overlaying filter bar above it.

### Specifics

![image](https://user-images.githubusercontent.com/7995797/76547778-ac28bb80-6485-11ea-8376-8e72a63c3968.png)

Notice: The 'dot' above the i is not visible. Extremely minor bug but a bug nonetheless

### Steps to reproduce

Select an empty recycle bin node

### Expected result

Text should be padded further down to be fully visible

### Actual result

Messaging slightly clipped

**Comment by nul800sebastiaan** [comment]
I can reproduce in 8.6!

![image](https://user-images.githubusercontent.com/304656/76570543-d1352280-64b5-11ea-8ed8-f44f365057a3.png)

But I'm guessing your browser height is higher than 150px...?

So I'll close this as it seems already fixed in 8.6 ;-)

![image](https://user-images.githubusercontent.com/304656/76570589-ef9b1e00-64b5-11ea-8298-3e118bcef5d1.png)
