### ISSUE TITLE
Examine indexes are out of sync across load balanced servers upon deployment

### ISSUE THREAD

**Issue by garpunkal** [umbraco/Umbraco-CMS#7823]
We've noticed upon deployments of our codebase that our examine indexes are out of sync across load balanced servers, which results in different data being shown on the website. We're pulling results onto listing pages using examine, but the results are different on each server. 

## Umbraco version

8.5.3

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Upon a deployment our frontend servers have different results retrieved from examine results, causing inconsistencies in the data being shown on the website. 

If we publish the repository of items in the CMS, the examine indexes are brought up to date and the problem is resolved. 

### Actual result

Let me know if you need anymore information and we'll be happy to provide it.

**Comment by nul800sebastiaan** [comment]
I'm afraid there's not much to go on here, many people have set this up successfully, so you will need to investigate.

In order for someone to say anything sensible about this, make sure to follow all the instructions here to the letter (if you see anything and go: "well, I didn't do this because.." then you're probably going to need to reconsider that 😉).

Detail all the things you've done, config settings, servers setup, etc. and then maybe there's something to go on.

**Comment by nul800sebastiaan** [comment]
Forgot the link to "all the instructions here" - https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/

**Comment by emma-hq** [comment]
Hey @garpunkal,

Thanks for submitting this issue - we don't have enough to go on to investigate as it stands and as there's not been a response for a while I'm going close for now. Hopefully, you've solved it long ago :)

Emma
