### ISSUE TITLE
v8.5.5 - Changing Template after initial Save does not update Preview

### ISSUE THREAD

**Issue by AussieInSeattle** [umbraco/Umbraco-CMS#7826]
Repro steps:
- Setup environment with a doc type that has two different templates available
- Create a piece of content using the doc type you created - default template is used - save the content (not save and publish) and then do a preview
- Edit the content and change the template being used and save the content
- Preview content again and you will see that the template being used has not changed

**Comment by nul800sebastiaan** [comment]
Hi Matt, I unfortunately can't reproduce the problem, see gif below. I also tried this with a brand new document and it worked there as well. Also tried pressing "Save" first and then "Preview" but that doesn't make a difference (it should not, since the "Preview" button does a "Save" first).

![7826](https://user-images.githubusercontent.com/304656/77149302-8d33b600-6a91-11ea-91ef-533d45206f3d.gif)
