### ISSUE TITLE
ContentService_Publishing PublishedEntity property value contains brackets

### ISSUE THREAD

**Issue by lcichanowicz** [umbraco/Umbraco-CMS#7863]
Umbraco 8.5.3

myDocType has a property of type dropdown, with a value of **Small Business**.  If I inspect its value during server-side publishing, for validation, it contains square brackets and escaped quotes.

```
private void ContentService_Publishing(Umbraco.Core.Services.IContentService sender,
    Umbraco.Core.Events.ContentPublishingEventArgs e) {
    foreach (var node in e.PublishedEntities) {
        if (node.ContentType.Alias == "myDocType") {
            bool propIsDirty = node.IsPropertyDirty("serviceType");
            // false
            string thisIsUnexpected = node.GetValue("serviceType").ToString();
            // "[\"Small Business\"]"
         ...
            using (var cref = _context.EnsureUmbracoContext()) {
                var cache = cref.UmbracoContext.Content;
                 if (node.Id != 0) {
                    myDocType nodeFromCache = (myDocType)cache.GetById(node.Id);
                        string thisIsExpected = nodeFromCache.ServiceType;
                        // "Small Business"
```
Why does the PublishedEntity dropdown property value contain escaped quotes and brackets?  How do I get the value without them, other than removing them with string manipulation?

**Comment by nul800sebastiaan** [comment]
In the services you're looking directly at what's stored in the database. In this case it's a ("json") array with a single value, is you configure the datatype so that multiple values can be selected you will get multiples: `["test1","test2"]`.


From the `FlexibleDropdownPropertyValueConverter` class you could borrow:  `return JsonConvert.DeserializeObject<string[]>(source.ToString()) ?? Array.Empty<string>();` 

We need to talk at HQ about why this is stored in this way and if we want to make changes in the future, make sure to follow the related issue: https://github.com/umbraco/Umbraco-CMS/issues/7858

**Comment by lcichanowicz** [comment]
Thanks, @nul800sebastiaan.  I was just reading that related issue, and I got to the part where you linked it here.  :]  I appreciate the swift reply.  Yeah, drop-downs are quite common and important; so, they should ideally not having such weirdness going on.

I am a big fan of the strongly-typed push in Umbraco 8; yet, when I'm in these events (Publishing, Saving, etc.), it is pretty crude.  I cannot easily get an MNTP's selected value ID or a dropdown's--and, the dropdown's GetValue "value" does not even match its actual value.
