### ISSUE TITLE
Media Tracking not tracking media set before v8.6 release until page published

### ISSUE THREAD

**Issue by ConfusedShark** [umbraco/Umbraco-CMS#7882]
New Media Tracking feature not showing image references and uses set before upgrading to v.8.6. You need to republish the page they are used in for the image tom start being tracked.  

This may be deliberate but I couldn't see anything stating as much in release notes.   

## Umbraco version

I am seeing this issue on Umbraco version: 8.6

Reproduction
------------

This is simple to reproduce,  look at the media element and it will not have any uses or references shown. Then go back to the page/component where the image is used and publish that page and then go back to media element and you will now see its used on that page. 

### Bug summary

Need to republish page/pages for Media Tracking to work on image links configured before v8.6

### Specifics

Not browser specific issue

### Steps to reproduce
- Check media item info tab for image referenced on a page before upgrading to v8.6 and notice it has links section with image name and references section that says "This Media item has no references."
- Go to page that images is used in and click 'Publish' (save doesn't change anything) 
- Return to the images info tab and you now see the Media Tracking features as expected

### Expected result

I expected to see the uses of images without having to do something.  

### Actual result

Images Info tab looks as it was before for images used in the site

**Comment by nul800sebastiaan** [comment]
This is correct, media tracking only kicks in from 8.6 onwards, if you upgrade then the existing items aren't added. We thought about adding a migration for it but it was too risky to try and migrate large media libraries. What you could look into is writing a script that publishes all the currently published pages so that the event handlers kick in and add the tracking.

FYI - we don't intend to do anything about this, media tracking starts from a fresh install for 8.6 or after an upgrade only.
