### ISSUE TITLE
ContentService.GetVersions returns incorrect property values for saved version

### ISSUE THREAD

**Issue by lcichanowicz** [umbraco/Umbraco-CMS#7886]
Umbraco 8.5.3

I have a document/node that was created and published.  Then some field values were changed, and it was saved, not 'saved and published'.  When I use ContentService.GetVersions and inspect property values for the original published version and the saved version, they both appear to be published.  Both have a PublishedDate date-time stamp.  Both report Published = True.  Both report PublishedState = Published.  Both of their GetStatus returns Published.  The only way to tell which is the published version is to compare their VersionId to the PublishedVersionId.  It would not seem I should have to infer which is published when there are so many propreties specifically around "Published".

I was doing this inspection programmatically, because the backoffice does not provide a way to see the document's property values of the published version after there is a saved version.  Content managers need a way to see the published values _in the backoffice_ for the published version, even if there was a save after that.

**Comment by nul800sebastiaan** [comment]
Sorry, currently there is no feature where you can switch between a "published values" version and "the most recently saved" version. This is on our list of things we'd love to provide in the future because it also benefits scheduled publishing. Just imagine this one: Editor schedules a node for publishing 2 days from now, different editor comes in and makes changes and saves them (doesn't publish). The changes will be published when scheduled publishing kicks in, but they're not the changes the original editor intended to publish.

These are big changes and we don't yet know how we can do them to make this easy to use. It's something that doesn't fit into our current roadmap and I expect it will be quite a while before we can get to it. 

Ideas on how to implement this are very welcome in the comments on this issue.

**Comment by nul800sebastiaan** [comment]
I just realized I read over the fact that your were using the ContentService. We'll need to investigate why we have this current behavior and if it is "correct". I am not sure how `GetVersions` works at all.

**Comment by nul800sebastiaan** [comment]
Alright, apologies for the wait @lcichanowicz - this is the answer I got back:

> The `IContent.Published` property means: This content has a published version.
> 
> So if any versions are published then this will be true, that is how you know if it is published. The `PublishedVersionId` tells you exactly which version ID is the one that is currently published (so if the id of the version is different from the id you're looking at then that version you're looking at is not the published version).
> The `Published` flag indicates that the content is published - some version of it is live. If you unpublished the content item, then all versions will be unpublished and `Published` will be false.
> `PublishedState` is a property that can have a 'transition' value, it can be used to indicate the state of the current Model, not the current persisted state. It is a bit of a special property but if the `IContent` item isn't modified, than `PublishedState` will indicate the persisted state. But this is an indicator the Content as a whole, not for a particular version.
> 
> This is expected behavior.
>
> `IContent.Edited` is a similar thing. It means there is an edited version ahead of the published version (so edits have been saved but not published). When working with `IContent` - we are working with the content item as a whole, specific version information is handled by comparing `VersionId` and  `PublishedVersionId` along with these properties.

I've clarified some of this in the xml docs to be released with v8.7.0 - https://github.com/umbraco/Umbraco-CMS/commit/95cb7e72d1a8423b4e36b7e40127e0c473c33d8a
