### ISSUE TITLE
Ability to check whether a new Member password is valid before creating Member

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#7887]
When programmatically creating a new Member (via a "Registration" form), you first need to create the member, then set the password. 
example:
```
m = memberService.CreateMemberWithIdentity([username], [email], [name], [membertype]);
memberService.SavePassword(m, [password]);
```
If the [password] doesn't meet security requirements (as set in the web.config - `minRequiredPasswordLength`, etc.), an Exception is thrown - but the member has already been created. 

It would be nice if there were some way to check that a provided password string would be accepted, before creating the member, either by a helper-sort of function:
`bool PasswordMeetsRequirements(string PasswordToTest)`
or via a "TryCreateMemberWithIdentity()" method, which would cancel the creation of the member and return FALSE, if the password doesn't meet requirements.

In ASP.Net Membership providers, it seems the only way to know about a valid password is through the "Membership.ValidatingPassword Event" (https://docs.microsoft.com/en-us/dotnet/api/system.web.security.membership.validatingpassword?view=netframework-4.8)

**Comment by Shazwazza** [comment]
It is advised to not use this method since it won't actually work for updating members, see notes. It should have been obsoleted a long time ago https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Services/IMemberService.cs#L99

For creating members via forms on the front-end, use `MembershipHelper` which is exposed as @Members on views or on controllers. This is also how the built in macros for registering members works. You can see the code here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Security/MembershipHelper.cs#L196 which uses the underlying providers to create the member which will fail if the password doesn't meet requirements.

Working with members is annoying because:

* we still need to support membership providers
* membership providers are weird and inflexible
* membership providers are how password security is enforced in v8/v7
* the IMemberService should never have contained logic for dealing with passwords, this service (like all other services) are purely for working with data in the database
* members should be governed by ASP.Net identity, but they are not ... unless you install nuget.org/packages/UmbracoIdentity ... in netcore they of course will be which makes things flexible

**Comment by hfloyd** [comment]
Hi @Shazwazza, Thanks for the info. I am actually doing this in a Forms Workflow, which doesn't seem to have MembershipHelper readily available. From my tests, the memberservice does seem to work, and for my own purposes, I have it catch any errors at SavePassword and delete the Member which was just created, to avoid having password-less (?) Members in the database.

**Comment by Shazwazza** [comment]
If you want to avoid that you'll need to use the membership provider directly to first attempt member creation with a password and then potentially update further with the member service, you can see how that works in the code for MembershipHelper, you'll basically need to follow the same approach. 

The only alternative is to create another wrapper around all of this like the MembershipHelper but maybe with less dependencies, but i don't think that is going to get any priority since you can work with the membership helpers directly for now.

**Comment by hfloyd** [comment]
Thanks for your additional thoughts, and have a great day!
