### ISSUE TITLE
Amending an Image Crop

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#8015]
Hello,

Seen on Umbraco 8.6.1.

If you amend the dimensions of an image crop in the image cropper data type from one size to a new one. The new dimensions are not output on the front end of the website .GetCropUrl() until the site restarts (via web config). The crop itself in the media section is updated, and you can adjust it, which in turn will adjust the positioning but to the original crop dimensions for the front end.

Expected result: adjust crop dimensions are output to the front end in real time, without need to restart. 

Cheers
Ric

**Comment by nul800sebastiaan** [comment]
Thanks @Ric-Carey - this duplicates https://github.com/umbraco/Umbraco-CMS/issues/5737

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan This is a different issue, as https://github.com/umbraco/Umbraco-CMS/issues/5737 refers to missing crops and this seems like it's using cached/outdated crops.

This might be the case when the configuration is not updated correctly (and the old crops are merged with the saved value) or because the value converter caches the `ImageCropperValue` based on content changes (my best guess).
