### ISSUE TITLE
NestedContent -pin-button to keep section open

### ISSUE THREAD

**Issue by tomotrepo** [umbraco/Umbraco-CMS#8017]
Can I suggest a feature for NestedContent, to have 'Pin-button' beside 'Copy, Delete', to keep segment(s) open in editing time. It would be nice to see sibling's content - not to hide them every time.

**Comment by vaags** [comment]
It would be even better not to hide them at all in my opinion.

**Comment by nul800sebastiaan** [comment]
Hi there @tomotrepo and thanks for the feature request. Out of curiosity I'm wondering why you'd want to see multiple open NC items, is it because you want to get an overview of "what's already there" or do you just want to copy/paste between the items maybe?

We had a chat about this with a few people and while we acknowledge that the current situation might not be ideal, it's also not something a many people have indicated that they have a need for. Additionally, the actions menu is more meant to perform specific actions on each item, while pinning is an action, it seems more like a bit of a band-aid.
So for that reason, we won't be spending a lot of time ourselves on this feature request.

There's two other things to take into account: 
1. There's a new project just released, designed to work with existing Nested Content items, the underlying stored data is the same so you can switch a NC to this datatype and back: https://our.umbraco.com/packages/backoffice-extensions/perplexcontentblocks/
This project might do exactly what you wish Nested Content would do out of the box.,
2. At HQ we're working on the next new thing called the Block Editor (see roadmap: https://umbraco.com/products/roadmap/) which will keep all the items open by default. 

I'll close this for now but if there's an easy PR that someone wants to make to make the behavior configurable we would propably have a look at that. This would mean that you can configure "always closed" or "always open" on the NC datatype.

**Comment by tomotrepo** [comment]
Yeah, exactly what you found out. This came from our editors, not the programmers. Let’s say an editor is working on a segment of sliders: image, title, summary, and link. First he enters an image in nc1, then he goes to nc2 and doesn't see which image he entered in nc1 - so when he wants to check - n2 closes, and so on.
I'll check Perplex's ContentBlocks, thnx - maybe that would be the solution. Btw, we don't like to use a grid-editor and we convert every Umbraco to nc or https://our.umbraco.com/packages/backoffice-extensions/embedded-content-blocks/ (yes, that’s why we still mostly use v7 - maybe now is the time to switch ...)

Regards
