### ISSUE TITLE
404 error when viewing doctypes

### ISSUE THREAD

**Issue by junkin77** [umbraco/Umbraco-CMS#8042]
I see this error message when viewing a doctype under settings in the backoffice:
Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/ContentType/HasContentNodes

## Umbraco version

I am seeing this issue on Umbraco version: Umbraco Cloud 8.6.1 Didn't notice it before the upgrade to 8.6

Reproduction
------------
Under 'Settings' in the backoffice select a doctype (not element type) and I see this error display: Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/ContentType/HasContentNodes

![umbraco-hascontentnodes-404](https://user-images.githubusercontent.com/25978840/80795413-4f4ba680-8b94-11ea-91d6-54cc544ae83c.gif)

**Comment by nul800sebastiaan** [comment]
Well, that's not expected behavior of course! There must be something wrong with your site or with the upgrade since that works just fine in a fresh install of 8.6.1. 

I would recommend you reach out to Cloud support about this problem, seems like you are missing something. The `HasContentNodes` method was introduced in 8.6.0 (https://github.com/umbraco/Umbraco-CMS/pull/5668) - if yours gives a 404 that likely means that your dlls have not (correctly) been update.
