### ISSUE TITLE
Unexpected Xpath Behaviour

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#8066]
Hello,

Umbraco 8.6.1.

Strange one, I have just ran an xpath query:

`Umbraco.ContentAtXPath("//" + Models.Location.ModelTypeAlias)`

I would only expect nodes of document type "Location" to be returned. However, in the return it also included nodes of a different type of document type which had the property of Location on it as a textfield. 

Steps to replicate:

Create a node with alias of Location. Create a node with alias of Event and add a property called Location on it. Then search for the above Xapth. 

Cheers
Ric

**Comment by nul800sebastiaan** [comment]
You get what you ask for, *everything* that matches `Location` 😊

I think you need to use something like `//Location[@isNode='1']` to match only nodes, not properties. 

Two matches: 
![image](https://user-images.githubusercontent.com/304656/81570950-8fcfcf00-93a1-11ea-8e8c-fea0618b49e7.png)


Note: with NuCache, we strongly encourage you not to use XPath queries, they don't perform well since the cache is no longer actually represented as XML. This one in particular is not great, since it will scan ALL of your content for a match, even in v7 this would not be a nice query. 😅
