### ISSUE TITLE
List of pages to link to shows in wrong language

### ISSUE THREAD

**Issue by ek-create** [umbraco/Umbraco-CMS#8097]
When adding a link to the French (Canada) page (when it is on the right in split view), the search and the Content tree show the page names in English (see screen capture below). 

## Umbraco version

I am seeing this issue on Umbraco version: 8.6

### Bug summary
When adding a link to the French (Canada) page (when it is on the right in split view), the search and the Content tree show the page names in English (see screen capture below). 

### Specifics
- Running Umbraco 8.6.0 on our own Azure hosting. 
-  Working in pages in split view (default language is English (Canada) en-CA, other pages in to French (Canada) fr-CA).

### Steps to reproduce

When adding a link to the French (Canada) page (when it is on the right in split view), the search and the Content tree show the page names in English (see screen capture below). 

If you choose a page, it then correctly creates a link to the French version, but it is confusing for editors to see the pages listed in English when they expect to see them in French. 

### Expected result

It should show the pages listed in French not English.

### Actual result

The list of possible pages to link to is in English.

![search-umbraco-page-language](https://user-images.githubusercontent.com/65245094/81723009-71b8ac00-943f-11ea-81ae-5efbb0f4b354.jpg)

**Comment by nul800sebastiaan** [comment]
Thanks, at the moment, the dropdown above the content tree determines which language gets shown in the picker.

![image](https://user-images.githubusercontent.com/304656/82330656-6b987180-99e3-11ea-80ea-ce758946ebcf.png)

We are looking for some help with that issue and a good addition for that feature could be that pickers opened in side-by-side editing will use the culture from the side where the picker was opened. 

I'll close this so that the discussion can continue on #7546.
