### ISSUE TITLE
Umbraco 8 WYSIWYG - Lack of height

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco-CMS#8232]
If you just created a standard Editor Property and do not specify a height, very often when you view content even if there is content in the content editor it can show as empty and you have to be very specific to click into the 1px high area which then causes it to expand.

## Umbraco version

I am seeing this issue on Umbraco version:  8.5.3

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Editor property does not have height and does not show its content when viewed.

### Specifics

    * Umbraco version 8.5.3
    * Latest Chrome, Safari and Firefox on Mac
    * Checked in Brave and Edge

### Steps to reproduce

- In a document type go to add a content editor picker
- Do not specify a width or height
- Add content or view a new item in content with the editor - often it will appear closed (you just see the toolbar)

### Expected result

 * An editor with some height shown when new
* An editor showing the content when it has content

### Actual result

 * Height matching the content where there is some
 * Min height of the editor so if empty it has a space
* Possible default height value in Property when created to overcome the issue

**Comment by nul800sebastiaan** [comment]
Thanks for reporting @thenexus00. I'm afraid don't know where this problem is coming from for you, when you leave the width/height empty:

- If there's content in the RTE then it should auto scale the height to the amount of content that is in there (so it grows in height until there's no more content in the RTE)
- When you're creating a new page, the RTE sizes to 68px in height so that there's room for you to start typing (see screenshot).

![image](https://user-images.githubusercontent.com/304656/83858315-9a6d5200-a71c-11ea-9724-eb9db0f02c62.png)

As such, I am afraid there might be something wrong on your end with the configuration possibly? Not sure. All I can tell you is that what you're seeing is not default behavior.

I'll close this issue for now, I'll encourage you to discuss this on the forum at https://our.umbraco.com to see if you can get some help getting to the bottom of this.
