### ISSUE TITLE
"Hide label"-setting on block-list editor

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#8289]
When setting up a block-list-editor, we would see this as the main content on a page. As with grid and nested content, we are able to hide the label on the property-editor, giving the user a view that gives more focus on the block when composing a page.

**Comment by emmaburstow** [comment]
Hey @soreng,

Thanks for raising this issue - I'm a little confused as to what you mean though. Do we want the 'hide label' option? Or do we want the screen to scroll to the position of the block editor?

Thanks,

Emma

**Comment by nul800sebastiaan** [comment]
Additionally, I am not sure what a "block-list-editor" is, please enlighten us @soreng! 😄

**Comment by soreng** [comment]
@nul800sebastiaan https://github.com/umbraco/Umbraco-CMS/blob/v8/feature/block-editor-list/src/Umbraco.Web/PropertyEditors/BlockListPropertyEditor.cs

**Comment by soreng** [comment]
hide label on nested content:
![image](https://user-images.githubusercontent.com/359492/84749127-db395680-afb9-11ea-8500-ae9538cb79a6.png)

"distraction free" on grid layout
![image](https://user-images.githubusercontent.com/359492/84749279-0c198b80-afba-11ea-87de-474263111c91.png)

**Comment by nul800sebastiaan** [comment]
Oh, the upcoming Block Editor, you're so far into the future mate! 

We want to move away from the "hide label" paradigm in the future so we're not going to implement it for new editors. Instead, we want an additional new feature to put the label above the property. We're actively looking for contributions for that, or we might have to work on it ourselves soon. https://github.com/umbraco/Umbraco-CMS/issues/6502

I'll close this feature request in favor of #6502 which is the direction we want to go in, thanks for clarifying!

**Comment by ronaldbarendse** [comment]
@soreng I've also commented on this when the property actions were added as dropdown after the label: https://github.com/umbraco/Umbraco-CMS/pull/6593#issuecomment-545164470.

So the current situation is that hiding the label is removing/breaking property actions (for that property), but gives more space/width for the content (a trade-off I don't mind for Nested Content). Having the labels on top (#6502, as linked by Sebastiaan) keeps the property actions available and gives more space/width to the editor. This might also be implemented on the property itself (like the mandatory configuration), instead of the editor, so it's consitently available on all properties/editors!
