### ISSUE TITLE
Uploading large files (1GB+) to blob storage fails to display the file in the media library

### ISSUE THREAD

**Issue by gavimoss** [umbraco/Umbraco-CMS#8380]
When I try to upload large files (>1Gb < 2GB) in Umbraco 8, the files don't appear in the Media library despite being successfully uploaded to the blob storage.  Small files are fine and I can download the large files from the blob storage so I know Umbraco is successfully uploading them into there; it's as if the upload process never returns a success message back to Umbraco so it never creates the item in the Media library - it just seems to hang at 100% (see screenshot below).

<img width="789" alt="umbraco_issue" src="https://user-images.githubusercontent.com/29046997/86454948-deea0e80-bd17-11ea-8e8b-c00d7e6483e7.png">

I'm wondering if there is another way to upload large files directly to blob storage and then ask Umbraco to create a link from there perhaps?

**Comment by nul800sebastiaan** [comment]
Thanks @gavimoss - as a general note, Umbraco is not meant to be an assets management library and was never built to accept files of that size. I think you might have some luck looking at console errors or network errors in your browser's developer tools when you are uploading files of these large sizes. 

If you would like to dig in deeper then we'd welcome hearing about your results and possibly even looking at a fix, but please do note that I am not sure what level of support we would want to give for this use case. I'll set this to Up For Grabs meaning we're looking for a code contribution, but before you start coding, maybe first figure out what the actual problem is so we can guide you in what level of fixing we'd want to look at.

**Comment by RSDevelopsUK** [comment]
I'm in a similar situation and can share my findings:
I have an Umbraco version 8.6.2 build utilising the UmbracoFileSystemProviders.Azure.Media plugin.
I have updated the necessary web config settings to allow large files.
I then tried uploading a 500MB zip file to a folder in the media section (not ideal I know, but these are the clients requirements!) and waited.
I waited some more (just over 9 minutes to be precise)
I was about to give up hope when the library page refreshed and my 500MB zip was visible in the library (patience is a virtue and all that...!)
All throughout I had Chrome dev tools open and was watching the network tab intently. The PostAddFile was always pending and completed after 9.2 minutes (I have a good broadband connection)

What is interesting as well is that I had previously tried uploading the 500MB file in another folder and lost patience and navigated away. Upon returned to the folder later I can see that the file successfully uploaded there as well.

I'm not sure how similar your situation is to mine @gavimoss, but it seems that due to there being no visual representation that Umbraco is still uploading your file, you would be forgiven for thinking that it wasn't working.

**Comment by gavimoss** [comment]
@RSDevelopsUK I think my issue was slightly different as although my file upload was ultimately successful (I could see the video and download directly from my blob storage using another client application), Umbraco never created a Media Library item for it so it wasn't able to be referenced on the site.

I've since updated the app and I'm no longer using the Umbraco Media Library (for the videos anyway) in favour of a dedicated media hosting service; as @nul800sebastiaan mentioned, Umbraco isn't really designed to support the ~2Gb files I'm working with and it turns out media streaming is an even heavier kettle of fish to deal with so I had to move that part of the solution elsewhere.

Still using Umbraco for the CMS part of the site though, you can't beat it for that!

**Comment by nul800sebastiaan** [comment]
I think you've encountered what I was afraid of already, since we're not a media server, we really can't recommend storing / processing large files from within the Umbraco setup. I would indeed integrate with a digital asset management solution instead. I will tentatively close this issue for now since we're not intending to become a DAM solution. However if there's really strong new reasons in the future to reconsider then we can re-open this. Thanks for the feedback! 👍
