### ISSUE TITLE
V7.4.2 - Content is deleted when copying a child node

### ISSUE THREAD

**Issue by Lasher** [umbraco/Umbraco-CMS#8434]
Hi, Recently, a strange problem occurred when trying to copy a child node (inner item) and paste it, the content of the item (original item) gets deleted. Meaning, it's content tab turns to be empty after executing copy & paste.
Please help.
Thanks
Umbraco version: 7.4.2

**Comment by nul800sebastiaan** [comment]
Hey there @Lasher - ouch that sounds rough. Unfortunately version 7.4.2 is pretty old right now and this might be fixed in a newer version (nothing comes to mind I'm afraid). It would be worth a try to do an upgrade or if that's not in the cards, maybe try and get some help for this on our friendly forum at https://our.umbraco.com/

**Comment by Lasher** [comment]
> Hey there @Lasher - ouch that sounds rough. Unfortunately version 7.4.2 is pretty old right now and this might be fixed in a newer version (nothing comes to mind I'm afraid). It would be worth a try to do an upgrade or if that's not in the cards, maybe try and get some help for this on our friendly forum at https://our.umbraco.com/

Hi  **@nul800sebastiaan** ,
Thank you for your response
unfortunately, upgrading is currently out of the scope

i have tried to get some help using the forum 
here is the link: [https://our.umbraco.com/forum/using-umbraco-and-getting-started/102868-umbraco-742-content-is-deleted-when-using-copying-a-child-node](url)

but no replies so far.
