### ISSUE TITLE
Refactor Media Picker configuration

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#8471]
At the moment Media Picker has a "Pick multiple items" to decide whether to picker should be a multi picker or not.

![image](https://user-images.githubusercontent.com/2919859/88398352-91683b00-cdc5-11ea-9515-099af0c7d40d.png)

However many other pickers like Multi URL Picker and MNTP have "Minimum" and "Maximum" prevalues to configurate the picker as multi picker. I think this is more flexible since you can configurate the picker to allow selecting up to e.g. 3 or 10 images instead or unlimited number of images.

Furthermore it has a "Pick only images" property and "Disable folder select". I think these could be consolidated to a single prevalue to select media type similar to "Allow items of type" in MNTP-configuration.

![image](https://user-images.githubusercontent.com/2919859/88399027-88c43480-cdc6-11ea-8f9e-477a7181e3ad.png)

**Comment by nul800sebastiaan** [comment]
That's great but we somehow need to keep exposing "is multiple" everywhere since there is code relying on that boolean.. so you'd need to combine the min = 0 and max = 1 to "is multiple == false" or something.

Same for pick only images / disable folder select.

Might be better to make a v2 picker.. Not sure. We learned it's a pain to have "v2" pickers, people don't understand what the difference is, panic, then try to switch to the new version, losing data, getting sad.

**Comment by bjarnef** [comment]
Would it be possible via a migration to update max to 1 is multipicker was false? Otherwise it could leave both min and max with value zero (multi picker and unlimited), which is default in media picker.

This might be a "easy" change and er could then look at only images / disable folder select later and whether we need to make a v2 picker or something else.

**Comment by nul800sebastiaan** [comment]
Yep, I think a migration like that would be fine since it doesn't need to update any content.

And then indeed it would be cool to have "allow items of type" in a later iteration, maybe v2. I am not sure how we enforce "Pick only images" property and "Disable folder select" at the moment, maybe it can be migrated too if we only rely on the built-in `Folder` and `Image` datatypes, not sure.

**Comment by nul800sebastiaan** [comment]
I think this is all covered now in the mediapicker v3! I'll close this one.
