### ISSUE TITLE
NetCore: Error selecting a child of a node with list view

### ISSUE THREAD

**Issue by ksolberg** [umbraco/Umbraco-CMS#8816]
To reproduce:

1. Create two document types, f.ex. Articles and Article
2. Allow Article as child of Articles
3. Enable List view on Articles
4. Create two content items: Articles and a child Article
5. Select Article and Umbraco will show the article, but also display an error saying:

Request error: The URL returned a 404 (not found):
/umbraco/backoffice/umbracotrees/contenttree/GetTreeNode/9040795c09f348ae80f9eef63ff6758d

![error](https://user-images.githubusercontent.com/144644/92204457-d5019a80-ee83-11ea-8b8b-e92373451985.PNG)

**Comment by elit0451** [comment]
Thank you for reporting this issue @ksolberg! The cause of it was due to the wrong mapping on the _id_ parameter - we should get it from **Route** rather than from **Query**. 

The solution to this is to add `[FromRoute]` attribute to the passed parameter. For a reference, check [this PR](https://github.com/umbraco/Umbraco-CMS/pull/8847) 🙂
