### ISSUE TITLE
Dotnet core alpha: cannot disable url tracker

### ISSUE THREAD

**Issue by crgrieve** [umbraco/Umbraco-CMS#8835]
## Umbraco version

I am seeing this issue on Umbraco version: Dotnet core alpha

### Bug summary

Error when choosing to "Disable URL tracker".

### Expected result

Like on v8 we should have a message saying it worked.
![image](https://user-images.githubusercontent.com/9353655/92304903-30ae4f80-ef7a-11ea-8c61-454caddc9aca.png)

### Actual result
Error saying it didn't work and to check logs. There isn't anything in logs to indicate what is wrong.
![image](https://user-images.githubusercontent.com/9353655/92304911-3efc6b80-ef7a-11ea-9115-b7a47fb34949.png)

**Comment by elit0451** [comment]
Thank you for reporting this issue @crgrieve! The cause of it was due to trying to update the value of _DisableRedirectUrlTracking_ in **~/config/umbracoSettings.config** instead of also doing so in **appsettings.json**

A solution has been implemented in this [PR](https://github.com/umbraco/Umbraco-CMS/pull/8852) 🙂
