### ISSUE TITLE
Allow Nested Content inside Block List Editor

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#8895]
Given you can natively add Nested Content inside another, it will be great to be able to do the same with the Block List editor

**Comment by nathanwoulfe** [comment]
Might be another one for @nielslyngsoe to clarify, but my understanding is that Block List is intended to replace NC - it does everything NC does, plus more, so nested Block Lists would enable the equivalent editing experience (assuming that's possible). There's also some interesting model-syncing in NC that may not play nice with Block List.

**Comment by nielslyngsoe** [comment]
@TRexStark It's not intuitive that you can pick it and then later you will be shown that it's not supported. That's not a good experience, but that's what we have at hand currently, there are a few other editors that are not supported either. Would be lovely to improve this experience.

On the other side, the intend of Block List is to replace Nested Content. As Nathan mentions, so if you're building something new you should not use Nested Content.

Let me know if you see any difficulties with that path?

**Comment by TRexStark** [comment]
Thanks @nathanwoulfe and @neilgaietto ... Here's an example where I thought a nested content may be useful.

If you have a rotating banner but you would like to have a unified content for the banner, so you will have a string for a heading and a textarea for multiline content, but you would want to have multiple images rotating. So you would need a "Sub" Nested list of images to be added.

Unless if you have a suggestion on how you can achieve similar outcome without this feature?

Thanks

**Comment by duanleou90** [comment]
@TRexStark I agree with you. Umbraco team should support a nested content in a nested content. Many situations we will need it

**Comment by nathanwoulfe** [comment]
> If you have a rotating banner but you would like to have a unified content for the banner, so you will have a string for a heading and a textarea for multiline content, but you would want to have multiple images rotating. So you would need a "Sub" Nested list of images to be added.

I'd do that either with multi media picker or by nesting another block list, with the required properties on the list element - maybe an image picker, a field for alt text and a link picker (just an example). 

I don't see what nested content would offer that can't be achieved with a nested block list?

**Comment by nielslyngsoe** [comment]
@TRexStark @duanleou90 The Block List property editor is intended as a replacement of Nested Content, there should be no job that you previously used Nested Content for that the Block List property editor cant replace. When you think Nested Content, then you should from now on just think Block List. As of upgrade reasons we cant remove Nested Content, therefore it's still around. But you should see it as `deprecated` and use Block List for this need instead.

Let me know if you experience any situation that Block List cant handle for you, but currently I see no reason not to use Block List for anything. :-)

**Comment by TRexStark** [comment]
> > If you have a rotating banner but you would like to have a unified content for the banner, so you will have a string for a heading and a textarea for multiline content, but you would want to have multiple images rotating. So you would need a "Sub" Nested list of images to be added.
> 
> I'd do that either with multi media picker or by nesting another block list, with the required properties on the list element - maybe an image picker, a field for alt text and a link picker (just an example).
> 
> I don't see what nested content would offer that can't be achieved with a nested block list?

That's interesting, so from what i understand, you can nest Block Lists? I mean have a block list inside another?

**Comment by duanleou90** [comment]
@nathanwoulfe @TRexStark I know you mean now. We can have nested Block Lists.

**Comment by nathanwoulfe** [comment]
Yup, nesting works - and can do some pretty cool stuff: https://twitter.com/skttl/status/1303675858494861312?s=19

**Comment by TRexStark** [comment]
That's super great! love it.

Thanks @nathanwoulfe and @nielslyngsoe

**Comment by wvduffelen** [comment]
I've found this issue because I had the same error! The reason why I want to use Nested Content inside a Block List is because of the editorial experience... I only have one Element Type that can be added. The benefit of Nested Content in stead of Block List is that when you only have one type in Nested Content it will automatically add that one. With Block List you always have a click extra. But i understand it will not be supported as stated in the [Github](https://github.com/umbraco/Umbraco-CMS/blob/862a7fdce69a7cce3e0cf139922f74480313fdb4/src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js#L230)

I now use a mix of Nested Content and Block List because of this reason. If an editor needs to fill multiple nodes with a lot of content it is a click extra where (in my opinion) its unnecessary.

**Comment by TRexStark** [comment]
I agree @wvduffelen ... I actually ended up reverting back to full Nested content as editors found the Block List so confusing with multiple clicks, where Nested Content is just there to edit and doesn't require creating additional components.

I was excited about BlockLists at start, but with implementation, not too much now.

**Comment by wvduffelen** [comment]
I'm in doubt what to do now... I like the fact dat you can add secondary 'information/settings' to a settings tab so that settings that aren't used that often don't affect the editor experience! But only Nested Content items work fine for me... My only concern was one of the first reactions.

_As of upgrade reasons we cant remove Nested Content, therefore it's still around. But you should see it as deprecated and use Block List for this need instead._

I haven't installed U9 yet but I hope there's still Nested Content there or else a good migration would be necessary for this exact reason and we just have to deal with the fact that the editor experience isn't the way as we wanted it to be...

**Comment by nielslyngsoe** [comment]
Nested Content is still in Umbraco 9, V9 is just V8 with NetCore, so no worries :-)

**Comment by nathanwoulfe** [comment]
I think there's an issue floating around to change how Block List works with single options, to change the add-content button behaviour - if there's only one option and nothing one the clipboard, there's no need for the block-picker overlay

**Comment by wvduffelen** [comment]
> 
> 
> I think there's an issue floating around to change how Block List works with single options, to change the add-content button behaviour - if there's only one option and nothing one the clipboard, there's no need for the block-picker overlay

That would be the way to go then in my (humble) opinion!

**Comment by TRexStark** [comment]
@nathanwoulfe I think that is a priority if we want to migrate from Nested Content to Block List.

As an experiment, I built a super customisable Single Page Site using Block Lists only - I mean every item is customisable from colours to fonts, size, buttons and what have you. After completing it, I was happy with how flexible it is, when presented to a tester (Non-Technical person) - He was, nah, too much, I'd rather use the other Drag and Drop editors out there.

As a conclusion, Block Lists are not for everyone or everything. Long live Nested Content (For now) :D

**Comment by shearer3000** [comment]
bump - there is no reason why an element type used in a block list editor shouldn't allow the nested content editor to be used on it. Unless nested content editor is marked as obsolete/retired in the core (which it isn't as far as i know)

**Comment by nielslyngsoe** [comment]
@shearer3000 Nested Content has a technical problem(other would call it a hack) of which we can’t ensure the changes made to data is synchronized in time, this is only a problem when used in the context of Blocks where the data needs to be synchronized to the document for changes to be included in a save action. This is the sole reason for Nested Content not being allowed in Blocks.

This could be fixed, but we haven’t prioritized fixing this legacy property editor.
I would rather recommend bringing improvements for the cases where Block List Editor doesn’t perform as well as Nested Content.

**Comment by shearer3000** [comment]
hi @nielslyngsoe thanks for the reply. Can you confirm 'legacy property editor'? Nested Content editor is not flagged that way in the backoffice - is it due to be removed from umbraco in favour of block editor? it seems there is still valid use case for simple element types using, well, the nested content editor.

**Comment by nielslyngsoe** [comment]
@shearer3000 as far as I know, the plan is to keep it until v.13.

Out of interest in the product design could you elaborate more on the use case and the details of such where you see Nested Content fitting? Thanks in advance

**Comment by shearer3000** [comment]
Hi @nielslyngsoe the use case was one of UI simplicity. In situations where the element doctype might only have one or two fields, then its arguably simpler to have the content editor author that content "in line".

to demonstrate the difference with examples:

**Nested content** where "Gadget" elements are being used to author a simple list of content:
![image](https://user-images.githubusercontent.com/2433680/190312265-90677bb0-857a-44dc-9fdf-f3ede31a0f1f.png)

and in contrast, a list of "Widget" elements authored with the **block** editor means a flyout for the main element content:
![image](https://user-images.githubusercontent.com/2433680/190312801-35585e2f-2666-4880-96a2-e0eab314c2d4.png)

and then another overlay flyout for each sub element content:
![image](https://user-images.githubusercontent.com/2433680/190312944-2a0abc10-102a-45da-a28c-93ce0930f7f6.png)

still being able to used nested content within blocks seems like it would be the best of both worlds.

**Comment by nielslyngsoe** [comment]
@shearer3000 thanks for sharing.
It seems like you are unaware of the Inline mode you can toggle on for Block List Editor. With this turned on you should get the exact same experience as with Nested Content.
Let me know if that helps for your use case, thanks :-)

**Comment by shearer3000** [comment]
Hi @nielslyngsoe Yes I'm aware of the inline mode. However, my understanding is that can only be toggled on for the entire block editor. The desired use case would be most blocks using the [default] overlay editor experience but with a select few configured to use the inline editing mode.

In my original example, i realise the second step could've been configured as inline rather than flyout (i.e. avoiding 1 of the 2 flyouts the screenshots indicate), but the ideal would be no flyout at all for certain blocks.

if there's no appetite/demand in the community for this dual UX capability then that's fine, I was just putting the idea out there :)
