### ISSUE TITLE
Block List Item Naming

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#9229]
Rather than having to add an extra field to the Content Section of a Block so that you can then use that field to name each individual block, it would be good if the name of the Block was editable. See red highlight on screengrab. Then you would have a standard way of providing a unique name for all blocks in a list.

Not sure if this has already been requested, I couldn't find any suggestion of this.
![Screenshot](https://user-images.githubusercontent.com/22817718/96607559-615f0400-12f0-11eb-9a70-e1dbd3e7a330.png)

**Comment by nielslyngsoe** [comment]
@uSkinned this hasn't been requested before but is never the less a relevant request.

In general, your request could be solved by adding a Property to the Content ElementType with the name and alias of "Name", and then you should write the following template for your Block "{{name}}".

I completely understand that this would then be a different UI experience than we have for Documents, as the 'name' editing can happen in the Header.

But it also enables you to compose your Block Name of several properties, relevant for that Block.

We can come up with a few more or less "hacky" solutions to hide the name prop and display it in the Header(in the marked spot on your screenshot) but I'm not sure that would be beneficial in the longer run.

First, let me know if the proposed solution can work for your scenario.

Btw. Notice in the label you can write the Type as well. like so: "Banner — {{name}}", this will help users identify the Blocks. Otherwise, it is a bit hard to identify which Block the existing content has been made of.

**Comment by uSkinned** [comment]
Hi Niels,

Thanks for getting back so quickly. We just wanted to check with you guys before going down the hacky approach and adding a new field to the Content section, because this isn’t Content we were kind of against this approach however if that’s our only option we will need to go with this approach for now. We would probably prefer to have this sitting in the Settings section of a content block however there is a second issue with not being able to pull settings values into the Block list. 

https://github.com/umbraco/Umbraco-CMS/issues/8689

Do you know if there are any plans to get this working?

Cheers,

Marc

**Comment by nielslyngsoe** [comment]
@uSkinned oh yes, good point. We will be looking into this in near future.

**Comment by uSkinned** [comment]
@nielslyngsoe any indication when this might happen as we need to know if we can wait for this or need to introduce a name field into the content tab.

**Comment by nielslyngsoe** [comment]
Hi @uSkinned, I made this avaiable in this PR: https://github.com/umbraco/Umbraco-CMS/pull/9275

Which means it will be part of next release (8.10), which will be at the end of this year.

**Comment by emma-hq** [comment]
Hey @uSkinned,

Thanks for reporting this one. It's a relevant request! 

If I'm reading the comments correctly here, Niels' fix in #9275 should allow you to add the field and pull the value from settings into the block - so this issue can be closed? If not, please feel free to reopen. 

Emma
