### ISSUE TITLE
Sort options for a multinode treepicker

### ISSUE THREAD

**Issue by Wolfkhan66** [umbraco/Umbraco-CMS#9285]
Would it be possible to get some sort options for a multinode treepicker to sort on save?
e.g. ensure nodes in the tree picker are sorted alphabetically ascending by node name on document save.

This is purely to better the back office experience when selecting a large number of nodes instead of having to manually drag them into order if something new is added at a later date.

**Comment by nul800sebastiaan** [comment]
Hi @Wolfkhan66 - We don't do this automatically but in order to achieve this you can hook in to the contentservice events and perform the sorting exactly the way you like it. Some documentation is here: https://our.umbraco.com/documentation/Reference/Events/ContentService-Events

For questions around implementation, make sure to head to the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
