### ISSUE TITLE
Umbraco 8.9 - MNTP ui issue in editor pane - expand icon has not-allowed class applied 

### ISSUE THREAD

**Issue by mjbarlow** [umbraco/Umbraco-CMS#9314]
When I create a multi node tree picker and limit it by a document type, I then open the picker and drill down to the containing folder of the node that I want to pick. The issue is that the cursor "not-allowed" class is on the block that contains the expand option.

## Umbraco version

I am seeing this issue on Umbraco version: 8.9

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The issue is that the cursor "not-allowed" class is on the block that contains the expand option. Which makes it seem that the expand icon can't be clicked:

<img width="394" alt="expand-not-hover-state-not-allowed" src="https://user-images.githubusercontent.com/1984515/97690252-a45d6c00-1a94-11eb-9a7f-cf488110151c.png">

See here the class is applied:

<img width="857" alt="not-allowed" src="https://user-images.githubusercontent.com/1984515/97690567-0cac4d80-1a95-11eb-9933-5c56cb22291a.png">

### Steps to reproduce

Create a multi-node tree picker
Set the allow type to one specific doc type
Pick that allowed type from a folder (that has a list view)

### Expected result

Should not have the not-allowed class applied to the expand icon

### Actual result

Has the not-allowed class applied to the expand icon

**Comment by nul800sebastiaan** [comment]
Hi @mjbarlow - I can't reproduce this, am I doing something wrong?

![9314](https://user-images.githubusercontent.com/304656/97978564-03411f00-1dce-11eb-8699-9e9b15af3f58.gif)


Ah, I think you might not have updated all files during upgrade or haven't updated the version in ClientDependency.config since that block of html was changed and should look quite different: 

![image](https://user-images.githubusercontent.com/304656/97978835-7185e180-1dce-11eb-8622-c6ed01287062.png)

If you haven't upgraded or have other steps to reproduce then let me know so we can revisit this. Thanks!
