### ISSUE TITLE
Annoying reformat of views/web.config when upgradring

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#9382]
When upgrading using nuget `Update-Package UmbracoCms`, I usually let it overwrite all my files, and then handle eventual changes in git. But one change that annoys me, is how it changes the formatting of Views/Web.config. See this screenshot
![image](https://user-images.githubusercontent.com/3726467/98920952-05436600-24d1-11eb-8b94-c7c5fd80c35c.png)

Compared to /web.config, it's a lot easier to digest, it just moved some assemblybindings around.
![image](https://user-images.githubusercontent.com/3726467/98921036-2015da80-24d1-11eb-980b-8005c2a1d850.png)

Can we do anything to make it not mess up Views/Web.config like that?

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1 - but it's not new, it has been like this earlier too

Reproduction
------------

### Steps to reproduce

Install Umbraco using Nuget, make an effort to make your Views/Web.config look pretty, when you are adding stuff to it.

Upgrade Umbraco using Nuget, let it overwrite all files. Notice how the formatting in Views/Web.config is now all messed up.

### Expected result

Views/Web.config is transformed in a prettier way, not messed up like the screenshot.

### Actual result

Views/Web.config is messed up, making it harder to accept and commit the changes.

**Comment by rbottema** [comment]
Yes that's very annoying! I actually took a look at it this October, but I wasn't able to fully understand & test what was happening. I've been meaning to share my notes, so I'll do so here:

On line 390 in the build.ps1 `Views/web.config` is used as a .transform file, but that doesn't happen for any of the other web.config files.
https://github.com/umbraco/Umbraco-CMS/blob/c413079159c3c685a46a39903501aeafd2f94a83/build/build.ps1#L384-L392

In the nuspec there is also the `Views/web.config`, but now with an XDT file. Also note the `FIXME` comment here. I don't really understand what it says, but it's been there since @zpqrtbnk wrote it in 2018.
https://github.com/umbraco/Umbraco-CMS/blob/c413079159c3c685a46a39903501aeafd2f94a83/build/NuSpecs/UmbracoCms.nuspec#L57-L63

Probably the issue is caused by the fact that there are two transformations going on.

**Comment by nul800sebastiaan** [comment]
Hi both! This is unfortunate indeed. We've decided that this is not going to be fixed for v8, vNext will not be using the powershell script any more and therefore we expect no problems there when doing upgrades like this.

While I would LOVE to get this fixed for v8, the time investment (even if there was a perfect pull request for it) is simply too much for the gains it would have. 🙂
