### ISSUE TITLE
Backoffice load balancing in V8. Supported?

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#9443]
Is the documentation https://our.umbraco.com/documentation/getting-started/setup/server-setup/load-balancing/ for load balancing the backoffice still correct for V8 given there is now database level locking? 
If load balancing is still not supported, what changes are required?

**Comment by Shazwazza** [comment]
That's the million dollar question :) 

I think what you are really asking is ... "Can the back office be load balanced?"

With distributed locks in place, the theory is 'yes' and that was the intention of creating the distributed locks. However, there has been no testing regarding whether the back office can be load balanced effectively or what changes would still be required to make that work. High volume concurrent testing is the main thing here to determine what may explode. We've just not prioritized time to create and perform these tests but if anyone has the time and ability to do so, then please please do! :) 

Keeping in mind that things like auto-scaling in Azure behave differently than classic hosting providers. Trying to auto-scale the back office won't work because that means that there are a number of web apps all pointing and writing to the same shared network file system. So things like the cache files and index files would need to be dealt with differently (i.e. only stored in local temp file system and/or using hosted search services like ExamineX and Azure Search). 

(I'll close this issue since this is just a discussion)

**Comment by nzdev** [comment]
So in theory, if you were using ExamineX, Azure Blob Storage for Media and made no changes to anything written to disk (templates, css, js) and there were no bugs in the locking code, then it might work?

**Comment by Shazwazza** [comment]
That would be the theory :) 
You'd still need to set the 2 app settings for azure

```
<add
    key="Umbraco.Core.MainDom.Lock"
    value="SqlMainDomLock" />
<add
    key="Umbraco.Core.LocalTempStorage"
    value="EnvironmentTemp" />
```

some temp files still get created like the last synced marker files and the plugin hashes
