### ISSUE TITLE
NetCore: Members functionality needs to be migrated to .NET Core

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#9471]
## Members functionality needs to be migrated to .NET Core

Members and related functionality needs to be migrated to .NET Core. More detail can be fleshed out from this issue but essentially we will be:

- Using the ASP.Net Core identity implementation
- Creating `MemberManager` for the *Manager*
- Creating `MembersUserStore` for the *Store*
- Creating `MembersIdentityUser` for the _User_ class
- Removing/moving code from the `MembershipProvider`
- Removing/moving code the `MembershipHelper`
- Attempt to keep the `MemberService` functional with the same signatures
- Unit and integration tests to be added for all relevant areas

There are wider areas to complete around:

- Roles
- Public Access
- Passwords
- Back Office
- Authentication/Authorization
- Macros and views
- Enabling external logins for members (TBC re scope)

Will be easier to create these as individual GitHub issues and link to this main issue.

**Comment by rustybox** [comment]
I know that this is how things are now, but otherwise is there good reason to split the usermanagers? An UmbracoMember and an UmbracoUser are both just users with different claims.

**Comment by Shazwazza** [comment]
Users and members are entirely different things though. They have different storage systems, different properties, different everything. Members are based on member types which are dynamic for each instance and users are not. Combining these forces has been floated around for a while and though it might be possible in some way and shape, I'm not convinced that its the better approach. It's also hugely out of the scope for the first netcore release.

**Comment by rustybox** [comment]
> It's also hugely out of the scope for the first netcore release.

Fair

**Comment by Shazwazza** [comment]
We can defo revisit when all is done. Will be the first time that both members and users are based on identity, it's almost 2021 😛

**Comment by rustybox** [comment]
One final protest, I won't moan any further but looking at the current setup in BackOfficeServiceCollectionExtensions which is a bit of a hacky mess, and the PR which aims to duplicate that setup, I honestly believe this is the wrong approach.

> Users and members are entirely different things though. 

Authentication, Authorization, object ACL, what's different.

> They have different storage systems, different properties, different everything.

Why different storage systems?
Different properties == different claims.

> Members are based on member types which are dynamic for each instance and users are not.

Users have fixed set of claims, members have dynamic set of claims.

> It's also hugely out of the scope for the first netcore release.

I think it is a decrease in scope to only have one UserManager, one PasswordHasher, etc etc

**Comment by Shazwazza** [comment]
User UserManager is not just "Authentication, Authorization, object ACL, what's different.". A UserManager is used to manage a users in a UserStore, to persist and retrieve them, to manage passwords and various other utilities like converting resolving the 'IdentityUser` object from a ClaimsIdentity, etc... It is the "Service" (UserManager) to the "Repository" (UserStore). Then there is the SignInManager responsible for interacting with the UserManager to create the authentication ticket and the resulting Identity (i.e. ClaimsIdentity).  

> Why different storage systems?

Member are based on member types, just like document types are configured by the end-user. They have dynamic properties. Users are not like this at all. They have different storage systems, different properties and therefore different implementations of `IdentityUser` and UserStores and UserManager's.

> Different properties == different claims.
> Users have fixed set of claims, members have dynamic set of claims.

What you are referring to is the Identity that is used within the application (i.e. ClaimsIdentity) that stores claims. This isn't the responsibility of the UserManager, that resides in the UserClaimsPrincipalFactory which extracts claims from the underlying `IdentityUser`.  

There's TODO notes on the legacy `UmbracoBackOfficeIdentity` (inherits from ClaimsIdentity) to be removed since we should only be relying on ClaimsIdentity and in this case, yes that will be the same as a Member. The Principle/User/Identity assigned in the request is based on ClaimsIdentity with claims.

> I think it is a decrease in scope to only have one UserManager, one PasswordHasher, etc etc

I agree! We shouldn't duplicate the entire thing. 

I honestly haven't had a chance to look at any PRs yet for members yet and maybe it was a mistake of mine to reply here before seeing what has been proposed. 

But absolutely we should re-use as much code and decrease duplication wherever possible and this is certainly possible  to do between Users and Members. Although they will both have different implementations of `IdentityUser`, `UserManager<T>` and `IUserStore<TIdentityUser>` they will both be based on base classes which can most likely share quite a lot of logic. 

> which is a bit of a hacky mess

Sorry you feel that way. If you have constructive feedback it is most welcomed.

**Comment by rustybox** [comment]
> Sorry you feel that way. If you have constructive feedback it is most welcomed.

Perhaps that came across more critical than intended, part of the hacky mess is from my PR for the MSDI switchover so I'm just as guilty as anyone else for making a mess.

Main suggestion

Reduce class / interface count, here are the moving parts to keep track of.

+ IBackOfficeUserManager : IBackOfficeUserManager<BackOfficeIdentityUser>
+ IBackOfficeUserManager\<T\>
+ BackOfficeUserManager : BackOfficeUserManager\<BackOfficeIdentityUser\>, IBackOfficeUserManager
+ BackOfficeUserManager\<T\> : UserManager\<T\>
+ UserManager\<BackOfficeIdentityUser\>

There is no way that many classes and interfaces are required.

**Comment by Shazwazza** [comment]
Ah yes some of this can be reviewed and modified for re-use. This has all been migrated from old identity to new without the notion of members but since we have them we should re-use. I appreciate raising this since yes you are right and it can easily be cleaned up and simplified. I'll do it now 👍 

> Is there a reason that combined member+user ClaimsPrincipalFactory / UserStore, UserManager, IdentityUser, implementations can't exist?

I suppose if we wanted to 'stringly' identify custom properties for users than that could work but it's not the prettiest when they can be strongly typed. Things like AllowedSections, etc... In the meantime we can definitely share a lot of this. If we determine that after that cleanup that we can save more code by doing something like this and it makes sense then sure let's explore those options.

UserStores will definitely be different, they will support different features and they persist to different services but we can see what can be re-used, perhaps a lot, I'll see. 

Other things like BackOfficeClaimsPrincipalFactory will not be used for members. 

---

@emmagarland re: UmbracoMembersSignInManager  you won't need that one, we will just use the default aspnet SignInManager for members which will use the default aspnet identity schemes. [This class does not cater well for custom schemes](https://github.com/dotnet/aspnetcore/issues/27979) and we don't need them for members.

I'll commit some change re: the above so we aren't fully duplicating everything but don't let that hold you back for now we can always adjust later.

**Comment by rustybox** [comment]
That all sounds fair!

WRT 'stringly' typing, that wouldn't be the case in a member **has a** IdentityUser scenario

Other remarks. default IdentityUser PK (string) might make life easier with the oauth stuff from #9470

**Comment by emmagarland** [comment]
I also commented on some duplicated areas that I wondered if we would combine with Backoffice Users but I will leave that for now so we don't end up with big merge conflicts. 

@Shazwazza thanks, I will continue with adding the CRUD functionality for members and not do the UmbracoMembersSignInManager anymore. I will probably have a lot of questions once I've finished the first PR draft, for now I'm noting them as I go. Will let you know when I'm ready for review.

**Comment by Shazwazza** [comment]
Also realize that the base user class was brought up from v8 using the old identity user which I think can be very much simplified. Currently that user is in the Core project so it doesn't have access to aspnetcore stuff which already has a base user class that we could use. I'll see what is possible for cleanup but definitely worth it.

> WRT 'stringly' typing, that wouldn't be the case in a member has a IdentityUser scenario

I guess I'm not quite sure what you are meaning here by **has a** ?

The `IBackOfficeUserManager<T>` was born out of migrating I believe, not as a design. However, it can just be renamed `IUmbracoUserManager<T>` and be used as the centralized/shared interface from members/users where T is the base user of both users and members. Then IBackOfficeUserManager is just there so for to assign it's strongly typed user and additional features and is also nicer than injecting a generic. Would be similar with the MembersUserManager and then code is shared.

**Comment by rustybox** [comment]
> I guess I'm not quite sure what you are meaning here by has a ?

I mean composition vs inheritance, do those additional downstream properties need to live on the IdentityUser or could a downstream class reference a IdentityUser.

> IUmbracoUserManager<T> and be used as the centralized/shared interface from members/users where T is the base user of both users and members

Sounds nice

**Comment by Shazwazza** [comment]
> I mean composition vs inheritance, do those additional downstream properties need to live on the IdentityUser or could a downstream class reference a IdentityUser.

ahh i see what you mean, i'll see how some refactoring/cleanup goes.

**Comment by Shazwazza** [comment]
@emmagarland One thing that is overlooked and potentially out of scope is enabling external logins for members like the UmbracoIdentity package allows. This would need additional DB tables, services, etc... This all exists in the UmbracoIdentity project but we've forgot to chat about that. It can also wait till the guts of everything else is in place so maybe that can be a bullet point in the `There are wider areas to complete around` in your notes.

**Comment by emmagarland** [comment]
@Shazwazza yes I saw that in the Identity project and was wondering about that too. Have added to the notes as a future task to discuss and decide if in scope.

**Comment by Shazwazza** [comment]
@emmagarland yep and as part of not duplicating code we should probably look into just re-using the existing table to cater for both members and users. Would be easy but means there won't be referential integrity on the table but i think that's an ok trade off than having 2x the same tables. The user/members key in that case will be it's GUID (means we also need to make a GUID field on a user ... which should be there anyways). But anyways, i think we can deal with that all much later 👍

**Comment by Shazwazza** [comment]
@emmagarland Have pushed a branch here that i'll merge tomorrow https://github.com/umbraco/Umbraco-CMS/pull/9496 it will look like a lot of noise so not looking for a review or anything but just wanted to put it somewhere for now. This is some changes to pull apart the BackOfficeUserManager, BackOfficeIdentityUser, and others so that they can be re-used in theory with members. 

We can always re-factor what your outcome is back into these things but once merged you will have the option to try to use them. There's still more bits to do like pulling apart the user store for re-use as well but i'll do that tomorrow.

Here's the gist for now:

* `UmbracoIdentityUser` is the base class that can be shared by both users/members. There's no more generics involved because we know what id types users/members will use
* `UmbracoUserManager<TUser, TPasswordConfig>` is the base class that can be shared by both users/members.

**Comment by emmagarland** [comment]
@Shazwazza great, I'll have a look and merge it when it is in.

I was going to check in my initial PR with a simple member identity user implementation for now, to get the back-office members functionality (create etc) working with the new manager, store and identity member user.

Then we can implement the identity user base class in future.

I'm on hols until Tuesday now, but I'd like to get an initial PR for you to review hopefully next week, so we can progress and split tasks further from there.

**Comment by emmagarland** [comment]
@Shazwazza this is the big one that was a hold-all for members functionality. I'm wondering whether it is better now to have smaller specific tasks and close this one (based on how much we have left on the bullet point list)?

**Comment by Shazwazza** [comment]
The only thing left is external logins. We have another task for that but that will happen after Examine work is done.

**Comment by emmagarland** [comment]
Thanks @Shazwazza
