### ISSUE TITLE
Umb8 vs umb7 examine indexes no longer have nodeTypeAlias field only the special examine __NodeTypeAlias field

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#9539]
Noticed when updating an examine query from v7 to v8, that nodes were no longer being excluded by the nodeTypeAlias GroupedOr we had.

It would seem that umb8 doesn't now have a nodeTypeAlias field.. only the underlying examine special __NodeTypeAlias

Is this by design, and are we safe to use "__NodeTypeAlias" instead?

```c#
        var searcher = ExamineManager.Instance.TryGetIndex("ExternalIndex", out var externalIndex) ? externalIndex.GetSearcher() : null;
        //var searchProvider = ExamineManager.Instance.DefaultSearchProvider;
        // limit to content and default is or
        //var criteria = searchProvider.CreateSearchCriteria(IndexTypes.Content, BooleanOperation.Or);
        var searchCriteria = searcher.CreateQuery(category: IndexTypes.Content, defaultOperation: BooleanOperation.Or);
        // set up a filter to query the index
        IBooleanOperation filter = null;
        // exact phrase match - case sensitive (this does check for term in each of the fields)
        filter = searchCriteria.GroupedOr(new[] { "gridContent", "nodeName", "metaDescription" }, terms.Boost(8));
        // split on words and allow wildcard plurals etc
        foreach (var t in terms.Split(' ')) { if (t.Length > 2) { filter.Or().GroupedOr(new[] { "gridContent", "nodeName", "metaDescription" }, (t.MultipleCharacterWildcard())); } }
        // split on words fuzy extends
        //foreach (var t in terms.Split(' ')) { if (t.Length > 2) { filter.Or().GroupedOr(new[] { "gridContent", "nodeName" }, t.Fuzzy(0.5f)); } }

        // exclude by HideFromSearch
        filter.Not().GroupedOr(new[] { "hideFromSearch" }, "1");
        filter.Not().GroupedOr(new[] { "__NodeTypeAlias" }, new[] { "datedPage", "plotPage" });

        @*string stringToParse = searchCriteria.ToString();
            int indexOfPropertyValue = stringToParse.IndexOf("LuceneQuery:") + 12;
            string rawQuery = stringToParse.Substring(indexOfPropertyValue).TrimEnd('}');
            @(rawQuery)*@

        // get our results
        //only need to load upto our current page (examine optimised)
        //items = searchProvider.Search(filter.Compile(), pageSize * (page));
        items = filter.Execute(maxResults: pageSize * (page));

```

**Comment by Shazwazza** [comment]
> Is this by design, and are we safe to use "__NodeTypeAlias" instead?

yes it is by design and yes it is safe.

The double underscore prefix on field names indicates system fields that should be analyzed differently and not as full text (i.e. standard analyzer). double underscore prefix names by default will be analyzed with our custom `CultureInvariantWhitespaceAnalyzer` which is a combination of `LetterOrDigitTokenizer` (only includes letters/digits), [`ASCIIFoldingFilter`](https://lucene.apache.org/core/4_9_0/analyzers-common/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.html), and [`LowerCaseFilter`](https://lucene.apache.org/core/7_4_0/core/org/apache/lucene/analysis/LowerCaseFilter.html)

which all means it will match more on exact names and not have stop words stripped out and not be treated as if its a sentence which makes sense since content type aliases are very static.

There's a `NodeTypeAlias` extension method you can use: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Examine/UmbracoExamineExtensions.cs#L69

**Comment by mistyn8** [comment]
Thank you kindly.. can I ask a silly question... why are other fields duplicated as both __Field and field ?? 

```
__Icon	icon-home color-pink
__NodeId	1606
__Path	-1,1064,1134,1606


icon	icon-home color-pink
id	1606
path	-1,1064,1134,1606
```

**Comment by henryson** [comment]
> 

That link is 404. Can I find it elsewhere?

**Comment by nul800sebastiaan** [comment]
@henryson https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Examine/UmbracoExamineExtensions.cs#L69
