### ISSUE TITLE
Intermittent PureLive models not being created

### ISSUE THREAD

**Issue by StephenJamesKindertons** [umbraco/Umbraco-CMS#9549]
Sometimes ModelsBuilder is not creating models, I get a 

The type or namespace name 'Homepage' could not be found (are you missing a using directive or an assembly reference?)

ModelsBuilder is in Purelive mode

Can you help me please. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.1.5

Reproduction
------------

go to https://www.kindertons.co.uk and hit refresh till you see the error we get.

### Bug summary

Purelive is not building the particular model "KinderHome", sometimes.

**Comment by nul800sebastiaan** [comment]
Thanks @StephenJamesKindertons, a lot has happened since version 8.1.5 and I would encourage you to update to the latest version of Umbraco first and see if you can reproduce the same problem there. I haven't seen any issues around this problem so I am assuming it's been fixed along the way.  

Ps. I refreshed that page about 50 times, no errors so far :-)
