### ISSUE TITLE
UsersMembershipProvider and useLegacyEncoding=true

### ISSUE THREAD

**Issue by kistva** [umbraco/Umbraco-CMS#9610]
This is not a bug - More like missing properties

## Umbraco version 7.15.6

I am seeing this issue on Umbraco version: 7.15.6
The web.config use to have a full set of on properties set on UsersMembershipProvider - Which is removed in 7.15.6

Then we only found useLegacyEncoding in the UmbracoMembershipProvider and the result was that one couldn't login.

Reproduction
------------
In a upgrade process we notice that the web.config has changed when we look at the setup for the UsersMembershipProvider

It use to be set with all the proberties like following 

` <add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="8" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Hashed" allowManuallyChangingPassword="false" />
`
But in the web.config it is now set without properties 
`<add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco" />`

**Comment by nul800sebastiaan** [comment]
As with all upgrades, we would advise to only copy relevant differences into your web.config. When comparing the old web.config to one from a fresh install, removing membership properties will indeed most likely give you problems logging in. 

Please not that using legacy encoding is extremely insecure, which is why the new default (also when you do not provide this property) is set to `false`.
