### ISSUE TITLE
Update HtmlSanitizer

### ISSUE THREAD

**Issue by TheBekker** [umbraco/Umbraco-CMS#9615]
As one that's been using AngleSharp for quite a while on earlier versions of Umbraco 8 (8.6.4), i was a bit confused when trying to upgrade to 8.10.1 today.

Seeing that it has a dependency on a 2 year old version of HtmlSanitizer, and that in turn having a dependency on a 3 year old version of AngleSharp, stopping me from upgrading, unless i downgrade AngleSharp.

Any reason for these old versions suddenly appearing, or would it be possible to include a newer version of HtmlSanitizer, and by that a newer AngleSharp?

**Comment by nul800sebastiaan** [comment]
Hi @TheBekker - the dependency on HtmlSanitizer is new since version 8.8.0 where we use it to strip potentially harmful content out of svg icons. 

The PR for the svg icon feature was made before HtmlSanitizer v5 was out, so we ended up with v4. Interestingly, there's a low severity security problem with v4 so an attempt was made to update to v5. This has resulted in a build error which we'll need to investigate. I can reproduce the problem locally and am not sure what we can do about it.

For reference, the PR: https://github.com/umbraco/Umbraco-CMS/pull/9613
The failed build: https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=54300&view=results

The error message: `##[error]SGEN(0,0): Error : An attempt was made to load an assembly with an incorrect format: C:\Users\VssAdministrator\.nuget\packages\system.text.encoding.codepages\4.5.0\ref\netstandard2.0\System.Text.Encoding.CodePages.dll.`
It seems to have something to do with the referenced .net framework, but I don't fully understand it yet.

**Comment by ronaldbarendse** [comment]
It's even worse now, because `HtmlSanitizer` has unlisted all v4 versions from NuGet and version 4.0.217 has an exact version restriction on AngleSharp 0.9.11: https://www.nuget.org/packages/HtmlSanitizer/4.0.217. If you do a `Update-Package` in the Package Manager Console, NuGet can't find any matching version for HtmlSanitizer 😖

**Comment by ronaldbarendse** [comment]
The quick-fix was to download the `HtmlSanitizer` NuGet package from the above link and push it to our own/internal NuGet feed, but the same is possible using a local package source folder: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections.

**Comment by nul800sebastiaan** [comment]
We came to the conclusion that it's best to remove HtmlSanitizer for now (which lifts the restriction on AngleSharp).

I can't reproduce the NuGet problem though, not sure how people are running into that one, the package is available (though unlisted) and can be installed (for me) through `Install-Package UmbracoCms` and `Update-Package` as well. I did clear my local nuget caches too.

**Comment by nul800sebastiaan** [comment]
Oh forgot the link to the PR: https://github.com/umbraco/Umbraco-CMS/pull/9803

**Comment by nul800sebastiaan** [comment]
Ah, when I upgrade an 8.7 install from the package manager command line, it doesn't find the HtmlSanitizer version, however, Visual Studio's NuGet UI lets me upgrade to the newest Umbraco. 🤷  

That's a workaround for now.

**Comment by ksolberg** [comment]
My temporary solution for upgrading via nuget was to push the package to our local feed and manually install it from there before upgrading.

**Comment by nul800sebastiaan** [comment]
We've managed to update it after all, 8.12 will ship with v5 of HtmlSanitizer.

**Comment by nul800sebastiaan** [comment]
Note: we should do the same upgrade to 8.8+ patch releases as well.

**Comment by ribsdigital** [comment]
ran into this issue today - posted it up on the [forum](https://our.umbraco.com/forum/using-umbraco-and-getting-started/105231-upgrading-v880-through-v8111-is-broken-by-htmlsanitizer-dependency) as i can't find any other reference to this issue other than this post and my suspission is that people will search there 1st rather than github...

> The quick-fix was to download the `HtmlSanitizer` NuGet package from the above link and push it to our own/internal NuGet feed, but the same is possible using a local package source folder: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections.

@ronaldbarendse your suggestion of hosting the v4xxx version on a local feed seems to be a viable workaround, my thinking being to force update HtmlSanitizer to v5xxx once i've completed the upgrades...

would you be able to attach a v4xxx version of HtmlSanitizer to this thread?! i've been searching for ages trying to get a version but can't find a package to download as it's since been deleted from nuget...

**Comment by ribsdigital** [comment]
ok, hacking around and i think i've got the full workaround...

i found that the last released 4x version of HtmlSanitizer was v4.0.217 (based on [https://github.com/mganss/HtmlSanitizer/tags?after=v4.0.230](https://github.com/mganss/HtmlSanitizer/tags?after=v4.0.230))

although it doesn't appear on [https://www.nuget.org/packages/HtmlSanitizer/](https://www.nuget.org/packages/HtmlSanitizer/) it is still available on this link:

[http://nuget.org/api/v2/package/HtmlSanitizer/4.0.217](http://nuget.org/api/v2/package/HtmlSanitizer/4.0.217)

so i downloaded that, stuck it in a directory and then installed it via the package manager:

`Install-Package HtmlSanitizer -source C:\Temp\packages`
(i guess you could set up `C:\Temp\packages` as a package source in the settings but i figured try this first...)

now i can do `update-Package UmbracoCms -Version 8.8.0` and as the package is already installed, the dependency is resolved and away the upgrade goes.

so i've worked through the rest of the installs and my final step was to upgrade HtmlSanitizer to version 5 so the security vulnerability discovered in 4x doesn't effect any production based site.

lucky i told my project manager upgrading the sites may take a while!

**Comment by bjarnef** [comment]
@nul800sebastiaan it expected when updating Umbraco via NuGet, e.g. from v8.11.1 to v8.11.2 it also upgrades HtmlSanitizer to v5?

![image](https://user-images.githubusercontent.com/2919859/111438709-db12e680-8704-11eb-9db3-ea33471c994b.png)

For example when Umbraco Cloud has upgraded from v8.11.1 to v8.11.2, but the class library dependency is using Umbraco v8.11.1, which seems to be because HtmlSanitizer v4 has been unlisted from NuGet.

It would probably be faster just upgrading the Umbraco Cloud project to v8.12 instead :)

**Comment by nul800sebastiaan** [comment]
Yes, as you can see, this dependency has been updated for all the patches of 8.8+

**Comment by bjarnef** [comment]
Ahh okay, normally there wouldn't be breaking changes in patches, but I guess this is an exception.

**Comment by hfloyd** [comment]
I just came up against a related issue - dealing with a Cloud site which was auto-updated to 8.11.2, but when I update my external code project (.Core) references to use the Umbraco 8.11.2 NuGet package, I am now seeing a "consolidate" discrepancy with "System.Text.Encoding.CodePages"...

![image](https://user-images.githubusercontent.com/1252593/111521586-ad8f6280-872f-11eb-8788-1bc36261b742.png)

It looks like the version was downgraded from 4.5.0 to 4.3.0? Is that correct? or should I update the .Web project to 4.5.0? 

Generally, I do my best to keep the versions aligned with what Umbraco CMS is using.

**Comment by hfloyd** [comment]
FYI - It seems I needed to update the .Web project to System.Text.Encoding.CodePages 4.5.0. I'm not sure why the Cloud-updated packages.config wasn't updated as well, but I have seen this sort of issue before...
