### ISSUE TITLE
Use Specflow for some tests

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#9704]
Consider using [Specflow](https://specflow.org/) for some tests. Having a library of common specflow steps could help with getting more tests written for scenarios.

**Comment by csharpforevermore** [comment]
Hi - I'm happy to take this one. Should I just create a feature branch?  

This is essentially a form of refactoring the code. I like it because  I've worked a lot in the past with similar Fluent syntax test extensions - namely a great project called [Fluent Automation](https://github.com/stirno/FluentAutomation).  Time estimate wise - I think this would be a bit of a spike in dev work - maybe a week or two?
