### ISSUE TITLE
Use localdb instead of SQL Compact for tests that require a database

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#9706]
Use [localdb ](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-2017)instead of SQL Compact for tests that require a database. Local db can be used in Azure Pipelines and supports more sql features than SQL Compact.

How to enable localdb:
https://www.jannikbuschke.de/blog/azure-devops-enable-mssqllocaldb/

**Comment by Shazwazza** [comment]
LocalDb is being used already in netcore (no sqlce) so don't think we need to redo this for v8. We also did this quite some time ago in v8/v7 and the perf is actually worse and requires a lot of extra wrangling to make it perform ok. 

Will close this one since there isn't a plan to update this for v8.
