### ISSUE TITLE
v 8.11 Textarea number of rows validation does not work on frontend.

### ISSUE THREAD

**Issue by EneldoDev** [umbraco/Umbraco-CMS#9862]
When editing content node with property using Textarea property editor, frontend validation doesn't block postback when number of rows configuration is exceeded.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.0

Reproduction
------------

### Steps to reproduce

1. Create document type with property using Textarea property editor (field NOT mandatory) and set number of rows to 5.
2. Using this document type create content node. Fill textarea with more than 5 rows.
3. Save/Save and publish content.

### Expected result

Validation message informing that number of rows in textarea were exceeded should appear. No post back.

### Actual result
Once Save/Save and publish button is clicked there is none validation massege and postback isn't blocked. Content node is saved, page reloaded. Textarea field is empty though, what means backend validation works correctly.

Validation is working properly only when "Field is mandatory" checkbox is checked.

**Comment by nul800sebastiaan** [comment]
Thanks @EneldoDev! This is the setting for the default "height" for a textarea  - so like this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#examples

It is not a validation setting and it would also be quite difficult to make it validate on 10 "lines" since the width of the textarea can vary. I recommend you work with the `Maximum allowed characters` validation instead.
