### ISSUE TITLE
Umbraco Forms 8.2.0 Workflow Issue

### ISSUE THREAD

**Issue by 5DevTeamAlerts** [umbraco/Umbraco-CMS#9941]
System : Umbraco 8.5.5 / Umbraco Forms 8.2.0

Yesterday we experienced a potentially serious scenario regarding two submissions of the same form at (apparently) exactly the same time.

We have a form which (like many of our other forms) has a workflow which populates the receiver email with a special field drawn from an email address input field on the form for the purposes of providing a submission confirmation email. 

On this occasion, two people appear to have submitted (with different details) the same form at the same time, however Person 1 received the form submission confirmation email containing details submitted by Person 2 as well as their own confirmation email, while Person 2 did not receive a confirmation email at all. In the back office there is only an entry for Person 1, with the correct details for that person. No entry for Person 2.

This is obviously very worrying for us. Fortunately this only affected internal staff, however many of our forms with similar workflows are used by members of the public. If this has happened to two members of the public we would be in serious breach of data protection laws.

This is the first (reported) time this has ever happened, however we have been able to replicate the error by two people co-ordinating a form submission at the same time. Both form submissions took noticeably longer to complete, and for one person a (handled) server error was encountered. This person did not receive an email, and the other person received BOTH form submission emails. Also only the entry for the person who received the emails appeared in the back office.

So, question - is it at all possible that if two people submitted the same Umbraco form at the same time there is the potential for a crossover while the submissions are being processed on the server (as appears to be the case here)? If so how can we avoid this happening again?

**Comment by nul800sebastiaan** [comment]
Hi there @5DevTeamAlerts and yes, that's a very unfortunate event caused by a very unfortunate bug in the version you're currently using. I would encourage you to upgrade to at least version 8.3.2 where this particular bug was fixed and I would even more encourage you to investigate and test an upgrade to the latest (8.6.1) version for a lot more fixing of other bugs. 

8.3.2 is available in the `Archived` files on Our https://our.umbraco.com/packages/developer-tools/umbraco-forms/ or on NuGet https://www.nuget.org/packages/UmbracoForms/8.3.2

**Comment by 5DevTeamAlerts** [comment]
Thank you so much for your confirmation and providing a solution so quickly.
