### ISSUE TITLE
Bug? Properties without Vary by culture won't be stored to ExternalIndex when publishing node in non-default language

### ISSUE THREAD

**Issue by remkovb** [umbraco/Umbraco-CMS#9963]
Properties that aren't culture dependent don't show up in External Index after publishing a node in non-default language.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1 (and also 8.12rc)

Reproduction
------------

### Bug summary

There are 2 (or more) languages: - Dutch nl-NL (default) - English en-US

On each node are several properties that aren't language dependant, so "Vary by culture" isn't checked for those properties.

However when when publishing a node for only English (so non-default language), we discovered these properties didn't show up in ExteralIndex... So when getting the node in razor these properties aren't available..

Only when we publish the node in Dutch, so the default language, the non-varying properties appear..

### Specifics

Already described above

### Steps to reproduce

- Set-up Umbraco in 2 languages with 1 default language
- Create documenttype with a textstring property (for instance "test" alias) that doesn't have Vary by culture checked
- Create node in other language than default one and publish it
- Go to Examine Manager and search for node in External Index
- The property with "test" alias isn't there in the node. So it isn't stored in Exteral Index

### Expected result

Expected result is this property is stored in External index at all time. Because it isn't culture dependent it should always be stored, no matter what culture you publish for a node.

### Actual result

The property isn't in External Index after publishing. Only when publishing the default language version of the node it appears in External index. This is strange behaviour right?

**Comment by emma-hq** [comment]
Hey @remkovb 

I'm able to recreate this yep. It looks like a bug to me. 

I have recorded a gif and attached it here. I'll label the issue so that it can reach the right people and we'll see what we can all come up with.

![examine index](https://user-images.githubusercontent.com/78740801/110640431-ba004200-81a8-11eb-92e2-b163773562e9.gif)

Emma

**Comment by nul800sebastiaan** [comment]
Okay, to be clear here, I thought this worked just fine but I was missing the finer detail:

Content that was never published doesn't end up in the External Index. 

The problem here is that the property on the main language (that is the second language is inheriting from) has not published that test property yet, which is why it is not in the index.

We'll have to ask around but I think this "works as intended". Ultimately, this is a backoffice display problem that might have to be fixed. The second language should show you the published property data, the data that is saved but not yet published.

**Comment by remkovb** [comment]
Sebastiaan.. 

Think this shouldn't be working like this..

Imagine you add product node to your site.. You only want to publish this product a non-default language and, because on the default language site it shouldn't be shown.. That could be for product, but I can imagine there all all kinds of scenarios where you want to publish a node in 1 partical language only. It shouldn't matter if it's the default language or not. 

Anyway, when you will do what I describe here.. The product will only be stored to index with culture varying properties... All other properties, for instance: length, width, height, price, that aren't culture dependent in our site, won't be indexed and thus won't be displayed on our site. More import, an External Id we save in textstring, that surely isn't culture dependent isn't stored. So in our daily import the product isn't even found because of the missing property.. You understand the problem?

**Comment by nul800sebastiaan** [comment]
Yes while I do understand what you mean, we need to be mindful of the fact that it might be on purpose that some content in  default language hasn't been published yet. 

If the content in the default language contains something secret, something that should not be public information yet, you shouldn't be able to "accidentally" publish this by naively clicking publish on the Dutch version.

**Comment by remkovb** [comment]
@nul800sebastiaan for me it's just as easy as this:
Everything an editor has created/edited in different fields in Umbraco (could be culture- or nonculture property) for a certain node, should be available on the website and thus in External Index. 

So, if a price (non culture property) value has been set for an English variant of a node, the price should be available. The Dutch variant won't be published then. 

So what possible  "secret" data could get in External Index then? I mean, everything you see in content-editor should be available in External Index after publish right?

**Comment by nul800sebastiaan** [comment]
The US market is ready to go with the launch of an exciting new product, everything is ready but the launch date is still a secret until corporate approves it. 
All the pages are ready to go, filled in and saved to publish for the second the sign-off comes in.

The South America market notices some spelling errors on their version and publishes those.. inadvertently also revealing the launch date.

> I mean, everything you see in content-editor should be available in External Index after publish right?

Yes, and in all of the things we talked about here it is clear that we're talking about a language that has not published the latest changes yet, so that's why they're not in the External Index 😄 

I'm not saying the UX is the best here, I'm just trying to highlight why we can't "just" publish unpublished data.

**Comment by nul800sebastiaan** [comment]
Sorry for the delay on this one, after a chat at HQ this indeed works as intended. You're very welcome to create your own indexes with the behavior you desire, but the default behavior will stay as it is now.
